### DISCUSSION TITLE
Problem: "servers" key in global configuration does not effect to resources

### DISCUSSION THREAD

**Discussion by kolotov** [api-platform/api-platform#2098] [Q&A]
Hello!
I noticed that the "servers" key does not effect to resources if I set it as global
Version 2.6.6

```
#api/config/packages/api_platform.yaml

api_platform:
    defaults:
        openapi_context:
            servers:
                - url: v1
                - url: v2
```
