### DISCUSSION TITLE
How to use voter with "provider" and "output" ?

### DISCUSSION THREAD

**Discussion by 4749448959599** [api-platform/api-platform#2309] [Q&A] [answered]
Hello, with this kind of configuration : 

```
App\Core\Domain\Inscription\Model\Inscription:
    normalizationContext:
        skip_null_values: false
    operations:
        ApiPlatform\Metadata\Get:
            uriTemplate: /inscription/{id}
            openapiContext:
                tags: [Inscription]
                summary: Retrouver une inscription.
            output: App\Core\Domain\Inscription\UseCase\VoirInscription\InscriptionView
            provider: App\Infrastructure\Api\Provider\InscriptionProvider

```

Where Inscription is an entity, InscriptionProvider the provider  InscriptionView the object wich will be serialized in a json response like 
it is explained here : https://api-platform.com/docs/core/dto/#implementing-a-read-operation-with-an-output-different-from-the-resource

What is the correct way to use the voter ? Currently I call it like I used to do in the controller in older version : 

```
    public function provide(Operation $operation, array $uriVariables = [], array $context = []): ?InscriptionView
    {
        $inscription = $this->decorated->provide($operation, $uriVariables, $context);

        if ($inscription instanceof Inscription) {
            if (!$this->authorizationChecker->isGranted(InscriptionVoter::VOIR, $inscription)) {
                throw new AccessDeniedException();
            }

            return (new InscriptionView())->build($inscription);
        }

        return null;
    } 
```

But is there a better way to do that, directly in the mapping for example ?
