### DISCUSSION TITLE
Using provider and processor with yaml configuration

### DISCUSSION THREAD

**Discussion by Muspi** [api-platform/api-platform#2324] [Q&A]
Hi, I try to use Processor and Provider on V2.7, and my yaml configuration is ignored (also on get, post or patch routes).
Services are well autoconfigured, they appear in debug container, but not fired.
I did not found yaml documentation on official documentation.

this is my routing configuration:

```
get_information:
    path: /structures/{id}/information
    method: GET
    normalization_context:
        skip_null_values: false
        groups: ['structure:read_item']
    provider: App\DataProvider\StructureGeneralInformationDataProvider
    output: App\Dto\Structure\StructureGeneralInformation


patch_information:
    path: /structures/{id}/information
    method: PATCH
    validation_groups:
        - "structure:update_information"
    processor: App\Processor\StructureGeneralInformationProcessor
    provider: App\DataProvider\StructureGeneralInformationDataProvider
    input: App\Dto\Structure\StructureGeneralInformation
    output: App\Dto\Structure\StructureGeneralInformation
```

Any idea of the problem?
