### DISCUSSION TITLE
Prefix / conflict

### DISCUSSION THREAD

**Discussion by julienmiclo** [api-platform/api-platform#2326] [Q&A]
Hello,
i hope some one can help me. :)

I want to make a html twig homepage on `/` and an api without prefix, how can i have both ? Because when i go on `/`, i have a json **resource_name_collection**

I have :
```
config/packages/api_platform.yaml

api_platform:
    enable_swagger_ui: false
    enable_re_doc: false
```
```
config/routes/api_platform.yaml

api_platform:
    resource: .
    type: api_platform
    prefix: /
api_doc:
    path: /docs
    controller: api_platform.swagger_ui.action
```
```
src/Controller/HelpController.php

class HelpController extends AbstractController
{
    #[Route('/', name: 'app_home', methods: ['GET'])]
    public function home(): Response
    {
        return $this->render('home.html.twig');
    }
}
```

Thank you.
