### DISCUSSION TITLE
API Platform handles all my projet Exceptions

### DISCUSSION THREAD

**Discussion by SimonVanacco** [api-platform/api-platform#2608] [Q&A]
I recently upgraded to Symfony 6.4, and since then API Platform handles every PHP Exception even when outside of the API context. 

For example my project is configured to have the API only on /api/* : 

```yaml
# config/routes/api_platform.yaml
api_platform:
    resource: .
    type: api_platform
    prefix: /api
```

But when i get a PHP Exception on any route (for example this is on /user-admin/create) it gets handled by API Platform : 
![image](https://github.com/api-platform/api-platform/assets/5305627/deb38e89-bcb5-40a2-a236-92f4039ccbda)

I would really like to get the Symfony error pages back ! Any ideas ? 
Thanks !
