### DISCUSSION TITLE
Issue with IDE code completion on PWA with the docker install : node modules not found

### DISCUSSION THREAD

**Discussion by Ak1r0** [api-platform/api-platform#2674] [Q&A]
Hi,

### IDE code completion on PWA with the docker install

I'm encountering a problem with coding on the PWA when using the Docker installation: there is no autocomplete functionality, and my IDE (PhpStorm) is displaying errors because node modules cannot be found.

Ex: `TS2307: Cannot find module next or its corresponding type declarations.`

I assume the issue comes from pnpm storing modules in `/.pnpm-store` (default pnpm dir defined in pwa/Dockerfile),
and `pwa/node_modules` contains only symlinks, which my IDE (on the host machine) cannot resolve...

![image](https://github.com/api-platform/api-platform/assets/7613997/c944bcd0-0844-437b-8c3e-4c23894f4576)

I tried to set up a bound volume for pwa in compose.override.yaml :

```
  pwa:
    build:
      context: ./pwa
      target: dev
    volumes:
      - ./pwa:/srv/app
      - /srv/app/node_modules
      - ./.pnpm-store/:/.pnpm-store
 ```
but it didnt work (obvisouly but i still tried :D)

For now i changed the pwa/Dockerfile to use npm instead of pnpm in dev but i'd rather keep pnpm if possible.

Any tips ?

### Second point : 
the `/.pnpm_store` should maybe be added as a volume for consistency and performances (when rebuilding) ?

___
I'm on Windows11 with Docker Desktop 4.18.0
