### DISCUSSION TITLE
Weird Behaviour with MapRequestPayload

### DISCUSSION THREAD

**Discussion by mikabnm** [api-platform/api-platform#2691] [Q&A]
Hi !

I'm working on an app that has apiplatform (currently migrating actually so a lot of my routes are still made with classic Symfony Controllers.

On one of them I tried to use the new MapRequestPayload attribute to hydrate a DTO and validate it. But in case there is a validation error, instead of having a nice "violations" array in my response, i get a weird 0:
```
{
    "type": "https://tools.ietf.org/html/rfc2616#section-10",
    "title": "An error occurred",
    "status": 422,
    "detail": "app.user.old_password.invalid",
    "0":
    {
        "propertyPath": "old_password",
        "message": "app.user.old_password.invalid",
        "code": "2d2a8bb4-ddc8-45e4-9b0f-8670d3a3e290"
    },
    "class": "Symfony\\Component\\HttpKernel\\Exception\\HttpException"
}
```

Here's the code of my controller:
```
#[Route(
    'account/credentials',
    name: 'put_account_credentials',
    methods: ['PUT'],
)]
class PutCredentialsAction extends AbstractController
{
    public function __construct(
        private readonly Security $security,
        private readonly UserAssembler $userAssembler,
        private readonly UserManager $userManager,
        private readonly JsonSerializer $serializer,
        private readonly JWTTokenManagerInterface $JWTManager
    ) {
    }

    public function __invoke(
        Request $request,
        #[MapRequestPayload] UserUpdateCredentialsDto $updatedUserDto,
    ): JsonResponse {
        $currentUser = $this->security->getUser();
        if (null === $currentUser) {
            throw new HttpException(Response::HTTP_FORBIDDEN, 'Not logged');
        }

        /** @var UserDto $userDto */
        $userDto = $this->serializer->denormalize($updatedUserDto, UserDto::class, $this->userAssembler->transform($currentUser));

        $currentUser = $this->userAssembler->reverseTransform($userDto, $currentUser);

        $this->userManager->save($currentUser);

        /** @var UserDto $userDto */
        $userDto        = $this->userAssembler->transform($currentUser);
        $userDto->token = $this->JWTManager->create($currentUser);

        return $this->json($userDto, Response::HTTP_OK, ['user']);
    }
}
```

and DTO:

```
class UserUpdateCredentialsDto
{
    #[Assert\NotBlank]
    #[Assert\Length(min: 6)]
    #[AppAssert\EmailDns]
    #[Groups(['update_credentials_all'])]
    public ?string $email = null;

    #[Assert\NotBlank]
    #[Assert\Length(min: 6)]
    #[Groups(['update_credentials_all'])]
    public ?string $password = null;

    #[SecurityAssert\UserPassword(
        message: 'app.user.old_password.invalid',
    )]
    #[Groups(['update_credentials_all'])]
    public ?string $oldPassword = null;
}
```

After a LOONG session of debugging I ended up finding the culprit for it : the apiplatform's ConstraintViolationListNormalizer
I still didn't figure out why it transforms the answers this way. I m haven't found anyone else who has the same problem as me so I guess soemthing's wrong with my app. Maybe the configuration of apiplatform ? 
here s mine:
```
api_platform:
    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
    formats:
        jsonapi:     ['application/json']
        json:     ['application/json']

    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/src/Elastica/Document']
    patch_formats:
        json: ['application/merge-patch+json']

    enable_swagger: false
    enable_swagger_ui: false
    enable_re_doc: false
    enable_entrypoint: false
    enable_docs: false

    defaults:
        normalization_context:
            skip_null_values: false
        pagination_enabled: true
        pagination_client_enabled: true
        pagination_items_per_page: 30 # Default value
        pagination_client_items_per_page: true # Allow the client to request a different number of items per page
        cache_headers:
            max_age: 0 # Set 60 to reactivates cache
#            shared_max_age: 3600
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
            invalidation:
                xkey:
                    glue: ', '
    collection:
        pagination:
            items_per_page_parameter_name: per_page
            enabled_parameter_name: pagination # optional
```

Any help would be welcome... Thanks !
