### DISCUSSION TITLE
Kong API Gateway route awareness at runtime

### DISCUSSION THREAD

**Discussion by ngrafa** [api-platform/api-platform#2768] [Q&A]
Greetings! 

Since we now have countless API Platform instances running in our company's private network, we are only fronting the API endpoints and OpenAPI docs page via Kong API Gateway, which sits on a host that is part of the private company network but also has a route from an edge/proxy/gateway.

For backward compatibility, we need to continue to support our internal URLs for each API Platform instance, which would be in the format of `{microservice-name}.svcs.corp.exampledomain.net` with no path route prefixes, (so `/` yields the docs page) 

When using Kong API Gateway, we aim to have a single host domain route such as `api.gateway.exampledomain.com` and each microservice would be reachable as a path such as `api.gateway.exampledomain.com/microservice1` and so forth.

What is the best way to configure this conditional behaviour? It has to be the same runtime that supports both conditions, so no environment variables.

I have tried or considered the following approaches:
1. Using condition parameters in `api/config/routes/api_platform.yaml` & `api/config/routes.yaml`, but we've found the 2nd definition doesn't kick in (see `api/config/routes/api_platform.yaml` below)
2. Kernel event listener, which loops through routes (I personally don't like this - it seems hacky). See `RoutePrefixListener` below.
3. (Considered) Symfony Compiler Pass to change the prefix parameter (`api_platform_prefix` as shown below) but CompilerPass is too early in the runtime lifecycle and doesn't have access to request/route information.

I feel there has to be a better way rather than iterating over routes.

Here are my files.

```
# @file: api/config/routes/api_platform.yaml

# Kong API Gateway route with custom prefix
api_platform_gateway:
    resource: .
    type: api_platform
    # condition: "context.getHost() matches '/gateway/i'"
    # condition: "context.getHost() == 'api.gateway.exampledomain.com'"
    # condition: "request.headers.has('x-kong-request-id')"
    prefix: /microservice1
    # Compiler Pass approach
    # prefix: '%api_platform_prefix%'


api_platform:
    resource: .
    type: api_platform
    prefix: '%api_platform_prefix%' # Use a parameter placeholder
    # condition: "not (context.getHost() matches '/gateway/')"
    condition: "context.getHost() != 'api.gateway.exampledomain.com'"
    # condition: "context.getHost() == 'microservice1.svcs.privatenetwork.exampledomain.net'"
    # condition: "not (request.headers.has('x-kong-request-id'))"
    prefix: /
```

```
# @file: api/config/routes.yaml
controllers:
    resource: ../src/Controller/
    type: attribute

# api_doc_gw:
#     path: /microservice1/docs
#     controller: api_platform.swagger_ui.action
#     condition: "context.getHost() == 'api.gateway.exampledomain.com'"

# api_doc:
#     path: /docs
#     controller: api_platform.swagger_ui.action
#     condition: "context.getHost() != 'api.gateway.exampledomain.com'"
```

Here is the crazy route iteration approach, which shows the prefixed URLs correctly in OpenAPI but the cURL responses.

(Note, we use `url_generation_strategy: !php/const ApiPlatform\Api\UrlGeneratorInterface::ABS_URL` in our `api/config/packages/api_platform.yaml` config.

```
<?php

namespace App\Listener;

use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\HttpKernelInterface;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

class RoutePrefixListener
{
    private $parameterBag;
    private $gatewayHost = 'api.gateway.exampledomain.com';
    private $gatewayPrefix = '/microservice1';
    private $defaultPrefix = '/'; // Default API Platform prefix
    private $router;

    public function __construct(RouterInterface $router, ParameterBagInterface $parameterBag)
    {
        $this->router = $router;
        $this->parameterBag = $parameterBag;
    }

    public function onKernelRequest(RequestEvent $event)
    {
        if (!$event->isMainRequest())
        {
            return;
        }

        $request = $event->getRequest();

        // Check for the host or a specific header
        if ($request->headers->has('x-kong-request-id') || $request->getHost() === $this->gatewayHost)
        {
            // Set the prefix dynamically
            // $this->parameterBag->set('api_platform_prefix', $this->gatewayPrefix);

            $this->addPrefix($request, $this->gatewayPrefix);
            $this->updateApiPlatformRoutes($this->gatewayPrefix);
        }
        else
        {
            // Set the default prefix
            // $this->parameterBag->set('api_platform_prefix', $this->defaultPrefix);

            $this->updateApiPlatformRoutes($this->defaultPrefix);
        }
    }

    private function addPrefix(Request $request, string $prefix): void
    {
        $pathInfo = $request->getPathInfo();

        // Prevent double prefixing
        if (strpos($pathInfo, $prefix) !== 0)
        {
            $request->attributes->set('original_path_info', $pathInfo);
            $request->server->set('REQUEST_URI', $prefix . $pathInfo);
            $request->server->set('PATH_INFO', $prefix . $pathInfo);
        }
    }

    private function updateApiPlatformRoutes(string $prefix): void
    {
        $routeCollection = $this->router->getRouteCollection();

        foreach ($routeCollection as $route)
        {
            if (strpos($route->getPath(), $this->defaultPrefix) === 0)
            {
                $route->setPath($prefix . $route->getPath());
            }
        }
    }
}
```
