### ISSUE TITLE
[BUG] User password reset on DELETE resource actions

### ISSUE THREAD

**Issue by Cethy** [api-platform/api-platform#1005]
With `api-platform` (api-pack ^1.1) + `lexik/jwt-authentication-bundle` (^2.5), and a "standard" security configuration :
```yaml
security:
    encoders:
        App\User\Entity\User:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: App\User\Entity\User
                property: username

    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            user_checker: App\Security\UserChecker
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }


    role_hierarchy:
        # ...
``` 

Whenever I send a DELETE request for a resource (not User), I noticed that the authenticated user is persisted with a empty password :
```
[2019-02-18 12:48:22] doctrine.DEBUG: "START TRANSACTION" [] []
[2019-02-18 12:48:22] doctrine.DEBUG: UPDATE app_users SET password = ?, updated_at = ? WHERE id = ? ["","2019-02-18 12:48:22",1] []
[2019-02-18 12:48:22] doctrine.DEBUG: DELETE FROM intervention WHERE id = ? [1] []
[2019-02-18 12:48:22] doctrine.DEBUG: "COMMIT" [] []
```

For testing purpose, I modified the `Symfony\Bridge\Doctrine\Security\User\EntityUserProvider::loadUserByUsername()` to detach the user before returning it and it seems to do the trick.

Is it a known problem ? Is there a better fix than using a custom UserProvider and detach the user from doctrine myself ? 

Thx !
