### ISSUE TITLE
Describing Request Body

### ISSUE THREAD

**Issue by kpn13** [api-platform/api-platform#1019]
Hello,

I try to describe my request body using OpenAPI v3 and "openapi_context" key in a YAML file, but I think the "required" key is not take in consideration. Is there a way to show in the swagger interface that some properties in the body are required and others are optionals ?

        foobar:
          method: 'PUT'
          path: '/foo/{id}/bar'
          controller: 'App\Controller\FooController'
          openapi_context:
            summary: Something
              -
                 in: body
                 schema:
                   type: object
                   properties:
                       user:
                          type: object
                          properties:
                              firstname: {type: string, example: 'john'}
                              lastname:  {type: string, example: 'doe'}
                              country:   {type: string, example: 'FR'}
                          required:
                            - firstname
                            - lastname
`

Thank you in advance !

**Comment by wizbit** [comment]
Try
```yaml
    foobar:
      method: 'PUT'
      path: '/foo/{id}/bar'
      controller: 'App\Controller\FooController'
      openapi_context:
        summary: Something
          -
             in: body
             schema:
               type: object
               properties:
                   user:
                      type: object
                      properties:
                          firstname: {type: string, example: 'john', required: true}
                          lastname:  {type: string, example: 'doe', required: true}
                          country:   {type: string, example: 'FR'}
```
https://swagger.io/docs/specification/describing-parameters/
