### ISSUE TITLE
Kubernetes enviroment displays swagger instead of RedDoc

### ISSUE THREAD

**Issue by rubenvdlinde** [api-platform/api-platform#1028]
Okey I ran into a bit of wierd on the other day, where setting up a project. We switched from Swagger to ReDoc (for, well a ton of reasons). 

Now this workst neatly for the local docker-compose installation. But.... when we shift the thing over to a kubernetes cluster (http://178.128.136.195/). The whole thing returns back to the swagger docs....

And then fails missarably at that becouse it is missing some files. Now the only difference between these enviroments should be the use of a helm chart instead of docker-compose file.

```yaml
# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: prod
debug: '0'
secret: *** #ChangeMe
corsAllowOrigin: http://178.128.136.195/

php:
  repository: docker.io/conduction/larping-php
  tag: latest
  pullPolicy: Always
  replicaCount: 1

nginx:
  repository: docker.io/conduction/larping-nginx
  tag: latest
  pullPolicy: Always
  replicaCount: 1

varnish:
  enabled: true
  #url: https://www.larping.eu
  repository: docker.io/conduction/larping-varnish
  tag: latest
  pullPolicy: Always
  replicaCount: 1

ingress:
  annotations:
    # kubernetes.io/ingress.class: gce
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

postgresql:
  enabled: true
  imageTag: 10-alpine
  # If bringing your own PostgreSQL, the full uri to use
  #url: postgres://api-platform:!ChangeMe!@example.com/api
  postgresUser: api-platform
  postgresPassword: ***
  postgresDatabase: api
  # Persistent Volume Storage configuration.
  # ref: https://kubernetes.io/docs/user-guide/persistent-volumes
  persistence:
    enabled: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
```
Quite frankly i'm at a loss as to how this is happing. Where using the same containers locally as in the kubernetes cluster. One of the options might be the whole prod versus def thing. But.... if we change the 'prod' in helm chart to 'dev' we end up with the same behavior. 

Even wierder....  the enviroment seemt to be really really intend on presenting us with a symfony debug toolbar, even doh its on prod.......

Any idee where I should start looking? Rather at a loss here....
