### ISSUE TITLE
DTO doc is using @ApiResource in entity, Is there any DTO sample using yaml configuration?

### ISSUE THREAD

**Issue by rapax87** [api-platform/api-platform#1040]
DTO doc is using @ApiResource in entity.
`https://api-platform.com/docs/core/dto/#using-data-transfer-objects-dtos`

```
* @ApiResource(
 *   input=BookInput::class,
 *   output=BookOutput::class
 * )
```

 Is there any DTO sample configured by yaml?
I addbelow to api_resource.yaml, but it seems ignored and doesn't work.
```
post_service:
                input:  App\Dto\BookInput
                output:  App\Dto\BookOutput
                method: POST
```
