### ISSUE TITLE
Design constraints when using DataProvider and Api Entity with simple class (not Doctrine Entity)

### ISSUE THREAD

**Issue by Rebolon** [api-platform/api-platform#1058]
Hi !
I'm getting a problem using ApiPlatform and following [General Design Considerations](https://api-platform.com/docs/core/design/). 
In this explanation it says that we have to split Entity for ApiPlatform fro mEntity for Doctrine.

Ok, i did it. I have a class with ApiPlatform Annotation and another class with Doctrine Annotation.

Then, we need DataProvider (and DataPersister if we need tu mutate data) to bind the ApiPlatform Entity with Doctrine. This DataProvider can implement ItemDataProviderInterface and/or CollectionDataProviderInterface and that's what i did. 
The support method only return true/false when the resourceClass match the ApiPlatform Entity.
In the getItem or getCollection, i use the Repository from Doctrine Entity class to query the database.
And it works.

Now, i want to use Extensions ! 
Indeed, when we split Entity we no more use the wonderful features from ApiPlatform like Pagination, Sorting, Filtering, ... Those great features are no more implemented in the DataProvider because you have to do it manually.

So i inject the item and collection extensions in my service declaration. And then i loop over those iterable to use them over my QueryBuilder. But i have a big, big problem.
 
 * when i just do the foreach like described [Injecting Extension in DataProvider](https://api-platform.com/docs/core/data-providers/#injecting-extensions-pagination-filter-eagerloading-etc) the appliToCollection fail cause this method doesn't exist **Attempted to call an undefined method named "applyToCollection" of class "Symfony\Component\DependencyInjection\Argument\RewindableGenerator"**. So i decided to loop again over it and it's now ok (where may i be wrong ?)
```
foreach ($this->collectionExtensions as $extensions) {
            foreach ($extensions as $extension) {
```
* Then the applyToCollection can throw an error because $resourceClass is the ApiPlatform Entity, whereas some extension expect Doctrine Entity. This is the case for eagerExtension, FilterEagerExtension, SortExtension... So i'm fully confused and i don't know what to do. Even debugging with xdebug is quite hard and doesn't help me at this stage.

So the question would be: What are the constraints of using 2 Entities with DataProvider/DataPersister ? Do we need to add some specific annotation to allow Extension to run finely ?

Thanks a lot for help.
I will add a sample in a demo project to make it more explicit if required.

**Comment by teohhanhui** [comment]
> whereas some extension expect Doctrine Entity

If they're under the `ApiPlatform\Core\Bridge\Doctrine\Orm` namespace, then yes, they're written for Doctrine ORM. :smile:

**Comment by teohhanhui** [comment]
I guess the first question to ask yourself is: do you really need to separate them?

If your answer is "absolutely yes", then you need to implement your own extensions too.

**Comment by Rebolon** [comment]
Ok, so i don't really understand the recommandation from documentation to split into 2 classes, one for Doctrine and one for ApiPlatform 😲

**Comment by Rebolon** [comment]
Moreover, when you work with a legacy application, you may want to keep a separation between legacy Doctrine entities and the new Api system. So the split is a good idea. But in this case you cannot benefits from all ApiPlatform cool features like Filters. 

I've just understood why i had to loop twice and i fixed this (service declaration misconfiguration). But i still get an error about the Entity that is unkown:
```
"hydra:description": "Resource \"App\\Entity\\Patient\\PatientSimple\" not found.",
    "trace": [
        {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "",
            "file": "C:\\dev\\projects\\studiosystems\\tom\\symfony\\vendor\\api-platform\\core\\src\\Metadata\\Resource\\Factory\\AnnotationResourceFilterMetadataFactory.php",
            "line": 96,
            "args": []
        }
```

**Comment by Rebolon** [comment]
Ok, so i looked a bit more and:
 * /api: the root uri that display documentations analyze all entities and it uses Bridge\Doctrine\Common\PropertyHelperTrait

This will fail when you declare @APiFilter (with SearchFilter or OrderFilter per exemple) in your Entity that is not a Doctrine entity => you cannot use that kind of annotation

But if you alter the PropertyHelperTrait::getClassMetaData to change the $resourceClass to the related Doctrine entity, then it works. So one way would be to add extra information in the ApiResource annotation to allow Filters to read information in the right class.
Default would be the current class, and it could be overloaded by an ormResourceClass.

Not sure it would be enough to works but i will still investigate on that way.

**Comment by soyuka** [comment]
The ApiFilter annotation is only used to declare filters represented by the given filter class. Indeed, most of our filters are tight to doctrine (SearchFilter, OrderFilter etc) because they impact the query. Some are not though like PropertyFilter.

**Comment by fragoe** [comment]
@soyuka, I had the same problem today. I followed the documentation [Injecting Extensions (Pagination, Filter, EagerLoading etc.)](https://api-platform.com/docs/core/data-providers/#injecting-extensions-pagination-filter-eagerloading-etc) where it says, the service description should look something like this:

```
App\DataProvider\BlogPostItemDataProvider:
    tags: [ { name: 'api_platform.collection_data_provider', priority: 2 } ]
    # Autoconfiguration must be disabled to set a custom priority
    autoconfigure: false
    arguments:
        - '@doctrine_mongodb'
        - '@api_platform.metadata.resource.metadata_factory'
        - $collectionExtensions: !tagged api_platform.doctrine_mongodb.odm.aggregation_extension.collection
```

My constructor looks like this:
```
final class BlogPostItemDataProvider implements CollectionDataProviderInterface
{
    public function __construct(ManagerRegistry $managerRegistry, ResourceMetadataFactoryInterface $resourceMetadataFactory, iterable $collectionExtensions = [])
    {
        ...
    }
```

The issue here is the definition of the third parameter. It works properly after changing it to:

```
App\DataProvider\BlogPostItemDataProvider:
    tags: [ { name: 'api_platform.collection_data_provider', priority: 2 } ]
    # Autoconfiguration must be disabled to set a custom priority
    autoconfigure: false
    arguments:
        - '@doctrine_mongodb'
        - '@api_platform.metadata.resource.metadata_factory'
        - !tagged_iterator api_platform.doctrine_mongodb.odm.aggregation_extension.collection
```
