### ISSUE TITLE
Normalization context for same entity but different property subresource

### ISSUE THREAD

**Issue by BenWaNH** [api-platform/api-platform#1086]
Hi everyone,
i don't know how apply a normalization context for my case
I've an entity User which has 2 properties mapped to the same entity (one property for history, which is a collection, the other for the current so not a collection)

```
class User
{
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Course", mappedBy="user")
     */
    private $courseHistory;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Course")
     */
    private $currentCourse;
```

I want keep history return with String (ex: ["/api/courses/1", "/api/courses/2", ...] because array can be huge, so i don't wan't the entity content, just the uri. But for current, i would like properties -_-
If i apply a context for one, it's apply for the other too...

I tried something like this in resource.yaml:
App\Entity\Course:
    itemOperations:
      user_get_current_course:
        route_name: api_users_current_course_get_subresource
        normalization_context: {groups: ['currentcourse:read']}

with Course.yaml
App\Entity\Course:
  attributes:
    id:
      groups: ['course:read', 'currentcourse:read']
    ...

But nothing happen

Anyone has an idea?
Thanks
BenWa

**Comment by teohhanhui** [comment]
Are you using a subresource operation, `/api/users/{id}/currentCourse`?

**Comment by BenWaNH** [comment]
I tried to apply context here too but nothing happened 
```
resources:
  App\Entity\User:
    subresourceOperations:
      current_course_get_subresource:
        normalization_context:
          groups: ['currentcourse:read']
    properties:
      courseHistory:
        subresource:
          resourceClass: 'App\Entity\Course'
          collection: true
          maxDepth: 1
      currentCourse:
        subresource:
          resourceClass: 'App\Entity\Course'
          collection: false
          maxDepth: 1
```
