### ISSUE TITLE
"messenger" property does not work in YAML

### ISSUE THREAD

**Issue by kpn13** [api-platform/api-platform#1088]
It seems the "messenger" property does not work (or maybe I misuse it...).

I try
 ```
resources:
  App\Entity\Foo:
      attributes:
        messenger: true
```
or 
 ```
resources:
  App\Entity\Foo:
      messenger: true
```
or
```
resources:
  App\Entity\Foo:
      collectionOperations:
        post:
          attributes:
            messenger: true
```

and no message was send.

If I add an annotation on my entity it works fine : 
```
/**
 * @ApiResource(
 *     collectionOperations={
 *         "post" = {"messenger"=true},
 *     }
 * )
 */
final class Foo
{
```
