### ISSUE TITLE
how to specify the IRI by any operation which I want?

### ISSUE THREAD

**Issue by lichnow** [api-platform/api-platform#1098]
From [document](https://api-platform.com/docs/core/operations/#creating-custom-operations-and-controllers) I see "By default, API Platform uses the first GET operation defined in itemOperations to generate the IRI of an item and the first GET operation defined in collectionOperations to generate the IRI of a collection.".
But now I want to uses which operation that not is the first operation.like
```yaml
itemOperations:
            me:
                method: 'GET'
                path: '/users/me'
#                controller: App\Entity\User\GetMe
                access_control: 'is_granted("user.view-own")'
                access_control_message: 'Sorry, only the user himself or super admin can view his own detail info.'
            get:
                access_control: 'is_granted("user.view",object)'
                access_control_message: 'Sorry, you must login first.'
```
and change 
```
{
  "@context": "\/api\/contexts\/User",
  "@id": "\/api\/users\/me?id=2",
  "@type": "User",
```
to
```
{
  "@context": "\/api\/contexts\/User",
  "@id": "\/api\/users\/2",
  "@type": "User",
 }
```
how to specify the IRI by any operation which I want?
