### ISSUE TITLE
Best practice to secure my api

### ISSUE THREAD

**Issue by katsenkatorz** [api-platform/api-platform#1101]
Hello,

After several tests for 2 days I can not do what I want. I can not find my need on the forums / documentation either.
Will someone here help me?
I would like to have documentation of my public API with any methods accessible with an authentication token.
And add the authentication method that will be public in the documentation.

For exemple :
![image](https://user-images.githubusercontent.com/5629437/55948229-5bdf2300-5c50-11e9-8b7c-54d59df1c8ab.png)

Actually (not work, of course)

- My security :
```
security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        register:
            pattern:  ^/register
            stateless: true
            anonymous: true
        main:
            anonymous: true
            pattern: ^/api
        api:
            pattern:   /api/*
            stateless: true
            anonymous: false
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/*, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
```
My package conf
```
api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
```

**Comment by teohhanhui** [comment]
Are you trying to hide the documentation from unauthenticated users? That's not supported.

Few observations:

1. "Security by obscurity" is bad.
2. `/Get`, `/GetAll`, etc. are not RESTful.

**Comment by katsenkatorz** [comment]
No, I want to make the documentation public and the method call accessible by the token.

the screen is just an example of what I want. It does not come from a symfony application

**Comment by teohhanhui** [comment]
Did you follow this guide? https://api-platform.com/docs/core/jwt/#jwt-authentication

**Comment by teohhanhui** [comment]
```yaml
        main:
            anonymous: true
            pattern: ^/api
        api:
            pattern:   /api/*
```

This seems wrong. It'll always match the `main` firewall. You probably want to move the `main` firewall below the `api` firewall, and remove its pattern.
