### ISSUE TITLE
related entities not loaded?

### ISSUE THREAD

**Issue by yivi** [api-platform/api-platform#1143]
My entity has a Many2One relationship

```php
    /**
     * @var Industry
     *
     * @ORM\ManyToOne(targetEntity="Industry", fetch="EAGER")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="IndustryId", referencedColumnName="Id")
     * })
     */
    private $industry;
```

But when requesting from this resource, the related entities are not fetched.

The results would only include:

```json
  "industry": "/api/industries/1",
```

Instead of the whole entity.

I'm using the default configuration

```yaml
eager_loading:
        # To enable or disable eager loading.
        enabled: true

        # Fetch only partial data according to serialization groups.
        # If enabled, Doctrine ORM entities will not work as expected if any of the other fields are used.
        fetch_partial: false

        # Max number of joined relations before EagerLoading throws a RuntimeException.
        max_joins: 30

        # Force join on every relation.
        # If disabled, it will only join relations having the EAGER fetch mode.
        force_eager: true
```

which makes the `fetch="EAGER"` annotation redundant, yet I added it to see if it made any difference.

I could only got to get the related entities by creating a serialization group and adding each of the properties on the related entity to that group. While it works, it seems a bit convoluted, and from what I gathered from documentation and configuration the relationships were going to be forced to be eager by API-Platform.

Am I missing something here?
