### ISSUE TITLE
Make sure there is a loader supporting the "api_platform" type.

### ISSUE THREAD

**Issue by shehi** [api-platform/api-platform#1156]
Today I started to switch from Annotation-based ORM definitions to the YML ones. Current situation:

```./api/config/package/doctrine.yaml```:
```
parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: 'mariadb-10.3.14'

        # With Symfony 3.3, remove the `resolve:` prefix
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/config/doctrine/orm'
                prefix: 'App\Entity'
                alias: App
```

```./api/config/routes/api_platform.yaml```:
```
api_platform:
    resource: .
    type: api_platform
    prefix: /api
```

```./api/config/doctrine/orm/User.orm.yml```:
```
User:
    type: entity
    table: user
    uniqueConstraints:
        USER_EMAIL_UNIQUE:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
        roles:
            type: json
            nullable: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        active:
            type: boolean
            nullable: false
            options:
                default: '0'
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
    lifecycleCallbacks: {  }
```
and finally my actually Entity class at ```./api/src/Entity/User.php```:
```
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiProperty;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class User implements UserInterface
{
    private $id;

    /**
     * @Assert\NotBlank()
     * @Assert\Email(
     *     message = "The email {{ value }} is not a valid email.",
     *     mode = "strict"
     * )
     */
    private $email;

    /**
     * @ApiProperty(
     *     iri="http://schema.org/ItemList",
     *     attributes={
     *         "itemListElement"={
     *             "@type"="http://schema.org/Text"
     *         }
     *     }
     * )
     */
    private $roles = [];

    /**
     * @var string The hashed password
     *
     * @Assert\NotBlank()
     */
    private $password;

    /**
     * @ApiProperty(iri="http://schema.org/Date")
     */
    private $lastLogin;

    /**
     * @ApiProperty(iri="http://schema.org/Boolean")
     */
    private $active = false;

    /**
     * @ApiProperty(iri="http://schema.org/dateCreated")
     */
    private $createdAt;

    /**
     * @ApiProperty(iri="http://schema.org/dateModified")
     */
    private $updatedAt;

    /**
     * @ApiProperty(iri="http://schema.org/Date")
     */
    private $deletedAt;

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @param string $email
     *
     * @return User
     */
    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        return $this->roles;
    }

    /**
     * @param array $roles
     *
     * @return User
     */
    public function setRoles(array $roles): self
    {
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';
        $this->roles = array_unique($roles);

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    /**
     * @param string $password
     *
     * @return User
     */
    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * {@inheritdoc}
     */
    public function getSalt(): ?string
    {
        return '';
    }

    /**
     * {@inheritdoc}
     */
    public function eraseCredentials(): void
    {
        // Do nothing.
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getLastLogin(): ?\DateTimeInterface
    {
        return $this->lastLogin;
    }

    /**
     * @param \DateTimeInterface|null $lastLogin
     *
     * @return User
     */
    public function setLastLogin(?\DateTimeInterface $lastLogin): self
    {
        $this->lastLogin = $lastLogin;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getActive(): ?bool
    {
        return $this->active;
    }

    /**
     * @param bool $active
     *
     * @return User
     */
    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTimeInterface $createdAt
     *
     * @return User
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTimeInterface|null $updatedAt
     *
     * @return User
     */
    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return \DateTimeInterface|null
     */
    public function getDeletedAt(): ?\DateTimeInterface
    {
        return $this->deletedAt;
    }

    /**
     * @param \DateTimeInterface|null $deletedAt
     *
     * @return User
     */
    public function setDeletedAt(?\DateTimeInterface $deletedAt): self
    {
        $this->deletedAt = $deletedAt;

        return $this;
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     *
     * @throws \Exception
     */
    public function touch(): void
    {
        $now = new \DateTimeImmutable();
        $this->setUpdatedAt($now);
        if (null === $this->getCreatedAt()) {
            $this->setCreatedAt($now);
        }
    }
}
```

I am getting this error when I try to reach API at: https://localhost:8443/api

![image](https://user-images.githubusercontent.com/653569/58473349-ace79f80-8148-11e9-955f-89622b279c72.png)

Before my switch to YML files everything was working smoothly. Any idea what am I doing wrong? Thanks!
