### ISSUE TITLE
Route not found NotFoundHttpException

### ISSUE THREAD

**Issue by mortalkiller** [api-platform/api-platform#1165]
Hi I'm facing a issue.

So I've a project that uses two databases.

I've changed my doctrine file to support multiple connections 

Doctrine.yaml
````
parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                driver: '%env(DATABASE_SERVER_DRIVER)%'
                server_version: '%env(DATABASE_SERVER_VERSION)%'

                # With Symfony 3.3, remove the `resolve:` prefix
                url: '%env(resolve:DATABASE_URL)%'
                # With Symfony 3.3, remove the `resolve:` prefix
                #        schema_filter: ~^(?![crm\_address\_contact|crm\_entity\_account\_address]).*$~
                mapping_types:
                    enum: string 
                charset:  UTF8
            main:
                # configure these for your database server
                driver: '%env(DATABASE_SERVER_DRIVER)%'
                server_version: '%env(DATABASE_SERVER_VERSION)%'

                # With Symfony 3.3, remove the `resolve:` prefix
                url: '%env(resolve:DATABASE_URL_MAIN)%'
                # With Symfony 3.3, remove the `resolve:` prefix
                #        schema_filter: ~^(?![crm\_address\_contact|crm\_entity\_account\_address]).*$~
                mapping_types:
                    enum: string
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
#                auto_mapping: true
                connection: default
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
#                        exclude: '%kernel.project_dir%/src/Entity/{Main}'
                        prefix: 'App\Entity'
                        alias: App
            main:
                naming_strategy: doctrine.orm.naming_strategy.underscore
#                auto_mapping: true
                connection: main
                mappings:
                    App\Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Main/Entity'
                        prefix: 'App\Main\Entity'
                        alias: App\Main

````

I create a folder to deal with the entities related to main connection api/src/Main/Entity

I've also add in api_platform.yaml
````
api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/config/api_platform/resources'
            - '%kernel.project_dir%/src/Main/Entity'
````

I've created an Entity for the Main connection

````
<?php

namespace App\Main\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * Tenants
 *
 * @ApiResource()
 * @ORM\Table(name="tenants", uniqueConstraints={@ORM\UniqueConstraint(name="tenants_slug_uindex", columns={"slug"}), @ORM\UniqueConstraint(name="tenants_bucket_uindex", columns={"bucket"}), @ORM\UniqueConstraint(name="tenants_db_name_uindex", columns={"db_name"}), @ORM\UniqueConstraint(name="tenants_domain_uindex", columns={"domain"})})
 * @ORM\Entity
 */
class Tenants
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="slug", type="string", length=50, nullable=false)
     */
    private $slug;

    /**
     * @var bool
     *
     * @ORM\Column(name="active", type="boolean", nullable=false)
     */
    private $active = '0';

    /**
     * @var bool
     *
     * @ORM\Column(name="scheduled", type="boolean", nullable=false, options={"default"="1"})
     */
    private $scheduled = '1';

    /**
     * @var string
     *
     * @ORM\Column(name="domain", type="string", length=191, nullable=false)
     */
    private $domain;

    /**
     * @var string
     *
     * @ORM\Column(name="db_name", type="string", length=60, nullable=false)
     */
    private $dbName;

    /**
     * @var string
     *
     * @ORM\Column(name="db_username", type="string", length=50, nullable=false)
     */
    private $dbUsername;

    /**
     * @var string
     *
     * @ORM\Column(name="db_pass", type="string", length=60, nullable=false)
     */
    private $dbPass;

    /**
     * @var string|null
     *
     * @ORM\Column(name="bucket", type="string", length=60, nullable=true)
     */
    private $bucket;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created_at", type="datetime", nullable=false)
     */
    private $createdAt;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="updated_at", type="datetime", nullable=true)
     */
    private $updatedAt;


}
````

I've debug the router ``docker-compose exec php php bin/console debug:router`` and the routes where created correctly:
 api_tenants_get_collection                                    GET      ANY      ANY    /tenants.{_format}
  api_tenants_post_collection                                   POST     ANY      ANY    /tenants.{_format}
  api_tenants_get_item                                          GET      ANY      ANY    /tenants/{id}.{_format}
  api_tenants_delete_item                                       DELETE   ANY      ANY    /tenants/{id}.{_format}
  api_tenants_put_item                                          PUT      ANY      ANY    /tenants/{id}.{_format}

However when I try send a request to the endpoint I receive the following error:

No route found for "GET /tenants"

What I'm missing or doing wrong?

Thank you!
