### ISSUE TITLE
Serialized output of custom operation broke after upgrading to 2.4

### ISSUE THREAD

**Issue by DieterVanmoortel** [api-platform/api-platform#1172]
I was running api-platform/core 2.4.4 & api-platform/api-pack 1.2.0
I had a custom operation to show the children of an entity. Below is a simplified version, but I used variations of this concept on various occasions.

It was defined in config
```
    App\Entity\Parent:
        properties:
            analyses:
                subresource:
                    resource: 'App\Entity\Child'
                    collection: true
        itemOperations:
            get: ~
            history:
                path: '/parents/{id}/children'
                controller: App\Action\ParentChildAction
                method: 'GET'
```
and the controllerAction was easy as : 
```
class ParentChildAction
{
    public function __invoke(Parent $data)
    {
        return  $data->getChildren();
    }
}
```
Before upgrading to 2.4, this worked flawlessly and gave me the serialized list of children, but after the upgrade serialization fails with error **"The object is of class CHILD and does not match the resource_class PARENT"**, which is exactly the point of this operation...

Wasted some time trying to debug this, but in the end I just reverted to core 2.3.6.
