### ISSUE TITLE
Generation doc for nested DTO objects

### ISSUE THREAD

**Issue by YuriyChmil** [api-platform/api-platform#1202]
Hello. I am using DTO for GET methods. All work fine except documentation.
I have 3 levels of nested objects (relations). And for nested objects in swagger describe like simple string. 
How I describe nested DTO ?. I have tried to use a **swagger_context** but it not useful for those kinds of nested DTO.
Are any possibility to use  references **$ref** like in Swagger or something similar ?

**Comment by mindaugasbarysas** [comment]
Yes! You just need to dive into the source itself: at `api-platform/core/src/Swagger/Serializer/DocumentationNormalizer.php:685` you'll find that if `true === $readableLink`, a $ref will be generated. `$type` comes from `@var` annotation. So to get it into documentation you need to:
```
    /**
     * @Groups({"choice:read", "quizStep:read"})
     *
     * @ApiProperty(readableLink=true)
     *
     * @var \Full\Namespace\To\DTO\IngredientAliasDTO
     */
    private $ingredientAlias;
```

and you should be good.

It is definitely a sign of good documentation is when someone has to go and read the source code in order to do somewhat trivial things. /s

Sorry about that last snark, but I just spent 4 hours trying to figure out the solution to the same problem.

**Comment by FabienSalles** [comment]
I had a similar problem and the solution wasn't obvious when we use yaml configuration and a little bit weird : 

I have 2 resources link to 2 output DTOs : 

```yaml
Domain\Product\Entity\ProductVariant:
    collectionOperations:
        get: ~
    itemOperations:
        get: ~
    attributes:
        output: Domain\Product\DTO\ProductVariantOutput
        normalization_context:
            jsonld_has_context: true

Domain\Product\Entity\ProductOptionValue:
    collectionOperations:
        get: ~
    itemOperations:
        get: ~
    attributes:
        output: Domain\Product\DTO\ProductOptionValueOutput
        normalization_context:
            jsonld_has_context: true
```
```php
<?php

namespace Domain\Product\DTO;

use Domain\Product\Entity\ProductOptionValue;

class ProductVariantOutput
{
    /** @var string */
    public $code;

    /** @var string */
    public $position;

    /** @var \DateTimeInterface */
    public $createdAt;

    /** @var \DateTimeInterface */
    public $updatedAt;

    /** @var ProductOptionValue[] */
    public $optionsValues;
}

```
```php
<?php

namespace Domain\Product\DTO;

class ProductOptionValueOutput
{
    /** @var string */
    public $code;

    /** @var string */
    public $optionCode;

    /** @var integer */
    public $position;
}
```

With this configuration, my documentation show an array of string type for my ProductOptionValue nested object : 

```json
{
  "code": "string",
  "position": "string",
  "createdAt": "string",
  "updatedAt": "string",
  "optionsValues": [
    "string"
  ]
}
```

I thought naively that I could configure my output properties directly on my resource but it does not seem to be connected. I have the impression that the configuration of the properties acts only on the properties of the resource not of the output DTO. If I do that : 

```yaml
Domain\Product\Entity\ProductVariant:
    collectionOperations:
        get: ~
    itemOperations:
        get: ~
    attributes:
        output: Domain\Product\DTO\ProductVariantOutput
        normalization_context:
            jsonld_has_context: true
    properties:
        optionsValues:
            readableLink: true

Domain\Product\Entity\ProductOptionValue:
    collectionOperations:
        get: ~
    itemOperations:
        get: ~
    attributes:
        output: Domain\Product\DTO\ProductOptionValueOutput
        normalization_context:
            jsonld_has_context: true
```
**Nothing changes.**

In order to link my properties configuration to my DTO, I have to simulate my DTO like an other resource like this : 

```yaml
Domain\Product\Entity\ProductVariant:
    collectionOperations:
        get: ~
    itemOperations:
        get: ~
    attributes:
        output: Domain\Product\DTO\ProductVariantOutput
        normalization_context:
            jsonld_has_context: true
            
Domain\Product\DTO\ProductVariantOutput:
    collectionOperations: []
    itemOperations: []
    properties:
        optionsValues:
            readableLink: true

Domain\Product\Entity\ProductOptionValue:
    collectionOperations:
        get: ~
    itemOperations:
        get: ~
    attributes:
        output: Domain\Product\DTO\ProductOptionValueOutput
        normalization_context:
            jsonld_has_context: true
    
```

With this configuration and the same classes than before I have the correct swagger documentation : 

```json
{
  "code": "string",
  "position": "string",
  "createdAt": "string",
  "updatedAt": "string",
  "optionsValues": [
    {
      "code": "string",
      "optionCode": "string",
      "position": 0
    }
  ]
}
```

Is there a more logical way to arrive at the same result with a yaml configuration and avoid declaring my DTO as a resource?

**Comment by FabienSalles** [comment]
I found a solution but I'm afraid to discover again new problems in the future...

I stopped using my entity as resource. Instead  I used directly my output DTO. So I had to create my own ItemDataProvider and transform myself the entity return by my repository to my output DTO.

```yaml
Domain\Product\DTO\ProductVariantOutput:
    shortName: ProductVariant
    collectionOperations:
        get: ~
    itemOperations:
        get: ~
    attributes:
        normalization_context:
            jsonld_has_context: true
    properties:
        code:
            identifier: true
        optionsValues:
            readableLink: true

Domain\Product\Entity\ProductOptionValue:
    collectionOperations:
        get: ~
    itemOperations:
        get: ~
    attributes:
        output: Domain\Product\DTO\ProductOptionValueOutput
        normalization_context:
            jsonld_has_context: true
```

```php
final class ProductVariantItemDataProvider implements ItemDataProviderInterface, RestrictedDataProviderInterface
{
    /** @var ProductVariantRepository */
    private $productVariantRepository;

    /** @var DataTransformerRegistryInterface */
    private $dataTransformerRegistry;

    public function __construct(ProductVariantRepository $productVariantRepository, DataTransformerRegistryInterface $dataTransformerRegistry)
    {
        $this->productVariantRepository = $productVariantRepository;
        $this->dataTransformerRegistry = $dataTransformerRegistry;
    }

    public function supports(string $resourceClass, string $operationName = null, array $context = []): bool
    {
        return ProductVariantOutput::class === $resourceClass;
    }

    /**
     * {@inheritDoc}
     * @throws UnexpectedResultException
     * @throws NotFoundException
     */
    public function getItem(string $resourceClass, $id, string $operationName = null, array $context = []): ?object
    {
        return $this->dataTransformerRegistry->transform($this->productVariantRepository->findOneByCode($id), ProductVariantOutput::class);
    }
}
```

Now I had to handle when entity is not found and the CollectionDataProvider.

Is there a better solution ?

**Comment by marcusesa** [comment]
I am dealing the same problem, using `DTO` approach I can not declare relation between `DTO's`, the result is always an array of strings instead of an array of objects.

**Comment by henry2778** [comment]
Also had that issue with "string" instead object. The following code worked for me
```
properties:
        season:
            attributes:
                readableLink: true
                swagger_context:
                    type: object
        pushNotifications:
            attributes:
                readableLink: true
                swagger_context:
                    type: array
                    items:
                        type: object
```

Result:

```
"season": {},
"pushNotifications": [
  {}
],
```

**Comment by soyuka** [comment]
Thanks! Would you help us improve the documentation?

**Comment by mindaugasbarysas** [comment]
Would be happy to help, actually.

**Comment by mkrauser** [comment]
I also have this problem. I'm using a model consisting of many popo classes and only the top level class is an api-platform-resource. The data are provided as json documents from external sources and we just want to provide an API-Endpoint to get them. 
This works fine with a customer DataProvider, except the OpenAPI-Documentation shows the child-objects having the type "string", which is not correct. 

Using readableLink only works (for me at least), if the target object type is an ApiResource too (see [AnnotationResourceMetadataFactory.php#L58](https://github.com/api-platform/core/blob/d8e624ba242593365773ec8070d92f548f77d575/src/Metadata/Resource/Factory/AnnotationResourceMetadataFactory.php#L58)).

I don't think, this is just a documentation issue. In my case, I want to generate the OpenAPI documentation of the whole object model, but only the top-level-class should be exposed as ApiResource. Handling this with a SwaggerDecorator is certainly possible, but tedious and redundant, since the Classes itself provide enough information already.

This functionality does not exist so far, am I wrong?

**Comment by FabienSalles** [comment]
Hello @soyuka,

Further to our discussion, I didn't find a solution for my problem. I use yml in order to declare my ressources and decide to not use DTOs as ressources and have to define data providers and filters. 

I let my entities as ressources with DTOs and data tranformers, used Doctrine data providers and filters and I still have this problem.

**Comment by er1z** [comment]
@mindaugasbarysas — you're my hero!

**Comment by vzhurin** [comment]
Any news on this issue?
Really there is no way to get the generated Swagger documentation for nested objects that are not resources?

**Comment by teohhanhui** [comment]
It should have been fixed by #3309 (You need to use version `2.5.x-dev` of `api-platform/core` for now).

Please let us know if you're still having any issues with this.

**Comment by embargo2710** [comment]
> It should have been fixed by [api-platform/core#3309](https://github.com/api-platform/core/pull/3309) (You need to use version `2.5.x-dev` of `api-platform/core` for now).
> 
> Please let us know if you're still having any issues with this.

@teohhanhui Hi. I have the same issue with api-platform/core v2.5.3.

In my case: `OfferSearchOutput` (DTO, not resource) defined as output for custom operation. I have some nested DTO's.

```
itemOperations:
        searchByTerm:
            output: App\DTO\OfferSearchOutput
```
`OfferSearchOutput` has field like this with get/set methods:

```
 /**
  * @var OfferOutput[]
  */
 private array $offers;
```

and `OfferOutput` with some not important fields (in fact with another compex DTO's).

As result i have this generated docs, field `offers` as array of strings instead of array of my DTO:

```
{
...
"offers": [
   "string"
]
}
```

But when i tested API - all denormalization process works fine.

Can you help me?

**Comment by fgamess** [comment]
Hi @teohhanhui  I confirm that I have the same issue with api-platform/core v2.5.4.

**Comment by sfi-fgarnier** [comment]
Hi @teohhanhui I still have the same issue with api-platform/core v2.5.4.

**Comment by h3llr4iser** [comment]
If someone want to document with swagger I have found a solution:
Add this for input:
```
"$ref"="#/components/schemas/OrderItem-order:write" 
```
Add this for output:
```
"$ref"="#/components/schemas/OrderItem-order:read" 
```

"OrderItem-xxxx:xxxx" depends on your normalization_context or denormalization_context, you can see in swagger.json file in components -> schema

```php
   /**
     * @ApiProperty(
     *     readableLink=true,
     *     attributes={
     *         "openapi_context"={
     *             "type"="array",
     *             "items"={
     *                 "type"="object",
     *                 "$ref"="#/components/schemas/OrderItem-order:read",
     *             }
     *         }
     *     }
     * )
     *
     * @var OrderItem[]
     */
    private $items;
```

If OrderItem is not a resource you can create your own swagger decorator and add your custom schema for OrderItem:

More info for swagger decorator:
https://api-platform.com/docs/core/jwt/#documenting-the-authentication-mechanism-with-swaggeropen-api
https://api-platform.com/docs/core/swagger/#overriding-the-openapi-specification

``` php
 $docs['components']['schemas']['OrderItem-order:read'] = [
                 'description' =>  'Your description',
                'type' => 'object',
                /* How to document an object see https://swagger.io/docs/specification/data-models/data-types/#object*/
            ];
```

**Comment by tuancode** [comment]
Is there a proper way to add @ApiResource to a DTO by yaml configuration so far? I couldn't find a way.

**Comment by denisancelle** [comment]
> Is there a proper way to add @ApiResource to a DTO by yaml configuration so far? I'm struggling with that.

Same question but with @ApiProperty for DTO in Yaml configuration ?

**Comment by fgamess** [comment]
@tuancode @denisancelle 

you have examples here showing how to define operations in YAML: https://api-platform.com/docs/core/operations/

in the examples, entities are used but you can use any PHP classes to achieve that (DTO for example). I use DTO regularly and I don't have any issues

**Comment by h3llr4iser** [comment]
@tuancode @denisancelle Dont forget to add mapping in api_platform configuration:

```yaml
api_platform:
  mapping:
    paths:
      - '%kernel.project_dir%/config/api_platform/resources'
```
