### ISSUE TITLE
[Question] Multiple elastic search instances

### ISSUE THREAD

**Issue by dParadiz** [api-platform/api-platform#1203]
Is there any way to configure elastic search to use multiple instances?
Some thing like this:
```yaml
api_platform:
  elasticsearch:
    instance_1:
       hosts: ['host1']
       mapping:
         App\Resource\Foo:
           index: foo-index
    instance_2:
       hosts: ['host2']
       mapping:
         App\Resource\Bar:
           index: bar-index
```
