### ISSUE TITLE
How to give a custom name to a Dto model

### ISSUE THREAD

**Issue by juanpablomorenomartin** [api-platform/api-platform#1225]
When I use a Dto in the models of the api documentation, the name of the Dto is documented as follows, Customer: 01d691680190c1b19dfee75af0f2e292, it is possible to customize this name to Customer: Input or anything else.

This is the configuration of my resource:

```
App\Entity\Customer\Customer:
    collectionOperations:
        register:
            method: POST
            path: /register
            controller: App\Controller\ShopApi\Customer\RegisterCustomerAction
            input:
                class: App\Dto\RegisterCustomerRequest
                name: RegisterCustomerRequest
    itemOperations:
        get:
            normalization_context:
                jsonld_embed_context: true
                groups: ['customer:read']
                swagger_definition_name: CustomerResponse

```

But then in the api doc I get as a model:
```
Customer:01d691680190c1b19dfee75af0f2e292 {
    email*	string
    plainPassword*	string
    firstName*	string
    lastName*	string
   gender*	string
   identificationNumber*	string
   typeIdentificationNumber*	string
   subscribedToNewsletter	boolean
   confirmTermsConditions	boolean
   addressAlias	string
   address*	string
   countryCode*	string
   provinceCode	string
   provinceName	string
   city*	string
   postcode*	string
   phoneNumber*	string
}
```
