### ISSUE TITLE
[Question] Partial search filter in YML

### ISSUE THREAD

**Issue by JuanWilde** [api-platform/api-platform#1231]
I'd like to use this configuration but using the YAML approach. I was trying different things but without success. Any help will be appreciated
```
<?php
// api/src/Entity/Offer.php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiFilter;
use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;

/**
 * @ApiResource()
 * @ApiFilter(SearchFilter::class, properties={"id": "exact", "price": "exact", "description": "partial"})
 */
class Offer
{
    // ...
}
```

This is my resource configuration
```
App\Entity\Company:
  attributes:
    normalization_context:
      groups: ['company_read']
    filters:
      - ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter
  collectionOperations:
    get:
      method: 'GET'
      access_control: 'is_granted("COMPANY_READ")'
  itemOperations:
    get:
      method: 'GET'
      access_control: 'is_granted("COMPANY_READ")'
```

And this is the config in services.yml
```
    # Filters
    ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\DateFilter:
        tags: ['api_platform.filter']

    ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter:
        tags: ['api_platform.filter']

    ApiPlatform\Core\Serializer\Filter\PropertyFilter:
        tags: ['api_platform.filter']
```

With this config the search filter is working, but just in the exact mode, not partial

**Comment by JuanWilde** [comment]
Well, I've managed to solve it. It is important to know that if you are using `_instanceof:` in your `services.yml` file, you must create a new YML file to store this filters and then import the file

`services.yml`
```
imports:
    - { resource: api_platform/filters/custom-filters.yml }
...
...
services:
    _instanceof:
            App\Api\Listener\PreWriteListener:
                tags:
                    - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 33 }
```
`custom-filters.yml`
```
services:
  app.company.search_filter:
    parent: 'api_platform.doctrine.orm.search_filter'
    arguments:
      - { id: exact, name: partial }
    tags:
      - { name: 'api_platform.filter', id: 'company.search_filter' }
    autowire: false
    autoconfigure: false
```

And finally in your resources file:
`resources.yaml`
```
App\Entity\Company:
  attributes:
    normalization_context:
      groups: ['company_read']
    filters:
      - company.search_filter
  collectionOperations:
    get:
      method: 'GET'
      access_control: 'is_granted("COMPANY_READ")'
  itemOperations:
    get:
      method: 'GET'
      access_control: 'is_granted("COMPANY_READ")'
```

These tips are not in any part of the documentation, so hope this can help someone :)
