### ISSUE TITLE
PHP with xdebug on separate container

### ISSUE THREAD

**Issue by Brewal** [api-platform/api-platform#1240]
I'm trying to setup XDebug on a separate php container so I can use it only when I want. 
I followed [the documentation](https://api-platform.com/docs/distribution/debugging/) about debugging, but instead of using a `docker-compose.override.yml`, I added a new service in `docker-compose.yml` : 

```yaml
php_debug:
    image: ${CONTAINER_REGISTRY_BASE}/php
    build:
      context: ./api
      target: api_platform_php_dev
      <<: *cache
    depends_on:
      - db
    # Comment out these volumes in production
    volumes:
      - ./api:/srv/api:rw,cached
      # If you develop on Linux, uncomment the following line to use a bind-mounted host directory instead
      # - ./api/var:/srv/api/var:rw
    environment:
      # See https://docs.docker.com/docker-for-mac/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host
      # See https://github.com/docker/for-linux/issues/264
      # The `remote_host` below may optionally be replaced with `remote_connect_back`
      XDEBUG_CONFIG: >-
        remote_enable=1
        remote_host=host.docker.internal
        remote_connect_back=1
        remote_port=9000
        idekey=PHPSTORM
      # This should correspond to the server declared in PHPStorm `Preferences | Languages & Frameworks | PHP | Servers`
      # Then PHPStorm will use the corresponding path mappings
      PHP_IDE_CONFIG: serverName=api-platform
```

This does build, but XDebug doesn't seems to be installed in the `php_debug` service (after executing `php -i` directly from the container). 
Is there something more to do ?
