### ISSUE TITLE
ApiPlatform bypassing configuration made through YAML files?

### ISSUE THREAD

**Issue by rperezmira** [api-platform/api-platform#1245]
I am using Api Platform in a project and this is what I have installed:

```
api-platform/api-pack               v1.2.0
api-platform/core                   v2.4.6
```

I have made several changes through YAML files for the API as for example:

```
api_platform:
    enable_nelmio_api_doc: false
    enable_swagger_ui: false
    enable_re_doc: true
    formats:
        json: ['application/json']
        html: ['text/html']
    mapping:
        paths:
           - '%kernel.project_dir%/config/packages/api_resources/Case/CaseManagement/case_assign.yaml'
    resource_class_directories:
        - '%kernel.project_dir%/Entity'
    graphql:
        graphiql:
            enabled: '%show_graphiql%'
```

From what is above I would expect not to have Nelmio Api enabled or at least shown once I access the Swagger UI but that is not true since I am still able to see NelmioDocBundle handling the UI. Am I missing something here? 

> Note: ApiPlatform is great but Documentation is not, it is really hard to find a fully example using OpenAPI v3 or for how to change the default OpenAPI v2 to v3 and trivial things that should be documented.
