### ISSUE TITLE
[#Graphql, #Serializer] Serializer Groups for Graphql dont's works

### ISSUE THREAD

**Issue by nietzscheson** [api-platform/api-platform#1246]
I have API-Platform installed with:

```yml
"api-platform/api-pack": "^1.2"
```

Following the Api-Platform documentation ([graphql](https://api-platform.com/docs/core/graphql/) and [serialization process](https://api-platform.com/docs/core/serialization/)) I'm trying setup the project's entities with the next configuration:

```yml
### config/api_platform/
resources:
    App\Entity\Commercial\Address:
        properties:
            id:
                identifier: true
        graphql:
            query:
                normalization_context:
                    groups: ['graphql']

### config/serialization/
App\Entity\Address:
    attributes:
        firstName:
            groups: ['graphql']
```
But not works:

<img width="1676" alt="api-platform" src="https://user-images.githubusercontent.com/1699198/64921039-aa569780-d783-11e9-9630-bf357390d92f.png">

Without serializer groups works correctly:
<img width="1680" alt="api-platform-done" src="https://user-images.githubusercontent.com/1699198/64921066-fdc8e580-d783-11e9-98ea-79e421dc2097.png">
