### ISSUE TITLE
Resource context not built correctly when extending another entity

### ISSUE THREAD

**Issue by Brewal** [api-platform/api-platform#1247]
I used [single table inheritance](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/inheritance-mapping.html#single-table-inheritance) and tried to [extend the json-ld context](https://api-platform.com/docs/core/extending-jsonld-context/) of some properties of the child entity (with yaml files) :

**Customer**

```php
<?php

namespace App\Entity;

// uses ...

/**
 * @ORM\Entity(repositoryClass="App\Repository\CustomerRepository")
 * @ORM\Table(name="user")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({"customer" = "Customer", "vendor" = "Vendor"})
 */
class Customer
{
    use Id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastName;
    
    // ...

}
```

**Vendor**

```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VendorRepository")
 */
class Vendor extends Customer
{
}
```

**Customer resource config**

```yaml
App\Entity\Customer:
    properties:
        email:
            attributes:
                jsonld_context:
                    searchable: "partial"
```

**Vendor resource config**

```yaml
App\Entity\Vendor:
    properties:
        email:
            attributes:
                jsonld_context:
                    searchable: "partial"
```

The `/contexts/Customer` url is correctly building the context, but the `/contexts/Vendor` url is ignoring the configuration. 

I found a workaround by specifying attributes in the child entity : 

```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VendorRepository")
 */
class Vendor extends Customer
{
    private $email;
}
```
