### ISSUE TITLE
[Swagger-UI] no JSON body sent on operations using self-defined swagger parameters in body

### ISSUE THREAD

**Issue by fgamess** [api-platform/api-platform#1305]
**API Platform version(s) affected**: 2.5.0

**Description**  
I think there is a regression. Let me explain:

Since I updated to API Platform core 2.5, every operation configured with `swagger_context` and JSON body in the request, does not send any JSON body using the **Try it out/Execute** feature of the OpenAPI/Swagger UI.

I say again every endpoint using this kind of swagger context does not have a JSON body when trying it directly on the documentation.

I also tried to downgrade to **api-platform/core:2.4.7**, it is working so the issue happens using **api-platform/core:2.5.0**

Also auto-generated POST endpoints are working, so it truly happens when defining body parameter under `swagger_context:` > `parameters:`

I guess it is related to swagger/openapi

**How to reproduce**  
```
            swagger_context:
                summary: "My summary"
                parameters:
                    - in: body
                      name: my_ressource
                      description: body description
                      schema:
                          type: object
                          required:
                              - field1
                              - field2
                          properties:
                              field1:
                                  type: string
                                  example: example
                              field2:
                                  type: string
                                  example: example
                                  
```

When I use the button *Try it out* visible on the endpoint documentation and then I click on *Execute*, I see that the Curl request sent is:

```
curl -X POST "http://my-endpoint/api/v1/login" -H  "accept: application/json" -H  "Content-Type: application/json"
```

As you can see there is no JSON body.
And I receive such JSON response:

```
{
  "type": "https://tools.ietf.org/html/rfc2616#section-10",
  "title": "An error occurred",
  "detail": "Invalid JSON.",
}
```
**Possible Solution**  
Not explored yet

**Additional Context**
