### ISSUE TITLE
Serialization groups and validation question.

### ISSUE THREAD

**Issue by abeal-hottomali** [api-platform/api-platform#1330]
Hi all,

I have a question about the use of serialization groups with validation.  I'm wanting to see if the path I'm going down is one that the core team would consider viable, or see inherent problems with.

I currently have a custom context builder (decorates `SerializerContextBuilderInterface`), which is responsible for adding serialization groups to a given request based on both the roles of the logged in user, and a series of custom voters (which are invoked at that same point).  This works fine.

Now, for one of my entities, I'm using a symfony assertion, `NotBlank`, called during a `post` operation, set up as the API-platform documentation suggests.  I'm getting an objection from the API that I'm not passing a value (even though I am), and the reason I'm getting it (I'm 95% sure) is that the logged in user does not have the correct serialization groups assigned, so the value passed in the `Request` is not forwarded along as part of the serialized object.

By way of example:

Entity "Foo" has the properties "name" and "email", with the serialization groups:
```yaml
        name:
            groups:
                - 'admin:foo:post'
                - 'foo:patch'
                - 'foo:get'
                - 'foo:list'
                - 'admin:foo:delete'
         email:
             groups:
                - 'foo:post'
                - 'foo:patch'
                - 'foo:get'
                - 'foo:list'
                - 'admin:foo:delete'
```
If a user has permission to perform the given op on `foo`, then they get the group `foo:[opname]`, e.g. `foo:post` or `foo:get`.  If they also have the role `ROLE_ADMIN`, then they also get the group `admin:foo:[opname]`.  This allows the ability to grant a user access to write to an entity for a given operation, but restrict access to certain properties to those users who also have a given role in the system.

Now, if I log into a non-admin user, and pass the following:

```json
{
    "name": "Foo (faker) Facere repellendus quis adipisci.",
    "email": "kale.witting@example.com"
}
```

The user is granted access to `POST` an email value, but not to `POST` a name.  The email value is propagated to the nascent object, but the name is not.  The symfony core assertion then fails due to the missing value.

I've hit this pain point in several different fashions before, and I'd like to do something about it.  The best thing I can think to do is to write my own custom validation that runs before the other ones, and compares the serialization groups assigned to the entity metadata from the ones generated in the context builder I set up initially.  This way, I could get ahead of the validation failure from a missing value, by generating a validation failure that the user does not have permission to modify a property they're trying to modify.

My question is just this: Would you encourage the use of a custom validator to verify property access, given that properties may be denied via serialization groups?  Or is there a better place to hook in?

I know a lot of this may need particulars on my given build.  I've tried to follow either SymfonyCasts or API-platform documentation whenever possible in my construction.  Advice would be welcome, and thank you in advance.
