### ISSUE TITLE
Deserialization of DTO input for custom operation 

### ISSUE THREAD

**Issue by yivi** [api-platform/api-platform#1349]
**Description**  
I'm not entirely sure if this is a bug report (which I imagine unlikely), a feature request, or simply a misunderstanding of the documentation on my part.

**Example**  
I'm trying a little custom operation over an existing api resource, which should receive a DTO as input parameter.

I've described the operation like this:

```yml
App\Domain\Entity\Invoice:
  collectionOperations:
    credit_note:
      input: App\Application\Invoice\CreateCreditNoteRequest
      method: POST
      path: /invoices/credit_note
      controller: App\Infrastructure\Http\ApiResource\CreateCreditNote
```

This seems to be picked up correctly by the doc generator, and it shows me the structure for `CreateCreditNoteRequest` in the new action:

<img width="354" alt="image" src="https://user-images.githubusercontent.com/1815039/69903819-ff777200-139e-11ea-93a6-86b70a85619a.png">

However, when submitting the request, it fails because it attempts to deserialize the payload into 
`App\Domain\Entity\Invoice` instead of `App\Application\Invoice\CreateCreditNoteRequest`.

I've trying debugging the process, and I've gotten to `DeserializeListener:107`, that says:

```php
$request->attributes->set(
    'data',
    $this->serializer->deserialize($request->getContent(), $context['resource_class'], $format, $context)
);
```

So no matter what input we declared, it will always try to deserialize to the resource class.

As an experiment, I've changed it to:

```php
 $request->attributes->set(
     'data',
     $this->serializer->deserialize(
         $request->getContent(),
         $context['input']['class'] ?? $context['resource_class'],
         $format,
         $context)
  );
```

(Attempt to deserialize to `input.class` if declared, or continue with `resource_class` otherwise).

Is there another way to accomplish this? If not, wouldn't the above be more practical to handle this scenario? The alternative I've found is to disable deserialization altogether, and handle it myself, but it doesn't smell very good.
