### ISSUE TITLE
The service "serializer.name_converter.metadata_aware" has a dependency...

### ISSUE THREAD

**Issue by lukepass** [api-platform/api-platform#1354]
**API Platform version(s) affected**: 1.2

**Description**  
I tried to follow the following guide to enable snake case converter:

https://api-platform.com/docs/core/serialization/#name-conversion

Unfortunately it gives me the following error:

```
The service "serializer.name_converter.metadata_aware" has a dependency on a non-existent service "Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter".
```

This class exists (I use the Symfony serializer) but it cannot be found.

**How to reproduce**  
See above.

**Additional Context**  
My config:

```
api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
```
