### ISSUE TITLE
Docs say "patch" is buildin when using json+ld, but it seems not to be

### ISSUE THREAD

**Issue by leberknecht** [api-platform/api-platform#1360]
Ahoi, 

it says on https://api-platform.com/docs/core/operations/ 
> (PATCH is also supported when using the JSON API format, as required by the specification).
I have 
```yaml
api_platform:
[...]
    formats:
      jsonld:   ['application/ld+json']
```
in my config and a resource definition:
```
App\Entity\Segment:
  itemOperations:
    patch:
      access_control: is_granted('ROLE_ADMIN')
```
which results in 
```
@context | "/contexts/Error"
-- | --
@type | "hydra:Error"
hydra:title | "An error occurred"
hydra:description | "The route \"patch\" does not exist."
```
So i guess the docs are outdated and `PATCH` isnt supported as build-in any longer?
