### ISSUE TITLE
Identifier for inheritance entities

### ISSUE THREAD

**Issue by mbdax034** [api-platform/api-platform#1362]
Hello,

**API Platform version(s) affected**: 1.2.0
**Description**  
Custom Identifier work only for parent entities. If i have some subclasses, id is used as identifier instead of custom identifier

**How to reproduce**  

```php
class Profile{
 protected $id;
 private $username;

}


class Professor extends Profile{
 protected $id:
}

class Student extends Profile{
 protected $id:
}

```
In resources.yaml

``` yaml

App\Entity\Profile:
        properties:
              id:
                    identifier: false
              username:
                    identifier: true


App\Entity\Student:
        properties:
              id:
                    identifier: false
              username:
                    identifier: true

```

**GET /api/profiles**

``` json
{
"@context": "/api/contexts/Profile",
"@id": "/api/profiles",
"@type": "hydra:Collection",
"hydra:member": [
  {
      "@id": "/api/profiles/test_123",
      "@type": "Profile",
      "id": 2,
      "username": "test_123"
  },
  {
      "@id": "/api/Student/55",
      "@type": "Student",
      "id": 55,
      "username": "student_55"
  },

```

**Possible Solution**  

**GET /api/profiles**

``` json
{
"@context": "/api/contexts/Profile",
"@id": "/api/profiles",
"@type": "hydra:Collection",
"hydra:member": [
  {
      "@id": "/api/profiles/test_123",
      "@type": "Profile",
      "id": 2,
      "username": "test_123"
  },
  {
      "@id": "/api/Student/student_55",
      "@type": "Student",
      "id": 55,
      "username": "student_55"
  },

```
