### ISSUE TITLE
Result OpenAPI file doesn't contain field's values restrictions based on validator setting

### ISSUE THREAD

**Issue by alebedev80** [api-platform/api-platform#1365]
**API Platform version(s) affected**: 2.4

**Description**  
Result OpenAPI file doesn't contain field's values restrictions based on validator's setting.

**How to reproduce**  
Create a validator per the resource, e.g. config/validator/groups.yaml:
```
alebedev80\common\entities\test\Group:
    nameA:
      - Length:
          max: 50
```
Validator is working well.
But OpenAPI spec contain only field's type: 

```
"name_a": {
     "type": "string"
}
```

Is it bug, or my mistake or feature doesn't implemented yet?
