### ISSUE TITLE
How do I configure which attribute is the hydra "@id"

### ISSUE THREAD

**Issue by sschueller** [api-platform/api-platform#140]
Hi,

How do I configure which attribute in my Entity is used for the @id via YAML (without annotations). I have a custom DataProvider like in the example docs but all my api responses have the same "@id". Shouldn't the "@id" be unique for each? This is what I get:

```
{
  "@context": "/contexts/Person",
  "@id": "/people",
  "@type": "hydra:Collection",
  "hydra:member": [
    {
      "@id": "/people/",
      "@type": "http://schema.org/Person",
      "id": 1,
      "givenName": "John",
      "familyName": ""
    },
    {
      "@id": "/people/",
      "@type": "http://schema.org/Person",
      "id": 2,
      "givenName": "Jane",
      "familyName": ""
    }
  ],
  "hydra:totalItems": 2
}
```

Thanks

**Comment by teohhanhui** [comment]
Yes, `@id` should be a unique IRI.

Please provide more info to help in troubleshooting:

* Your custom data provider, if possible
* Your resource configuration in YAML (that's what you're using, right?)

**Comment by sschueller** [comment]
api/src/AppBundle/Resources/config/api_resources.yml
```
person:
    class: 'AppBundle\Entity\Person'
    shortName: 'Person' # optional
    description: 'A Person' # optional
    iri: 'http://schema.org/Person' # optional
    attributes: # optional
        pagination_items_per_page: 25 # optional
```

api/app/config/services.yml
```
services:
    person.collection_data_provider:
        class: 'AppBundle\DataProvider\PersonsCollectionDataProvider'
        tags:
            -  { name: 'api_platform.collection_data_provider' }
    person.item_data_provider:
        class: 'AppBundle\DataProvider\PersonItemDataProvider'
        tags:
            -  { name: 'api_platform.item_data_provider' }
```


api/src/AppBundle/DataProvider/PersonsCollectionDataProvider.php
```
<?php

namespace AppBundle\DataProvider;

use AppBundle\Entity\Person;
use ApiPlatform\Core\DataProvider\CollectionDataProviderInterface;
use ApiPlatform\Core\Exception\ResourceClassNotSupportedException;

final class PersonsCollectionDataProvider implements CollectionDataProviderInterface
{
    public function getCollection(string $resourceClass, string $operationName = null)
    {
        if (Person::class !== $resourceClass) {
            throw new ResourceClassNotSupportedException();
        }

        $person1 = new Person();
        $person1->setId(1);
        $person1->setFamilyName('john');

        $person2 = new Person();
        $person2->setId(2);
        $person2->setFamilyName('jane');

        // Retrieve the blog post collection from somewhere
        return [$person1, $person2];
    }
}

```

api/src/AppBundle/Entity/Person.php
```
<?php

namespace AppBundle\Entity;


class Person
{

    private $id;

    private $givenName = '';

    private $familyName = '';

    public function __construct()
    {

    }

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getGivenName(): string
    {
        return $this->givenName;
    }

    /**
     * @param string $givenName
     */
    public function setGivenName(string $givenName)
    {
        $this->givenName = $givenName;
    }

    /**
     * @return string
     */
    public function getFamilyName(): string
    {
        return $this->familyName;
    }

    /**
     * @param string $familyName
     */
    public function setFamilyName(string $familyName)
    {
        $this->familyName = $familyName;
    }
}
```

Thanks
