### ISSUE TITLE
ConstraintViolationList got Error 500 using validation groups

### ISSUE THREAD

**Issue by wow-apps** [api-platform/api-platform#1431]
**API Platform version(s) affected**: 2.5.4

**Description**  
I have entity with unique `string` property. When I try to `POST` this entity with exists key, I get next error:

```
{
  @context": "\/contexts\/ConstraintViolationList",
  "@type": "ConstraintViolationList",
  "hydra:title": "An error occurred",
  ...
}
```

Looks good, **but** when I'm adding validation group to `POST`, I'm getting MySQL error:

```
{
  "@context": "\/contexts\/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "An exception occurred while executing 'INSERT INTO countries (iso_code, name, created_at, updated_at) VALUES (?, ?, ?, ?)' with params [\"FR\", \"France\", \"2020-02-25 20:46:42\", null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'FR' for key 'countries.PRIMARY'",
}
```

**How to reproduce**  
_config/api/country.yaml_

```
resources:
  Api\Entity\Country:
    properties:
      isoCode:
        identifier: true
    attributes:
      pagination_items_per_page: 25
    collectionOperations:
      get:
        normalization_context:
          groups: ['v1_get_collection']
      post:
        validation_groups: ['v1_post_validation']
        normalization_context:
          groups: ['v1_post_collection_response']
        denormalization_context:
          groups: ['v1_post_collection_request']
    itemOperations:
      ...
```

_config/validator/country.yaml_
```
Api\Entity\Country:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: isoCode
  properties:
    isoCode:
      - NotBlank:
          groups: ['v1_post_validation', 'v1_put_validation']
      - Type:
          type: 'string'
          groups: ['v1_post_validation', 'v1_put_validation']
      - Length:
          min: 2
          max: 2
          minMessage: 'Country ISO code must be at least {{ limit }} characters long'
          maxMessage: 'Country ISO code cannot be longer than {{ limit }} characters'
          groups: ['v1_post_validation', 'v1_put_validation']
    name:
      - NotBlank:
          groups: ['v1_post_validation', 'v1_put_validation']
      - Type:
          type: 'string'
          groups: ['v1_post_validation', 'v1_put_validation']
      - Length:
          min: 2
          max: 255
          minMessage: 'Country name must be at least {{ limit }} characters long'
          maxMessage: 'Country name cannot be longer than {{ limit }} characters'
          groups: ['v1_post_validation', 'v1_put_validation']
```

_src/Entity/Country.php_
```
<?php

namespace Api\Entity;

use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Exception;

/**
 * @ORM\Table(
 *     name="countries",
 *     indexes={
 *         @ORM\Index(name="countries_iso_code_uindex", columns={"iso_code"})
 *     }
 * )
 * @ORM\Entity(repositoryClass="Api\Repository\CountryRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Country
{
    /**
     * @var string
     * @ORM\Id
     * @ORM\Column(type="string", length=2)
     */
    private $isoCode;

    /**
     * @var string
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    ...

    public function getIsoCode(): string
    {
        return $this->isoCode;
    }

    public function setIsoCode(string $isoCode): Country
    {
        $this->isoCode = $isoCode;

        return $this;
    }

    ...
}
```

**Additional Context**  
If we'll remove: `collectionOperations.post.validation_groups: ['v1_post_validation']` from `config/api/country.yaml` everything goes ok....

Any ideas? Bug or I do something wrong?
