### ISSUE TITLE
Multiple primary key with swagger - getting error

### ISSUE THREAD

**Issue by wow-apps** [api-platform/api-platform#1436]
I'm trying to add second field into parameters without custom controller for entity with multiple primary key and getting error ...

**Now step-by-step:**

> _DB table:_

```
create table measure_types
(
    id                varchar(10)  not null,
    language_iso_code varchar(2)   not null,
    label             varchar(255) null,
    created_at        datetime     not null,
    updated_at        datetime     null,
    constraint measure_types_id_language_iso_code_uindex
        unique (id, language_iso_code),
    constraint measure_types_languages_iso_code_fk
        foreign key (language_iso_code) references languages (iso_code)
);

alter table measure_types
    add primary key (id, language_iso_code);


```

> _src/Entity/MeasureType.php_

```
<?php

namespace Api\Entity;

use DateTime;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use Exception;

/**
 * @ORM\Table(
 *     name="measure_types",
 *     indexes={
 *         @ORM\Index(name="measure_types_uindex", columns={"id", "language_iso_code"})
 *     },
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="measure_types_uindex", columns={"id", "language_iso_code"})
 *     }
 * )
 * @ORM\Entity(repositoryClass="Klarstein\Api\Repository\MeasureTypeRepository")
 * @ORM\HasLifecycleCallbacks
 */
class MeasureType
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="string", length=10)
     */
    private string $id;

    /**
     * @ORM\Id()
     * @ORM\ManyToOne(targetEntity="Language", fetch="EAGER")
     * @ORM\JoinColumn(name="language_iso_code", referencedColumnName="iso_code")
     */
    private Language $language;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private string $label;

    /**
     * @ORM\Column(type="datetime")
     */
    private DateTimeInterface $createdAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private ?DateTimeInterface $updatedAt;

    public function __construct()
    {
        $this->createdAt = new DateTime();
    }

    /**
     * @ORM\PreUpdate
     *
     * @throws Exception
     */
    public function onPutHandler(): void
    {
        $this->updatedAt = new DateTime();
    }

    // ... under this comment getters and setters
}
```

> _config/api/measure_type.yaml_

```
resources:
  Api\Entity\MeasureType:
    properties:
      id:
        identifier: true
      language:
        identifier: true
    attributes:
      pagination_items_per_page: 25
    collectionOperations:
      get:
        normalization_context:
          groups: ['v1_get_collection']
      post:
        normalization_context:
          groups: ['v1_post_collection_response']
        denormalization_context:
          groups: ['v1_post_collection_request']
    itemOperations:
      get:
        method: 'GET'
        normalization_context:
          groups: ['v1_get_item']
      put:
        normalization_context:
          groups: ['v1_put_item_response']
        denormalization_context:
          groups: ['v1_put_item_request']
      delete:
        denormalization_context:
          groups: ['v1_delete_item']
```

It's work, for current moment:

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/2779949/75476986-36602280-59a4-11ea-8ebf-e1806d6247b5.png">

**But** i want to show in doc, that, I expect for 2 parameters as identifier.

What I'm doing:

> Adding: `path: '/measure_types/id={id};language={language}'` to `config/api/measure_type.yaml`

```
resources:
  Api\Entity\MeasureType:
    properties:
      id:
        identifier: true
      language:
        identifier: true
    attributes:
      pagination_items_per_page: 25
    collectionOperations:
      get:
        normalization_context:
          groups: ['v1_get_collection']
      post:
        normalization_context:
          groups: ['v1_post_collection_response']
        denormalization_context:
          groups: ['v1_post_collection_request']
    itemOperations:
      get:
        method: 'GET'
        path: '/measure_types/id={id};language={language}'
        normalization_context:
          groups: ['v1_get_item']
      put:
        normalization_context:
          groups: ['v1_put_item_response']
        denormalization_context:
          groups: ['v1_put_item_request']
      delete:
        denormalization_context:
          groups: ['v1_delete_item']
```

> Next step: I have `SwaggerEventRequire` Decorator:
> 
> _src/Swagger/SwaggerEventRequireDecorator.php_

```
<?php

namespace Api\Swagger;

use Symfony\Component\Finder\Finder;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Symfony\Component\Yaml\Yaml;

final class SwaggerEventRequireDecorator implements NormalizerInterface
{
    private const SWAGGER_DECORATIONS = __DIR__ . '/../../config/swagger/';

    private NormalizerInterface $decorated;

    public function __construct(NormalizerInterface $decorated)
    {
        $this->decorated = $decorated;
    }

    public function normalize($object, string $format = null, array $context = [])
    {
        $docs = $this->decorated->normalize($object, $format, $context);

        $customDefinition = $this->loadDefinitions();

        foreach ($customDefinition as $path => $methods) {
            foreach ($methods as $method => $parameters) {
                foreach ($parameters as $paramKey => $paramValues) {
                    if (empty($paramValues['name'])) {
                        continue;
                    }

                    if (empty($docs['paths'][$path]) || empty($docs['paths'][$path][$method])) {
                        continue;
                    }

                    // e.g. remove an existing event parameter
                    $docs['paths'][$path][$method]['parameters'] = array_values(
                        array_filter(
                            $docs['paths'][$path][$method]['parameters'],
                            function ($param) use ($paramKey) {
                                return $param['name'] !== $paramKey;
                            }
                        )
                    );

                    // e.g. add the new definition for event
                    $docs['paths'][$path][$method]['parameters'][] = $paramValues;
                }
            }
        }

        return $docs;
    }

    public function supportsNormalization($data, string $format = null)
    {
        return $this->decorated->supportsNormalization($data, $format);
    }

    private function loadDefinitions(): array
    {
        $result = [];
        $finder = new Finder();
        $finder
            ->files()
            ->in(self::SWAGGER_DECORATIONS)
            ->name('*.yaml');

        foreach ($finder as $file) {
            $yaml = Yaml::parseFile(self::SWAGGER_DECORATIONS . $file->getFilename());
            if (empty($yaml)) {
                continue;
            }
            $result = array_unique(array_merge($result, $yaml), SORT_REGULAR);
        }

        return $result;
    }
}
```

and decoration config file: _config/swagger/measure_type.yaml_

```
/measure_types/id={id};language={language}:
  get:
    id:
      name: 'id'
      description: 'Measure type ID'
      in: 'path'
      required: true
      type: 'string'
      example: 'ml'
    language:
      name: 'language'
      description: 'Language ISO code'
      in: 'path'
      required: true
      type: 'string'
      example: 'de'
```

In a result, I got working form in doc, but wrong result:

<img width="1349" alt="image" src="https://user-images.githubusercontent.com/2779949/75477679-5e03ba80-59a5-11ea-97f5-6dad6cebe3c9.png">

I want to use it without custom controller, because I have many entities with multiple primary keys and adding controllers for each one will take a lot of time

What I do wrong?

P.S. @teohhanhui I hope you'll help me ASAP, cuz this point blocks everything ... please ... )

**Comment by wow-apps** [comment]
@dunglas 
Kevin, can you check that, please? I see, that nobody have ideas ... :(

**Comment by soyuka** [comment]
> I want to use it without custom controller, because I have many entities with multiple primary keys and adding controllers for each one will take a lot of time

Language should definitely not be handled like this IMHO. Anyway, our current Swagger implementation doesn't support multiple identifiers, feel free to submit a patch if you can make this work.

**Comment by dunglas** [comment]
I'm not sure, (@soyuka will probably have more hints), but it looks like the identifier should be URL encoded. It is in the first (native) version, but not in the yours. Can you try that?

Also, if you manage to get something working, we'll be glad to merge it in core!

**Comment by dunglas** [comment]
Regarding how languages should be handled, @soyuka is right, it would be better to use the `Accept-Language` HTTP headers in combination with JSON-LD language maps: https://w3c.github.io/json-ld-syntax/#language-maps

It's currently not supported natively, but can be added using decorators.

**Comment by wow-apps** [comment]
@dunglas 
@soyuka 

That's right, at first I made with `Accept-Language` but in that case, I need to build controllers for each entity and that's not so fast like using without it

**Comment by wow-apps** [comment]
```
    public function getContentPage(Request $request, string $id): ContentPage
    {
        $this->checkLanguageCountryHeader($request);
        $language = $this->getLanguage($request);
        $country = $this->getCountry($request);

        return $this->contentPageRepository->findOneBy(
            [
                'id' => $id,
                'country' => $country,
                'language' => $language,
            ]
        );
    }
```

**Comment by dunglas** [comment]
I would use a custom data provider instead

**Comment by wow-apps** [comment]
@dunglas 

Ok, that a good solution, but sorry for a stupid question, but how to get a `request` into Custom Data Provider - just inject it in `construct` and it will get current request or how?

**Comment by wow-apps** [comment]
@dunglas, @soyuka guys, can you review my solution?

I didn't find a way to provide headers from request to Custom Data Provider...
So, I make id transform using event subscribing ...

What do you think, is it the correct way to change request?

```php
<?php


namespace Api\EventSubscriber;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

abstract class AbstractAcceptLanguage
{
    protected function getLanguageIsoCode(Request $request)
    {
        return mb_substr($this->getLanguageCountry($request), 0, 2);
    }

    protected function getCountryIsoCode(Request $request)
    {
        return mb_substr($this->getLanguageCountry($request), 3);
    }

    private function getLanguageCountry(Request $request): string
    {
        $languageCountry = $request->getLanguages();
        if (empty($languageCountry)) {
            throw new NotFoundHttpException('Unknown language and country');
        }

        return $languageCountry[0];
    }
}
```

```php
<?php

namespace Api\EventSubscriber;

use Api\Entity\MeasureType;
use ApiPlatform\Core\EventListener\EventPriorities;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\KernelEvents;

final class MeasureTypeSubscriber extends AbstractAcceptLanguage implements EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        return [
            KernelEvents::REQUEST => ['extendResources', EventPriorities::PRE_READ]
        ];
    }

    public function extendResources(RequestEvent $event)
    {
        $request = $event->getRequest();
        $class = $request->attributes->get('_api_resource_class');

        if ($class === MeasureType::class && $request->attributes->has('_api_item_operation_name')) {
            $newId = sprintf(
                'id=%s;language=%s',
                $request->attributes->get('id'),
                $this->getLanguageIsoCode($request)
            );
            $request->attributes->set('id', $newId);

            $routeParams = $request->attributes->get('_route_params');
            $routeParams['id'] = $newId;
            $request->attributes->set('_route_params', $routeParams);
        }
    }
}
```

**Comment by soyuka** [comment]
This is acceptable indeed! For a general solution I'd probably avoid changing the request but instead adding this to my queries via an Extension or even directly through the data provider / persister.

**Comment by wow-apps** [comment]
@soyuka `Request` object has methods `->getLanguages` but it's not used in api-platform

**Comment by wow-apps** [comment]
Custom solution in https://github.com/api-platform/api-platform/issues/1436#issuecomment-594926239

**Comment by LazarevDA** [comment]
@wow-apps 
try it
```
    attributes:
      composite_identifier: false
```

It's work for me
```

class ProductWarehouse
{
    /**
     * @var Product
     * @ORM\Id()
     * @ORM\ManyToOne(targetEntity=Product::class, inversedBy="productWarehouses", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private Product $product;

    /**
     * @var Warehouse
     * @ORM\Id()
     * @ORM\ManyToOne(targetEntity=Warehouse::class, inversedBy="productWarehouses", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private Warehouse $warehouse;

 ....
```
```
resources:
      App\Entity\ProductWarehouse:
        attributes:
            composite_identifier: false
        collectionOperations:
            get:
                path: /warehouses
                method: GET
                controller: ApiPlatform\Core\Action\NotFoundAction
                read: false
                output: false
        itemOperations:
            get:
                path: /warehouse/{warehouse}/{product}
                method: GET
                input: App\DTO\WarehouseDto
            update:
                path: /warehouse/{warehouse}/{product}
                method: PUT
                input: App\DTO\WarehouseDto
                output: false
```
![image](https://user-images.githubusercontent.com/19623103/120476640-7be37a80-c3b3-11eb-9646-bcb000192d8d.png)
