### ISSUE TITLE
Allow to merge external OpenAPI/Swagger specs with non ApiResource routes

### ISSUE THREAD

**Issue by dvc** [api-platform/api-platform#1448]
Hello everybody!

**Description**  
It is all about ApiPlatform Swagger UI (like https://demo.api-platform.com/). 

Sometimes we need to:

1. Add some 3-rd party bundles routes ( LexikJWTAuthenticationBundle, FOSUserBundle, etc) to single Swagger interface
2. Add some legacy routes outside ApiPlatform app to single Swagger interface
3. Add some my routes, which doesn't looks like REST resource operations, to single Swagger interface. 

**Example**  

We need ability to /login (get JWT and refresh token). Our developers and testers uses Postman for that. And for rest other actions instead. It's ugly.
Login is special case - the best for me is interactive apply token after login. But i will glad for ability to configure this route manually as common use case (1).

We have some non REST routes. It is not intuitive to do them resource operations. But why not to add them to  Swagger UI?

And i have some legacy (Laravel and also fully custom) API routes without OpenApi Spec, which logically - a single monolith app with Symfony. And i want to write Specs for this routes and use as is before refactor/remove.

** Realization **

Custom specs should be separate files (yaml, json) for merging with ApiPlatform spec. With ApiPlatform spec priority.

Config may looks like:

```yaml
# api/config/packages/api_platform.yaml
api_platform:
    swagger:
        custom_specs_path: 
           - confing/swagger/my_routes.yaml
           - confing/swagger/bundle_routes.yaml
           - confing/swagger/legacy_routes.yaml
```

I don't know about client generator. May be some flag required for alien routes ignoring.
