### ISSUE TITLE
Not login to get token when connect direct localhost:8443

### ISSUE THREAD

**Issue by ilove3q** [api-platform/api-platform#1468]
I followed the tutorial, but I got this error:
![image](https://user-images.githubusercontent.com/36936865/77557183-be5d1d80-6eb9-11ea-8783-043aade1c0cf.png)
in the tutorial, it said an Authorize button would appear in Swagger UI but this didn't happen to me.
![image](https://user-images.githubusercontent.com/36936865/77557459-13009880-6eba-11ea-83bc-9591c2c0af51.png)
how can I log in and get the token?

my code:
Entity User
```
/**
 * @ApiResource(
 *     itemOperations={"GET"},
 *     collectionOperations={"POST", "GET"},
 *     normalizationContext={
 *          "groups" = {"read"}
 *     }
 * )
 * @ORM\Table(name="users")
 * @ORM\Entity()
 * @UniqueEntity("username")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"read"})
     */
    private $id;

    /**
     * @ORM\Column(name="username", type="string", length=255)
     * @Assert\NotBlank()
     * @Groups({"read"})
     */
    private $username;

    /**
     * @ORM\Column(name="password",type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Regex(
     *     pattern="/(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).{7,}/",
     *     message="Password must be seven characters long and contain at least one digit, one upper case letter and one lower case letter"
     * )
     */
    private $password;
...
}
```
api_platform.yaml
```
api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header

    # Mercure integration, remove if unwanted
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
```
security.yaml

```
security:
    encoders:
        App\Entity\User:
            algorithm: argon2i

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false
        main:
            stateless: true
            anonymous: true
            provider: app_user_provider
            json_login:
                check_path: /authentication_token
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY } # Allows accessing the Swagger UI
        - { path: ^/authentication_token, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
```
```
# routes.yaml
authentication_token:
    path: /authentication_token
    methods: ['POST']
```
