### ISSUE TITLE
Error 500 after disabling swagger and docs

### ISSUE THREAD

**Issue by krstns** [api-platform/api-platform#1504]
**API Platform version(s) affected**: 1.2.1

**Description**  
After disabling the swagger on prod I receive error 500 with the following written to logs:
`[2020-04-16 07:45:57] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Serializer\Exception\NotEncodableValueException: "Serialization for the format html is not supported" at /app/vendor/symfony/serializer/Serializer.php line 121 {"exception":"[object] (Symfony\\Component\\Serializer\\Exception\\NotEncodableValueException(code: 0): Serialization for the format html is not supported at /app/vendor/symfony/serializer/Serializer.php:121)"} []`

**How to reproduce**  
here's my config/packages/prod/api_platform.yml config for prod:
```
api_platform:
    enable_swagger: false
    enable_swagger_ui: false
    enable_re_doc: false
    show_webby: false
    enable_docs: false
    enable_profiler: false
    graphql:
        enabled: false
    collection:
        pagination:
            items_per_page: 30
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
```

Here's conig/routes.yml:
```
index:
    path: /
    controller: App\Controller\DefaultController::index
register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST
api:
  path: /auth
  controller: App\Controller\AuthController::api

login_check:
  path:     /login_check
  methods:  [POST]

swagger_ui:
  path: /docs
  controller: api_platform.swagger.action.ui
```
config/routes/api_platform.yml
```
api_platform:
    resource: .
    type: api_platform
    prefix: /

```

**Additional Context**  
I've seen 
https://github.com/api-platform/core/pull/841
https://github.com/api-platform/api-platform/issues/195

**Comment by dunglas** [comment]
Can you try to disable the HTML format too?

```yaml
api_platform:
    formats:
        jsonld:   ['application/ld+json']
```

**Comment by krstns** [comment]
hm,

i only use json, never ld+json.

**Comment by tekmi** [comment]
I have just experienced a similar issue. 

I've followed the @dunglas recommendation to disable the HTML format and it works! Thank you.

Here is the YAML configuration that worked for me.

```
api_platform:
    title: API Platform
    version: 0.1.0
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    # Enabling only JSON-LD and JSON formats while disabling HTML format
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
    
    # Disabling the displaying of the API documentation 
    enable_swagger_ui: false
    enable_re_doc: false
```
