### ISSUE TITLE
api_platform.mapping.paths Completely ignored

### ISSUE THREAD

**Issue by tebaly** [api-platform/api-platform#1515]
**API Platform version(s) affected**: 2.5.5

**Description**  
Hello.

With default config `config/packages/api_platform.yaml` 
```yaml
api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
```

I have some `autowire` and `autoconfigure` Bundles(installed in vendor) with 

```yaml
  Vendor\SomeBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity}'
```

Eventually: console command `debug:router` show absolutely ALL resources, from all installed Bundles (entity marked with \@ApiResource())

ignored any path in `resource`: `config/routes/api_platform.yaml`
```yaml
api_platform:
    resource: .
    type: api_platform
    prefix: /api
```

**Comment by tebaly** [comment]
Reconfig to 

```yaml
api_platform:
  mapping:
    paths: ['%kernel.project_dir%/config/resources.yaml']
```

```yaml
#config/resources.yaml
resources:
  App\Entity\City: ~
```
In this case: also load all resources **from all bundles**
**BUT**: Only `App\Entity\City` from App

---

1. How to disable loading of all resources from all bundles?
2. How to specify a specific path and prefix, like

```yaml
#config/routes/api_platform.yaml
api_platform:
    resource: '@BundleName/Entity' # eg
    type: api_platform
    prefix: /some/api 
```

**Comment by tebaly** [comment]
I think the "problem" is here

https://github.com/api-platform/core/blob/cfc05d1ce5e9e45898cb95ab71abf47e2d579da3/src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L275

And "here" https://github.com/api-platform/docs/blame/2.5/core/getting-started.md#L29

## Disable doctrine

https://github.com/api-platform/core/blob/cfc05d1ce5e9e45898cb95ab71abf47e2d579da3/src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L279

Option may be clearer.

```yaml
auto_mapping: true
# or
is_bundle: false
# or
bundles_auto_mapping: true
```
