### ISSUE TITLE
Custom paths not working in functional tests

### ISSUE THREAD

**Issue by JuanWilde** [api-platform/api-platform#1524]
**API Platform version(s) affected**: `api-platform/api-pack 1.2.2`

**Description**  
Update a path in resource.yaml makes functional tests to fail

**How to reproduce**  
Create a custom path in resources
```
post:
      method: 'POST'
      security: 'is_granted("BUSINESS_CREATE")'
      path: '/business' <- default is businesses
      denormalization_context:
        groups: ['business_post']
```

If I use Postman to create one it works
```
POST /api/v1/business
{
  "name": "string",
  "phone": "string",
  "address": "string",
  "postalCode": "string"
}
```
Run a tests with that path results in a HttpNotFoundException
```
$payload = [
            'name' => 'name',
            'phone' => '900222333',
            'address' => 'Fake street 321',
            'postalCode' => '22222',
        ];

self::$business->request(
            'POST',
            '/api/v1/business.jsonld',
            [],
            [],
            [],
            \json_encode($payload)
        );
```
Output:
```
No route found for "POST /api/v1/business.jsonld" (from "http://localhost/api/v1/users/login_check")
```

Other endpoints like
```
POST /api/v1/users.jsonld
```
are working fine because I didn't update the path in the resource file.
