### ISSUE TITLE
Using a DTO for batch operations

### ISSUE THREAD

**Issue by ctrl-f5** [api-platform/api-platform#1554]
There is some discussion on batch operations here https://github.com/api-platform/core/pull/1645

And the conclusion seems to be to just use DTOs for batch actions, so that's what I'm doing. But I can't get the DTO in my controller, it always want to deserialize it into the resource class, which ends up in a, Exception `Cannot create an instance of App\Entity\User from serialized data because its constructor requires parameter`

The way to disable this normalization is to configure `input: false`, but then the request body does not get converted to the DTO anymore...

So what's the DTO batch setup supposed to look like?

My current setup which produces the error looks like this:

```
# resource config
resources:
    App\Entity\User:
        collectionOperations:
            enabled:
                path: /users/enabled-batch
                method: PUT
                controller: App\Controller\User\EnableUserBatchController
                read: false
                input: App\DTO\User\UserEnabledBatchInput
                output: App\DTO\User\UserEnabledBatchOutput
                openapi_context:
                    summary: 'Updates enabled status of multiple User resources.'
```

```
# controller
class EnableUserBatchController extends AbstractController
{
    public function __invoke(UserEnabledbatchInput $data): UserEnabledBatchOutput
    { ... }
```

# input DTO
final class UserEnabledBatchInput
{
    /**
     * @Assert\All(
     *     @Assert\NotNull(),
     *     @Assert\Type("int")
     * )
     */
    public array $ids;

    /**
     * @Assert\NotNull()
     */
    public bool $enabled;
}
