### ISSUE TITLE
Denormalization for extended entities with relations that require constructor arguments

### ISSUE THREAD

**Issue by kelvin2200** [api-platform/api-platform#1583]
**API Platform version(s) affected**: latest

**Description**  
Custom denormalizers don't make use of autowiring for entities that have constructor arguments, much less for relations within said entity, to other entities that also require constructor args. This example illustrates the need to set some entity params that cannot be null and cannot be sent by the user either, to an entity that has constructor arguments.

**How to reproduce** 
EntityA.php
```php
/**
* @ORM\MappedSuperclass()
*/
class EntityA{
    
    private $createdBy;   

    public function __construct(Security $security) {
	$user = $security->getUser();
	$this->createdBy = $user ? $user->getId() : 0;// because it can't be null
    }
    // omitting getters, setters etc...
}
```
EntityB.php
```php
/**
* @ApiResource()
* @ORM\Entity(repositoryClass="App\Repository\EntityBRepository")
*/
class EntityB extends EntityA{
    public function __construct(Security $security) {
	parent::__construct($security);
    }

    /**
     * EntityC also extends EntityA thus it requires Security as a constructor arg
     * @var EntityC
     * @ORM\OneToOne(targetEntity="App\Entity\EntityC", cascade={"persist"})
     */
    private $relation;

    // omitting getters, setters etc...
}
```
A custom Denormalizer
```php

namespace App\Serializer\CustomDenormalizer

class CustomDenormalizer implements NormalizerInterface, DenormalizerInterface, SerializerAwareInterface {

    use SerializerAwareTrait;
    private $decorated;
    private $security;

    public function __construct(NormalizerInterface $decorated, Security $security) {
	if(!$decorated instanceof DenormalizerInterface){
	    throw new \InvalidArgumentException(__CLASS__.' normalizer must implement the DenormalizerInterface');
	}
	$this->decorated = $decorated;
	$this->security = $security;
    }

    public function denormalize($data, string $type, string $format = null, array $context = []) {
        // this is required for the entity being denormalized ($type)
        // and for all entities related to it
        // this can't possibly be the solution
        $context[AbstractItemNormalizer::DEFAULT_CONSTRUCTOR_ARGUMENTS] = [
            $type => ['security' => $this->security],
            'App\\Entity\\EntityC' => ['security' => $this->security],
            'Other\\Relation\\Namespace' => ['someParam' => 'string'] // just i.e.
        ];

        $obj = $this->decorated->denormalize($data, $type, $format, $context);
        // check for some weird condition
        $obj->setSomeVar();
        // do something else with the $obj
        return $obj;    
    }

    public function supportsDenormalization($data, string $type, string $format = null) {
	return $type == EntityB::class && $this->decorated->supportsDenormalization($data, $type, $format);
    }


    public function normalize($object, string $format = null, array $context = []) {
	return $this->decorated->normalize($object, $format, $context);
    }


    public function supportsNormalization($data, string $format = null) {
	return $this->decorated->supportsNormalization($data, $format);
    }

    public function setSerializer(SerializerInterface $serializer) {
	if($this->decorated instanceof SerializerAwareInterface){
	    $this->decorated->setSerializer($serializer);
	}
    }
}
```
Services declaration for the denormalizer
```yaml
 App\Serializer\CustomDenormalizer:
    decorates: 'api_platform.jsonld.normalizer.item'
    arguments: [ '@App\Serializer\CustomDenormalizer.inner' ]
    tags:
      - {name: serializer.normalizer}
```

**Possible Solution**  

1. Always update (manually) the denormalizer when adding or removing relations, (this can't possibly be right)
2. Drop constructor arguments altogether, since you can do whatever you want with the entity when denormalizing i.e. `$entity->setSomeSecurityBasedVar()`, (this still doesn't sound right because it requires you to have a custom denormalizer FOR EVERY entity that needs some "external" params.

**Additional Context**  
I remember reading that this IS the intended behavior in API Platform, but I must be missing something... surely there is an easier way.

Not related, but I'm also a bit confused about `normalization` in this case. Returning `false` from `supportsNormalization()` breaks normal API Platform behavior. I'm guessing the API Platform normalizer(s) don't get called, which makes sense since it does (duh) decorate the one in API Platform. Banged my head for a few hours before I discovered this was the reason that `@context` `@id` etc... were not being added to the JSONLD output anymore. Shouldn't just `this` normalizer be skipped if it doesn't support normalization?

I love that API Platform provides so many useful features, but this whole normalizing/denormalizing thing has got me scratching my head. The Docs are by far what they need to be.

**Comment by rugolinifr** [comment]
Indeed, this is the expected behaviour of api-platform and symfony. Entities are not supposed to be autowired.
Take a look at the **exclude** property:

```
# config/services.yaml
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
```

You can set the **createdBy** value by adding an [event listener](https://api-platform.com/docs/core/events/#custom-event-listeners) to your POST request lifecycle.
