### ISSUE TITLE
Attempted to load class "Debug" from namespace "GraphQL\Error".

### ISSUE THREAD

**Issue by moni1080** [api-platform/api-platform#1584]
Hi guys

I am working within API platform symfony 5 and want to enable GraphQL.
After I required the "webonyx/graphql-php" and "symfony/twig-pack"(needed for GraphQL interface) library with composer, I get the following error when I try to access "/api/graphql": "Attempted to load class "Debug" from namespace "GraphQL\Error". Did you forget a "use" statement for e.g. "Symfony\Component\ErrorHandler\Debug" or "Doctrine\Common\Util\Debug"?"

Here is also the configuration of the api platform(api_platform.yaml):

```yaml
api_platform:
    graphql:
        enabled: true
        graphiql:
            enabled: true
        graphql_playground:
            enabled: true
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        jsonld:
            mime_types:
                - application/ld+json
        json:
            mime_types:
                - application/json
        html:
            mime_types:
                - text/html
        jsonhal:
            mime_types:
                - application/hal+json
        csv:
            mime_types:
                - text/csv
        graphql: ["application/graphql"]
```
