### ISSUE TITLE
Profiler not working with custom authenticator

### ISSUE THREAD

**Issue by h3llr4iser** [api-platform/api-platform#1588]
**API Platform version(s) affected**: 2.5.6

**Description**  
Using a custom authenticator (Api key) profiler not registering the token to debug the request/ response. If I use lexik_jwt_authentication.jwt_token_authenticator the token is registered in profiler. 

The authentication works ok but I cant debug in profiler.  On authetication failure if I return a jsonResponse I cant not see in profiler But If I return an exception I can see in profiler.

When I authenticate successly I can see the correct response from api platform but nothing is registered in symfony profiler.

**How to reproduce**  
```yaml
  providers:
    app_auth_tokens:
      entity:
        class: App\Entity\Admin\AuthToken
        property: token
  firewalls:
    app_api:
      pattern: ^/api/v1
      host: ^((?!admin).)*$
      provider: app_auth_tokens
      stateless: true
      anonymous: false
      guard:
        authenticators:
          - App\Security\TokenAuthenticator
#    app_api_jwt:
#      pattern: ^/api/v1
#      host: ^((?!admin).)*$
#      stateless: true
#      anonymous: false
#      provider: app_users
#      guard:
#        authenticators:
#          - lexik_jwt_authentication.jwt_token_authenticator
```

```php
namespace App\Security;
class TokenAuthenticator extends AbstractGuardAuthenticator
{
    private $defaultEm;

    public function __construct(EntityManagerInterface $defaultEm)
    {
        $this->defaultEm = $defaultEm;
    }

    /**
     * Called on every request to decide if this authenticator should be
     * used for the request. Returning `false` will cause this authenticator
     * to be skipped.
     */
    public function supports(Request $request)
    {
        return $request->headers->has('X-AUTH-TOKEN');
    }

    /**
     * Called on every request. Return whatever credentials you want to
     * be passed to getUser() as $credentials.
     */
    public function getCredentials(Request $request)
    {
        return $request->headers->get('X-AUTH-TOKEN');
    }

    public function getUser($credentials, UserProviderInterface $userProvider)
    {

        if (null === $credentials) {
            throw new CustomUserMessageAuthenticationException(
                'Invalid API Token'
            );
        }

        $authToken =  $this->defaultEm->getRepository(AuthToken::class)
                                      ->findOneBy(['token' => $credentials])
        ;

        if (null === $authToken) {
            throw new CustomUserMessageAuthenticationException(
                'Invalid API Token'
            );
        }

        // if a User is returned, checkCredentials() is called
        return $authToken;
    }

    public function checkCredentials($credentials, UserInterface $user)
    {
        return true;
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        // on success, let the request continue
        return;
    }

    public function onAuthenticationFailure(Request $request, AuthenticationException $exception)
    {
        $data = [
            // you may want to customize or obfuscate the message first
            'message' => strtr($exception->getMessageKey(), $exception->getMessageData())

            // or to translate this message
            // $this->translator->trans($exception->getMessageKey(), $exception->getMessageData())
        ];



        return new JsonResponse($data, Response::HTTP_UNAUTHORIZED);
    }

    /**
     * Called when authentication is needed, but it's not sent
     */
    public function start(Request $request, AuthenticationException $authException = null)
    {
        $data = [
            // you might translate this message
            'message' => 'Authentication Required'
        ];

        return new JsonResponse($data, Response::HTTP_UNAUTHORIZED);
    }

    public function supportsRememberMe()
    {
        return false;
    }
}
```
