### ISSUE TITLE
Custom collection operation with POST method

### ISSUE THREAD

**Issue by abratko** [api-platform/api-platform#1597]
I have problem with custom controller for POST method.

I have entity with annotations and contoller

```php
/**
 * @file: src/Domain/Entity/Project.php
 **/
namespace App\Domain\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource(
 *     collectionOperations={
 *          "get"={
 *              "method"="GET",
 *              "access_control"="is_granted('ROLE_MANAGER') or is_granted('ROLE_ADMIN')",
 *              "path"="/projects",
 *              "controller"="\App\PresentationLayer\Controller\ProjectController"
 *          },
 *          "post"={
 *               "method"="POST",
 *              "access_control"="is_granted('ROLE_MANAGER') or is_granted('ROLE_ADMIN')",
 *              "path"="/projects",
 *              "controller"="\App\PresentationLayer\Controller\CreateProjectController"
 *          },
 *     },
 *     itemOperations={
 *          "delete"={
 *              "access_control"="is_granted('ROLE_MANAGER') or is_granted('ROLE_ADMIN')",
 *              "method"="DELETE"
 *          },
 *          "get"={
 *              "method"="GET"
 *          },
 *          "put"={
 *              "method"="PUT"
 *          }
 *     }
 * )
 * @ORM\Entity
 */
class Project extends DomainEntity
{
...
}
```

``` php
/**
 * @file: src/PresentationLayer/Controller/CreateProjectController.php
 **/
declare(strict_types=1);

namespace App\PresentationLayer\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class CreateProjectController extends AbstractController
{
    public function __invoke(Request $request)
    {
        return [];
    }
}
```
Then i do request 
```
POST http://localhost:8000/api/projects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "address": "Владивост ок Гоголя 38",
  "customerName": "Иванов Иван Иванович",
  "amountOfDeal": 12346
}
```
and get response 

```
"Cannot create an instance of App\\Domain\\Entity\\Project from serialized data because its constructor requires parameter "user" to be present."
```

So, default platform controller was called.

Why my controller not used?

I  tried [alternative method](https://api-platform.com/docs/core/controllers/#alternative-method) and it works. But using this method is not recommended.

Have i mistake in operation definition or it is bug?

**Comment by cavasinf** [comment]
Can you show us your `Project` AND `DomainEntity` constructor.

It's seems like you need a $user param in there.

**Comment by abratko** [comment]
Yes, constructor has param User $user

```php
    protected function __construct(User $user)
    {
        parent::__construct($user);
    }
```

Can't entity have constructor parameters? 

Problem is not in parameters. I want create custom controller for POST collection operation.

**Comment by rugolinifr** [comment]
You can't have constructor with parameters  within your entities.

Beside, i assume that your User class is both an entity and an UserInterface object. In that case, it is not autowired even in services and you should fetch it using the [Security service](https://symfony.com/doc/current/security.html#b-fetching-the-user-from-a-service).

Finally, the parameter within your CreateProjectController::__invoke() method [must be called **$data**](https://api-platform.com/docs/core/controllers/):

> Warning: the __invoke() method parameter MUST be called $data, otherwise, it will not be filled correctly!

**Comment by abratko** [comment]
> You can't have constructor with parameters within your entities.

is it a platform limitation?

> Finally, the parameter within your CreateProjectController::__invoke() method must be called $data:

 i tried to do it. it does not work.

How can i link entity with current user?

**Comment by rugolinifr** [comment]
> is it a platform limitation ?

It's the way entities work with symfony, they're meant to store data, not to act as services. They're _excluded_ from autowiring.
```
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
```

Note that doctrine does not call the constructor during deserialization.

> i tried to do it. it does not work.

It does. You just do it wrong. But you do not provide any error message so it's hard to say why.

> How can i link entity with current user?

By using a controller, an event subscriber or even custom data provider, depending your needs.

> How can i create custom controller for POST method?

It is very well explained [here](https://api-platform.com/docs/core/controllers/#creating-custom-operations-and-controllers).
