### ISSUE TITLE
Cannot load resource ".".

### ISSUE THREAD

**Issue by Aerendir** [api-platform/api-platform#161]
I'm trying to configure `api-platform/core` on an existing app.

Following [Installing API Platform Core](https://api-platform.com/docs/core/getting-started#installing-api-platform-core) I've set

```yaml
# app/config/routing.yml

api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api' # Optional
```

But, going to `127.0.0.1:8001/api` I receive the exception

> FileLoaderLoadException in Loader.php line 73:
> Cannot load resource ".".

What am I missing?
