### ISSUE TITLE
docker-compose stack on Traefik with https

### ISSUE THREAD

**Issue by gbourgeat** [api-platform/api-platform#1617]
**API Platform version(s) affected:** 2.5.6

**Description**
I try to use docker-compose stack with traefik and I am having issues with api/vulcain services

**How to reproduce**
I tried to add labels on vulcain service

```
    api:
        build:
            context: ./api
            target: stack_nginx
            <<: *api-cache-from
        depends_on:
            - php
        volumes:
            - ./api/public:/srv/api/public:ro

    vulcain:
        image: dunglas/vulcain
        environment:
            - CERT_FILE=/certs/localhost.crt
            - KEY_FILE=/certs/localhost.key
            - UPSTREAM=http://api
        depends_on:
            - api
            - traefik
        volumes:
            - dev-certs:/certs:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api-http.rule=Host(`api.stack.localhost`)"
            - "traefik.http.routers.api-http.entrypoints=http"
            - "traefik.http.routers.api-http.middlewares=redirect@file"
            - "traefik.http.routers.api-https.rule=Host(`api.stack.localhost`)"
            - "traefik.http.routers.api-https.entrypoints=https"
            - "traefik.http.routers.api-https.tls=true"
            - "traefik.http.services.api.loadbalancer.server.port=443"
```
Result on https://api.stack.localhost

```
Client sent an HTTP request to an HTTPS server.
```
Traefik logs:

```
time="2020-08-14T12:32:23Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6\"],\"Cache-Control\":[\"max-age=0\"],\"Cookie\":[\"_gcl_au=1.1.441923151.1597334928\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36\"],\"X-Forwarded-Host\":[\"vulcain.stack.localhost\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"2326c06272d4\"],\"X-Real-Ip\":[\"172.25.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"vulcain.stack.localhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.25.0.1:46926\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-08-14T12:32:23Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL="http://172.25.0.13:443" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6\"],\"Cache-Control\":[\"max-age=0\"],\"Cookie\":[\"_gcl_au=1.1.441923151.1597334928\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36\"],\"X-Forwarded-Host\":[\"vulcain.stack.localhost\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"2326c06272d4\"],\"X-Real-Ip\":[\"172.25.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"vulcain.stack.localhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.25.0.1:46926\",\"RequestURI\":\"/\",\"TLS\":null}"
2020/08/14 12:32:23 reverseproxy.go:445: httputil: ReverseProxy read error during body copy: read tcp 172.25.0.2:44316->172.25.0.13:443: read: connection reset by peer
time="2020-08-14T12:32:23Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6\"],\"Cache-Control\":[\"max-age=0\"],\"Cookie\":[\"_gcl_au=1.1.441923151.1597334928\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36\"],\"X-Forwarded-Host\":[\"vulcain.stack.localhost\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"2326c06272d4\"],\"X-Real-Ip\":[\"172.25.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"vulcain.stack.localhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.25.0.1:46926\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-08-14T12:32:23Z" level=debug msg="Request has been aborted [172.25.0.1:46926 - /]: net/http: abort Handler" middlewareName=traefik-internal-recovery middlewareType=Recovery
time="2020-08-14T12:32:23Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/favicon.ico\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6\"],\"Cache-Control\":[\"no-cache\"],\"Cookie\":[\"_gcl_au=1.1.441923151.1597334928\"],\"Pragma\":[\"no-cache\"],\"Referer\":[\"https://vulcain.stack.localhost/\"],\"Sec-Fetch-Dest\":[\"image\"],\"Sec-Fetch-Mode\":[\"no-cors\"],\"Sec-Fetch-Site\":[\"same-origin\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36\"],\"X-Forwarded-Host\":[\"vulcain.stack.localhost\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"2326c06272d4\"],\"X-Real-Ip\":[\"172.25.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"vulcain.stack.localhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.25.0.1:46926\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
time="2020-08-14T12:32:23Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL="http://172.25.0.13:443" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/favicon.ico\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6\"],\"Cache-Control\":[\"no-cache\"],\"Cookie\":[\"_gcl_au=1.1.441923151.1597334928\"],\"Pragma\":[\"no-cache\"],\"Referer\":[\"https://vulcain.stack.localhost/\"],\"Sec-Fetch-Dest\":[\"image\"],\"Sec-Fetch-Mode\":[\"no-cors\"],\"Sec-Fetch-Site\":[\"same-origin\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36\"],\"X-Forwarded-Host\":[\"vulcain.stack.localhost\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"2326c06272d4\"],\"X-Real-Ip\":[\"172.25.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"vulcain.stack.localhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.25.0.1:46926\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"
2020/08/14 12:32:23 reverseproxy.go:445: httputil: ReverseProxy read error during body copy: read tcp 172.25.0.2:44318->172.25.0.13:443: read: connection reset by peer
time="2020-08-14T12:32:23Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/favicon.ico\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"image/webp,image/apng,image/*,*/*;q=0.8\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6\"],\"Cache-Control\":[\"no-cache\"],\"Cookie\":[\"_gcl_au=1.1.441923151.1597334928\"],\"Pragma\":[\"no-cache\"],\"Referer\":[\"https://vulcain.stack.localhost/\"],\"Sec-Fetch-Dest\":[\"image\"],\"Sec-Fetch-Mode\":[\"no-cors\"],\"Sec-Fetch-Site\":[\"same-origin\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36\"],\"X-Forwarded-Host\":[\"vulcain.stack.localhost\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"2326c06272d4\"],\"X-Real-Ip\":[\"172.25.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"vulcain.stack.localhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.25.0.1:46926\",\"RequestURI\":\"/favicon.ico\",\"TLS\":null}"

```

So I tried without vulcain service:

```
    api:
        build:
            context: ./api
            target: stack_nginx
            <<: *api-cache-from
        depends_on:
            - php
        volumes:
            - ./api/public:/srv/api/public:ro
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.api-http.rule=Host(`api.stack.localhost`)"
            - "traefik.http.routers.api-http.entrypoints=http"
            - "traefik.http.routers.api-http.middlewares=redirect@file"
            - "traefik.http.routers.api-https.rule=Host(`api.stack.localhost`)"
            - "traefik.http.routers.api-https.entrypoints=https"
            - "traefik.http.routers.api-https.tls=true"
            - "traefik.http.services.api.loadbalancer.server.port=80"
```

Result on https://api.stack.localhost

```
500 Internal Server Error
openresty/1.15.8.3
```
Traefik logs:
```

time="2020-08-14T12:27:05Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL="http://172.25.0.10:80" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6\"],\"Cache-Control\":[\"max-age=0\"],\"Cookie\":[\"_gcl_au=1.1.441923151.1597334928\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36\"],\"X-Forwarded-Host\":[\"api.stack.localhost\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"2326c06272d4\"],\"X-Real-Ip\":[\"172.25.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"api.stack.localhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.25.0.1:46642\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-08-14T12:27:05Z" level=debug msg="vulcand/oxy/roundrobin/rr: completed ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6\"],\"Cache-Control\":[\"max-age=0\"],\"Cookie\":[\"_gcl_au=1.1.441923151.1597334928\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36\"],\"X-Forwarded-Host\":[\"api.stack.localhost\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"2326c06272d4\"],\"X-Real-Ip\":[\"172.25.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"api.stack.localhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.25.0.1:46642\",\"RequestURI\":\"/\",\"TLS\":null}"
time="2020-08-14T12:27:07Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{\"Method\":\"GET\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Accept\":[\"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\"],\"Accept-Encoding\":[\"gzip, deflate, br\"],\"Accept-Language\":[\"fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7,de;q=0.6\"],\"Cache-Control\":[\"max-age=0\"],\"Cookie\":[\"_gcl_au=1.1.441923151.1597334928\"],\"Sec-Fetch-Dest\":[\"document\"],\"Sec-Fetch-Mode\":[\"navigate\"],\"Sec-Fetch-Site\":[\"none\"],\"Sec-Fetch-User\":[\"?1\"],\"Upgrade-Insecure-Requests\":[\"1\"],\"User-Agent\":[\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36\"],\"X-Forwarded-Host\":[\"api.stack.localhost\"],\"X-Forwarded-Port\":[\"443\"],\"X-Forwarded-Proto\":[\"https\"],\"X-Forwarded-Server\":[\"2326c06272d4\"],\"X-Real-Ip\":[\"172.25.0.1\"]},\"ContentLength\":0,\"TransferEncoding\":null,\"Host\":\"api.stack.localhost\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.25.0.1:46642\",\"RequestURI\":\"/\",\"TLS\":null}"
```
