### ISSUE TITLE
[GraphQL] unable to embed relation and show fields other then the iri

### ISSUE THREAD

**Issue by JustDylan23** [api-platform/api-platform#1636]
v1.3.0

Hi, I have been trying to embed a relation into my query and fetch fields other then the id but it doesnt seem to work, I have my serialization groups set up correctly and there is no reason from my point of view why it shouldnbt work
`"Cannot query field \"title\" on type \"SongItem\"."`
I constantly get this error when I try to access any field in songs other then the id

```
{
  album(id: "/api/albums/1") {
    songs {
      edges {
        node {
          id
          title
        }
      }
    }
  }
}
```
my configuration in my album entity is as following
```
/**
 * @ApiResource(
 *     security="is_granted('ROLE_USER')",
 *     collectionOperations={
 *         "get"={
 *             "normalization_context"={
 *                 "groups"={"song:read", "song:collection:get"},
 *             },
 *         },
 *     },
 *     itemOperations={
 *         "get"={
 *             "normalization_context"={
 *                "groups"={"song:read", "song:item:get"},
 *             },
 *         },
 *     },
 *     graphql={
 *         "item_query"={"normalization_context"={"groups"={"song:read", "song:item:get"}}},
 *         "collection_query"={"normalization_context"={"groups"={"song:read", "song:collection:get"}}},
 *     },
 * )
 * @ApiFilter(PropertyFilter::class)
 * @ApiFilter(SearchFilter::class, properties={
 *     "title"="partial",
 * })
 *
 * @ORM\Entity(repositoryClass="App\Repository\SongRepository")
 */

/**
 * @ORM\OneToMany(targetEntity="App\Entity\Song", mappedBy="album", orphanRemoval=true)
 *
 * @Groups("album:read")
 */
private $songs;
```
and in my songs class I am properly exposing the title
```
/**
 * @ORM\Column(type="string", length=100)
 *
 * @Groups("album:read")
 *
 * @Assert\NotBlank
 * @Assert\Length(max=100)
 */
private $title;
```
```
api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    formats:
        jsonld:
            mime_types:
                - application/ld+json
        json:
            mime_types:
                - application/json
        html:
            mime_types:
                - text/html
        graphql:
            mime_types:
                - application/graphql
    collection:
        pagination:
            maximum_items_per_page: 50
            client_items_per_page: true
            items_per_page_parameter_name: itemsPerPage
```
