### ISSUE TITLE
Recommendation to disable autoconfigure in the core/serialization docs

### ISSUE THREAD

**Issue by denisvmedia** [api-platform/api-platform#1652]
[Here](https://api-platform.com/docs/core/serialization/#changing-the-serialization-context-dynamically) in the docs we have the following config example:

```yaml
# api/config/services.yaml
services:
    # ...
    'App\Serializer\BookContextBuilder':
        decorates: 'api_platform.serializer.context_builder'
        arguments: [ '@App\Serializer\BookContextBuilder.inner' ]
        autoconfigure: false
```

Could you please explain, why do we have to use `autoconfigure: false`? The docs don't say anything on this and for me it looks like a potential problem causer here.
