### ISSUE TITLE
API Filter not applied in GraphQL but in REST.

### ISSUE THREAD

**Issue by javajan** [api-platform/api-platform#1674]
**API Platform version(s) affected**: v2.5.7

**Description**  
API Filter not applied in GraphQL but in REST using yaml configuration. 

**How to reproduce**  
I registered a filter in services.yaml:
```
entry.search_filter:
    parent: 'api_platform.doctrine.orm.search_filter'
    arguments: [ { title: 'partial' } ]
    tags: [ { name: 'api_platform.filter', id: 'entry.search' } ]
```

Add filter to yaml resource configuration:
```
get:
      method: GET
      filters: ['entry.search']
      normalization_context:
        groups:
          - 'news_entry:read'

...

graphql:
    collection_query:
      filters: ['entry.search']
      normalization_context:
        groups: ['news_entry:read']
```

Search using REST:

```
curl -X GET "http://localhost:8000/api/news_entries?title=ipsum&page=1" -H  "accept: application/ld+json"

{
  "@context": "/api/contexts/NewsEntry",
  "@id": "/api/news_entries",
  "@type": "hydra:Collection",
  "hydra:member": [
    {
      "@id": "/api/news_entries/1",
      "@type": "NewsEntry",
      "createdBy": "/api/users/3",
      "category": "/api/news_categories/1",
      "title": "Vel ipsum velit velit recusandae aliquam.",
      "text": "A esse molestiae incidunt id sapiente quo. Voluptatem quis enim quos doloribus. Quasi sint est commodi. Cupiditate ratione numquam eos non. Dolores id asperiores vel et perferendis.",
      "createdAt": "2020-10-25T21:56:14+00:00",
      "updatedAt": "2020-10-25T21:56:14+00:00",
      "latitude": "-70.297666",
      "longitude": "85.283865",
      "commentCount": 0,
      "likeCount": 4
    },
    {
      "@id": "/api/news_entries/19",
      "@type": "NewsEntry",
      "createdBy": "/api/users/37",
      "category": "/api/news_categories/7",
      "title": "Aliquam illo et ipsum ab error.",
      "text": "Ex non expedita veritatis ut temporibus voluptatibus. Id alias sapiente dolorem nesciunt sequi amet distinctio. Eum delectus autem qui voluptatum maiores ut laboriosam. Non ipsa tenetur vero eos provident. Omnis enim eum ut distinctio labore vero eveniet adipisci.",
      "createdAt": "2020-10-25T21:56:14+00:00",
      "updatedAt": "2020-10-25T21:56:14+00:00",
      "latitude": "29.956390",
      "longitude": "49.940944",
      "commentCount": 1,
      "likeCount": 2
    }
  ],
  "hydra:totalItems": 2,
  "hydra:view": {
    "@id": "/api/news_entries?title=ipsum",
    "@type": "hydra:PartialCollectionView"
  },
  "hydra:search": {
    "@type": "hydra:IriTemplate",
    "hydra:template": "/api/news_entries{?title}",
    "hydra:variableRepresentation": "BasicRepresentation",
    "hydra:mapping": [
      {
        "@type": "IriTemplateMapping",
        "variable": "title",
        "property": "title",
        "required": false
      }
    ]
  }
}
```

Search using GraphQL:

```
{
  newsEntries(title: "ipsum") {
    edges {
      node {
        id
      }
    }
  }
}

{
  "data": {
    "newsEntries": {
      "edges": [
        {
          "node": {
            "id": "/api/news_entries/1"
          }
        },
        {
          "node": {
            "id": "/api/news_entries/2"
          }
        },
        {
          "node": {
            "id": "/api/news_entries/3"
          }
        },
        {
          "node": {
            "id": "/api/news_entries/4"
          }
        },
        {
          "node": {
            "id": "/api/news_entries/5"
          }
        },
        {
          "node": {
            "id": "/api/news_entries/6"
          }
        },
        {
          "node": {
            "id": "/api/news_entries/7"
          }
        },
        {
          "node": {
            "id": "/api/news_entries/8"
          }
        },
        {
          "node": {
            "id": "/api/news_entries/9"
          }
        },
        {
          "node": {
            "id": "/api/news_entries/10"
          }
        },
        ...
      ]
    }
  }
}
```

As you can see all entries are being returned in GraphQL. The Filter not being applied. I also tried creating a custom filter, where the `filterProperty` method is not being called.

This might not be a bug, but I followed the steps in the documentation. If it's not a bug, whats the easiest way to find out why the filter is not called?

**Possible Solution**  

**Additional Context**
