### ISSUE TITLE
Documentation for custom operation

### ISSUE THREAD

**Issue by svatok13** [api-platform/api-platform#17]
I have some operation, which allows me to add, edit and delete additional phones, emails and addresses for user. Here is example of operation: 
```yaml   
 resource.user_telephone.item_operation.put:
    class:   "Dunglas\ApiBundle\Api\Operation\Operation"
    public:  false
    factory: [ "@api.operation_factory", "createItemOperation" ]
    arguments:
      -    "@resource.user"      # Resource
      -    [ "PUT" ]                  # Methods
      -    "/users/{id}/phones/"     # Path
      -    SIPApiBundle:User:additionalTelephonePut  # Controller
      -    "user_additional_telephone_put"      # Route name
      -
        "@type": "hydra:Operation"
        "hydra:title": "Edit additional phone Operation"
        "returns": "xmls:string"
```
And here is my resource
```yaml
resource.user:
    parent:    "api.resource"
    arguments: [ "SIP\ResourceBundle\Entity\User\User" ]
    calls:
      - method:    "initNormalizationContext"
        arguments: [ { groups: [ "user_read" ] } ]
      - method:    "initDenormalizationContext"
        arguments: [ { groups: [ "user_write" ] } ]
      - method:    "initCollectionOperations"
        arguments:
          -
            - @resource.user_email.item_operation.put
            - @resource.user.collection_operation.post
            - @resource.user.collection_operation.get
            - @resource.user_collections.current_user
            - @resource.user_telephone.collection_operation.post
            - @resource.user_telephone.item_operation.put
            - @resource.user_telephone.item_operation.delete
            - @resource.user_email.collection_operation.post
            - @resource.user_email.item_operation.delete
            - @resource.user_address.collection_operation.post
            - @resource.user_address.item_operation.put
            - @resource.user_address.item_operation.delete
      - method:    "initFilters"
        arguments:
          -
           - @resource.user.search_filter
           - @resource.user.order_filter
    tags:      [ { name: "api.resource" } ]
```
How can i override generated  documentation, because it is incorrect for my method. I don`t need so much parameters. Also the title for method is generated by the firs declareted method, not for each one individually.
![]
(http://dl2.joxi.net/drive/0008/3161/568409/151005/ab9816b85d.png)
![]
(http://dl2.joxi.net/drive/0008/3161/568409/151005/07df222040.png)
