### ISSUE TITLE
Access to self-referenced ManyToOne relation owning side in POST method

### ISSUE THREAD

**Issue by parsllc** [api-platform/api-platform#1731]
I have created an entity as follows:
```
<?php
// src/Entity/Department

namespace App\Entity;

use App\Repository\DepartmentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ApiResource
 * @ORM\Entity(repositoryClass=DepartmentRepository::class)
 */
class Department
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     * @Groups("Create")
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity=Department::class, inversedBy="subsets")
     * @Groups("Create")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity=Department::class, mappedBy="parent")
     * @Groups("Create")
     */
    private $subsets;

    // ...
```

As you can see above, properties 'name', 'parent' and 'subsets' are in the serialization group 'Create'. Now please pay attention to POST endpoint Configuration:

```
# config/api_platform/department.yaml
App\Entity\Department2:
    normalization_context:
        groups: [ Read ]
    denormalization_context:
        groups: [ Create ]
    pagination_client_enabled: true
    pagination_items_per_page: 10
    collectionOperations:
        create:
            method: POST
            path: /create
            controller: App\Controller\Admin\CreateDepartmentController
            normalization_context:
                groups: Read
            denormalization_context:
                groups: Create
#...
```
According to the above configuration is expected the request body of the POST method includes 'name', 'parent' and 'subsets' properties. But only 'name' and 'subsets' properties are displayed in Swagger documentation. Do you know why?
