### ISSUE TITLE
2.6.0 Beta 1 Authentication_token route

### ISSUE THREAD

**Issue by Nayte91** [api-platform/api-platform#1733]
Hi there, 
On API-P 2.6 beta, I was trying to make authentication_token works by following the current tutorial at https://api-platform.com/docs/core/jwt and to be sure I'm not the problem, I made some tests with the simpliest setup possible (just a user class made with make:auth), on either 2.5 and 2.6 :

- It works perfectly on 2.5, from the beginning to the end of the tutorial,
- On 2.6, I block on the step https://api-platform.com/docs/core/jwt/#configuring-the-symfony-securitybundle because I can't reach the route /authentication_token with POST method, where I definitely can with 2.5 at the same step.

I'm not strong enough to correct this, not even to understand what is struggling: API-P 2.6 ? Symfony 5.2 ? PHP 8 ? New SwaggerUI version ? Maybe it's just about adapt the documentation along, I don't really know, but I made 2 small repo to compare 2.5 and 2.6 if you want to witness:

- https://github.com/Nayte91/apifive
- https://github.com/Nayte91/apisix

Maybe it's something very easy to fix, but I'm pretty sure it's not kind of a typing mistake on my side.

Note that produce 2 discrepancies if we follow the jwt tutorial page :

1. What I told about the /authentication_token route unreachable,
2. You can't make /authentication_token endpoint appears on SwaggerUI, with the Decorator class; That doesn't crash, that just doesn't appear.

Hope this can help to make 2.6 a blast,

**Comment by LeoBenoist** [comment]
I have upgraded to 1.6 and everything is working for me except Swagger Decorator. Meaning that it dont appear in Swagger html interface but it work properly.

I have 
```
# api/config/routes.yaml
authentication_token:
    path: /authentication/token
    methods: ['POST']
```

```
# api/config/packages/api_platform.yaml
api_platform:
    title: XXX API
    version: 0.0.1
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    # Good defaults value for REST APIs
    defaults:
        stateless: true
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    # Good cache defaults
    http_cache:
        vary: ['Content-Type', 'Authorization', 'Origin']
```

```
# security.yaml
security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider: # used to reload user from session & other features (e.g. switch_user)
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            stateless: true
            anonymous: true
            provider: app_user_provider
            json_login:
                check_path: /authentication/token
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
```
