### ISSUE TITLE
Fails when calculating security if TokenStorageInterface::getToken returns null

### ISSUE THREAD

**Issue by nathansalter** [api-platform/api-platform#1758]
**API Platform version(s) affected**: v2.5.9

**Description**  
If you're using the [updated](https://symfony.com/blog/new-in-symfony-5-1-updated-security-system) security component in Symfony versions >= 5.1, they have removed the 'anonymous user' concept. This means that if no one is logged in, `TokenStorageInterface::getToken` returns `null`. This works fine when `GET`ting, but on `POST`/`PATCH` it throws an error while trying to calculate the `security` attribute for an entity.

**How to reproduce**  
Given this entity:
```
/**
 * @ApiResource(
 *     attributes={"security"="is_granted('ROLE_USER')"}
 * )
 */
class Example {}
```

And this security config:
```
security:
  enable_authenticator_manager: true
  
  encoders:
    App\Entity\User:
      algorithm: auto

  providers:
    account_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    main:
      pattern: ^/
      entry_point: App\Security\JsonFormAuthenticator
      custom_authenticators:
        - App\Security\JsonFormAuthenticator
```

Send this request:
```
POST /examples HTTP/1.1
Content-Type: application/json

{}
```

Returns this:
```
HTTP/1.1 500 Internal Server Error
Content-Type: application/json

{
  "@context": "\/api\/contexts\/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "The current token must be set to use the \"security\" attribute (is the URL behind a firewall?)."
  ...
}
```

**Possible Solution**  
In `ApiPlatform\Core\Security\ResourceAccessChecker::isGranted`, when the `token` is null, it should just return `false` instead of throwing an exception.
