### ISSUE TITLE
Discriminated entities sometimes not returned fully / as expected

### ISSUE THREAD

**Issue by rkeet** [api-platform/api-platform#1807]
**API Platform version(s) affected**: 2.5.10

**Description**  
When using Discriminated Entities (using Doctrine Discriminator) the entities are not returned as expected when requesting them.

[I have created a repository demonstrating the problem.](https://github.com/rkeet/api-platform-discriminator-issue)

**How to reproduce**  

- Create an abstract Entity
- Have a few Entities extend from there 

**Issues**

- See (below) that properties defined in AbstractInput are not returned
- See that association _is_ returned (in `GET /forms` result), but the AbstractInput properties are not

**Additional Context**  
[Repository](https://github.com/rkeet/api-platform-discriminator-issue) >  All changes made to clean installation of Symfony 5.2.3 and ApiPlatform 2.5.10 are viewable in [this commit](https://github.com/rkeet/api-platform-discriminator-issue/commit/f20635c02045438ea035042b6e954a629c8a5a53). 

Project includes Postman configuration for easy import, a docker container for database and a ReadMe with steps to follow to setup and reproduce issue.

Showing missing properties in Workflow entity:
![image](https://user-images.githubusercontent.com/3327864/107344510-d3876e80-6ac2-11eb-8fdb-58528318365c.png)

Showing the same AbstractInput used for Form entity:
![image](https://user-images.githubusercontent.com/3327864/107344722-0cbfde80-6ac3-11eb-8795-fff14d48c712.png)

**Expected**

- Get all properties and associations returned from an Entity as a whole

**Comment by rkeet** [comment]
Whelp. Disregard this issue. I've been dumb. 

Turns out I configured wrong and did not clear cache every request causing me to see things that I didn't expect. 

For those running into things with discriminated entities:

- Define the discriminator map in the config for serialization
- Define each attribute on in the serialization per each inheriting class

For example shown in images above, config would be as following:

`file: serialization/Input.yaml`

```yaml
App\Entity\Input:
  discriminator_map:
    type_property: discr
    mapping:
      workflow: 'App\Entity\Workflow'
      form: 'App\Entity\Form'
# Discriminator class: do not define attributes to return, instead this must be done in every inheriting class config
```
`file: serialization/Form.yaml`
```yaml
App\Entity\Form:
  attributes:
    id:
      groups:
        - input-item
        - input-list
        - input-write
        - input-summary
    name:
      groups:
        - input-item
        - input-list
        - input-write
        - input-summary
    anothers:
      groups:
        - form-item
        - form-list
        - form-write
        - form-summary
    # Can choose to also return 'discr' property defined as discriminator if you want, make sure it has a `getDiscr` function available if you do though
```
Pretty much same for Workflow entity. 

And for some sake: clear the cache!
