### ISSUE TITLE
GraphQL Serieliazer cannot Resolve nested Objects from ES Support

### ISSUE THREAD

**Issue by lukaszgoworko** [api-platform/api-platform#1809]
**API Platform version(s) affected**: 2.6.2
**ES**: 7.10.1
**PHP**: 7.4

**Description**  
Tried to use ES Support as described in the [documentaion](https://api-platform.com/docs/core/elasticsearch/). Getting an Error on GraphQL serializer, when trying to get collection of tweets nested in user as tweets field.

**How to reproduce**  

* Create this documents (needed to add a param to ES query):
```json
PUT tweet?include_type_name=true
{
  "mappings": {
    "_doc": {
      "properties": {
        "id": {
          "type": "keyword"
        },
        "author": {
          "properties": {
            "id": {
              "type": "keyword"
            },
            "gender": {
              "type": "keyword"
            },
            "age": {
              "type": "integer"
            },
            "firstName": {
              "type": "text"
            },
            "lastName": {
              "type": "text"
            }
          },
          "dynamic": "strict"
        },
        "date": {
          "type": "date",
          "format": "yyyy-MM-dd HH:mm:ss"
        },
        "message": {
          "type": "text"
        }
      },
      "dynamic": "strict"
    }
  }
}

PUT user?include_type_name=true
{
  "mappings": {
    "_doc": {
      "properties": {
        "id": {
          "type": "keyword"
        },
        "gender": {
          "type": "keyword"
        },
        "age": {
          "type": "integer"
        },
        "firstName": {
          "type": "text"
        },
        "lastName": {
          "type": "text"
        },
        "tweets": {
          "type": "nested",
          "properties": {
            "id": {
              "type": "keyword"
            },
            "date": {
              "type": "date",
              "format": "yyyy-MM-dd HH:mm:ss"
            },
            "message": {
              "type": "text"
            }
          },
          "dynamic": "strict"
        }
      },
      "dynamic": "strict"
    }
  }
}

PUT user/_doc/myID
{
  "id": "myID",
  "gender": "male",
  "age": 25,
  "firstName": "John",
  "lastName": "Doe",
  "tweets": [
    {
      "id": "firstmsg",
      "date": "2021-01-10 13:24:10",
      "message": "test tweet"
    }
  ]
}

PUT tweet/_doc/firstmsg
{
  "author": {
    "id": "myID",
    "gender": "male",
    "age": 25,
    "firstName": "John",
    "lastName": "Doe"
  },
  "id": "firstmsg",
  "date": "2021-01-10 13:24:10",
  "message": "test tweet"
}
```
* create Tweet and User entities as described in [documentation](https://api-platform.com/docs/core/elasticsearch/#creating-models)
```php
<?php
//Entity/User.php
declare(strict_types=1);

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiProperty;
use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ApiResource
 */
class User
{
    /** @ApiProperty(identifier=true) */
    public string $id = '';

    public string $gender;

    public int $age;

    public string $firstName="";

    public string $lastName="";

    /**
     * @var Tweet[]
     */
    public array $tweets;
}
``` 
```php
<?php
// Entity/Tweet.php
declare(strict_types=1);

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiProperty;
use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ApiResource
 */
class Tweet
{
    /** @ApiProperty(identifier=true) */
    public string $id = '';

    public User $author;

    public \DateTimeInterface $date;

    public string $message;
}
```

* my api_platform.yaml
```yaml
parameters:
    env(ELASTICSEARCH_HOST): 'elasticsearch.vilo.local:9200'
api_platform:
    title: Product Service
    version: 0.1.0
    mapping:
        paths:
        - '%kernel.project_dir%/src/App/Entity'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    eager_loading:
        # To enable or disable eager loading.
        enabled: true

        # Fetch only partial data according to serialization groups.
        # If enabled, Doctrine ORM entities will not work as expected if any of the other fields are used.
        fetch_partial: false

        # Max number of joined relations before EagerLoading throws a RuntimeException.
        max_joins: 30

        # Force join on every relation.
        # If disabled, it will only join relations having the EAGER fetch mode.
        force_eager: true
    collection:
        pagination:
            enabled: true
            client_items_per_page: true
            items_per_page_parameter_name: itemsPerPage
            maximum_items_per_page: 100
    graphql:
        collection:
            pagination:
                enabled: true
    formats:
        jsonld: [ 'application/ld+json' ]
        jsonhal: [ 'application/hal+json' ]
        jsonapi: [ 'application/vnd.api+json' ]
        json: [ 'application/json' ]
        xml: [ 'application/xml', 'text/xml' ]
        yaml: [ 'application/x-yaml' ]
        csv: [ 'text/csv' ]
        html: [ 'text/html' ]
    defaults:
        mercure: true
        attributes:
            pagination_type: page
    elasticsearch:
        hosts: ['%env(ELASTICSEARCH_HOST)%']

```

* use this query on graphql playground:
```graphql
query {
  users
  {
    collection{
      id,
      gender,
      tweets{collection{
        id,
        message,
      }}
    }
  }
}
```

This is the response:
```json
{
  "errors": [
    {
      "debugMessage": "Collection returned by the collection data provider must implement ApiPlatform\\Core\\DataProvider\\PaginatorInterface.",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ],
      "path": [
        "users",
        "collection",
        0,
        "tweets"
      ],
      "trace": [
        {
          "file": "/srv/api/vendor/api-platform/core/src/GraphQl/Resolver/Stage/SerializeStage.php",
          "line": 100,
          "call": "ApiPlatform\\Core\\GraphQl\\Resolver\\Stage\\SerializeStage::serializePageBasedPaginatedCollection(array(0), array(5))"
        },
        {
          "file": "/srv/api/vendor/api-platform/core/src/GraphQl/Resolver/Factory/CollectionResolverFactory.php",
          "line": 102,
          "call": "ApiPlatform\\Core\\GraphQl\\Resolver\\Stage\\SerializeStage::__invoke(array(0), 'App\\Entity\\Tweet', 'item_query', array(6))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 624,
          "call": "ApiPlatform\\Core\\GraphQl\\Resolver\\Factory\\CollectionResolverFactory::ApiPlatform\\Core\\GraphQl\\Resolver\\Factory\\{closure}(array(5), array(0), null, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 550,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveFieldValueOrError(instance of GraphQL\\Type\\Definition\\FieldDefinition, instance of GraphQL\\Language\\AST\\FieldNode, instance of Closure, array(5), instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 1196,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField(GraphQLType: User, array(5), instance of ArrayObject(1), array(4))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 1146,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeFields(GraphQLType: User, array(5), array(3), instance of ArrayObject(3))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 1107,
          "call": "GraphQL\\Executor\\ReferenceExecutor::collectAndExecuteSubfields(GraphQLType: User, instance of ArrayObject(1), array(3), array(5))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 794,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeObjectValue(GraphQLType: User, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(3), array(5))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 655,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeValue(GraphQLType: User, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(3), array(5))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 888,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeValueCatchingError(GraphQLType: User, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(3), array(5))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 762,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeListValue(GraphQLType: User, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(2), array(1))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 655,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeValue(GraphQLType: User, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(2), array(1))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 557,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeValueCatchingError(GraphQLType: User, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(2), array(1))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 1196,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField(GraphQLType: UserConnection, array(2), instance of ArrayObject(1), array(2))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 1146,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeFields(GraphQLType: UserConnection, array(2), array(1), instance of ArrayObject(1))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 1107,
          "call": "GraphQL\\Executor\\ReferenceExecutor::collectAndExecuteSubfields(GraphQLType: UserConnection, instance of ArrayObject(1), array(1), array(2))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 794,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeObjectValue(GraphQLType: UserConnection, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(1), array(2))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 655,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeValue(GraphQLType: UserConnection, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(1), array(2))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 557,
          "call": "GraphQL\\Executor\\ReferenceExecutor::completeValueCatchingError(GraphQLType: UserConnection, instance of ArrayObject(1), instance of GraphQL\\Type\\Definition\\ResolveInfo, array(1), array(2))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 1196,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField(GraphQLType: Query, null, instance of ArrayObject(1), array(1))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 264,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeFields(GraphQLType: Query, null, array(0), instance of ArrayObject(1))"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 215,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeOperation(instance of GraphQL\\Language\\AST\\OperationDefinitionNode, null)"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 156,
          "call": "GraphQL\\Executor\\ReferenceExecutor::doExecute()"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 162,
          "call": "GraphQL\\Executor\\Executor::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, instance of GraphQL\\Language\\AST\\DocumentNode, null, null, array(0), null, null)"
        },
        {
          "file": "/srv/api/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 94,
          "call": "GraphQL\\GraphQL::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, '{\n  users {\n    collection {\n      id\n      gender\n      tweets {\n        collection {\n          id\n          message\n        }\n      }\n    }\n  }\n}\n', null, null, array(0), null, null, null)"
        },
        {
          "file": "/srv/api/vendor/api-platform/core/src/GraphQl/Executor.php",
          "line": 34,
          "call": "GraphQL\\GraphQL::executeQuery(instance of GraphQL\\Type\\Schema, '{\n  users {\n    collection {\n      id\n      gender\n      tweets {\n        collection {\n          id\n          message\n        }\n      }\n    }\n  }\n}\n', null, null, array(0), null, null, null)"
        },
        {
          "file": "/srv/api/vendor/api-platform/core/src/GraphQl/Action/EntrypointAction.php",
          "line": 86,
          "call": "ApiPlatform\\Core\\GraphQl\\Executor::executeQuery(instance of GraphQL\\Type\\Schema, '{\n  users {\n    collection {\n      id\n      gender\n      tweets {\n        collection {\n          id\n          message\n        }\n      }\n    }\n  }\n}\n', null, null, array(0), null)"
        },
        {
          "file": "/srv/api/vendor/symfony/http-kernel/HttpKernel.php",
          "line": 157,
          "call": "ApiPlatform\\Core\\GraphQl\\Action\\EntrypointAction::__invoke(instance of Symfony\\Component\\HttpFoundation\\Request)"
        },
        {
          "file": "/srv/api/vendor/symfony/http-kernel/HttpKernel.php",
          "line": 79,
          "call": "Symfony\\Component\\HttpKernel\\HttpKernel::handleRaw(instance of Symfony\\Component\\HttpFoundation\\Request, 1)"
        },
        {
          "file": "/srv/api/vendor/symfony/http-kernel/Kernel.php",
          "line": 195,
          "call": "Symfony\\Component\\HttpKernel\\HttpKernel::handle(instance of Symfony\\Component\\HttpFoundation\\Request, 1, true)"
        },
        {
          "file": "/srv/api/public/index.php",
          "line": 30,
          "call": "Symfony\\Component\\HttpKernel\\Kernel::handle(instance of Symfony\\Component\\HttpFoundation\\Request)"
        }
      ]
    }
  ],
  "data": {
    "users": {
      "collection": [
        {
          "id": "/users/myID",
          "gender": "male",
          "tweets": null
        }
      ]
    }
  }
}
```

**Possible Solution**  
no idea

**Additional Context**  
no
