### ISSUE TITLE
Memory consumption since last update

### ISSUE THREAD

**Issue by Jarablus** [api-platform/api-platform#181]
Since last update I have a lot of  timeout and Allowed memory size of XXX bytes exhausted on every entity that have lot joins (8 for examples)
I should mention that everything worked fine before updating  and after reverting the core to 2.0.0.

**Comment by teohhanhui** [comment]
This is probably related to the "force_eager" #845

**Comment by soyuka** [comment]
Can you set the option to `true` and check if this still happens? Thanks.

```yaml
api_platform:
  eager_loading
    force_eager: false
```
