### ISSUE TITLE
OpenApi context : required parameters or errors ?

### ISSUE THREAD

**Issue by remif25** [api-platform/api-platform#1814]
**API Platform version(s) affected**: 2.6.2
**PHP**: 8.0.0

**Description**  
I got problems which are linked : 

**1/** The cli `php bin/console api:openapi:export` return this error :
```error
In OpenApiFactory.php line 167:

  Warning: Undefined array key "name"
```

If I add the parameters name in my openapi_content in file config file it solve the problem.  Now "name" seems to be a required parameters but but I don't knwo if this is the expected behaviour.

`kes-serveur-auth/config/packages/api_platform/foo.yml`
```yml
esources:
  App\Entity\Foo:
    collectionOperations:
      custom_operation:
        path: /foo/bar
        controller: App\Controller\FooBar
        method: POST
        read: false
        openapi_context:
          summary:  Sumarry
          description: Description
          parameters:
            -    
              name: test   // Line added
              in: body
              schema:
                type: object
                properties:
                  title:
                      type: string
                      required: true
```
`api-platform/core/src/OpenApi/Factory/OpenApiFactory.php`
```php
if ($operation['openapi_context']['parameters'] ?? false) {
    foreach ($operation['openapi_context']['parameters'] as $parameter) {
        $parameters[] = new Model\Parameter($parameter['name'], $parameter['in'], $parameter['description'] ?? '', 
                                      $parameter['required'] ?? false, $parameter['deprecated'] ?? false, $parameter['allowEmptyValue'] ?? false, 
                                      $parameter['schema'] ?? []);
    }
}
```

**2/** After solving the first issue, I got a second error with `php bin/console api:openapi:export` : 
```cli
In PropertyAccessor.php line 432:

  The method "ApiPlatform\Core\OpenApi\Model\Parameter::getStyle()" returned "null", but expected type "string". Did you forget to initialize a property or to make the return type nullable using "?string"?


In Parameter.php line 96:

  ApiPlatform\Core\OpenApi\Model\Parameter::getStyle(): Return value must be of type string, null returned
```

A parameters style seems to be required too but I don't know where I am supposed to add it in my config file. Again I don't know the excepted behaviour, it's a really a requird parameters and the documentation isn't up to date, or is-it a error in the file : 
`api-platform/core/src/OpenApi/Model/Parameters.php` (line 94)
```php
public function getStyle(): ?string  //Missing : ?
    {
        return $this->style;
    }
```

Thank for you help.
