### ISSUE TITLE
how to persist PWA changes with Docker 

### ISSUE THREAD

**Issue by olessiap** [api-platform/api-platform#1816]
Hello api platform community! 

Is it possible to have hot reloading with api platform and docker? I am working on the frontend of things and would love it if I didn't have to stop and re-run the docker containers each time I wanted to see a code change. Can anyone please guide me how to go about it since I'm a configuration and docker newb?

**Comment by dunglas** [comment]
Hot reloading should be enabled by default. What operating system are you using?

**Comment by olessiap** [comment]
@dunglas  I am on Windows 10. The php side does have hot reloading, but the PWA doesn't. Each time I want to see a code change I have to create a new docker image. Please see my docker-compose.yml configs below. Do you see anything missing? 

```
version: "3.4"

services:
  php:
    build:
      context: ./api
      target: api_platform_php
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  pwa:
    build:
      context: ./pwa
      target: api_platform_pwa_prod
    environment:
      API_PLATFORM_CLIENT_GENERATOR_ENTRYPOINT: http://caddy

  caddy:
    build:
      context: api/
      target: api_platform_caddy
    depends_on:
      - php
      - pwa
    environment:
      PWA_UPSTREAM: pwa:3000
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY:-xxxx}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY:-xxxx}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
      - target: 443
        published: 443
        protocol: udp

volumes:
  php_socket:
  caddy_data:
  caddy_config:
```

**Comment by dunglas** [comment]
I don't use Windows, does any other Windows user reading this has this problem? It would help a lot if we can confirm the issue.

**Comment by VeryStrongFingers** [comment]
@olessiap your `pwa` docker-compose service has the wrong target - it's using prod.

Should be using `dev`, like
```
  pwa:
    build:
      context: ./pwa
      target: api_platform_pwa_dev
    environment:
      API_PLATFORM_CLIENT_GENERATOR_ENTRYPOINT: http://caddy
```
