### ISSUE TITLE
Cannot override default maximum items per page with annotation

### ISSUE THREAD

**Issue by silverbackdan** [api-platform/api-platform#1861]
**API Platform version(s) affected**: 2.6.3

**Description**  
The issue is to do with overriding the pagination maximum items per page.

With the deprecated config
```
...
collection:
  pagination:
    client_items_per_page: true
    items_per_page_parameter_name: perPage
    maximum_items_per_page: 100
```

If I then set an annotation on a resource
```
@ApiResource(attributes={"maximum_items_per_page"=40})
```
The maximum items per page is applied as 40, as expected.

If I use the new config
```
...
defaults:
  pagination_client_items_per_page: true
  pagination_maximum_items_per_page: 100
collection:
  pagination:
    items_per_page_parameter_name: perPage
```
The maximum continues to be set to 100.

My full annotation is
```
/* 
 * @ApiResource(attributes={
 *     "maximum_items_per_page"=40,
 *     "pagination_items_per_page"=10,
 *     "pagination_client_items_per_page"=true,
 *     "pagination_client_enabled"=true,
 * })
 * /
```
I can get all the results by setting perPage to `0` or disabling pagination as configured still.

As a side-note, I'm curious why to properties were moved from the collection config but `items_per_page_parameter_name` remains there.

I've tried adding `collectionOperations={ "get"={"maximum_items_per_page"=40} }` to the annotation as well... curious..
