### ISSUE TITLE
ManyToMany self referencing and exceeded number of join relations exception

### ISSUE THREAD

**Issue by cve** [api-platform/api-platform#187]
Hi,

First of all, big thanks for api-platform it's amazing. 

I have the Campaign resource:

````php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * A campaign.
 *
 * @ORM\Entity()
 */
class Campaign
{
    /**
     * @Groups({"campaign_list", "campaign_get"})
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Groups({"campaign_list", "campaign_get"})
     *
     * @ORM\Column
     */
    private $name;

    /**
     * @Groups({"campaign_get"})
     *
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Campaign")
     */
    private $excluded;
}
````

When I try to GET /campaigns I get this exception:

````
The total number of joined relations has exceeded the specified maximum. Raise the limit if necessary.
````

**Comment by soyuka** [comment]
Indeed, you have a recursive relation here, where campaign is referencing itself. You may want to disable [eager loading](https://api-platform.com/docs/core/performance#eager-loading) here by using `@ApiResource(attributes={"force_eager"=false})`.

**Comment by cve** [comment]
Thanks for your reply.

How to "load" that relation after that?

**Comment by soyuka** [comment]
We're working on this as some would want to get back a limited number of relations. The best option would be to use the serializer max depth property. 
While we work on this, I think that Doctrine will use lazy loading if you serialize correctly. You may also try `fetch="EAGER"`.

**Comment by cve** [comment]
with `fetch="EAGER"` it is the same problem like without `@ApiResource(attributes={"force_eager"=false})`

**Comment by soyuka** [comment]
If you use `force_eager=false` the extension will  
> apply it only on join relations having the EAGER fetch mode

**Comment by cve** [comment]
```yaml
resources:
  AppBundle\Entity\Campaign:
    collectionOperations:
      get:
        method: 'GET'
        normalization_context:
          groups: ['campaign_list']
    itemOperations:
      get:
        method: 'GET'
        normalization_context:
          groups: ['campaign_get']
        force_eager: false
````

````php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * A campaign.
 *
 * @ORM\Entity()
 */
class Campaign
{
    /**
     * @Groups({"campaign_list", "campaign_get"})
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Groups({"campaign_list", "campaign_get"})
     *
     * @ORM\Column
     */
    private $name;

    /**
     * @Groups({"campaign_get"})
     *
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Campaign", fetch="EAGER")
     */
    private $excluded;
}
````

and the result after GET /campaigns/1:

`The total number of joined relations has exceeded the specified maximum. Raise the limit if necessary.`
