### ISSUE TITLE
normalization_context doesn't work when output DTO is in place

### ISSUE THREAD

**Issue by michaelHottomali** [api-platform/api-platform#1871]
**API Platform version(s) affected**: 2.6.3

**Description**  
After a recent upgrade of API platform to the latest version, normalization_context doesn't work when output DTO is in place in the resource config.

**How to reproduce**  

```
    itemOperations:
        get_brand_training_modules:
            security: "is_granted('get', object)"
            path: '/brands/{uuid}/modules'
            method: 'GET'
            output: App\Dto\Brand\BrandTrainingModuleOutput
            normalization_context:
                groups: ['brand:get', 'image_object:get']
```
Properties are missing from the API response where should be fetched by `brand:get`.
