### ISSUE TITLE
Use instruction missing on QualitativeValue's children

### ISSUE THREAD

**Issue by Matthieu-Lescieux** [api-platform/api-platform#19]
The instruction
>use SchemaOrg\Enum\QualitativeValue;

is missing in the QualitativeValue's children.

Example of generation with CarUsageType

><?php
>
>namespace AppBundle\Entity;
>
>use Doctrine\ORM\Mapping as ORM;
>use Dunglas\ApiBundle\Annotation\Iri;
>
>/* ... */
>
>class CarUsageType extends QualitativeValue
>{
>    ...
>}

The command
>username:~/path/to/project$ php app/console doctrine:schema:update

cause this error
>PHP Fatal error:  Class 'AppBundle\Entity\QualitativeValue' not found in /home/username/path/to/project/src/AppBundle/Entity/CarUsageType.php on line 17
[2015-10-11 17:27:49] php.CRITICAL: Fatal Error: Class 'AppBundle\Entity\QualitativeValue' not found {"type":1,"file":"/home/username/path/to/project/src/AppBundle/Entity/CarUsageType.php","line":17,"level":-1,"stack":[]}

Add
>use SchemaOrg\Enum\QualitativeValue;

fix the problem but you have to do it after each generation for each child.

**Comment by dunglas** [comment]
Can you paste your `schema.yml` file?

**Comment by Matthieu-Lescieux** [comment]
```
rdfa:
  - https://raw.githubusercontent.com/schemaorg/schemaorg/sdo-gozer/data/schema.rdfa
annotationGenerators:
  - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
  - ApiPlatform\SchemaGenerator\AnnotationGenerator\DoctrineOrmAnnotationGenerator
  - ApiPlatform\SchemaGenerator\AnnotationGenerator\ConstraintAnnotationGenerator
  - ApiPlatform\SchemaGenerator\AnnotationGenerator\DunglasApiAnnotationGenerator
namespaces:
  entity: AppBundle\Entity
types:
  #Thing
  Thing: ~

  #Thing/Intangible
  Intangible: ~

  #Thing/Intangible/Enumeration
  Enumeration: ~

  #Thing/Intangible/Enumeration/QualitativeValue
  QualitativeValue: ~

  #Thing/Intangible/Enumeration/QualitativeValue/CarUsageType
  CarUsageType: ~

  #Thing/Intangible/Enumeration/QualitativeValue/DriveWheelConfigurationValue
  DriveWheelConfigurationValue: ~

  #Thing/Intangible/Enumeration/QualitativeValue/SteeringPositionValue
  SteeringPositionValue: ~

#... Other types
```
