### ISSUE TITLE
[GraphQL] Define custom return type for query resolver

### ISSUE THREAD

**Issue by gettmure** [api-platform/api-platform#1917]
Greetings everyone.

So, I am trying to specify fields, that can be queried in my custom query. According to documentation, I have to configure serialization groups in api resource and entity, but it does not seem to work. Is it a bug, or is this feature not supported for query with resolver? Or am I doing something wrong at all?

Look at the code below (i think it is not necessary to provide resolvers code, but if someone needs to look at it, you can ask for it in the comments).

Api resource config (yaml):

```yaml
App\Entity\Session:
    graphql:
        mainPage:
            collection_query: App\Resolver\Query\MainPageSessionsCollectionResolver
            pagination_enabled: false
            read: false
        affichePage:
            collection_query: App\Resolver\Query\AffichePageSessionsCollectionResolver
            normalization_context:
                groups: ['collection_query']
            read: false
```

Property, which I am trying to restrict:
```php
    /**
     * @var int
     *
     * @Groups({"collection_query"})
     */
    private int $minPrice = 0;
    
    

    /**
     * @param int $minPrice
     *
     * @return $this
     */
    public function setMinPrice(int $minPrice): self
    {
        $this->minPrice = $minPrice;

        return $this;
    }

    /**
     * @return int
     */
    public function getMinPrice(): int
    {
        return $this->minPrice;
    }
```

Query, which is allowed to have this field in the response, is working like a charm:
```
query {
  affichePageSessions {
    edges {
      node {
        id,
        minPrice
      }
    }
  }
}
```

But I am expecting not to have access to this field in mainPageSessions query, but I do:

```
query {
  mainPageSessions {
    id,
    minPrice
  }
}
```

**Comment by maciej-laskowski** [comment]
Hi! The problem is that you didn't define any normalization_context on your mainPage query.

Try:

```
mainPage:
            collection_query: App\Resolver\Query\MainPageSessionsCollectionResolver
            pagination_enabled: false
            read: false
            normalization_context:
                groups: ['']
```
and you should see that no field except for id will be queryable. 

The way we are handling different set of fields for item and collection queries is by assigning a proper set of groups to all queryable fields. Have a look an example.

Queries:

```
@ApiResource(
 *     graphql={
 *         "item_query"={"normalization_context"={"groups"={"item_query"}}},
 *         "collection_query"={"normalization_context"={"groups"={"collection_query"}}},
```
Field visible in both queries
```
   /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"item_query", "collection_query"})
     */
    private $reference;
```
Field visible only on collection query
```
   /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"collection_query"})
     */
    private $reference;
```
Field visible only on item query
```
   /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"item_query"})
     */
    private $reference;
```
Field not visible on any queries
```
  /**
     * @ORM\Column(type="string", length=255)
     */
    private $reference;
```
