### ISSUE TITLE
Using Two Prefixed Routes with Different Auth Process for same API - Doc Not Working

### ISSUE THREAD

**Issue by simoninkel** [api-platform/api-platform#1941]
### Description

Using api-platform for some years now, we are giving it more and more focus. Initially, we integrated OAuth2 to secure the api endpoints. With growing needs, we wanted to integrate an alternative entrypoint for the same api, secured using JWT. For backward compatibility and some other needs, we need to keep the original OAuth api entrypoint. I tried adding prefixed entrypoints by doing so:

rouitng.yml
```
[...]

api_platform:
    resource: .
    type: api_platform
    prefix:
        closed: /api/v3
        open: /open-api/v3

[...]
```

The problem is OpenApi nor SwaggerUi doc seems to work. When trying to access the doc interface, I get:

`"Unable to generate a URL for the named route "api_doc" as such route does not exist."`

I can disable JSonld and set enable_docs to false to see my endpoints are working (exept I'm loosing openApi interface and hydra context doc, etc.) Both works fine alone with no prefix.

Am I missing something? I can't seem to find any similar use case. Is there another way of doing what I intend instead of using routing prefixes? Is there a config to map doc generation to two different entrypoints? Is there a reason I can't seem to find anyone with similar needs and issues?

Thank you, any help will be appreciated.

**Comment by simoninkel** [comment]
Is there additional information I could provide to help in addressing this issue? 

I've come up with a dead end and disabled my JWT endpoints temporarily. I can't seem to find any example in the doc concerning multiple entry points for the same API and surely can't be the only one needing to do this for BC purpose.

If I can add any relevant details, just ask. Thank you.

**Comment by andythedandy** [comment]
I would need that too, so still not working, right!?

I tried to achieve that with a duplicate of the routing like that:
```
api_platform:
    resource: .
    type: api_platform
    name_prefix: 'external_'
    prefix: /api/v3
        
internal:
    resource: .
    type: api_platform
    name_prefix: 'internal_'
    prefix: /open-api/v3
```

`bin/console debug:router` returns it right, but the `bin/console api:openapi:export` doesn't has the 'internal' routes...
