### ISSUE TITLE
Using MongoDB embedded document as sub resource gives an error 

### ISSUE THREAD

**Issue by smilesrg** [api-platform/api-platform#1943]
**API Platform version(s) affected**: `2.6.4`

**Description**  
Using MongoDB embedded document as sub resource gives an error `Resource "Room" not found in . (which is being imported from "/extranet/config/routes/api_platform.yaml"). Make sure there is a loader supporting the "api_platform" type.`

**How to reproduce**  
Sample files:

```php
<?php

namespace App\Document;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ODM\Document
 */
class Hotel
{
    /**
     * @ODM\Id(strategy="UUID")
     */
    protected $hotelId;

    /**
     * @ODM\EmbedMany(targetDocument="Room")
     */
    protected $hotelRooms;

    public function __construct()
    {
        $this->hotelRooms = new ArrayCollection();
    }
}
```

```php
<?php

namespace App\Document;

use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ODM\EmbeddedDocument
 */
class Room
{

    /**
     * @ODM\Id(strategy="UUID")
     */
    protected $id;
}
```

```yaml
App\Document\Room:
    properties:
        id:
            identifier: true
App\Document\Hotel:
    properties:
        hotelId:
            identifier: true
        hotelRooms:
            subresource:
                resourceClass: 'App\Document\Room'
                collection: true
```

**Comment by smilesrg** [comment]
**Fixed** by adding getter/setter for identifier property. Maybe it worths adding this prompt to the error message?

**Comment by smilesrg** [comment]
Reopening this. 

```yaml
App\Document\Room:
    properties:
        id:
            identifier: true
App\Document\Hotel:
    properties:
        hotelId:
            identifier: true
            attributes:
                openapi_context:
                    type: string
                    readOnly: true
                    example: 'b1aca7b91795446ea14675e3b8d66cea'
        hotelNameUk:
            attributes:
                openapi_context:
                    example: 'Хрещатик'
        hotelNameEn:
            attributes:
                openapi_context:
                    example: 'Khreschatyk'
        hotelAddressStreet:
            attributes:
                openapi_context:
                    example: 'Хрещатик 14'
        hotelAddressCity:
            attributes:
                openapi_context:
                    example: 'Київ'
        hotelAddressPostcode:
            attributes:
                openapi_context:
                    example: '01001'
        hotelAddressCountry:
            attributes:
                openapi_context:
                    example: 'Україна'
        hotelType:
            attributes:
                openapi_context:
                    example: 'hotelTypeHotel'
        hotelTypeStars:
            attributes:
                openapi_context:
                    example: 4
        hotelPhoneGeneral:
            attributes:
                openapi_context:
                    example: '+38 (044) 596 80 00'
        hotelEmailGeneral:
            attributes:
                openapi_context:
                    example: 'reservation@hotel-khreschatyk.kiev.ua'
        hotelEmailSales:
            attributes:
                openapi_context:
                    example: 'sales@hotel-khreschatyk.kiev.ua'
        hotelDescription:
            attributes:
                openapi_context:
                    example: 'Готель Хрещатик входить в топ-10 кращих готелів в центрі Києва. Серед готелів Києва готель Хрещатик виділяється своїм унікальним розташуванням на головній вулиці столиці України. Комфортабельні номери готелю оснащені міні-сейфами, електронною системою безпеки, супутниковим TV, міні-барами, системою клімат-контроль, системою управління звуком та світлом, фенами, підлогою з підігрівом у ванній кімнаті.'
        hotelTax:
            attributes:
                openapi_context:
                    example: 'hotelTaxIncluded'
        hotelCreditCard:
            attributes:
                openapi_context:
                    example: '5555341244441115'
        hotelTotalRoomQuantity:
            attributes:
                openapi_context:
                    example: 126
        hotelRooms:
            subresource:
                resourceClass: 'App\Document\Room'
                collection: true

```

```php
<?php

namespace App\Document;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ODM\Document
 */
class Hotel
{
    public const HOTEL_TYPES = ['hotelTypeHotel', 'hotelTypeBotel', 'hotelTypeVilla',
        'hotelTypeHealthHotel', 'hotelTypeGuesthouse', 'hotelTypeTourbase',
        'hotelTypeApartment', 'hotelTypeHostel', 'hotelTypeAparthotel'];

    public const TAX_TYPE = ['hotelTaxIncluded', 'hotelTaxNotIncluded'];

    /**
     * @ODM\Id(strategy="UUID")
     */
    protected $hotelId;

    /**
     * @ODM\Field
     */
    #[Assert\NotBlank]
    protected string $hotelNameUk;

    /**
     * @ODM\Field
     */
    #[Assert\NotBlank]
    protected string $hotelNameEn;

    /**
     * @ODM\Field
     */
    #[Assert\NotBlank]
    protected string $hotelAddressStreet;

    /**
     * @ODM\Field
     */
    #[Assert\NotBlank]
    protected string $hotelAddressCity;

    /**
     * @ODM\Field
     */
    #[Assert\NotBlank]
    protected string $hotelAddressPostcode;

    /**
     * @ODM\Field
     */
    #[Assert\NotBlank]
    protected string $hotelAddressCountry;

//    /**
//     * @ODM\Field
//     */
//    #[Assert\NotBlank]
//    protected array $hotelAddressLangLat;

    /**
     * @ODM\Field
     */
    #[Assert\Choice(self::HOTEL_TYPES)]
    protected $hotelType;

    /**
     * @ODM\Field(type="int")
     */
    #[Assert\Range(min: 1, max: 5)]
    protected int $hotelTypeStars;

    /**
     * @ODM\Field
     */
    #[Assert\NotBlank]
    protected string $hotelPhoneGeneral;

    /**
     * @ODM\Field
     */
    #[Assert\Email]
    protected string $hotelEmailGeneral;

    /**
     * @ODM\Field
     */
    #[Assert\Email]
    protected string $hotelEmailSales;

//    /**
//     * @ODM\EmbeddedDocument
//     */
//    protected string $hotelInsiteContacts;

    /**
     * @ODM\Field
     */
    #[Assert\NotBlank]
    protected string $hotelDescription;

//    protected $hotelServices;
    /**
     * @ODM\Field
     */
    #[Assert\Choice(self::TAX_TYPE)]
    protected $hotelTax;

    /**
     * @ODM\Field
     */
    #[Assert\CardScheme(schemes: [Assert\CardScheme::VISA, Assert\CardScheme::MASTERCARD])]
    protected $hotelCreditCard;

//    protected $hotelChildPolicy;
//    protected $hotelcheckInTime;
//    protected $hotelcheckOutTime;

    /**
     * @ODM\Field(type="int")
     */
    #[Assert\NotBlank]
    #[Assert\Positive]
    protected int $hotelTotalRoomQuantity;

    /**
     * @ODM\EmbedMany(targetDocument="Room")
     */
    protected $hotelRooms;

    public function __construct()
    {
        $this->hotelRooms = new ArrayCollection();
    }

    public function getHotelId()
    {
        return $this->hotelId;
    }

    public function setHotelId($hotelId): Hotel
    {
        $this->hotelId = $hotelId;

        return $this;
    }

    public function getHotelNameUk(): string
    {
        return $this->hotelNameUk;
    }

    public function setHotelNameUk(string $hotelNameUk): Hotel
    {
        $this->hotelNameUk = $hotelNameUk;

        return $this;
    }

    public function getHotelNameEn(): string
    {
        return $this->hotelNameEn;
    }

    public function setHotelNameEn(string $hotelNameEn): Hotel
    {
        $this->hotelNameEn = $hotelNameEn;

        return $this;
    }

    public function getHotelAddressStreet(): string
    {
        return $this->hotelAddressStreet;
    }

    public function setHotelAddressStreet(string $hotelAddressStreet): Hotel
    {
        $this->hotelAddressStreet = $hotelAddressStreet;

        return $this;
    }

    public function getHotelAddressCity(): string
    {
        return $this->hotelAddressCity;
    }

    public function setHotelAddressCity(string $hotelAddressCity): Hotel
    {
        $this->hotelAddressCity = $hotelAddressCity;

        return $this;
    }

    public function getHotelAddressPostcode(): string
    {
        return $this->hotelAddressPostcode;
    }

    public function setHotelAddressPostcode(string $hotelAddressPostcode): Hotel
    {
        $this->hotelAddressPostcode = $hotelAddressPostcode;

        return $this;
    }

    public function getHotelAddressCountry(): string
    {
        return $this->hotelAddressCountry;
    }

    public function setHotelAddressCountry(string $hotelAddressCountry): Hotel
    {
        $this->hotelAddressCountry = $hotelAddressCountry;

        return $this;
    }

    public function getHotelType(): string
    {
        return $this->hotelType;
    }

    public function setHotelType($hotelType): Hotel
    {
        $this->hotelType = $hotelType;

        return $this;
    }

    public function getHotelTypeStars(): int
    {
        return $this->hotelTypeStars;
    }

    public function setHotelTypeStars(int $hotelTypeStars): Hotel
    {
        $this->hotelTypeStars = $hotelTypeStars;

        return $this;
    }

    public function getHotelPhoneGeneral(): string
    {
        return $this->hotelPhoneGeneral;
    }

    public function setHotelPhoneGeneral(string $hotelPhoneGeneral): Hotel
    {
        $this->hotelPhoneGeneral = $hotelPhoneGeneral;

        return $this;
    }

    public function getHotelEmailGeneral(): string
    {
        return $this->hotelEmailGeneral;
    }

    public function setHotelEmailGeneral(string $hotelEmailGeneral): Hotel
    {
        $this->hotelEmailGeneral = $hotelEmailGeneral;

        return $this;
    }

    public function getHotelEmailSales(): string
    {
        return $this->hotelEmailSales;
    }

    public function setHotelEmailSales(string $hotelEmailSales): Hotel
    {
        $this->hotelEmailSales = $hotelEmailSales;

        return $this;
    }

    public function getHotelDescription(): string
    {
        return $this->hotelDescription;
    }

    public function setHotelDescription(string $hotelDescription): Hotel
    {
        $this->hotelDescription = $hotelDescription;

        return $this;
    }

    public function getHotelTax(): string
    {
        return $this->hotelTax;
    }

    public function setHotelTax(string $hotelTax): Hotel
    {
        $this->hotelTax = $hotelTax;

        return $this;
    }

    public function getHotelCreditCard(): string
    {
        return $this->hotelCreditCard;
    }

    public function setHotelCreditCard($hotelCreditCard): Hotel
    {
        $this->hotelCreditCard = $hotelCreditCard;

        return $this;
    }

    public function getHotelTotalRoomQuantity(): int
    {
        return $this->hotelTotalRoomQuantity;
    }

    public function setHotelTotalRoomQuantity(int $hotelTotalRoomQuantity): Hotel
    {
        $this->hotelTotalRoomQuantity = $hotelTotalRoomQuantity;

        return $this;
    }
}
```

```php
<?php

namespace App\Document;

use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ODM\EmbeddedDocument
 */
class Room
{
    protected const BED_TYPES = ['roomBedOneSize', 'roomBedHalfSize', 'roomBedTwoSize', 'roomBedQueenSize',
        'roomBedKingSize', 'roomBedBinbed', 'roomBedSofaOne', 'roomBedSofaTwo', 'roomBedSofaHalf',
        'roomBedFuton', 'roomBedSleepPlace', 'roomBedSleepPlaceBed',
    ];

    /**
     * @ODM\Id(strategy="UUID")
     */
    protected $id;

    /**
     * @ODM\Field
     */
    #[Assert\NotBlank]
    #[Assert\Choice(self::BED_TYPES)]
    protected string $hotelRoomType;

    /**
     * @ODM\Field
     */
    #[Assert\NotBlank]
    #[Assert\Range(min: 1, max: 20)]
    protected int $hotelRoomPax;

    /**
     * @ODM\Field
     */
    #[Assert\NotBlank]
    protected string $hotelRoomSelfname;

    /**
     * @ODM\Field(type="int")
     */
    #[Assert\NotBlank]
    #[Assert\Range(min: 1, max: 20)]
    protected int $hotelRoomPaxChild;

    /**
     * @ODM\Field(type="int")
     */
    #[Assert\NotBlank]
    #[Assert\Range(min: 1, max: 20)]
    protected int $hotelRoomBedQuantity;

    /**
     * @ODM\Field
     */
    #[Assert\NotBlank]
    protected string $hotelRoomBedType;

    /**
     * @ODM\Field(type="float")
     */
    #[Assert\NotBlank]
    //TODO: Decimal validation
    protected float $hotelRoomSize;

    /**
     * @ODM\Field
     */
    #[Assert\NotBlank]
    protected array $hotelRoomFacility;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id): Room
    {
        $this->id = $id;

        return $this;
    }
}
```

**Comment by smilesrg** [comment]
Found a bug: Target embeddable entities must contain a full namespace:

```php
    /**
     * @ODM\EmbedMany(targetDocument="App\Document\Room")
     */
    protected $hotelRooms;
```

https://github.com/api-platform/core/blob/main/src/Metadata/Resource/Factory/ExtractorResourceMetadataFactory.php#L53

Isn't relative class references is what's needed to be considered?

**Comment by smilesrg** [comment]
BTW, subresources configuration gives me just one `GET` route for embedded resource and fully operations with collection which I don't need. That happens even if I change `collection` parameter to `false`:
```yaml
        hotelRooms:
            subresource:
                resourceClass: 'App\Document\Room'
                collection: false
```
![screencapture-localhost-8081-2021-06-18-13_25_12](https://user-images.githubusercontent.com/576284/122547360-ae8aa580-d038-11eb-95bc-1225d50582a8.png)
