### ISSUE TITLE
Multiple entity managers and dynamic connection problem on some api operations

### ISSUE THREAD

**Issue by jarekkowol** [api-platform/api-platform#1957]
The following code shows a solution that almost everything works fine. But not everything ...
I am trying to use separate mysql databases for clients.

This is how the databases structure should look:

SystemEntityManager:
   -  database_system 
AccountEntityManager:
   -  database_account_1
   -  database_account_2
   -  database_account_3
   -  database_account_4
   ...and more and more...

When logged user (with proper JWT token) request API Platform I use a mechanism that selects the appropriate database.
It works during the create, delete and get collection operations. 

But... this does **NOT** work during the get item or update operation
The cause of this problem is wrong database selection.
During these operations an attempt is made to download data from the database_system instead of database_account_1 etc

Problem appear when I request from swagger documentation and functional tests.

This is my doctrine.yaml with configuration for two entity manager:
- system
- account (this is dynamic connection with multiple client databases)

```yaml
doctrine:
    dbal:
        default_connection: system
        connections:
            system:
                url: '%env(resolve:DATABASE_URL)%'
            account:
                url: '%env(resolve:DATABASE_URL)%'
                wrapper_class: App\Doctrine\DynamicConnection
    orm:
        default_entity_manager: system
        entity_managers:
            system:
                connection: system
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    System:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/System'
                        prefix: 'App\Entity\System'
                        alias: System
            account:
                connection: account
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Account:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Account'
                        prefix: 'App\Entity\Account'
                        alias: Account`
```

Class to switch connection:
```php
declare(strict_types=1);

namespace App\Doctrine;

use Doctrine\Common\EventManager;
use Doctrine\DBAL\Configuration;
use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Driver;

final class DynamicConnection extends Connection
{
    public function __construct(
        array $params,
        Driver $driver,
        ?Configuration $config = null,
        ?EventManager $eventManager = null
    ) {
        parent::__construct($params, $driver, $config, $eventManager);
    }

    public function switchConnection(int $account): void
    {
        if ($this->isConnected()) {
            $this->close();
        }

        $params = $this->getParams();
        $params['dbname'] = AccountDatabaseHelper::getAccountDatabaseName($account); // return account_1 or account_2
        parent::__construct($params, $this->_driver, $this->_config, $this->_eventManager);
    }
}
```

When request come from API and User is logged then I switch database (I am use user->id as prefix of database )
```php
namespace App\Doctrine;


use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\ControllerEvent;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class AccountContextControllerEventSubscriber implements EventSubscriberInterface
{
    private AccountContextService $accountContextService;
    private TokenStorageInterface $tokenStorage;

    public function __construct(AccountContextService $accountContextService, TokenStorageInterface $tokenStorage)
    {
        $this->accountContextService = $accountContextService;
        $this->tokenStorage = $tokenStorage;
    }

    public function onKernelController(ControllerEvent $event)
    {
        if (!$event->isMainRequest()) {
            return;
        }

        if ($this->tokenStorage->getToken()) {
            $this->accountContextService->switchAccount($this->tokenStorage->getToken()->getUser()->getId());
        }
    }

    public static function getSubscribedEvents()
    {
        return [
            KernelEvents::CONTROLLER => "onKernelController"
        ];
    }
}
```

This is my service with EventDispatcherInterface (this service is used above code)
```php
namespace App\Doctrine;

use Psr\EventDispatcher\EventDispatcherInterface;

class AccountContextService
{
    private EventDispatcherInterface $dispatcher;

    public function __construct(EventDispatcherInterface $dispatcher)
    {
        $this->dispatcher = $dispatcher;
    }

    public function switchAccount(int $account)
    {
        $this->dispatcher->dispatch(new AccountContextChangeEvent($account));
    }
}
```

And event subscriber:

```php
namespace App\Doctrine;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

class DoctrineAccountContextService implements EventSubscriberInterface
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $accountEntityManager)
    {
        $this->entityManager = $accountEntityManager;
    }

    public function onAccountContextChange(AccountContextChangeEvent $event): void
    {
        $this->switchAccount($event->getAccount());
    }

    public function switchAccount(int $account): void
    {
        $connection = $this->entityManager->getConnection();

        if ($connection instanceof DynamicConnection) {
            $connection->switchConnection($account);
        } else {
            throw new \LogicException("To switch connection to selected account, connection object must be instance of " . DynamicConnection::class);
        }
    }

    public static function getSubscribedEvents()
    {
        return [
            AccountContextChangeEvent::class => "onAccountContextChange"
        ];
    }
}
```
