### ISSUE TITLE
Using Messenger with an Input Object results in a serializer error

### ISSUE THREAD

**Issue by yakubenko** [api-platform/api-platform#1988]
**API Platform version(s) affected**: 2.6.5

**Description**  
I'm trying to create a custom resource operation using [this piece](https://api-platform.com/docs/core/messenger/#using-messenger-with-an-input-object) of the docs and can't get thing working. The error is the following `Cannot denormalize the input because the injected serializer is not a denormalizer`. This is what I want to achieve. I have a message class with some properties and a handler for it. According to the docs, I expect that my message class will be filled with the input data, go through the validation process and be passed to the handler once the validator is happy and a consumer reaches it. Am I missing the idea behind this feature or this is just a misconfiguration?

**How to reproduce**  
All my mappings are in YAML and here is an excerpt from my mappings

```yaml
App\Entity\Photo:
  collectionOperations:
      post:
      resize_photo:
        method: post
        status: 202
        output: false
        path: /photos/resize
        messenger: input
        input: App\Message\Photo\ResizePhotoMessage
```
Ignore the constructor as it's only an example and initially it was intended to dispatch the message manually.

```php
<?php
declare(strict_types=1);

namespace App\Message\Photo;

class ResizePhotoMessage
{
    /**
     * @param int $photoId Photo Id
     */
    public function __construct(private int $photoId)
    {
    }

    /**
     * Get the value of photoId
     *
     * @return int
     */
    public function getPhotoId(): int
    {
        return $this->photoId;
    }

    /**
     * Set the value of photoId
     *
     * @param int $photoId Photo id
     * @return  self
     */
    public function setPhotoId(int $photoId)
    {
        $this->photoId = $photoId;

        return $this;
    }
}
```

```php
<?php
declare(strict_types=1);

namespace App\MessageHandler\Photo;

use App\Message\Photo\ResizePhotoMessage;
use Symfony\Component\Messenger\Handler\MessageHandlerInterface;

class ResizePhotoMessageHandler implements MessageHandlerInterface
{
    /**
     * @param ResizePhotoMessage $message Message
     * @return void
     */
    public function __invoke(ResizePhotoMessage $message)
    {
    }
}
```

**Possible Solution**  
Add a YAML mapping example to the docs
