### ISSUE TITLE
Pagination disabled by default cannot be enabled by resource/operation

### ISSUE THREAD

**Issue by jzecca** [api-platform/api-platform#2021]
**API Platform version(s) affected**: 2.6.5

**Description**  
After disabling pagination globally using the `defaults.pagination_enabled` parameter [as shown in the docs](https://api-platform.com/docs/core/pagination/#disabling-the-pagination-globally), it looks like there is no way to enable it on a specific resource or operation.

**How to reproduce**  
Here is a reproducer: https://github.com/jzecca/api-platform-default-pagination/commit/e91d8b2f501268512ff5a5f25b661f36bd941bde

I tried with both PHP 8 attributes (`Greetings.php`) & Doctrine annotations (`Greetings2.php`), using everyway of enabling the pagination I could think of, no luck.

___

```yaml
# api/config/packages/api_platform.yaml
api_platform:
    defaults:
         # https://api-platform.com/docs/core/pagination/#disabling-the-pagination-globally
        pagination_enabled: false
```

```php
# api/src/Entity/Greetings.php
#[ApiResource(
    collectionOperations: [
        'get' => [
            'pagination_enabled' => true,
        ],
    ],
    attributes: [
        'pagination_enabled' => true,
    ],
    paginationEnabled: true,
)]
```

Maybe I'm doing something wrong?
