### ISSUE TITLE
Ability to override/configure OpenAPI servers

### ISSUE THREAD

**Issue by stephenmayer** [api-platform/api-platform#2045]
**Description**  
I would like to be able to define a list of specific server endpoints (environments) against which my OpenAPI schema can operate against.

**Example**  
I should be able to use a decorator to override the default servers listing so that I can have a list of servers within my openapi.json schema export.  For example:

```
final class JwtDecorator implements OpenApiFactoryInterface
{
    public function __construct(
        private OpenApiFactoryInterface $decorated
    ) {
    }

    public function __invoke(array $context = []): OpenApi
    {
        $context['servers'] = [
            new Model\Server('https://docker.local/', 'Docker'),
            new Model\Server('https://app-dev.company.com/', 'Dev'),
            new Model\Server('https://app-staging.company.com/', 'Staging'),
            new Model\Server('https://app.company.com/', 'Production'),
        ];
        return ($this->decorated)($context);
    }
}
```

After running the export:
`./bin/console api:openapi:export --output=openapi.json`

And upon reviewing the openapi.json file:
```
{
    "openapi": "3.0.3",
    "info": {
        "title": "App",
        "description": "description",
        "version": "version"
    },
    "servers": [
        {
            "url": "https://docker.local/",
            "description": "Docker"
        },
        {
            "url": "https://app-dev.company.com/",
            "description": "Dev"
        },
        {
            "url": "https://app-staging.company.com/",
            "description": "Staging"
        },
        {
            "url": "https://app.company.com/",
            "description": "Production"
        }
    ]
```

![image](https://user-images.githubusercontent.com/1039875/137376147-0928a273-b59f-462e-9d2c-9beff291729c.png)

**Comment by b2p-fred** [comment]
IMHO extending the configuration that still exists in the _api_platform.yaml_ file should be a better solution than the one you are proposing. It may be easy to : 
```
  openapi:
    contact:
      name: '%env(string:API_CONTACT_NAME)%'
      url: '%env(string:API_CONTACT_URL)%'
      email: '%env(string:API_CONTACT_EMAIL)%'
    termsOfService: '%env(string:API_TOS)%'
    license:
      name: '%env(string:API_LICENSE_NAME)%'
      url: '%env(string:API_LICENSE_URL)%'

   servers:
    server1:
      url: 'https://docker.local/'
      description: 'Docker'
    server2:
      url: 'https://app-dev.company.com/'
      description: 'Dev'

```

What do think about it?
