### ISSUE TITLE
OpenApi: support more authentication schemes (not only apiKey)

### ISSUE THREAD

**Issue by lukey78** [api-platform/api-platform#2064]
**Description**  

Under the "swagger" configuration one could use the "api_keys" parameter to describe API authentication schemes that will be exported into the OpenApi specs (api/docs.json).

Currently, it seems, there is only the ApiKey type supported. Why not open that up so that one could implement all authentication schemes supported by OpenApi (see: https://swagger.io/docs/specification/authentication/)?

This is important for client generators to work properly (e.g. the https://github.com/OpenAPITools/openapi-generator).

**Example**  

Currently, I "fake" my "Bearer JWT" scheme with the ApiKey scheme:

```
api_platform:
  swagger:
    api_keys:
      myAuth:
        name: Authorization
        type: header
```

This results in this OpenApi scheme:

```
components:
  securitySchemes:
    myAuth:
      type: "apiKey"
      description: "Value for the Authorization header parameter"
      name: "Authorization"
      in: "header"
```

And this is the desired OpenApi scheme to correctly support the "Bearer" type (for example):

```
components:
  securitySchemes:
    myAuth:
      type: "http"
      scheme: "bearer"
      bearerFormat: "JWT"
```
