### ISSUE TITLE
Schema generator usage of Enum properties break generated Model Assert\choices due to malformed syntax 

### ISSUE THREAD

**Issue by florianajir** [api-platform/api-platform#2108]
**API Platform version(s) affected**: x2.6.8

**Description**  
in  schema-generator component, Enum properties generation to `Assert/Choices` in models  is not well formed and create an error in app execution.

**How to reproduce**  

Create a simple `config/schema.yaml` file including this:

```
types:
    Offer:
        properties:
            availability: { range: "ItemAvailability" }
    ItemAvailability:
        properties: { }
```

**Possible Solution**  

generate this: 

```
    #[Assert\Choice(callback: [ItemAvailability::class, 'toArray'])]
    private ?string $availability = null;
```

instead of this

```
    #[Assert\Choice(callback: ['ItemAvailability', 'toArray'])]
    private ?string $availability = null;
```
