### ISSUE TITLE
Unable to get my simple schema working (PHP memory limit exceed)

### ISSUE THREAD

**Issue by florianajir** [api-platform/api-platform#2109]
**API Platform version(s) affected**:2.6.8

**Description**  
From scratch framework install, latest version, declaring a simple schema.yaml file in config and using schema-generator component to generated entities, the app is crashing

**How to reproduce**  

1. Generate a new project from latest api-platform version
2. Build and run docker-container `docker-compose build --no-cache --pull && docker-compose up -d`
3. Run `docker-compose exec php composer instal myclabs/php-enum` (for enum support)
4. Copy `schema.yaml` content below in `api/config/schema.yaml`
5. Run `docker-compose exec php vendor/bin/schema generate src/ config/schema.yaml`
6. Remove or fix `Assert\Choices` annotations in generated models (bug described in https://github.com/api-platform/api-platform/issues/2108)
7. Run `https://localhost/docs` in browser

```
# api/config/schema.yaml
namespaces:
    entity: App\Entity\Schema
types:
    # Business domain
    Person:
        properties:
            name: { groups: [ "public" ], nullable: false }
            email: { groups: [ "internal" ], nullable: false, unique: true }
    Product:
        properties:
            name: ~
            description: ~
            image: { range: "ImageObject" }
            offers: { range: "Offer" }
    Offer:
        properties:
            availability: { range: "ItemAvailability" }
            availabilityEnds: { range: "DateTime" }
            availabilityStarts: { range: "DateTime" }
            availableDeliveryMethod: { range: "DeliveryMethod" }
            availableAtOrFrom: { range: "Place" }
            eligibleTransactionVolume: { range: "PriceSpecification" }
            image: { range: "ImageObject" }
            priceSpecification: { embedded: true, range: "PriceSpecification" }
            seller: { range: "Person" }
    # GEO
    Place:
        properties:
            address:
                columnPrefix: false
                embedded: true
                range: "PostalAddress"
            geo:
                columnPrefix: false
                embedded: true
                range: "GeoCoordinates"
    PostalAddress:
        embeddable: true
        operations:
            item: {}
            collection: {}
        properties:
            addressCountry: { range: "Text" }
            addressLocality: ~
            addressRegion: ~
            postalCode: ~
            postOfficeBoxNumber: ~
            streetAddress: ~
    GeoCoordinates:
        embeddable: true
        operations:
            item: {}
            collection: {}
        properties:
            elevation: { range: "Number" }
            latitude: { range: "Number" }
            longitude: { range: "Number" }
    # Utility
    DeliveryMethod:
        properties: { }
    ItemAvailability:
        properties: { }
    ImageObject:
        properties:
            author: ~
            contentUrl: { nullable: false }
            datePublished: { nullable: false, range: "DateTime" }
    PriceSpecification:
        embeddable: true
        operations:
            item: {}
            collection: {}
        properties:
            eligibleQuantity: { columnPrefix: "max_qty", embedded: true, range: "QuantitativeValue" }
            eligibleTransactionVolume: { columnPrefix: "min_amount", embedded: true, range: "PriceSpecification" }
            price: { nullable: false, range: "Number" }
            priceCurrency: ~
    QuantitativeValue:
        embeddable: true
        operations:
            item: {}
            collection: {}
        properties:
            unitText: ~
            value: { nullable: false, range: "Number" }
```

**Possible Solution**  

I think this is related to ApiResource models using Embedded/Embeddable properties but don't figure why

**Additional Context**  

```
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /srv/api/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php on line 3662

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /srv/api/var/cache/dev/ContainerSdqmRC9/getSecrets_VaultService.php on line 1
```
