### ISSUE TITLE
SoftDeleted entities aren't filtered/excluded

### ISSUE THREAD

**Issue by Jayfrown** [api-platform/api-platform#2128]
**API Platform version(s) affected**: 2.6.8

**Description**  

I have all my entities set up as `SoftDeleteable` using `StofDoctrineExtensions`, but I've noticed a couple issues in using this.

- The first time I call `DELETE /api/resource/:id`, the entity's `deleted_at` field is updated correctly;
- If I call `GET /api/resource` afterwards, the resource I just (soft)deleted still shows up in the collection.
- If I call `GET /api/resource/:id`, the resource is shown instead of a 404 error.
- ~~If I call `DELETE /api/resource/:id` again, the entity is completely removed from the database.~~

> **_EDIT:_** This last part is apparently expected behavior which can be disabled as follows:
>```
> * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=true, hardDelete=false)
>```
> Doing this, repeated DELETE calls simply update the timestamp in the `deleted_at` field.

I had expected that the `SoftDeleteableFilter` would exclude the entity from DB query results, thus preventing the entity from showing in the collection, and it would return a 404 on any subsequent ItemOperations like GET or DELETE.

Is my expectation wrong? Should I explicitly use [extensions](https://api-platform.com/docs/core/extensions/) to filter entities with the `deleted_at` property set, regardless of the `SoftDeleteableFilter` already being enabled?

**How to reproduce**  
```yaml
# stof_doctrine_extensions.yaml
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            sluggable: true
            timestampable: true
            blameable: true
            loggable: true
            softdeleteable: true
```
```yaml
# doctrine.yaml
doctrine:
    dbal:
        driver: pdo_mysqli
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_general_ci
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        resolve_target_entities:
            App\Model\AbstractIdentityInterface: App\Entity\AbstractIdentity
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity/"
                alias: GedmoLoggable
                is_bundle: false
```
```php
<?php
// TestEvent.php

namespace App\Entity\Planning;

use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiProperty;
use App\Repository\Planning\TestEventRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Blameable\Traits\BlameableEntity;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\SoftDeleteable\Traits\SoftDeleteableEntity;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Uid\Uuid;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=TestEventRepository::class)
 * @ORM\Table(name="test_events")
 * @Gedmo\Loggable
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=true, hardDelete=false)
 * @UniqueEntity("id")
 * @ApiResource(
 *     mercure={"private"=true},
 *     attributes={
 *         "security"="is_granted('CAN_VIEW_PLANNED_EVENTS', object)",
 *         "normalization_context"={"groups"={"read","write"}},
 *         "denormalization_context"={"groups"={"read","write"}},
 *     },
 *     collectionOperations={
 *         "get"={"security"="is_granted('CAN_LIST_PLANNED_EVENTS', object)"},
 *         "post"={"security"="is_granted('CAN_ADD_PLANNED_EVENTS', object)"},
 *     },
 *     itemOperations={
 *         "get"={"security"="is_granted('CAN_VIEW_PLANNED_EVENTS', object)"},
 *         "put"={"security"="is_granted('CAN_EDIT_PLANNED_EVENTS', object)"},
 *         "delete"={"security"="is_granted('CAN_DELETE_PLANNED_EVENTS', object)"},
 *     }
 * )
 */
class TestEvent
{
    use TimestampableEntity;
    use BlameableEntity;
    use SoftDeleteableEntity;

    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     * @ApiProperty(identifier=true)
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Gedmo\Versioned
     * @Groups("read", "write")
     */
    private $name;

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
    
    // ..
}
```
-----
**Evidence**

Entity exists as normal, not yet SoftDeleted:
```
GET https://localhost/api/test_events/1ec86d4c-bc82-60fc-a131-dbf5dc845e65
{
    "@context": "/api/contexts/TestEvent",
    "@id": "/api/test_events/1ec86d4c-bc82-60fc-a131-dbf5dc845e65",
    "@type": "TestEvent",
    "name": "test_1"
}

❯ bin/console dbal:run-sql "SELECT deleted_at FROM test_events WHERE id = 0x1ec86d4cbc8260fca131dbf5dc845e65;" 
 ------------ 
  deleted_at  
 ------------ 
              
 ------------ 
```

After a DELETE call, the entity is SoftDeleted (ie. `deleted_at` is set)
```
DELETE https://localhost/api/test_events/1ec86d4c-bc82-60fc-a131-dbf5dc845e65

❯ bin/console dbal:run-sql "SELECT deleted_at FROM test_events WHERE id = 0x1ec86d4cbc8260fca131dbf5dc845e65;"
 --------------------- 
  deleted_at           
 --------------------- 
  2022-02-05 23:48:49  
 --------------------- 
```

However, the entity is still shown in collections and on item operations
```
GET https://localhost/api/test_events/
{
    "@context": "/api/contexts/TestEvent",
    "@id": "/api/test_events",
    "@type": "hydra:Collection",
    "hydra:member": [
        {
            "@id": "/api/test_events/1ec86d4c-bc82-60fc-a131-dbf5dc845e65",
            "@type": "TestEvent",
            "name": "test_1"
        },
        [..]
    ],
    "hydra:totalItems": 10
}

GET https://localhost/api/test_events/1ec86d4c-bc82-60fc-a131-dbf5dc845e65
{
    "@context": "/api/contexts/TestEvent",
    "@id": "/api/test_events/1ec86d4c-bc82-60fc-a131-dbf5dc845e65",
    "@type": "TestEvent",
    "name": "test_1"
}
```

Doing another DELETE call removes the entity from the database
```
DELETE https://localhost/api/test_events/1ec86d4c-bc82-60fc-a131-dbf5dc845e65

❯ bin/console dbal:run-sql "SELECT deleted_at FROM test_events WHERE id = 0x1ec86d4cbc8260fca131dbf5dc845e65;"

 [OK] The query yielded an empty result set.

GET https://localhost/api/test_events/1ec86d4c-bc82-60fc-a131-dbf5dc845e65
{
    "@context": "/api/contexts/Error",
    "@type": "hydra:Error",
    "hydra:title": "An error occurred",
    "hydra:description": "Not Found",
    "trace": [
        [..]
    ]
}
```

**Possible Solution**  

**Additional Context**
