### ISSUE TITLE
API Platform 2.6.8 MongoDB service not found

### ISSUE THREAD

**Issue by ubsysdev** [api-platform/api-platform#2147]
**API Platform version(s) affected**: 2.6.8

**Description**  
 When I run  composer require doctrine/mongodb-odm-bundle I get the error The service "api_platform.doctrine_mongodb.odm.default_document_manager.property_info_extractor" has a dependency on a non-existent service "doctrine_mongodb.odm.default_document_manager". Did you mean this "api_platform.doctrine_mongodb.odm.default_document_manager.property_info_extractor"? 

Please help

**Comment by osama-aref** [comment]
Did you manage to solve this?

**Comment by muttley73** [comment]
in your symfony/config/packages/api_platform.yaml add:

```
api_platform:
  doctrine:
    enabled: true
  doctrine_mongodb_odm:
    enabled: false
```

this is working form me.
