### ISSUE TITLE
Overriding default order doesn't work with YAML format

### ISSUE THREAD

**Issue by wmfelipe** [api-platform/api-platform#2178]
**API Platform version(s) affected**: 2.6

**Description**  
I'm trying to override the default order when getting records by following [this part of documentation](https://api-platform.com/docs/core/default-order/#overriding-default-order) in YAML format, but the API Plataform seems ignore this configuration.

**How to reproduce**  
This is my code
```
# config/api_platform/resources/Superheroes.yaml

App\Entity\Superheroes:
    attributes:
        order:
            name: DESC
```

But when the Swagger calls the endpoint /api/superheroes?page=1&itemsPerPage=50 the returned order is always by ID.

Does anyone have an ideia how can I do it work?
