### ISSUE TITLE
oAuth : Change the OAuth default Authorization key name

### ISSUE THREAD

**Issue by wassimbkd** [api-platform/api-platform#2180]
**Change the OAuth default Authorization key name**  

Hi, is there a way to replace the key **"Authorization"** with a specific name **"TEST-API-KEY"** for example ?

<img width="290" alt="report_api_platform_oauth" src="https://user-images.githubusercontent.com/22977244/165253570-98da8053-dde1-4f30-919e-6832a28e526a.PNG">

**Actual  :**

```
curl -X 'POST' \
  'https://endpoint.test/api/urls' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer YmE5Zjg0YTllZTI2MWJmNTFlNWQxYWE3ZWYzMDI3MjI5ZTM1ZjI1Yzg0YzM2M2FhZDIxNzBjY2M2NmEyYzM1MQ' \
  -H 'Content-Type: application/json' \
  -d '{
  "url": "string"
}'
```

**What i want :**

```
curl -X 'POST' \
  'https://endpoint.test/api/urls' \
  -H 'accept: application/json' \
  -H 'TEST-API-KEY: Bearer YmE5Zjg0YTllZTI2MWJmNTFlNWQxYWE3ZWYzMDI3MjI5ZTM1ZjI1Yzg0YzM2M2FhZDIxNzBjY2M2NmEyYzM1MQ' \
  -H 'Content-Type: application/json' \
  -d '{
  "url": "string"
}'
```

I assume that it could be done with defining **api_keys** in that way :
```
swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: TEST-API-KEY
                type: header
```

My current configuration :

```
oauth:
        # To enable or disable OAuth.
        enabled: true
        # The OAuth client ID.
        clientId: '%env(API_PLATFORM_CLIENT_ID)%'
        # The OAuth client secret.
        clientSecret: '%env(API_PLATFORM_CLIENT_SECRET)%'
        # The OAuth type.
        type: 'oauth2'
        # The OAuth flow grant type.
        flow: 'password'
        # The OAuth token URL.
        tokenUrl: '%env(API_PLATFORM_TOKEN_URL)%'
        # The Oauth refresh Url
        refreshUrl: '%env(API_PLATFORM_TOKEN_URL)%'
        # The OAuth authentication URL.
        authorizationUrl: '%env(API_PLATFORM_AUTHORIZATION_URL)%'
```
