### ISSUE TITLE
Easy fix hot-reload for pwa

### ISSUE THREAD

**Issue by EkawaD** [api-platform/api-platform#2207]
**API Platform version(s) affected**: 2.6.8
**OS**: Windows 10
**Docker Desktop**: 4.9.1

**Description**  
With windows 10
Hot reloading doesn't work for pwa, it does work for the API.
I can make it work by adding WATCHPACK_POLLING=true to env vars.

**How to reproduce**  
Use this template and git clone the repo to your computer. 
Start docker desktop.
docker-compose build --pull --no-cache
docker-compose up -d 
Hot reloading doesn't work when updating pages/index.ts
Hot reloading doesn't work when updating the file pages/index.ts from the container (I opened the container in remote from vscode remote and tried changing pages/index.ts but still no hot reload)

**Possible Solution**  
I give up and used an easy fix, i just added WATCHPACK_POLLING=true to docker-compose.override.yml : 

```
...
pwa:
    build:
      context: ./pwa
      target: api_platform_pwa_dev
    volumes:
      - ./pwa:/usr/src/pwa:rw,cached
    environment:
      - WATCHPACK_POLLING=true
...
```

**Additional Context**  
There are some underlying issues with docker and windows that were already discussed [here ](https://github.com/api-platform/api-platform/issues/1816) and documented [here ](https://api-platform.com/docs/client-generator/troubleshooting/#docker-distribution-on-windows-and-hot-reloading)
It seems that it's the same issue, however it feels wrong that this easyfix isnt documented (It's windows specific and may affect performance so it shouldn't be available in the template) 
I am not sure if i should report this here but it the first place i looked after encountering this issue
