### ISSUE TITLE
Unable to set formats for subresources

### ISSUE THREAD

**Issue by henrikac** [api-platform/api-platform#2211]
**API Platform version(s) affected**: 2.6
**PHP version**: 8.1
**Symfony version**: 6.0

**Description**  
I'm trying to make my api only support `application/json` and according to [the documentation](https://api-platform.com/docs/core/content-negotiation/#configuring-formats-globally) I should be able to do this by doing

```yaml
# config/packages/api_platform.yaml
api_platform:
  defaults:
    formats:
      json: ['application/json']
```

I would expect this to affect *ALL* routes/operations, however, this does not affect subresource operations which still uses the default formats. I have also tried to set the `"formats"` directly on the `subresourceOperations` but without any luck.

```php
#[ApiResource(
  // ...
  subresourceOperations: [
    'resource_get_subresource' => [
      // ...
      'formats' => ['json' => ['application/json']],
    ],
  ],
)]
class MyEntity {}
```

I am not sure why the subresources keeps the default formats and not the ones specified in `api_platform.defaults.formats`.
