### ISSUE TITLE
Symfony - Hide the "Schemas" section

### ISSUE THREAD

**Issue by LtCMDstone** [api-platform/api-platform#2233]
Hey I'm using api-platform in my symfony project and I don't get it to hide the schemas section on the bottom in swagger.
Can anyone give me a hint?

![image](https://user-images.githubusercontent.com/25282375/184085017-129d8539-d6d7-4745-8440-3245fabd1820.png)

**Comment by Aerendir** [comment]
It is not something you can do from Api Platform.

https://stackoverflow.com/questions/57138564/how-to-hide-the-models-section-in-swagger-ui

**Comment by LtCMDstone** [comment]
Damn, ok but thanks! :)

**Comment by alanpoulain** [comment]
Actually you can do it in API Platform 2.7/3 like this:

```yml
# config/packages/api_platform.yaml
api_platform:
    swagger:
        swagger_ui_extra_configuration:
            defaultModelsExpandDepth: -1
```

Related PR: https://github.com/api-platform/core/pull/3731
