### ISSUE TITLE
[ASK] Use Different Connection for Write and Read

### ISSUE THREAD

**Issue by ad3n** [api-platform/api-platform#226]
It is possible to use different connection for write and read using API Platform based on config?

It is possible, it is very cool feature :+1:

**Comment by dunglas** [comment]
It's possible by overriding services definition. To change the manager registry to use for write, use the following definition:

```yaml
# app/config/services.yml

api_platform.doctrine.listener.view.write:
    class: ApiPlatform\Core\Bridge\Doctrine\EventListener\WriteListener
    arguments: ['@my_write_manager_registry']
    tags:
        - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 32 }
```

**Comment by dunglas** [comment]
After a second, though, not sure it can work without creating a custom implementation of the `ManagerRegistry` interface returning the good connection because we use `getManagerForClass`. This can probably be improved.

**Comment by ad3n** [comment]
@dunglas : Do you use `getManagerForClass` (`ManagerRegistry`) in every where? It is possible to change that to `EntityManager` object for more flexibility?

Then you add configurations to separate that depending on action that called

**Comment by ad3n** [comment]
I read the `@doctrine` service and i not really that is a good choice to create my own manager registry. There is have many parameter to construct.

```
    public function __construct(ContainerInterface $container, array $connections, array $entityManagers, $defaultConnection, $defaultEntityManager)
    {
        $this->setContainer($container);

        parent::__construct('ORM', $connections, $entityManagers, $defaultConnection, $defaultEntityManager, 'Doctrine\ORM\Proxy\Proxy');
    }
```

**Comment by dunglas** [comment]
You can decorate the default one.

**Comment by ad3n** [comment]
@dunglas : :+1: ok i will try. Thanks for your suggestion

**Comment by ad3n** [comment]
@dunglas : sorry, i have more question. When i use `getManagerForClass`, i can not detect the action W/R. Do you have a clue how to determine the action?

Thanks before

**Comment by dunglas** [comment]
I suggest to keep the current `doctrine` service as is and create new one called `doctrine_write` using the decorated registry.

Then override the write listener definition like the following:

```yaml
# app/config/services.yml

api_platform.doctrine.listener.view.write:
    class: ApiPlatform\Core\Bridge\Doctrine\EventListener\WriteListener
    arguments: ['@doctrine_write']
    tags:
        - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 32 }
```

Can you confirm that it works? If it's the case I'll add a page in the documentation about how to do that.
