### ISSUE TITLE
_api_x_operation_name to bound them all

### ISSUE THREAD

**Issue by jordicaballero** [api-platform/api-platform#228]
Hello

I am using my own bundle to provide a search service returning entity collections due to architectural concerns.

I defined a route to access to this entity collections:

```yaml
# resources.yml
resources: 
    MyDomainBundle\Model\Property:
         collectionOperations: 
            get: 
                route_name: 'get_properties' 
                normalization_context:
                     groups: ['all'] 
                serialization_context:
                     groups: ['all']

# routing.yml
get_properties: 
    path: '/properties'
     methods:  ['GET']
     defaults: 
        _controller: 'AppBundle:Property:get' 
        _api_resource_class: ‘MyDomainBundle\Model\Property\Property' 
        _api_collection_operation_name: 'get'

```
I would like to use serialization capabilities provided in ApiPlatform\Core\EventListener\SerializeListener.

## Problem
An undesired call to Doctrine CollectionDataProvider is being triggered for every call to /properties.

I have been exploring two workarounds:

1) To add a Custom DataProvider with higher priority to override default behavior. But I override it for all Collections. I need to do it only for certain resources.

2) To remove the **_api_collection_operation_name** in my route. This way, we lose SerializeListener magic, but we can serialize responses inside the controller like this (copy-pasted from SerializeListener):

```php
private function serialize($request, $operation = 'get') {
      $attributes = array('collection_operation_name' => $operation, 
        'resource_class' => ‘MyDomainBundle\Model\Property\Property');
      $context = $this->get('app.serializer.builder.property')
         ->createFromRequest($request, true, $attributes);
     $request->attributes->set('_api_respond', true);  
    return $this->get('serializer')->serialize($request->attributes->get('data'), $request->getRequestFormat(), $context);
 }
```
However, RouteNameResolver:getRouteName throws an InvalidArgumentException when serializing a jsonld formatted response because no **_api_collection_operation_name** is found:

Description: ”No collection route associated with the type \”MyDomainBundle\\Model\\Property\\Property\"."
Trace:
```yaml
#0 /vendor/api-platform/core/src/Bridge/Symfony/Routing/CachedRouteNameResolver.php(52): ApiPlatform\Core\Bridge\Symfony\Routing\RouteNameResolver->getRouteName(‘MyDomainBun...', true)
#1 /vendor/api-platform/core/src/Bridge/Symfony/Routing/IriConverter.php(95): ApiPlatform\Core\Bridge\Symfony\Routing\CachedRouteNameResolver->getRouteName(‘MyDomainBun...', true)
#2 /vendor/api-platform/core/src/Hydra/Serializer/CollectionNormalizer.php(75): ApiPlatform\Core\Bridge\Symfony\Routing\IriConverter->getIriFromResourceClass(‘MyDomainBun...')
#3 /vendor/api-platform/core/src/Hydra/Serializer/PartialCollectionViewNormalizer.php(46): ApiPlatform\Core\Hydra\Serializer\CollectionNormalizer->normalize(Array, 'jsonld', Array)
#4 /vendor/api-platform/core/src/Hydra/Serializer/CollectionFiltersNormalizer.php(57): ApiPlatform\Core\Hydra\Serializer\PartialCollectionViewNormalizer->normalize(Array, 'jsonld', Array)
#5 /vendor/symfony/symfony/src/Symfony/Component/Serializer/Serializer.php(142): ApiPlatform\Core\Hydra\Serializer\CollectionFiltersNormalizer->normalize(Array, 'jsonld', Array)
#6 /vendor/symfony/symfony/src/Symfony/Component/Serializer/Serializer.php(115): Symfony\Component\Serializer\Serializer->normalize(Array, 'jsonld', Array)
#7 /src/AppBundle/Controller/PropertyController.php(49): Symfony\Component\Serializer\Serializer->serialize(Array, 'jsonld', Array)
#8 /src/AppBundle/Controller/PropertyController.php(27): AppBundle\Controller\PropertyController->serialize(Object(Symfony\Component\HttpFoundation\Request), Object(MyDomainBundle\Service\PropertySearchCollectionResponse))
#9 [internal function]: AppBundle\Controller\PropertyController->getAction(Object(Symfony\Component\HttpFoundation\Request))
#10 /var/cache/dev/classes.php(4216): call_user_func_array(Array, Array)
#11 /var/cache/dev/classes.php(4171): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#12 /vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(168): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#13 /web/app_dev.php(34): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#14 {main}
```
I suggest to add some extra logic in ReadListener::onKernelRequest, to avoid the getCollectionData method of being triggered. Maybe a good point would be decouple serialization from data read aspects derived from **_api_%s_operation_name** params, adding some “data_provider” config.

I am missing something or there is sense in this last suggestion?

Thanks for reading

**Comment by dunglas** [comment]
@jordicaballero  https://github.com/api-platform/core/pull/909 do exactly that. This patch will be included in API Platform 2.1. Can you confirm it fits to your use case?

**Comment by jordicaballero** [comment]
It looks ok to me. From now on, the brand new **_api_receive**  request param set to false will disable ValidateListener, DeserializeListener and ReadListener behaviors.

```yaml
# routing.yml
get_properties: 
    path: '/properties'
     methods:  ['GET']
     defaults: 
        _controller: 'AppBundle:Property:get' 
        _api_resource_class: ‘MyDomainBundle\Model\Property\Property' 
        _api_collection_operation_name: 'get'
        _api_receive: false
```
Thanks for this great work!
