### ISSUE TITLE
API Platform V3 : Using JWT & Graphql

### ISSUE THREAD

**Issue by cedricDevWP** [api-platform/api-platform#2289]
I try to use JWT and Graphql in API Platform V3 but i have all the time 403 response when i add security "is_granted('ROLE_USER')" on Entity.

i try to setup like the documentation https://api-platform.com/docs/core/jwt/#jwt-authentication, but not working... On the security.yaml,  i have :

```yaml
security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        jwt:
            lexik_jwt: 
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            stateless: true
            provider: jwt
            json_login:
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
```

i tried multiple configuration but not working...

Someone has this problem ?

**Comment by NeuralFramework** [comment]
Hi, for my part I haven't found a way to create multiple separate entity login endpoints with LexikJWTAuthenticationBundle, but if you use a single endpoint you can use Symfony's "Chain User Provider".

https://symfony.com/doc/current/security/user_providers.html#chain-user-provider


I hope this information is helpful

an example would be:

![Snap](https://user-images.githubusercontent.com/2681400/195194183-e5e320b6-1251-45a1-969d-c0547345fc4c.png)

**Comment by BrandonlinU** [comment]
I'm using the same bundle as you and I don't have problems with it. It looks like that your User entity does not register the default role "ROLE_USER". Can you check if the method `getRoles()` look like this?

```php
    /**
     * The roles granted to this user.
     *
     * @see UserInterface
     * @return string[]
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }
```

**Comment by cedricDevWP** [comment]
I found the solution with : 

```yaml
security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: id
    firewalls:
        main:
            pattern:   ^/api
            stateless: true
            jwt: ~


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/api, roles: PUBLIC_ACCESS }
        # - { path: ^/api, roles: PUBLIC_ACCESS } # Allows accessing the Swagger UI        
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
```
