### ISSUE TITLE
Update SubRessources Api platform not working as expected 

### ISSUE THREAD

**Issue by lmasforne** [api-platform/api-platform#2290]
Hi,

I try to update a resource with subResources on Api Platform an it's not working depending json raw format of my data.

I explain quickly my Model 

`dataPool` ManyToOne `dataPoolStartup` ManyToOne `Startup`

I update a part of my dataPool object and i do this as a PATCH method

```
   "dataPoolStartup":{
      "startup":{
         "@context": "/contexts/Startup",
         "@type": "Startup",
         "@id":"/api/v2/startups/2069",
         "id":2069
      }
   },
```

If dataPoolStartup dont have startup existing relation it's work and do the link with `startup_id:2069` on dataPoolStartup in database 

But if there is already a link with other id i doesn't work, i must send this : 

```
   "dataPoolStartup":{
      "startup": "/api/v2/startups/2069"
   },
```
And it's work. 
The problem is dev front must format data on every edit before send data raw, so is it the normal behaviour of Api Platform ?    

Thanks!

**Comment by soyuka** [comment]
missing data, version, reproducer etc.

**Comment by lmasforne** [comment]
Api Platform version 2.7.0 

Entity Folder : 

```
#[ORM\Entity(repositoryClass: DataPoolRepository::class)]
class DataPool
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(cascade: ['persist'], inversedBy: 'dataPools')]
    private ?DataPoolStartup $dataPoolStartup = null;
}

#[ORM\Entity(repositoryClass: DataPoolStartupRepository::class)]
class DataPoolStartup
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'dataPoolStartups')]
    private ?Startup $startup = null;
}

#[ORM\Entity(repositoryClass: 'App\Repository\StartupRepository')]
class Startup
{
    #[Groups(['api:startups:show', 'api:startups:write'])]
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;
}

```
Resources config : 

```
resources:
  App\Entity\DataPool:
    security: "is_granted('ROLE_CONSULTANT')"
    attributes:
      route_prefix: /v2
      normalization_context:
        groups: ['api:datapools:show']
      denormalization_context:
        groups: ['api:datapools:write']
    collectionOperations:
      post: ~
      get:
        normalization_context:
          groups: ['api:datapools:list']
        filters: [
          'data-pool.search_filter',
        ]
    itemOperations:
      get: ~
      put: ~
      patch: ~
      delete: ~
```

Serialization

```
App\Entity\DataPool:
  attributes:
    id:
      groups: ['api:datapools:show', 'api:datapools:list']
    dataPoolStartup:
      groups: ['api:datapools:show', 'api:datapools:list', 'api:datapools:write']
      
App\Entity\DataPoolStartup:
  attributes:
    id:
      groups: ['api:datapools:show', 'api:datapools:list']
    startup:
      groups: ['api:datapools:show', 'api:datapools:list' , 'api:datapools:write']
      
App\Entity\Profile:
  attributes:
    id:
      groups: ['api:datapools:write']
```
