### ISSUE TITLE
Normalization context

### ISSUE THREAD

**Issue by yelmontaser** [api-platform/api-platform#23]
Hi,
Currently the API Bundle lets you specify a group serialization through the service of a resource.

```yml
services:
    resource.person:
        parent:     api.resource
        tags:       [ { name: api.resource } ]
        arguments:  [ AppBundle\Entity\Person ]
        calls:
            - [ initNormalizationContext, [ { groups: [ list ] } ] ]
```

The problem is that the method ```initNormalizationContext``` is applied to all operations on items and collections.

If for example in a person list, we need to display only the givenName and familyName, we apply the ```list``` group. yet in the person detail page we need more informations: birhtDate, telephone etc. and we want to add the ```detail``` group.

```php
namespace AppBundle\Entity;

use ...

/**
 * A person (alive, dead, undead, or fictional).
 * 
 * @see http://schema.org/Person Documentation on Schema.org
 * 
 * @ORM\MappedSuperclass
 * @Iri("http://schema.org/Person")
 */
abstract class Person extends Thing
{
    /**
     * @var string Family name. In the U.S., the last name of an Person. This can be used along with givenName instead of the name property.
     * ...
     * @Groups({"list", "detail"})
     */
    private $familyName;

    /**
     * @var string Given name. In the U.S., the first name of a Person. This can be used along with familyName instead of the name property.
     * ...
     * @Groups({"list", "detail"})
     */
    private $givenName;

    /**
     * @var \DateTime Date of birth.
     * ...
     * @Groups({"detail"})
     */
    private $birthDate;

    /**
     * @var string The telephone number.
     * ...
     * @Groups({"detail"})
     */
    private $telephone
```
I see 2 solutions: 

##### 1. Use the ```api.retrieve``` event 

```php
<?php
namespace AppBundle\EventListener;

use Dunglas\ApiBundle\Event\DataEvent;

class MyEventListener
{
    /**
     * @param DataEvent $dataEvent
     */
    public function onRetrieve(DataEvent $dataEvent)
    {
        $resource = $dataEvent->getResource();

        $resource->initNormalizationContext(array_merge(
            $resource->getNormalizationGroups(),
            ['detail']
        ));
    }
```
Define the service:
```yml
services:
    my_event_listener:
        class: "AppBundle\EventListener\MyEventListener"
        tags:  [ { name: kernel.event_listener, event: api.retrieve, method: onPostCreate } ]
```
##### 2. Use ```initItemOperations``` and override ```item_operation.get``` via a controller:

```php
<?php
namespace AppBundle\Controller;

use Dunglas\ApiBundle\Controller\ResourceController;
use Symfony\Component\HttpFoundation\Request;

/**
 * Class OperationController
 * @package AppBundle\Controller
 */
class CustomController extends ResourceController
{
    /**
     * @param Request $request
     * @param int $id
     *
     * @return \Dunglas\ApiBundle\JsonLd\Response
     */
    public function getAction(Request $request, $id)
    {
        $resource = $this->getResource($request);

        $resource->initNormalizationContext(array_merge(
            $resource->getNormalizationGroups(),
            ['detail']
        ));

        return parent::getAction($request, $id);
    }
}
```
Define the service:

```yml
services:
    resource.person:
        parent:     api.resource
        tags:       [ { name: api.resource } ]
        arguments:  [ AppBundle\Entity\Person ]
        calls:
            - [ initNormalizationContext, [ { groups: [ list ] } ] ]
            - [ initItemOperations, [ [ @resource.person.item_operation.get ] ] ]

    resource.person.item_operation.get:
        public: false
        class: Dunglas\ApiBundle\Api\Operation\Operation
        factory: [ @api.operation_factory, createItemOperation ]
        arguments: [ @resource.person, [ GET ], null, AppBundle:Custom:get ]
```

Both solutions works, but it's an assault course for add a simple serialization group.

**Comment by yelmontaser** [comment]
I propose to add ```cget``` or ```collection``` and ```get``` or ```item``` to the array expected by ```initNormalizationContext```.

eg:
```yml
services:
    resource.person:
        parent:     api.resource
        tags:       [ { name: api.resource } ]
        arguments:  [ AppBundle\Entity\Person ]
        calls:
            -
                - initNormalizationContext
                - [ { groups: { cget: [ list ], get: [ list, detail ] } } ]
            # OR
            -
                - initNormalizationContext
                - [ { groups: { collection: [ list ], item: [ list, detail ] } } ]
```
what do you think?
