### ISSUE TITLE
Validation works in unit test but is ignored when using endpoint

### ISSUE THREAD

**Issue by 4749448959599** [api-platform/api-platform#2307]
**API Platform version(s) affected**: 3.0

**Description**  

It seems that the validation is ignored, the validation mapping seems good because when I test it like that in a unit test it works : 

```
    final public function test_it_can_be_validated(object $object, array $expectedErrors): void
    {
        $validator = static::getContainer()->get(ValidatorInterface::class);
        $errors = [];
        foreach ($validator->validate($object, null, []) as $constraintViolation) {
            $errors[$constraintViolation->getPropertyPath()][] = $constraintViolation->getMessage();
        }

        self::assertSame($expectedErrors, $errors);
    }
```

But if I use the endpoint in e2e test or with a curl command sending bad data, it's not detected and I do not receive a 400 code as expected. Maybe is just something missing in the endpoint mapping ?

**How to reproduce**  

I have this kind of mapping for the validation, in a file ModifierInscription.yaml :

```
App\Core\Domain\Inscription\UseCase\ModifierInscription\Formulaires\ModifierInscription:
    properties:
        coordonnees:
            - Valid: ~
            - Type: App\Core\Domain\Inscription\UseCase\ModifierInscription\Formulaires\Coordonnees
        etatCivil:
            - Valid: ~
            - Type: App\Core\Domain\Inscription\UseCase\ModifierInscription\Formulaires\EtatCivil
        informationsPersonnelles:
            - Valid: ~
            - Type: App\Core\Domain\Inscription\UseCase\ModifierInscription\Formulaires\InformationsPersonnelles
        situationAdministrative:
            - Valid: ~
            - Type: App\Core\Domain\Inscription\UseCase\ModifierInscription\Formulaires\SituationAdministrative
        informationsBancaires:
            - Valid: ~
            - Type: App\Core\Domain\Inscription\UseCase\ModifierInscription\Formulaires\InformationsBancaires
        sante:
            - Valid: ~
            - Type: App\Core\Domain\Inscription\UseCase\ModifierInscription\Formulaires\Sante 
```

then for example in Coordonnees.yaml : 

```
App\Core\Domain\Inscription\UseCase\ModifierInscription\Formulaires\Coordonnees:
    properties:
        nomHebergeur:
            - Type: string
        numeroEtVoie:
            - NotBlank: ~
            - Type: string
        complementAdresse:
            - Type: string
        codePostal:
            - NotBlank: ~
            - Type: string
        ville:
            - NotBlank: ~
            - Type: string
        pays:
            - NotBlank: ~
            - Type: string
```

This is my endpoint mapping (ModifierInscription.yaml) : 

```
App\Core\Domain\Inscription\UseCase\ModifierInscription\Formulaires\ModifierInscription:
    normalizationContext:
        skip_null_values: false
    validationContext:
        groups: Default
    operations:
        ApiPlatform\Metadata\Patch:
            validate: true
            uriTemplate: /inscription/{id}
            read: false
            openapiContext:
                tags: [Inscription]
                summary: Édite les informations.
            controller: App\Infrastructure\UserInterface\Http\Controller\Api\Inscription\ModifierInscriptionController
```

ModifierInscription object is a DTO : 

```
<?php

declare(strict_types=1);

namespace App\Core\Domain\Inscription\UseCase\ModifierInscription\Formulaires;

use App\Core\Domain\Inscription\Model\Inscription;

class ModifierInscription
{
    public Inscription|null $inscription = null;

    public Coordonnees|null $coordonnees = null;

    public EtatCivil|null $etatCivil = null;

    public InformationsPersonnelles|null $informationsPersonnelles = null;

    public SituationAdministrative|null $situationAdministrative = null;

    public InformationsBancaires|null $informationsBancaires = null;

    public Sante|null $sante = null;
}
```

And here, for example, Coordonnees : 

```
<?php

declare(strict_types=1);

namespace App\Core\Domain\Inscription\UseCase\ModifierInscription\Formulaires;

class Coordonnees
{
    /** @var string|null */
    public $nomHebergeur;

    /** @var string */
    public $numeroEtVoie;

    /** @var string|null */
    public $complementAdresse;

    /** @var string */
    public $codePostal;

    /** @var string */
    public $ville;

    /** @var string */
    public $pays;
}
```
