### ISSUE TITLE
Global item_operations default doesn't work

### ISSUE THREAD

**Issue by marvin255** [api-platform/api-platform#2329]
**API Platform version(s) affected**: 3.0.4

**Description**  
I'm trying to disable `delete` operations globally. I see that [defaults have such options](https://api-platform.com/docs/core/configuration/). 

Unfortunately when I'm trying something like
```yaml
// config/packages/api_platform.yaml
defaults:
    item_operations:
        - get: ~
        - put: ~
        - patch: ~
```
nothing happens. I also tried
**How to reproduce**  

**Possible Solution**  

**Additional Context**
