### ISSUE TITLE
Not use validation.yml

### ISSUE THREAD

**Issue by ThomAille** [api-platform/api-platform#236]
Hi Dunglas, 

I want to create the user via API. 
I use FOSUserBundle and PUGXMultiUserBundle and I also wish to send a confirmation email at the time of creation of account. 

I have created a new controller and in this one I use my FormType. 
Here are my form configuration options
```php
public function configureOptions(OptionsResolver $resolver)
{
$resolver->setDefaults(array(
'data_class' => 'AppBundle\Entity\Student',
'csrf_protection' => false,
'validation_groups' => array('default'),
));
}
```

And validation.yml 
```yml
AppBundle\Entity\User:
  properties:
    email:
      - NotBlank:
          groups: [default]
      - AppBundle\Validator\Constraints\DisposableEmail:
          groups: [default]
    plainPassword:
      - NotBlank:
          groups: [default]
```

When I call my POST with an email that does not pass my validation it creates me nevertheless my account. 

This is the same for my PlainPassword field which can only be null

How do I have to make the system take into account my validation group that is pushed into my formType ?

Best Regards 
Thomas
