### ISSUE TITLE
Custom routePrefix doesnt work in yaml configuration

### ISSUE THREAD

**Issue by OndrosI** [api-platform/api-platform#2367]
**API Platform version(s) affected**: 3.0.10

Hello, i am trying set custom route prefix according to [documentation](https://api-platform.com/docs/core/operations/#prefixing-all-routes-of-all-operations) but yaml configuration doenst work. 

```
Namespace\To\Entity:
    routePrefix: /custom
    operations:
        ...
    graphQlOperations:
        ...
```
It says that I need to use an array and not a string

`"routePrefix" setting is expected to be null or an array, string given in . (which is being imported from "/var/www/html/project/api/current/app/src/Resources/config/routes/api_platform.yaml"). Make sure there is a loader supporting the "api_platform" type.`

When i use array it says:

`Warning: Array to string conversion`

**Comment by Byidi** [comment]
You need to add `resources` one level on top of the first resources declaration: 

```yaml 
resources:
  Namespace\To\Entity:
    routePrefix: /custom
    operations:
        ...
    graphQlOperations:
        ...
```
