### ISSUE TITLE
Cannot create operations using the PlaceholderAction.

### ISSUE THREAD

**Issue by ikamikaz3** [api-platform/api-platform#2394]
**API Platform version(s) affected**: 3.1.3

**Description**  

Using YAML configuration, I'm trying to use the built-in `PlaceholderAction` in my operation configuration (as described in the documentation here https://api-platform.com/docs/core/controllers/#using-the-placeholderaction) but it doesn't work, the `ApiLoader` throws an exception:
```
There is no builtin action for the "admin_finish_mission_item" operation. You need to define the controller yourself.
```
**How to reproduce**  

In `resources.yaml` :
```
resources:
    App\Entity\Mission:
        # Admin operations
        - operations:
            admin_finish_mission_item:
                class: ApiPlatform\Metadata\Patch
                method: PATCH
                controller: ApiPlatform\Action\PlaceholderAction
                uriTemplate: /admin/missions/{id}/finish
```

**Possible Solution**  

Creating a service alias solves this issue in `core/src/Symfony/Bundle/Resources/config/api.xml` :

```
        <service id="api_platform.action.placeholder" class="ApiPlatform\Action\PlaceholderAction" public="true" />
        # new alias <service id="ApiPlatform\Action\PlaceholderAction" alias="api_platform.action.placeholder" public="true" />
        <service id="api_platform.action.get_collection" alias="api_platform.action.placeholder" public="true" />
        <service id="api_platform.action.post_collection" alias="api_platform.action.placeholder" public="true" />
        <service id="api_platform.action.get_item" alias="api_platform.action.placeholder" public="true" />
        <service id="api_platform.action.patch_item" alias="api_platform.action.placeholder" public="true" />
        <service id="api_platform.action.put_item" alias="api_platform.action.placeholder" public="true" />
        <service id="api_platform.action.delete_item" alias="api_platform.action.placeholder" public="true" />
        <service id="api_platform.action.not_found" class="ApiPlatform\Action\NotFoundAction" public="true" />
        <service id="api_platform.action.not_exposed" class="ApiPlatform\Action\NotExposedAction" public="true" />
        <service id="ApiPlatform\Action\NotFoundAction" alias="api_platform.action.not_found" public="true" />
        <service id="ApiPlatform\Action\NotExposedAction" alias="api_platform.action.not_exposed" public="true" />
```
