### ISSUE TITLE
[3.1] Changing the Location of Swagger UI

### ISSUE THREAD

**Issue by StevenRenaux** [api-platform/api-platform#2408]
**API Platform version(s) affected**: 3.1.2

**Description**  
According to the [documentation](https://api-platform.com/docs/core/openapi/#changing-the-route), to change the route we only need to manually register the route of the doc.

I did it like this.

``` yaml
# app/config/routes.yaml

api_doc:
    path: /documentation
    controller: api_platform.swagger_ui.action
```

But unfortunately I still also have the documentation at the default route.

To finally removed it, I updated my configuration as well and finally it disappear.

``` yaml
# api/config/packages/api_platform.yaml

api_platform:
  # Enable the entrypoint.
  enable_entrypoint: false
```

I don't know if it's the right way to do it but I just wanted to report it maybe to ajust the documentation.
