### ISSUE TITLE
Make custom operation as default for all resources

### ISSUE THREAD

**Issue by tokarmaxe** [api-platform/api-platform#2422]
Hey, im beginer in api platform, but im trying to make custom operation and want to add it for all resources at once(globally) instead of write it in each resource. so, how can i make it ?
I found this [documentation](https://api-platform.com/docs/core/configuration/#global-resources-defaults), but `defaults` key did not help me, or i just cant to use it properly.

My situation is:
```
#config/api_platform/resources.yaml

resources: 
  App\Entity\Post: ~
    operations:
       custom:
          class: ApiPlatform\Metadata\Post
          method: POST
          uriTemplate: /posts/custom
          controller: App\Controller\CustomController
          input: App\Dto\CustomDTO
          output: App\Dto\CustomDTO
          processor: App\State\CustomProcessor
```
it works fine, but i want to add it for any resource and try to do this:
```
#config/packages/api_platform.yaml

api_platform:
  defaults:
    operations:
      custom:
        class: ApiPlatform\Metadata\Post
        method: POST
        path: /{resource_class}/custom
        controller: App\Controller\CustomController
        input: App\Dto\CustomDTO
        output: App\Dto\CustomDTO
        processor: App\State\CustomProcessor
```
and this way doesn't work at all, it seems that API platform ignores this configuration. Keys `item_operations` and `collection_operations` exist according to the [documentation](https://api-platform.com/docs/core/configuration/#global-resources-defaults), but then i walk through code i don't see same properties in TreeBuilder.

Well, my question is does your system support thing what i want to add? or maybe you can give me a direction, or an advice best approach to implement my idea?
