### ISSUE TITLE
Using the IriConverterInterface during testing to generate an IRI from a resource class will throw an InvalidArgumentException

### ISSUE THREAD

**Issue by Mauriceu** [api-platform/api-platform#2432]
**API Platform version(s) affected**: 3.1.7

**Description**  
Using the IriConverterInterface during testing to generate an IRI from a resource class will throw:

InvalidArgumentException: 'Unable to generate an IRI for the item of type "%s"'

**How to reproduce**  

Configure the IriConverter to be fetched from the container

```yaml
when@test:
    services:
        # Make the Converter public, so it can be retrieved from the container
        iri_converter:
            alias: ApiPlatform\Api\IriConverterInterface
            public: true
```

Fetch the IriConverter inside the ApiTestCase:
```php
    # alias 'iri_converter' defined in services.yaml
    $converter = self::$kernel->getContainer()->get("iri_converter"); 
    $converter->getIriFromResource("Some\Entity\FQN"); # <--- throws
```

**Possible Solution**  
EDIT: Nevermind, this solution will lead to the jsonld "@id" property not being correctly generated upon calling an ApiResource endpoint... 

In vendor/api-platform/core/src/Symfony/Routing/IriConverter.php line 143 change

```php
$forceCollection = $operation instanceof CollectionOperationInterface;
 ```
to

```php
$forceCollection = !$operation instanceof CollectionOperationInterface;
```

**Additional Context**
I do not know if this problem is specific to the test-environment, but in my case this issue arises only during testing.
