### ISSUE TITLE
Add into Docs JWT auth. 

### ISSUE THREAD

**Issue by alborq** [api-platform/api-platform#246]
Hi, 
I try to add into documentation new item to register my Get token action. 
Create a custom unused Model seen to be bad. 

Can we handle into documentation an extract of definition resource without having one ? 
Use a basic Swagger syntax ? 

Thanks to reply. 
Related to : #217 #241

**Comment by alborq** [comment]
My personnal way : 
```yml
    app.documentation.normalizer:
      class:     AppBundle\Documentation\DocumentationNormalizer
      decorates: api_platform.swagger.normalizer.documentation
      arguments: ['@app.documentation.normalizer.inner']
      public:    false
```
