### ISSUE TITLE
V3 Wrong serializer is used for output DTO

### ISSUE THREAD

**Issue by mkardakov** [api-platform/api-platform#2496]
**API Platform version(s) affected**: v3.1.12

**Description**  
I create a custom action that should return symfony roles in proper JSONAPI format. 
The output DTO that I use is returned in plain json instead of json-api

**How to reproduce**  
*the resource*
```
resources:
    App\Domain\RequestManagement\DTO\User:
        operations:
            auth:
                class: ApiPlatform\Metadata\Post
                method: POST
                input: false
                uriTemplate: /actions/auth
                status: 200
#                output: App\Domain\RequestManagement\DTO\User
                controller: App\Infrastructure\ApiPlatform\Action\AuthAction
                normalizationContext:
                    groups: [ 'item:read' ]
        properties:
            id:
                identifier: true
```
*Action*
```
<?php
declare(strict_types=1);

namespace App\Infrastructure\ApiPlatform\Action;

use App\Domain\RequestManagement\DTO\User;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpKernel\Attribute\AsController;
use Symfony\Component\Security\Core\Role\RoleHierarchyInterface;
use Webmozart\Assert\Assert;

#[AsController]
final class AuthAction
{
    public function __invoke(Security $security, RoleHierarchyInterface $roleHierarchy): User
    {
        $user = $security->getUser();
        Assert::notNull($user);

        return new User(
            11,
            $roleHierarchy->getReachableRoleNames($user->getRoles())
        );
    }
}
```
*api_platform configuration*
```
api_platform:
    formats:
        jsonapi:  ['application/vnd.api+json']
        html:     ['text/html']
        json:     ['application/json']
```

**Possible Solution**  
There is a problem with the priority of normalizers. Default symfony serializer is taken instead of api_platform.jsonapi.normalizer.item.  As a workaround I create a decorator for jsonapi normalizer and in this case it is called first
```
    App\Infrastructure\ApiPlatform\Normalizer\MyNormalizer:
        decorates: 'api_platform.jsonapi.normalizer.item'
```
