### ISSUE TITLE
Custom IriConverter

### ISSUE THREAD

**Issue by Palethorn** [api-platform/api-platform#250]
Hello,
I've been browsing the documentation and the source code, and couldn't find how to implement IriConverterInterface for custom IriConverter. If I implement a custom class, is there any way I could specify which one to use using config.yml?

**Comment by teohhanhui** [comment]
The easiest way would probably be to decorate the `api_platform.iri_converter` service.

**Comment by Palethorn** [comment]
I managed to produce the effect I wanted using custom doctrine mapping. But I'll try your suggestion also.

**Comment by Palethorn** [comment]
Got it to work:

```
# app/config/services.yml
services:
    api_platform.iri_converter:
        public: false
        class: "AppBundle\\Bridge\\Symfony\\Routing\\IriConverter"
        arguments: ['@api_platform.metadata.property.name_collection_factory', '@api_platform.metadata.property.metadata_factory', '@api_platform.item_data_provider', '@api_platform.route_name_resolver', '@api_platform.router', '@api_platform.property_accessor']
        tags: [{ name: 'api_platform.iri_converter', id: 'api_platform.iri_converter' }]
```
Thank you.
