### ISSUE TITLE
Invalid service definition in extensions doumentation?

### ISSUE THREAD

**Issue by blaues0cke** [api-platform/api-platform#251]
Is this a bug or miss I something? The documentation here (https://api-platform.com/docs/core/extensions) has the following constructor (2 parameters):

```
public function __construct(TokenStorageInterface $tokenStorage, AuthorizationChecker $checker)
{
    $this->tokenStorage = $tokenStorage;
    $this->authorizationChecker = $checker;
}
```

But this service definition (4 parameters):

```
# app/config/services.yml

services:
    app.doctrine.orm.query_extension.current_user:
        class: AppBundle\Doctrine\ORM\Extension\CurrentUserExtension
        public: false
        arguments:
            - '@api_platform.metadata.property.name_collection_factory'
            - '@api_platform.metadata.property.metadata_factory'
            - '@security.token_storage'
            - '@security.authorization_checker'
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
            - { name: api_platform.doctrine.orm.query_extension.item }
```

The example code will work with this service definition:

```
# app/config/services.yml

services:
    app.doctrine.orm.query_extension.current_user:
        class: AppBundle\Doctrine\ORM\Extension\CurrentUserExtension
        public: false
        arguments:
            - '@security.token_storage'
            - '@security.authorization_checker'
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
            - { name: api_platform.doctrine.orm.query_extension.item }
```

So what is wrong, the constructor or the service definition?
