### ISSUE TITLE
Issue with subresource identifiers (Api Platform 2.7)

### ISSUE THREAD

**Issue by alexjaunasse** [api-platform/api-platform#2529]
Hello,

I'm facing an issue when setting up a subresource endpoint containing two identifiers (one for each resource) on API Platform 2.7.
I followed the example in the offical documentation: https://api-platform.com/docs/v2.7/core/subresources/#company-employees) but still can't get it working properly.
I'm not using my Doctrine entity as resource class but I have a dedicated one instead (DTO).
Also, I'm not using annotations but a yaml config.

Here is my yaml config:
```
properties:
    App\Core\UserInterface\ApiPlatform\Mail\EstablishmentMailTemplateResource:
        id:
            identifier: true
resources:
    App\Core\UserInterface\ApiPlatform\Mail\EstablishmentMailTemplateResource:
        operations:
            ApiPlatform\Metadata\GetCollection:
                method: GET
                name: 'mail_templates_establishment_get_collection'
                provider: 'App\Core\Infrastructure\ApiPlatform\Provider\Mail\EstablishmentMailTemplateProvider'
                uriTemplate: '/establishments/{establishmentId}/mail-templates'
                requirements:
                    establishmentId: '\d+'
                uriVariables:
                    establishmentId:
                        fromClass: App\Core\UserInterface\ApiPlatform\Mail\EstablishmentMailTemplateResource
                        toProperty: establishmentId
            ApiPlatform\Metadata\Get:
                uriTemplate: '/establishments/{establishmentId}/mail-templates/{id}'
                provider: 'App\Core\Infrastructure\ApiPlatform\Provider\Mail\EstablishmentMailTemplateProvider'
                uriVariables:
                    establishmentId:
                        fromClass: App\Core\UserInterface\ApiPlatform\Mail\EstablishmentMailTemplateResource
                        toProperty: establishmentId
                    id:
                        fromClass: App\Core\UserInterface\ApiPlatform\Mail\EstablishmentMailTemplateResource
                        toProperty: id
                requirements:
                    establishmentId: '\d+'
                    id: '\d+'
```

Here is my resource class:
```
final class EstablishmentMailTemplateResource
{
    public function __construct(
        public int    $id,
        public string $name,
        public string $content,
        public ?int   $establishmentId = null,
        public ?int   $rhId = null,
    ) {}

    public static function fromModel(MailTemplate $mailTemplate): static
    {
        return new static(
            $mailTemplate->getId(),
            $mailTemplate->getName(),
            $mailTemplate->getContent(),
            $mailTemplate->getEstablishment()?->getId(),
            $mailTemplate->getRh()?->getId(),
        );
    }
}
```

Technically speaking, I don't have an error, but you can see that the base resource identifier in the response are not correct.

Instead of having something like: `/establishments/{establishmentId}/mail-templates/{id}`
I get: `/establishments/{id}/mail-templates/{id}`

Here is the response output:
```
{
    "@context": "/v2/contexts/EstablishmentMailTemplateResource",
    "@id": "/v2/establishments/10/mail-templates",
    "@type": "hydra:Collection",
    "hydra:member": [
        {
            "@id": "/v2/establishments/84/mail-templates/84",
            "@type": "EstablishmentMailTemplateResource",
            "id": 84,
            "name": "...",
            "content": "...",
            "establishmentId": 10
        },
    ...
```

I'd like to have some help and/or any input to help find out what's going on.

Thanks!
