### ISSUE TITLE
Extend info section of api documentation

### ISSUE THREAD

**Issue by stefanniedermaier** [api-platform/api-platform#2538]
**Description**  
Extend the configuration to allow additional/custom values in the info section of the api documentation.

**Example**  
Currently it seems not to be possible to add additional data to the info section, as the key-value pairs are placed in the "root" level

```yaml
api_platform:
    title: 'My title'
    description: 'Some title'
    version: 0.0.0
```

Moving this to a nested location and adding support for additional/custom key-value pairs would allow the configuration of new values.

```yaml
api_platform:
    info:
        title: 'My title'
        description: 'Some description'
        version: 0.0.0
        x-custom1: 'Some custom value'
        x-custom2: 'Some custom value'
```

Which then could be rendered like this:

```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "My title",
    "description": "Some description",
    "version": "0.0.0",
    "x-custom1": "Some custom value",
    "x-custom2": "Some custom value"
  }
}
```
