### ISSUE TITLE
GraphQL IDEs display page source code when visited in browser

### ISSUE THREAD

**Issue by baspeeters** [api-platform/api-platform#2542]
**API Platform version(s) affected**: v3.1.13

**Description**  
With default configuration, the GraphiQL IDE was always rendered in the browser on route `/graphql` while that same endpoint supported GraphQL calls. Since yesterday, visiting this in the browser does not render the IDE anymore, but shows the page's source code (the response has `content-type: application/json`).

The same issue occurs when visiting `/graphql/graphiql` and `/graphql/graphql_playground`.

**How to reproduce**  
This happened after rebuilding and restarting the docker compose stack we are using. Rewinding to commits in a time that the issue was not happening kept producing the same issue.

**Possible Solution**  
Workaround, move IDEs to separate routes:

```yaml
#config/routes.yaml

graphql_playground:
    path: /docs/graphql_playground
    controller: api_platform.graphql.action.graphql_playground

graphiql:
    path: /docs/graphiql
    controller: api_platform.graphql.action.graphiql
```

**Additional Context**  

![image](https://github.com/api-platform/api-platform/assets/393346/aae83373-2b06-4598-b753-bda6c32417d1)

![image](https://github.com/api-platform/api-platform/assets/393346/5b470f9f-c9d9-470c-af93-33218485bbce)
