### ISSUE TITLE
Decorating Http cache purger don't allow to disable invalidation

### ISSUE THREAD

**Issue by vasilvestre** [api-platform/api-platform#2565]
**API Platform version(s) affected**: 2.7

I haven't try on 3.0+ but this issue is due to Symfony DI so I guess all versions are affected. 

**Description**  
I'm decorating the HttpCachePurger invalidation class with this configuration. My issue is that when you disable invalidation on an env the service decorated doesn't exists.

```
    App\HttpCache\Shared\Doctrine\EventListener\PurgeHttpCacheListener:
        decorates: 'api_platform.doctrine.listener.http_cache.purge'
        bind:
            $purger: '@api_platform.http_cache.purger'
            $iriConverter: '@api_platform.iri_converter'
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: onFlush }
            - { name: doctrine.event_listener, event: postFlush }
```

```
The service "App\HttpCache\Shared\Doctrine\EventListener\PurgeHttpCacheListener" has a dependency on a non-existent service "api_platform.doctrine.listener.http_cache.purge".
```

**Possible Solution**  
Having a way to extend this service safely.
