### ISSUE TITLE
GraphQl: how can add custom query next to default query in yaml?

### ISSUE THREAD

**Issue by OndrosI** [api-platform/api-platform#2584]
**API Platform version(s) affected**: 3.0.10

Hi, i want to add custom collection query next to default collection query for entity.

My yaml:

```
resources:
    Dragon\Project\Entity\Project:
        routePrefix: /project
        operations:
            ApiPlatform\Metadata\GetCollection:
                security: 'is_granted("ROLE_WRITER") or is_granted("ROLE_READER")'
            ApiPlatform\Metadata\Get:
                security: 'is_granted("ROLE_WRITER") or is_granted("ROLE_READER")'
        graphQlOperations:
            queries:
                - ApiPlatform\Metadata\GraphQl\Query:
                  class: Dragon\Project\Entity\Project
                  security: 'is_granted("ROLE_WRITER") or is_granted("ROLE_READER")'
                  resolver: Dragon\Project\Resolver\ProjectResolver
                  args:
                      id: { type: ID }
                      name: { type: String }
                - ApiPlatform\Metadata\GraphQl\QueryCollection:
                  shortName: project
                  name: projects
                  collection: true
                  class: Dragon\Project\Entity\Project
                  security: 'is_granted("ROLE_WRITER") or is_granted("ROLE_READER")'
```

but when i add a new value to "queries" like this:

```
        graphQlOperations:
            queries:
                - ApiPlatform\Metadata\GraphQl\Query:
                  class: Dragon\Project\Entity\Project
                  security: 'is_granted("ROLE_WRITER") or is_granted("ROLE_READER")'
                  resolver: Dragon\Project\Resolver\ProjectResolver
                  args:
                      id: { type: ID }
                      name: { type: String }
                - ApiPlatform\Metadata\GraphQl\QueryCollection:
                  shortName: project
                  name: projects
                  collection: true
                  class: Dragon\Project\Entity\Project
                  security: 'is_granted("ROLE_WRITER") or is_granted("ROLE_READER")'
                - ApiPlatform\Metadata\GraphQl\QueryCollection:
                  shortName: test
                  name: test
                  collection: true
                  class: Dragon\Project\Entity\Project
                  resolver: Dragon\Project\Resolver\AnotherResolver
                  security: 'is_granted("ROLE_WRITER") or is_granted("ROLE_READER")'
```

my default query is not available anymore. I tried experimenting with "name" and "shortName" but that does not work.

What am i doing wrong?

Thx for answer
