### ISSUE TITLE
Cache-Config ignored on resource/endpoint-level

### ISSUE THREAD

**Issue by leberknecht** [api-platform/api-platform#2586]
**API Platform version(s) affected**: 3.2.7, 3.1.4

**Description**  
I have a configuration like this:
```
# packages/api-platform.yml
[...]
api_platform:
    defaults:
      cache_headers:
        max_age: 0
        shared_max_age: 3600
        vary: ['Content-Type', 'Authorization']

# resources/nominations.yaml
App\Entity\Nomination:
[...]
    ApiPlatform\Metadata\GetCollection: # we can't add logic with object in collections
      security: 'is_granted("ROLE_USER")'
      controller: 'App\Controller\NominationsListAction'
      cache_headers:
        max_age: 86400
        public: false
        shared_max_age: 0
        vary: [ 'Content-Type', 'Authorization' ]
```

The resource-level configuration seemed to be ignored, i always get the values from the `defaults` section. I also tried removing the `defaults` cache configuration completely, then i get `no-cache, private`. Am i missing something? I tried with 3.1.4 and 3.2.7, i also tried to put the configuration on the resource-level instead of endpoint, but the result was the same. Google brought up this SF thread https://stackoverflow.com/questions/75448864/after-updating-to-php-8-setting-custom-http-cache-headers-with-api-platform-is where the OP says that latest version fixed the problem, but it didnt for me. 

**How to reproduce**  
Set a cache-header configuration on an resource-level and tirgger the corresponding endpoint

**Possible Solution**  
Im not sure, i see handling for `cache_header` directive for the `defaults`, and also for some attributes (not sure though if that is about attributes of the endpoint or the resource)
![image](https://github.com/api-platform/api-platform/assets/1165177/26f5d711-fdfd-48a1-8136-d4e9db46103b)
I debugged into both 
```php
$resourceCacheHeaders = $attributes['cache_headers'] ?? $operation?->getCacheHeaders() ?? [];
```
lines, the one from `vendor/api-platform/core/src/HttpCache/EventListener/AddHeadersListener.php` gets triggered, but the `$attributes` dont have a `cache_headers` key.
