### ISSUE TITLE
PATCH method without a provider throws a 404 error

### ISSUE THREAD

**Issue by adrienHoareau** [api-platform/api-platform#2596]
**API Platform version(s) affected**: 3.2.7

**Description**  
I am using yaml to configure Api-Platform.
I have an entity that I tried to updated by calling a PATCH method.
I don't need a provider to do some logic so I ommited it and I just registered a processor. When calling the url using the builtin swagger UI, I had a 404.

**How to reproduce**  
```yaml
#resources.yaml
properties:
  App\Entity\MyEntity:
    uuid:
      identifier: true
resources:
  App\Entity\MyEntity:
    paginationClientItemsPerPage: true
    operations:
      ApiPlatform\Metadata\Get:
        provider: App\ApiProvider\MyEntity\GetProvider
      ApiPlatform\Metadata\Patch:
        #provider: App\ApiProvider\MyEntity\GetProvider #commented  to produce a 404 error
        processor: App\ApiProcessor\MyEntity\PatchProcessor
```
**Possible Solution**  
If a provider is required for patch methods then we should update the documentation (or I missed it ?) otherwise it needs a fix.
