### ISSUE TITLE
Maybe a configuration problem?

### ISSUE THREAD

**Issue by wysow** [api-platform/api-platform#26]
Hello @dunglas 

Here is my `schema.yml` file:

```yml
rdfa:
  - https://raw.githubusercontent.com/schemaorg/schemaorg/sdo-gozer/data/schema.rdfa
annotationGenerators:
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\PhpDocAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DoctrineOrmAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\ConstraintAnnotationGenerator
    - ApiPlatform\SchemaGenerator\AnnotationGenerator\DunglasApiAnnotationGenerator
namespaces:
  entity: AppBundle\Entity
types:
  Thing:
    properties:
      name: ~
      description: ~
  Action:
    properties:
      url: ~
  OrganizeAction:
    properties: {}
  BookmarkAction:
    properties:
      agent:
        range: Person
        cardinality: (*..1)
  Person:
    properties: {}
  Organization:
    properties:
      url: ~
```

And here is the error message I get on the `index` page of the api:

```
Unable to generate an IRI for "BookmarkAction".
```

Do you have a hint or something to help me on this? Thanks for your help.
