### ISSUE TITLE
Yaml resource configs with Symfony parameters doesn't work

### ISSUE THREAD

**Issue by VictorKrasnov** [api-platform/api-platform#2606]
API Platform version(s) affected: 3.2.9

I configure ApiPlatform with yaml files in my bundle. I have to make some parameters to configure API.
It works for resource class name, but not working with operation configuration.

```yaml
resources:
  '%my_bundle.users.class%': # it works fine!
     - class: ApiPlatform\Metadata\Get
        uriTemplate: /profile
        security: '%my_bundle.users.security.profile%' # it doesn't work :(((
```

I get en error:

```json
{
  "@id": "/api/errors/500",
  "@type": "hydra:Error",
  "title": "An error occurred",
  "detail": "Unexpected token \"operator\" of value \"%\" around position 1 for expression `%my_bundle.users.security.profile%`.",
  "status": 500,
  "type": "/errors/500",
```

Yaml configs should work with parameters, according to the common Symfony documentation: https://symfony.com/doc/current/configuration.html#configuration-parameters.

Is it a bug? Could you implement this?
