### ISSUE TITLE
Serialization of 'Closure' is not allowed/ Async Symfony Messenger Processor / ContextStamp

### ISSUE THREAD

**Issue by cheike569** [api-platform/api-platform#2611]
**API Platform version(s) affected**: 3.2.10

When using an `ApiResource` with Symfony messenger in async mode (persistance and serialization of messages into the database), input mode and DTO object enabled:

```
#[ApiResource(
    operations: [
        new Post(
            uriTemplate: '/users/reset_password',
            status: 202,
            input: ResetPasswordRequest::class,
            output: false,
            messenger: 'input',
            name: 'reset_password',
        )
    ],
)]
```

This Exception is thrown:
`Serialization of 'Closure' is not allowed`
![image](https://github.com/api-platform/api-platform/assets/244036/a83128ae-2ba4-4000-89d9-92d88c54732e)

![image](https://github.com/api-platform/api-platform/assets/244036/2d91d9e7-d1c0-4673-a569-f49887d2aec7)

I was able to track it down to the `ApiPlatform\Symfony\Messenger\ContextStamp` class, with adds the context to the Envelope, including the entire `Symfony\Component\HttpFoundation\Request` object, which seems to cause the problem (it's very large).

When removing the `Request` object from the context, it's working as desired (my current workaround):

```
#[ApiResource(
    operations: [
        new Post(
            uriTemplate: '/users/reset_password',
            status: 202,
            input: ResetPasswordRequest::class,
            processor: \App\State\MessengerProcessor::class,
            output: false,
            messenger: 'input',
            name: 'reset_password',
        )
    ],
)]
```

```
<?php
declare(strict_types=1);

namespace App\State;

use ApiPlatform\Metadata\DeleteOperationInterface;
use ApiPlatform\Metadata\Operation;
use ApiPlatform\Metadata\Util\ClassInfoTrait;
use ApiPlatform\State\ProcessorInterface;
use ApiPlatform\Symfony\Messenger\ContextStamp;
use ApiPlatform\Symfony\Messenger\DispatchTrait;
use ApiPlatform\Symfony\Messenger\RemoveStamp;
use Symfony\Component\Messenger\Envelope;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Messenger\Stamp\HandledStamp;

final class MessengerProcessor implements ProcessorInterface
{
    use ClassInfoTrait;
    use DispatchTrait;

    public function __construct(MessageBusInterface $messageBus)
    {
        $this->messageBus = $messageBus;
    }

    private function persist(mixed $data, array $context = []): mixed
    {
        unset($context['request']);

        $envelope = $this->dispatch(
            (new Envelope($data))
                ->with(new ContextStamp($context))
        );

        $handledStamp = $envelope->last(HandledStamp::class);
        if (!$handledStamp instanceof HandledStamp) {
            return $data;
        }

        return $handledStamp->getResult();
    }

    private function remove(mixed $data): void
    {
        $this->dispatch(
            (new Envelope($data))
                ->with(new RemoveStamp())
        );
    }

    public function process(mixed $data, Operation $operation, array $uriVariables = [], array $context = []): mixed
    {
        if ($operation instanceof DeleteOperationInterface) {
            $this->remove($data);

            return $data;
        }

        return $this->persist($data, $context);
    }
}

```

**Comment by lhapaipai** [comment]
it seems that it works if you use Symfony serialiser

```yaml
# config/packages/messenger
framework:
    messenger:
        serializer:
            symfony_serializer:
                format: json

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
```

**Comment by devnix** [comment]
I've had this problem, take a look at https://github.com/symfony/symfony-docs/issues/17636#issuecomment-1665172764

**Comment by MariusJam** [comment]
Hi, 

I'm having the same problem here. It happens when your framework.yaml contains the following:

```yaml
framework:
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
```

If you comment these lines (and correctly configure your api-platform routes as stateless), the issue is fixed.

However, this is not possible every time as you might need this specific configuration in framework.yaml if your app also have some routes that are not stateless.

I've discussed a bit the point on Symfony's support channel on Slack and the original problem is that Symfony does not guarantee that the Request object is serializable. So passing it into an envelope seems problematic in itself. I guess a fix should be made Api-Platform side to ensure the envelope's content is serializable. Removing the Request from the $context before passing it to the envelope seems to be the good way to achieve this might be a breaking change...
