### ISSUE TITLE
ResponseDTO Types Get Serialized Incorrectly

### ISSUE THREAD

**Issue by ledux6** [api-platform/api-platform#2613]
I'm using API Platform 3.2.1.

I'm returning a DTO object from a processor, which implements ProcessorInterface. 

The DTO object looks like this: 

```
{
     "analysisAu" => 0.5,
    "analysisAg" => 1.32,
    "isActive" => true
}
```
And the json response that gets returned is:

```
{
   "analysisAu" : "0.5",
   "analysisAg" : "1.32"
}
```

Float values get converted to strings and boolean values disappear. Maybe this is a configuration problem, but doesn't feel like it.

```
api_platform:
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        jsonapi: ['application/json']
    docs_formats:
        jsonopenapi: ['application/vnd.openapi+json']
        json: ['application/json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    resource_class_directories:
        - '%kernel.project_dir%/src'
    collection:
        pagination:
            page_parameter_name: page
            items_per_page_parameter_name: page_size
    swagger:
        api_keys:
            JWT:
                name: X-AUTH-API-TOKEN
                type: header

```
