### ISSUE TITLE
CollectionOperation GET|POST with nested path no longer working in API-Platform v3.2 (coming from v2.4)

### ISSUE THREAD

**Issue by gschafra** [api-platform/api-platform#2618]
**API Platform version(s) affected**: 3.2

**Description**  
During migration from API-Platform 2.4 to 3.2 we encountered the following problem:
In version 2.4 it was possible to declare a collection endpoint with a nested path - e.g. /books/invoice
After migration to API-Platform 3.2 I get a 404 error when calling this endpoint.
Are nested paths without parameters not allowed anymore?
Declaration before migration:

```php
/**
 * API Entity "Book"
 *
 * @ApiResource(
 *     collectionOperations={
 *        "get"={},
 *        "post"={},
 *        "get_invoice"={
 *           "method"="GET",
 *           "path"="/books/invoice",
 *           "swagger_context"={
 *              "summary"="Gets all books that have not yet been invoiced"
 *           }
 *        }
 *     },
 *     itemOperations={
 *        "get"={},
 *        "put"={},
 *        "delete"={}
 *     }
 * )
 */
```

Code after migration:

```php
/**
 * API Entity "Book"
 */
#[ApiResource(
    operations: [
        new Get(),
        new Put(),
        new Delete(),
        new GetCollection(),
        new Post(),
        new GetCollection(
            uriTemplate: '/books/invoice',
            provider: BookInvoiceProvider::class,
            openapi: new Operation(
                summary: 'Gets all books that have not yet been invoiced',
            )
        )
    ]
)]
```
The debug:router commands shows `_api/books/invoice_get_collection  GET  ANY  ANY  /api/books/invoice`. But the router matches the single GET endpoint.

```shell
php bin/console router:match /api/books/invoice
```

[OK] Route "_api_/books/{id}{._format}_get" matches
Changing uriTemplate to "books_invoice" would solve the issue. But I was wondering why it doesn't work anymore.

**How to reproduce**  
Trying to access a API resources collection endpoint with configured nested path as `uriTemplate` in `GetCollection` (see above)

**Additional Context**  
Migrating from API-Platform v2.4 -> v3.2

**Comment by gschafra** [comment]
Re-posted here: https://github.com/api-platform/core/issues/6148. Unfortunately this is quite critical for us, as we want to avoid breaking changes as far as possible. Is there any chance that someone will take care of this problem? Or should we use commercial support?

**Comment by marcinkonwiak** [comment]
Had the same problem. Try adding requirements to the first Get() operation. 

For example if your IDs are in the UUID format add:
`requirements: ['id' => '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}']`

Then the 'invoice' part of the url won't be treated as the {id} in that first GET operation.


If you want to apply the same requirement to every operation you can do something like that:
```php
<?php

namespace App\Service;

use Symfony\Component\Config\Loader\Loader;

class RouteRequirementEnforceLoader extends Loader
{
    private $decorated;

    public function __construct(Loader $decorated, ?string $env = null)
    {
        parent::__construct($env);
        $this->decorated = $decorated;
    }


    public function load($resource, string $type = null)
    {
        $routes = $this->decorated->load($resource, $type);

        foreach ($routes as $route) {
            $route->setRequirement('id', '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}');
        }

        return $routes;
    }

    public function supports($resource, string $type = null)
    {
        return $this->decorated->supports($resource, $type);
    }
}
```

and then add that to the services:
```yaml
services:
    App\Service\RouteRequirementEnforceLoader:
        decorates: 'routing.loader'
        arguments: [ '@App\Service\RouteRequirementEnforceLoader.inner' ]
```

**Comment by GerRubio** [comment]
Hello. I have spent already like 3 days looking for some solutions to my problem and I think it is related with this issue.

I started a new project and I am using API Platform 3.2 too and PHP 8.2 but instead of getting an 404 error, I am getting an 405 error. This one in particular:

```
{"class":"Symfony\\Component\\HttpKernel\\Exception\\MethodNotAllowedHttpException","code":405,"message":"No route found for \"POST http://localhost:250/api/v1/users/register\": Method Not Allowed (Allow: GET, PUT, PATCH, DELETE)"}
```

This endpoint is for user register.

I am not using attributes directly in my PHP code, but I am using .yaml files instead. This my User.yaml file resources:

```
App\Entity\User:
  attributes:
    normalization_context:
      groups: [user_read]

  collectionOperations:

    # User register
    register:
      method: POST
      path: /users/register
      controller: App\Controller\Action\User\Register
      denormalization_context:
        groups: [user_register]
      openapi_context:
        summary: Register a new user

  itemOperations:
    get:
      method: GET
```

My question is if this issues is related, if not, I will open a new issue.

Thanks.
