### ISSUE TITLE
Apply filters in custom data provider

### ISSUE THREAD

**Issue by BerislavSapina** [api-platform/api-platform#262]
Hi,
i have a problem.

I can not figure it out how to apply filters for custom collection data provider. In this examples provider does not do anything but filters are problem.

This is my resource file:
```
resources:
    LocationBundle\Entity\Location:
        itemOperations:
            get:
                method: 'GET'
                normalization_context:
                    groups: ['location-item']
        collectionOperations:
            get:
                method: 'GET'
                normalization_context:
                    groups: ['location-list']
        attributes:
            filters: ['location.search', 'location.boolean']
```

My provider:
```
class LocationCollectionDataProvider implements CollectionDataProviderInterface
{
    /**
     * @var EntityRepository
     */
    private $locationRepository;

    public function __construct(EntityRepository $locationRepository)
    {
        $this->locationRepository = $locationRepository;
    }

    public function getCollection(string $resourceClass, string $operationName = null)
    {
        if (Location::class !== $resourceClass) {
            throw new ResourceClassNotSupportedException();
        }

        return $this->locationRepository->findAll();

    }

}
```

services:
```

    location.repository:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [ LocationBundle\Entity\Location ]

    location.collection_data_provider:
        class: 'LocationBundle\DataProvider\LocationCollectionDataProvider'
        public: false
        arguments: [ "@location.repository" ]
        tags:
            -  { name: 'api_platform.collection_data_provider', priority: 2 }
```

Tnx! :D

**Comment by Simperfit** [comment]
Could you please do the following ? 

- Fork the [API Platform Standard Edition](https://github.com/api-platform/api-platform)
- Do the minimum modification to reproduce
- Post the link in here

We will test that and try to help you.

**Comment by devrck** [comment]
Hi,

I'm also interested in this issue because it's not explained in the docs how you can create a custom filter and apply it to a custom data provider.
You have only an example where you create a custom filter but it's tied to doctrine.

**Comment by soyuka** [comment]
You need to inject the filters in your data provider and apply them. You can also use the `FilterExtension` to enable every filter.

See here for example: https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/CollectionDataProvider.php#L64

**Comment by mvigneron** [comment]
@devrck 
I'm also interested how we can create custom filter and apply it in a custom data provider, do you have implemented that ? Do you have an code example please ?

I would like to query with ElasticSearch my entity "Shop" with a custom filter (term) like that 
`http://localhost/api/shops?term=foo`
This request must return all shops entities where attributes "name" or/and"description" contains "foo"

Thanks

**Comment by devrck** [comment]
Hi @mvigneron ,

What I did is inject the filter in the data provider, they are both defined as services. Nothing to fancy.

**Comment by mvigneron** [comment]
Hi @devrck ,

maybe I don't understand utility of custom Filter and custom provider because, in my case, I don't know why I must inject the filter in the data provider.

in my case, I have a custom filter to accept a filter properties "term" and I have a custom data provider to search and get results in Elastic Search. In my custom data provider, I inject RequestStack to get my parameter "term" and call a service to get Results with this parameter.

Can you show me your custom filter and custom data provider to understand ?

Thanks

**Comment by mvigneron** [comment]
Hi @Simperfit 

I have a custom filter that I use in my custom provider but I don't know if it's the best solution.

```
class CustomShopFilter implements FilterInterface
{

    /**
     * Gets the description of this filter for the given resource.
     *
     * Returns an array with the filter parameter names as keys and array with the following data as values:
     *   - property: the property where the filter is applied
     *   - type: the type of the filter
     *   - required: if this filter is required
     *   - strategy: the used strategy
     *   - swagger (optional): additional parameters for the path operation,
     *     e.g. 'swagger' => [
     *       'description' => 'My Description',
     *       'name' => 'My Name',
     *       'type' => 'integer',
     *     ]
     * The description can contain additional data specific to a filter.
     *
     * @see \ApiPlatform\Core\Swagger\Serializer\DocumentationNormalizer::getFiltersParameters
     *
     * @param string $resourceClass
     *
     * @return array
     */
    public function getDescription(string $resourceClass): array
    {
        $description = [
            'term' => [
                'type' => 'string',
                'required' => false,
                'property' => 'term',
                'swagger' => [
                    'description' => 'Filter to search in name,description, product name, product description',
                    'name' => 'term',
                    'type' => 'string',
                ],
            ],
            'categories[]' => [
                'type' => 'string',
                'required' => false,
                'property' => 'categories',
                'swagger' => [
                    'description' => 'categories filter',
                    'name' => 'categories[]',
                    'type' => 'string',
                ],
            ],
            'geoloc[]' => [
                'type' => 'string',
                'required' => false,
                'property' => 'geoloc',
                'swagger' => [
                    'description' => 'geolocalisation filter [latitude,longitude,distance]',
                    'name' => 'geoloc[]',
                    'type' => 'string',
                ],
            ],
        ];

        return $description;
    }
}
```

```
class ElasticsearchCollectionDataProvider implements CollectionDataProviderInterface
{
    private $searcherService;
    private $requestStack;
    private $resourceMetadataFactory;
    private $itemsPerPageParameter;
    private $globalItemsPerPage;
    private $pageParameter;

    public function __construct(SearcherService $searcherService,RequestStack $requestStack,ResourceMetadataFactoryInterface $resourceMetadataFactory,int $itemsPerPage = 30,int $globalItemsPerPage = 30)
    {
        $this->searcherService = $searcherService;
        $this->requestStack = $requestStack;
        $this->resourceMetadataFactory = $resourceMetadataFactory;
        $this->itemsPerPageParameter = $itemsPerPage;
        $this->globalItemsPerPage = $globalItemsPerPage;
        $this->pageParameter = "page";
    }

    /**
     * Retrieves a collection.
     *
     * @param string $resourceClass
     * @param string|null $operationName
     *
     * @throws ResourceClassNotSupportedException
     *
     * @return array|\Traversable
     */
    public function getCollection(string $resourceClass, string $operationName = null)
    {
        // Add here all entities that's you want to query with ElasticSearch
        if (!in_array($resourceClass, [Shop::class,Offer::class])) {
            throw new ResourceClassNotSupportedException();
        }
        $request = $this->requestStack->getCurrentRequest();

        $index = explode('\\', $resourceClass);
        $index = strtolower(end($index));

        $filters = $request->query->all();

        // Results is a PagerFanta


        $results = $this->searcherService->search($index,$filters);

        $resourceMetadata = $this->resourceMetadataFactory->create($resourceClass);

        $results->setMaxPerPage(
            (int) $request->get(
                $this->itemsPerPageParameter,
                $resourceMetadata->getCollectionOperationAttribute(
                    $operationName,
                    'pagination_items_per_page',
                    $this->globalItemsPerPage,
                    true
                )
            )
        );

        $results->setCurrentPage((int) $request->get($this->pageParameter, 1));

        return $results;
    }
}
```

**Comment by fulopattila122** [comment]
How do you inject the filters?
Without the custom data provider we had this in `resources.yml`:

```yml
resources:
    EntityClass:
        collectionOperations:
            get:
                filters: ['api.filter.shop', 'api.filter.language']
```
And they got injected along with many other stuff:
```php
// dump($this->collectionExtensions)
CollectionDataProvider.php on line 64:
array:5 [▼
  0 => EagerLoadingExtension {#128827 ▶}
  1 => FilterExtension {#128979 ▶}
  2 => FilterEagerLoadingExtension {#128989 ▶}
  3 => OrderExtension {#128990 ▶}
  4 => PaginationExtension {#128991 ▶}
]
```
How can I inject all these to the custom data provider?

**Comment by fulopattila122** [comment]
I've found that for Symfony 3.4+ it can be added to the service definition this way:

```yml
services:
    AppBundle\DataProvider\ShopContentLibraryItemProvider:
        tags: [ { name: 'api_platform.collection_data_provider', priority: 3 } ]
        autoconfigure: false
        arguments:
            $collectionExtensions: !tagged api_platform.doctrine.orm.query_extension.collection
```
Unfortunately the project is on Symfony 3.3, so apparently I have to create a compiler pass 🙄
