### ISSUE TITLE
Problem: The owning side of an association has no "mappedBy" field.

### ISSUE THREAD

**Issue by ZeinMansor** [api-platform/api-platform#2644]
**API Platform version affected**:  `^3.2`

## Description  
i am unable to use `doctrine orm` relations with `#[ApiResource()]` attribute, i get the following error when calling `http://localhost:8000/api/graphql/graphql_playground`

## Error message

```bash
  Context: Calling Doctrine\ORM\Mapping\ClassMetadata::getAssociationMappedByTargetField() with "role", which is the owning side of an association.
  Problem: The owning side of an association has no "mappedBy" field.
  Solution: Call Doctrine\ORM\Mapping\ClassMetadata::isAssociationInverseSide() to check first in .
   (which is being imported from "C:\zein_workspace\FAST\fast-api\config/routes/api_platform.yaml")
  . Make sure there is a loader supporting the "api_platform" type.
```

## How to reproduce
i am following similar approach to the example provided by doctrine project documentation page [here](https://www.doctrine-project.org/projects/doctrine-orm/en/3.0/reference/association-mapping.html#one-to-many-bidirectional), but to build role management for my users API

### Role class

```php
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ApiResource]
class Role
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 64)]
    private ?string $name = null;

    #[ORM\OneToMany(targetEntity: User::class, mappedBy: 'role')]
    private Collection $users;



    public function __construct()
    {
        $this->users = new ArrayCollection();
    }
    
  // etc...

}


```

### User Class

```php
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ApiResource]
class User
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $firstName = null;


    #[ORM\ManyToOne(targetEntity: Role::class, inversedBy: 'users')]
    #[ORM\JoinColumn(nullable: false, name: "role_id", referencedColumnName: "id")]
    private ?Role $role = null;


    public function __construct()
    {
    }

   // etc...
}
```

## Extra Details

i thought this issue is related to a `doctrine/orm:3.1` [issue](https://github.com/doctrine/orm/issues/11250) , but i was recommended to publish the my issue here

### Environment

php version: `8.2`
symfony version: `6.4`
symfony cli version: `5.8.11`
doctrine/orm version: `3.1.x-dev (latest one)`
api-platform/core version:  `^3.2`

### Config:
```yaml
# /config/packages/api_platform.yaml
api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    
    doctrine:
        enabled: true

    graphql:
        graphql_playground:
            enabled: true


```
