### ISSUE TITLE
Docs OpenAPI yaml serializer not working

### ISSUE THREAD

**Issue by stvnwrgs** [api-platform/api-platform#2652]
**API Platform version(s) affected**: 3.2

**Description**  
I've tried to add yaml as openapi docs output under `api/docs.yamlopenapi` but it does not work. 

I've used the following reference: 
https://github.com/api-platform/core/blob/6d6f856148205d7b3fb906f9f2d9ca55fbe71518/src/Symfony/Bundle/DependencyInjection/Configuration.php#L170

**Response**
```
"detail": "Format \"yamlopenapi\" is not supported",
"status": 404,
```

**How to reproduce**  
```yaml
docs_formats:
        jsonopenapi:
            mime_types:
                - application/vnd.openapi+json
        yamlopenapi:
            mime_types:
                - application/vnd.openapi+yaml
        json:
            mime_types:
                - application/json
        jsonld:
            mime_types:
                - application/ld+json
```
