### ISSUE TITLE
Disabling Doctrine support clears up Swagger docs

### ISSUE THREAD

**Issue by JarJak** [api-platform/api-platform#2655]
**API Platform version(s) affected**: 3.2

**Description**  
Because I use API only as a gateway to other microservices, api platform does not use its own DB at all. So I want to disable Doctrine support.
When you disable doctrine in configuration, Api Resources / operations are not longer visible swagger docs ui. Re-enabling it brings them back.

**How to reproduce**  
Create api resource (can be the default greeting one), go to swagger docs.

**Possible Solution**  
Remove possibility to disable Doctrine support, or add info about this side effect.

**Additional Context**  
With Doctrine enabled:
![image](https://github.com/api-platform/api-platform/assets/4981490/fd0f2e2f-3bb7-4c76-bffd-4bc8c2f21625)

With Doctrine disabled:
![image](https://github.com/api-platform/api-platform/assets/4981490/b226102c-b1d9-414c-bc19-1577f32fd6fe)

**Comment by JarJak** [comment]
Resolved:
Apparently Resource classes by default can't be placed anywhere in the code just by adding `#[ApiResource]` to it.
I placed them under `src/Entity` and by default this directory is scanned only if doctrine support is enabled.

Fix:
There are two similar ways to fix it, by adding to the config file:
```yaml
    doctrine:
        enabled: false
    # 1st option
    resource_class_directories:
        - '%kernel.project_dir%/src/Entity'
    # 2nd option
    mapping:
        paths:
              - '%kernel.project_dir%/src/Entity'
```

@soyuka I think the documentation is missing the part explaining where to put resource classes?
