### ISSUE TITLE
ApiPlatform - FosUser - JWT

### ISSUE THREAD

**Issue by Dannebicque** [api-platform/api-platform#270]
Bonjour,

I try to use ApiPlatform with FosUserBundle and LexikJWTBundle (maybe, it is not a good idea ?).
I follow the documentation, I install the bundles, I create my User regarding the example. I test. It works.

I add LexikJwt, I copy the security.yml example. I test (http://127.0.0.1:8000/login), and I have this response {"code":401,"message":"Bad credentials"}

```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_READER: ROLE_USER
        ROLE_ADMIN: ROLE_READER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
            form_login:
                check_path: /login_check
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        main:
            pattern:   ^/
            provider: fos_userbundle
            stateless: true
            anonymous: true
            lexik_jwt: ~

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
```

Maybe I forgot something. Maybe I don't understand something, but I don't know what ? Someone can help me ?

Thanks

David
