### ISSUE TITLE
Eager loading on child embedded attributes not work

### ISSUE THREAD

**Issue by ramzes13** [api-platform/api-platform#272]
Hello, I have some entities with embedded fields:

```
AppBundle\Entity\Parent:
      id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 250
            nullable: false
   ....
    oneToMany:
        childs:
            targetEntity: AppBundle\Entity\Child
            joinColumn:
                referencedColumnName: id
                nullable: false
            mappedBy: parent
            cascade: [persist, remove]

AppBundle\Entity\Child:
      id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
   .....
    embedded:
        embeddedProperty:
            class: AppBundle\Entity\GenericEmbedded

AppBundle\Entity\GenericEmbedded
    type: embeddable
    fields:
        value1:
            type: integer
            nullable : false

        value2:
            type: integer
            nullable : false
```

Serialisations config:
```
AppBundle\Entity\Parent:
    attributes:
        name:
            groups:
                - 'sparent_read_item'

AppBundle\Entity\Child:
    attributes:
        embeddedProperty:
            groups:
                - 'sparent_read_item'

AppBundle\Entity\GenericEmbedded:
    attributes:
        value1:
            groups:
                - 'sparent_read_item'
        value2:
            groups:
                - 'sparent_read_item'
```

When I get parent by id the answer is:
```
{
 name: 'test',
 childs: [
  {
   embeddedProperty: null
  }
 ]
}
```
If I disable from config eager_loading:

```
api_platform:
    version: 0.0.1
    eager_loading:
        enabled: false
```
I have the correct answer:
```
{
 name: 'test',
 childs: [
  {
   embeddedProperty: {
    value1: '',
    value2: ''
   }
  }
 ]
}
```

I think that the problem is in eager loading system.

Thanks.
