### ISSUE TITLE
`DELETE` as a collection operation

### ISSUE THREAD

**Issue by DenuxPlays** [api-platform/api-platform#2749]
**Description**  

I recently wanted to use `DELETE` as a collection operation and wondered why api-platform does not allow it.
It does not make any sense to restrict the user in that way because they are reasonable use cases for it (for example: an endpoint for deleting every entity).

**Example**  
The following should be possible:
```yaml
App\Dto:
  collectionOperations:
     delete:
       path: /api/entity/del
```
