### ISSUE TITLE
Normalization context question and possible bug

### ISSUE THREAD

**Issue by antonioperic** [api-platform/api-platform#275]
From docs I understand that if i have "global" config i can do like this

```
resources:
    ChatBundle\Entity\Chat:
        normalization_context:
            groups: ['chat']
        collectionOperations:
            get:
                method: 'GET'
        itemOperations:
            get:
                method: 'GET'
```

But that doesn't work. If I do this, it works
```
resources:
    ChatBundle\Entity\Chat:
        normalization_context:
            groups: ['chat']
        collectionOperations:
            get:
                method: 'GET'
                normalization_context:
                    groups: ['chat']
        itemOperations:
            get:
                method: 'GET'
                normalization_context:
                    groups: ['chat']

```
Am I doing something wrong?
