### ISSUE TITLE
Swagger Documentation for multi App

### ISSUE THREAD

**Issue by galliroberto** [api-platform/api-platform#2763]
**API Platform version(s) affected**: 3.3.310

**Description**  
I am building a multi app as described here
https://symfony.com/doc/current/configuration/multiple_kernels.html
I have 4 apps with dedicated openapi documentation.
Every app has dedicated cache and log.
At the first load everything works fine.
At the second reload all the docs show the same

First load in sequence
![image](https://github.com/user-attachments/assets/a79f9eda-07a7-4c62-a0f7-64f0b4660ca5)
![image](https://github.com/user-attachments/assets/0be91190-ac51-4faa-8ecb-396a950ea580)

If I relaod the first app
![image](https://github.com/user-attachments/assets/9b19d281-5bfe-44a5-be5e-19d48fc67d0d)

Yaml configuration

api_platform.yaml
```yaml
api_platform:
    title: FixHub api
    version: 1.0.1
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    formats:
        jsonapi:  ['application/vnd.api+json']
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
    docs_formats:
        jsonapi:  ['application/vnd.api+json']
        jsonld: [ 'application/ld+json' ]
        html: [ 'text/html' ]
    error_formats:
        jsonproblem: [ 'application/problem+json' ]
        jsonapi: [ 'application/vnd.api+json' ]
        jsonld: [ 'application/ld+json' ]      # Hydra error formats
    #resource_class_directories:
    #    - '%kernel.project_dir%/shared/Entity'
    # Good defaults for REST APIs
    ...
```

First app
```yaml
api_platform:
    title: FixHub Security Api
    resource_class_directories:
    #    - '%kernel.project_dir%/apps/security/src/Modules/Auth/Entity/'
    defaults:
        namespaces:
            entity: "Security\\Modules\\**\\Entity"
            enum: "Security\\Modules\\**\\Enum"
```

second app
```yaml
api_platform:
    title: FixHub Organization Api
    resource_class_directories:
        - '%kernel.project_dir%/apps/organization/src/Modules/Company/Entity/'
        - '%kernel.project_dir%/apps/organization/src/Modules/User/Entity/'
    defaults:
        namespaces:
            entity: "Organization\\Modules\\**\\Entity"
            enum: "Organization\\Modules\\**\\Enum"
```

**How to reproduce**  

**Possible Solution**  
I don't know how to solve, I have checked the cache and it is different for the 2 apps, they load the right Entity.

**Comment by galliroberto** [comment]
I investigate more and I found the problem is caused by the cache_key

![image](https://github.com/user-attachments/assets/81972624-1ed9-4688-ac1c-846585dc851b)

I have added host to try.
So, for me the solution is to override the service:

```yaml
    api_platform.metadata.resource.name_collection_factory.cached:
        class: Shared\ApiPlatform\Metadata\Resource\Factory\CachedResourceNameCollectionFactory
        arguments:
            - '@api_platform.cache.metadata.resource'
            - '@api_platform.metadata.resource.name_collection_factory.cached.inner'
```
