### ISSUE TITLE
jsonhal: ApiPlatform\Hal\Serializer\EntrypointNormalizer" does not exist

### ISSUE THREAD

**Issue by madflow** [api-platform/api-platform#2810]
**API Platform version(s) affected**: 

        "api-platform/doctrine-orm": "^4.0.3",
        "api-platform/symfony": "^4.0.8",

**Description**  

* https://api-platform.com/docs/core/content-negotiation/
* I configured "jsonhal" like described in the docs.

```
# api/config/packages/api_platform.yaml
api_platform:
  formats:
    jsonld: ['application/ld+json']
    jsonhal: ['application/hal+json']
```

And I get:

```
Invalid service "api_platform.hal.normalizer.entrypoint": class "ApiPlatform\Hal\Serializer\EntrypointNormalizer" does not exist.
```

**How to reproduce**  

* I cloned this repository
* Executed `./update-deps.sh`
* Ran `docker compose up -d`
* Checked if the `https://localhost/docs` works.
* Added `jsonhal`.

**Possible Solution**  

**Additional Context**
