### ISSUE TITLE
The service "App\EventListener\DeserializeListener" has a dependency on a non-existent service "ApiPlatform\Symfony\EventListener\DeserializeListener".

### ISSUE THREAD

**Issue by Gigoshkin** [api-platform/api-platform#2811]
**API Platform version(s) affected**: ^4.0

**Description**  
Using `use ApiPlatform\Symfony\EventListener\DeserializeListener as DecoratedListener;` in a decorator causes `The service "App\EventListener\DeserializeListener" has a dependency on a non-existent service
"ApiPlatform\Symfony\EventListener\DeserializeListener"` error.  

Not using the class and replacing `decorates: DecoratedListener::class `with `'api_platform.listener.request.deserialize'` resolves the issue
```php
// use ApiPlatform\Symfony\EventListener\DeserializeListener as DecoratedListener; - removed
#[AsDecorator(
    decorates: 'api_platform.listener.request.deserialize' # replaced
)]
final class DeserializeListener
// ...
public function __construct(
    private DenormalizerInterface             $denormalizer,
    private SerializerContextBuilderInterface $serializerContextBuilder,
    #[AutowireDecorated]
    private $decorated # type-hint removed
)
{
}
```

Also this works:
```php
<?php

namespace App\EventListener;

use ApiPlatform\State\SerializerContextBuilderInterface;
use ApiPlatform\Symfony\Util\RequestAttributesExtractor;
use Symfony\Component\DependencyInjection\Attribute\AsDecorator;
use Symfony\Component\DependencyInjection\Attribute\AutowireDecorated;
use Symfony\Component\EventDispatcher\Attribute\AsEventListener;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
// use ApiPlatform\Symfony\EventListener\DeserializeListener as DecoratedListener;

final class DeserializeListener
{

    public function __construct(
        private DenormalizerInterface             $denormalizer,
        private SerializerContextBuilderInterface $serializerContextBuilder,
        private $decorated # type-hint removed
    )
    {
    }

    public function onKernelRequest(RequestEvent $event): void
    {
        $request = $event->getRequest();
        if ($request->isMethodCacheable() || $request->isMethod(Request::METHOD_DELETE)) {
            return;
        }

        if ('form === $request->getContentTypeFormat()) {
            $this->denormalizeFormRequest($request);
        } else {
            $this->decorated->onKernelRequest($event);
        }
    }

    private function denormalizeFormRequest(Request $request): void
    {
        if (!$attributes = RequestAttributesExtractor::extractAttributes($request)) {
            return;
        }

        $context = $this->serializerContextBuilder->createFromRequest($request, false, $attributes);
        $populated = $request->attributes->get('data');
        if (null !== $populated) {
            $context['object_to_populate'] = $populated;
        }

        $data = $request->request->all();
        $object = $this->denormalizer->denormalize($data, $attributes['resource_class'], null, $context);
        $request->attributes->set('data', $object);
    }
}

```

```yaml
#services.yaml
    'App\EventListener\DeserializeListener':
        tags:
            - {
                name: 'kernel.event_listener',
                event: 'kernel.request',
                method: 'onKernelRequest',
                priority: 2,
            }
        # Autoconfiguration must be disabled to set a custom priority
        autoconfigure: false
        decorates: 'api_platform.listener.request.deserialize'
        arguments:
            $decorated: '@App\EventListener\DeserializeListener.inner'
```

**How to reproduce**  
Follow this example https://api-platform.com/docs/core/form-data/

```php
<?php

namespace App\EventListener;

use ApiPlatform\State\SerializerContextBuilderInterface;
use ApiPlatform\Symfony\Util\RequestAttributesExtractor;
use Symfony\Component\DependencyInjection\Attribute\AsDecorator;
use Symfony\Component\DependencyInjection\Attribute\AutowireDecorated;
use Symfony\Component\EventDispatcher\Attribute\AsEventListener;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use ApiPlatform\Symfony\EventListener\DeserializeListener as DecoratedListener;

#[AsDecorator(
    decorates: DecoratedListener::class
)]
final class DeserializeListener
{

    public function __construct(
        private DenormalizerInterface             $denormalizer,
        private SerializerContextBuilderInterface $serializerContextBuilder,
        #[AutowireDecorated]
        private DecoratedListener $decorated
    )
    {
    }

    #[AsEventListener(event: KernelEvents::REQUEST, priority: 2)]
    public function onKernelRequest(RequestEvent $event): void
    {
        $request = $event->getRequest();
        if ($request->isMethodCacheable() || $request->isMethod(Request::METHOD_DELETE)) {
            return;
        }

        if ('form' === $request->getContentTypeFormat()) {
            $this->denormalizeFormRequest($request);
        } else {
            $this->decorated->onKernelRequest($event);
        }
    }

    private function denormalizeFormRequest(Request $request): void
    {
        if (!$attributes = RequestAttributesExtractor::extractAttributes($request)) {
            return;
        }

        $context = $this->serializerContextBuilder->createFromRequest($request, false, $attributes);
        $populated = $request->attributes->get('data');
        if (null !== $populated) {
            $context['object_to_populate'] = $populated;
        }

        $data = $request->request->all();
        $object = $this->denormalizer->denormalize($data, $attributes['resource_class'], null, $context);
        $request->attributes->set('data', $object);
    }
}

```

**Possible Solution**

**Additional Context**  
```yaml
api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    name_converter: 'Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter'
    use_symfony_listeners: true
```
