### ISSUE TITLE
Service in action not autowired

### ISSUE THREAD

**Issue by amarCosmospace** [api-platform/api-platform#283]
Hello,

I got an issue with an action using a service in __construct
```
  "@context": "/app_dev.php/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Type error: Argument 1 passed to AppBundle\\Action\\MailSpecial::__construct() must be an instance of AppBundle\\Services\\SWServices, none given, called in /var/www/projet/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php on line 202",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/var/www/projet/src/AppBundle/Action/MailSpecial.php",
      "line": 17,
      "args": []
    },
```

Here is my action : 

```
<?php

// src/AppBundle/Action/MailSpecial.php

namespace AppBundle\Action;

use AppBundle\Entity\Mail;
use AppBundle\Services\SWServices;
use Doctrine\Common\Persistence\ManagerRegistry;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\Routing\Annotation\Route;

class MailSpecial
{
    private $sWServices;

    public function __construct(SWServices $sWServices)
    {
        $this->sWServices = $sWServices;
    }

    /**
     * @Route(
     *     name="mail_special",
     *     path="/mails/special",
     *     defaults={"_api_resource_class"=Mail::class, "_api_collection_operation_name"="special"}
     * )
     * @Method("GET")
     */
    public function __invoke($data) // API Platform retrieves the PHP entity using the data provider then (for POST and
        // PUT method) deserializes user data in it. Then passes it to the action. Here $data
        // is an instance of Book having the given ID. By convention, the action's parameter
        // must be called $data.
    {
        $em = $this->sWServices->getEm();
        $mail = $em->find('AppBundle:Mail',7);

        return $mail; // API Platform will automatically validate, persist (if you use Doctrine) and serialize an entity
        // for you. If you prefer to do it yourself, return an instance of Symfony\Component\HttpFoundation\Response
    }
}
```

My service declaration : 
```
    SWServices:
        class: AppBundle\Services\SWServices
        arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
```

My service : 
```
<?php
namespace AppBundle\Services;

use Doctrine\ORM\EntityManager;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Config\Definition\Exception\Exception;
use Symfony\Component\DependencyInjection\Container;

class SWServices{
    protected $em;
    private $container;

    public function __construct(EntityManager $entityManager, Container $container)
    {
        $this->em = $entityManager;
        $this->container = $container;
    }

    /**
     * Some method
     * @param string $somevar
     * @return mixed
     */
    public function someMethod($somevar) {
        return $somevar;
    }
}
```

Is there something that i've missed ? The service in action constructor should been autowired.

Thanks in advance

**Comment by soyuka** [comment]
I'm using `yaml` to declare routes:

```yaml
product_stocks_item:
    path: /api/products/stocks/{product}
    defaults: { _controller: product_products.action.stocks }
```

Controller service:
```yaml
    product_products.action.stocks:
        class: Product\ProductBundle\Action\StocksAction
        autowire: true
```

Maybe you need to declare the `Action` as a service to specify the `autowire` configuration?

**Comment by amarCosmospace** [comment]
Thanks for your answer. I've tried it and it's a no no i got the same issue
```
    SWServices:
        class: AppBundle\Services\SWServices
        arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
        autowire: true
    MailSpecial:
        class: AppBundle\Action\MailSpecial
        autowire: true
```

**Comment by Simperfit** [comment]
Do you have the same error (none given) ?

**Comment by amarCosmospace** [comment]
Yes i got exactly the same error.

**Comment by soyuka** [comment]
```
SWServices:
    class: AppBundle\Services\SWServices
    arguments: [ "@doctrine.orm.entity_manager" , "@service_container" ]
MailSpecial:
    class: AppBundle\Action\MailSpecial
    autowire: true
```

Should work, it does to me at least :|.

**Comment by amarCosmospace** [comment]
@soyuka i've tried both and i got the same result... it's akward

**Comment by devrck** [comment]
@amarCosmospace  if its still relevant:

```yaml
AppBundle\Action\MailSpecial:
    class: AppBundle\Action\MailSpecial
    autowire: true
```

The trick is to define the service the same way as [API Platform](https://api-platform.com/docs/core/operations#creating-custom-operations-and-controllers) does. Look at the link and read where it says:

> Here we consider that DunglasActionBundle is installed (the default when using the API Platform distribution). This action will be automatically registered as a service (the service name is the same as the class name: AppBundle\Action\BookSpecial).
