### ISSUE TITLE
Endpoint /api/docs.yamlopenapi returns JSON instead of YAML

### ISSUE THREAD

**Issue by Miras4207** [api-platform/api-platform#2886]
**API Platform version(s) affected**: 4.1.9

**Description**  

When requesting API documentation in YAML format at `/api/docs.yamlopenapi`, the response contains JSON format instead of YAML format, which I think is wrong.

**How to reproduce**  

1. Use default `api_platform` configuration, or use the following:
```yaml
api_platform:
    docs_formats:
        html:
            mime_types:
                - text/html
        jsonopenapi:
            mime_types:
                - application/vnd.openapi+json
        yamlopenapi:
            mime_types:
                - application/vnd.openapi+yaml
```

2. Request `/api/docs.yamlopenapi`
3. See the response contains JSON instead of YAML

**Additional Context**  

Executing `api:openapi:export --yaml` works well.

I am using these compose packages:

```
api-platform/doctrine-common                   4.1.9              Common files used by api-platform/doctrine-orm and api-platform/doctrine-odm
api-platform/doctrine-orm                      4.1.9              Doctrine ORM bridge
api-platform/documentation                     4.1.9              API Platform documentation controller.
api-platform/http-cache                        4.1.9              API Platform HttpCache component
api-platform/hydra                             4.1.9              API Hydra support
api-platform/json-schema                       4.1.9              Generate a JSON Schema from a PHP class
api-platform/jsonld                            4.1.9              API JSON-LD support
api-platform/metadata                          4.1.9              API Resource-oriented metadata attributes and factories
api-platform/openapi                           4.1.9              Models to build and serialize an OpenAPI specification.
api-platform/serializer                        4.1.9              API Platform core Serializer
api-platform/state                             4.1.9              API Platform State component
api-platform/symfony                           4.1.9              Symfony API Platform integration
api-platform/validator                         4.1.9              API Platform validator component
symfony/yaml                                   7.2.5              Loads and dumps YAML files
```
