### ISSUE TITLE
Filter not working with embedded properties (multiple levels)

### ISSUE THREAD

**Issue by blaues0cke** [api-platform/api-platform#297]
I dont know if this relates to https://github.com/api-platform/api-platform/issues/277 but I have a issue with filtering by embedded properties. For example, I have to following entity structure:

* `User` has `Profile`
* `Profile` has `Address`
* `Address` has `postalCode` (`string`)

So when I call

`/api/users?profile.address.postalCode=88`

with the filter configuration

```
filter.search_user:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { profile.firstName: 'partial', profile.lastName: 'partial', profile.address.postalCode: 'starts' } ]
        tags:      [ { name: 'api_platform.filter', id: 'filter.search_user' } ]
```

I would expect a response that only contains users with a postal code starting with `88`. But all users are returned since the filter is not applied at all.

The same issue occurs when I call

`/api/users?profile.firstName=Thomas`

what should return only users with `Thomas` in their `firstName` but all users are returned. I digged a lot in the issues and found https://github.com/api-platform/core/pull/242 and https://github.com/api-platform/core/issues/83.

So is this already a feature and/or am I facing a bug?

**EDIT**: Thought that only occurs with embedded entities deeper that one level. But it seems its not possible to filter by embedded entity properties at all.

**Comment by soyuka** [comment]
Do the filters show up in the hydra metadata? We've a test on this and AFAIR it's working to me.

**Comment by blaues0cke** [comment]
@soyuka You are right, all embedded filter do **not** appear in the metadata. Its seems that all embedded relations are skipped. I tested this with another entity in my project that is called `Scan`. This property has also an embedded `Address` but also a property called `title`. The following filter definition seems to work, expect that the embedded property is skipped at all.

```
filter.search_scan:
    parent:    'api_platform.doctrine.orm.search_filter'
    arguments: [ { store.title: 'partial', status: 'exact', store.address.postalCode: 'starts' } ]
    tags:      [ { name: 'api_platform.filter', id: 'filter.search_scan' } ]
```

The response lists `store.title` in `hydra:search`, but not `store.address.postalCode`:

```
"hydra:search": {
    "@type": "hydra:IriTemplate",
    "hydra:template": "/app_dev.php/api/scans{?creationDate[before],creationDate[after],order[creationDate],store.title,status,status[],geoOnly}",
    "hydra:variableRepresentation": "BasicRepresentation",
    "hydra:mapping": [
      {
        "@type": "IriTemplateMapping",
        "variable": "creationDate[before]",
        "property": "creationDate",
        "required": false
      },
      {
        "@type": "IriTemplateMapping",
        "variable": "creationDate[after]",
        "property": "creationDate",
        "required": false
      },
      {
        "@type": "IriTemplateMapping",
        "variable": "order[creationDate]",
        "property": "creationDate",
        "required": false
      },
      {
        "@type": "IriTemplateMapping",
        "variable": "store.title",
        "property": "store.title",
        "required": false
      },
      {
        "@type": "IriTemplateMapping",
        "variable": "status",
        "property": "status",
        "required": false
      },
      {
        "@type": "IriTemplateMapping",
        "variable": "status[]",
        "property": "status",
        "required": false
      },
      {
        "@type": "IriTemplateMapping",
        "variable": "geoOnly",
        "property": "geoOnly",
        "required": false
      }
    ]
  }
```

**Comment by Simperfit** [comment]
This is not working `/api/users?profile.address.postalCode=88` because this is 2 level.
`/api/users?profile.firstName=Thomas` this should be working, could you please show us the hydra return ?

**Comment by soyuka** [comment]
@Simperfit should work with as many levels as we need:

![filters](https://cloud.githubusercontent.com/assets/1321971/25852518/ec5e9b8c-34c9-11e7-8e95-180f5391c74d.png)

Extract of filters services:

```yaml
    product_referencing.filter.date:
        parent: 'api_platform.doctrine.orm.date_filter'
        arguments: [ { 'fromDate': 'include_null_after', 'thruDate': 'include_null_after' } ]
        tags: [ {name: 'api_platform.filter', id: 'product_referencing.filter.date' }]

    product_referencing.filter.enabled:
        parent: 'api_platform.doctrine.orm.boolean_filter'
        arguments: [ { 'enabled': ~, 'product.productToPackaging.isDefault': ~, 'product.productInternalOrganization.referencingStatus.isBlocking': ~} ]
        tags: [ {name: 'api_platform.filter', id: 'product_referencing.filter.enabled' }]

    product_referencing.filter.product:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { 'product': 'exact', 'product.category.id': 'exact', 'product.priceDefinitionFamily.id': 'exact', 'product.code': 'exact', 'product.productInternalOrganization.internalOrganization': 'exact' } ]
        tags: [ {name: 'api_platform.filter', id: 'product_referencing.filter.product' }]
```
