### ISSUE TITLE
Call custom __construct on POST

### ISSUE THREAD

**Issue by regniblod** [api-platform/api-platform#300]
I have a simple resource mapped and I can perform the default CRUD operations on it, but I want to create my entity calling a custom constructor like `public function __construct(Email $email)`.

Is this even possible with a custom action / event / option in serializer?

**Comment by Simperfit** [comment]
Do you want to create the entity based on a email entity or do you want to create the email entity ?

**Comment by regniblod** [comment]
The `Email` class is just a simple Value Object that I create and pass to the User `__construct`, but it could be a `string`, `int` o whatever.

**Comment by soyuka** [comment]
Entities can't have custom constructor arguments AFAIR. Still, you should be able to use listeners/subscribers to add whatever you need to your entity.

**Comment by regniblod** [comment]
I'm using a DDD/Hexagonal architecture approach and I would like to decouple my Domain from the Framework, so not having a `__construct` and just call all the `setters` that I need to initialise my entity doesn't fit in my project.

Is it technicaly possible to add this option to the framework in a PR? Maybe someone can take over and code it if enough people find it useful.

**Comment by soyuka** [comment]
I think that this isn't fixable as is. Still, you can do your own controller/event listener to enable such behavior (ie instantiate a new ResourceClass with your own agruments).

**Comment by regniblod** [comment]
@soyuka Could you please provide an example? I tried both the event and the action for `POST /<resource>` without success.

Extra points for opening a PR to the official docs 😛

**Comment by soyuka** [comment]
Sure I'll try something asap.

**Comment by regniblod** [comment]
I tried to create a custom action to try to do what I need and I still can't do it. This is my code:
```php
<?php

namespace Inkuinen\User\Application\UserBundle\Action;

use Inkuinen\User\Domain\Model\User;
use Inkuinen\User\Domain\Value\Email;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

class DebugAction
{
    /**
     * @Method("POST")
     * @Route(
     *     name="users_new",
     *     path="/users_new/{id}",
     *     defaults={"_api_resource_class"=Inkuinen\User\Domain\Model\User::class, "_api_item_operation_name"="users_new"}
     * )
     */
    public function __invoke($data)
    {
        return new User(new Email('test@test.com'));
    }
}
```
```yaml
resources:
    Inkuinen\User\Domain\Model\User:
        class: Inkuinen\User\Domain\Model\User
        collectionOperations:
            getUsers:
                method: GET
            postUser:
                method: POST
            special:
                route_name: 'users_new'
        itemOperations:
            getUser:
                method: GET
            editUser:
                method: PUT
            deleteUser:
                method: DELETE
```
This is the response I get in the `hydra:description`: `Invalid identifier \"\", \"id\" has not been found.`

If I change the route to `/users_new/{id}` this is the response: `Not Found`

Am I missing something?
