### ISSUE TITLE
api-platform + docker + postgresql 

### ISSUE THREAD

**Issue by sbacem** [api-platform/api-platform#303]
There is a config to use api-platform + docker + postgresql  ?

**Comment by sbacem** [comment]
I tried to replace `pdo_mysql` by `pdo_pgsql` but i have 
warning : can't find pdo_pgsql
when `docker-compose up -d`
 any idea for this ?

**Comment by amenophis** [comment]
@sbacem You need to install the php driver for postgresql in the docker image.
Only mysql driver is installed by default

**Comment by Simperfit** [comment]
@sbacem 

This my configuration for postgresql : 

```

RUN apk add --no-cache --virtual .persistent-deps \
		git \
		icu-libs \
		zlib \
		postgresql-client

ENV APCU_VERSION 5.1.8

RUN set -xe \
	&& apk add --no-cache --virtual .build-deps \
		$PHPIZE_DEPS \
		icu-dev \
		zlib-dev \
        postgresql-dev \
        sqlite-dev \
        pcre-dev \
	&& docker-php-ext-install \
        intl \
        mbstring \
        pdo_mysql \
        pdo_pgsql \
        pdo \
        pgsql \
        zip \
        pdo_sqlite \
	&& pecl install \
		apcu-${APCU_VERSION} \
	&& docker-php-ext-enable --ini-name 20-apcu.ini apcu \
	&& docker-php-ext-enable --ini-name 05-opcache.ini opcache \
	&& apk del .build-deps
# .... docker-php, compose etc.
```

This is the docker-compose.yml part for postgres

```
  postgres:
        image: postgres
        volumes:
            - /var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: db
            POSTGRES_PASSWORD: password
            POSTGRES_USER: user
```
