### ISSUE TITLE
Make ApiPlatform\Core\Hydra\Serializer\ErrorNormalizer not final

### ISSUE THREAD

**Issue by blaues0cke** [api-platform/api-platform#322]
I wanted to overwrite `ApiPlatform\Core\Hydra\Serializer\ErrorNormalizer` to make `normalize()` to keep the `hydra:description` even in production mode. The code here is nice, so theoretically I only have to extend `ApiPlatform\Core\Hydra\Serializer\ErrorNormalizer` and overwrite `getErrorMessage()` that is provided by `ApiPlatform\Core\Problem\Serializer\ErrorNormalizerTrait`. But unfortunately `ApiPlatform\Core\Hydra\Serializer\ErrorNormalizer` is `final` so I have to copy the whole service to achieve my goal.

```
api_platform.hydra.normalizer.error:
    public: false
    class: AppBundle\Serializer\ErrorNormalizer
    arguments: [ '@api_platform.router', '%kernel.debug%']
    tags: [ { name: serializer.normalizer, priority: 32 } ]
```

So, is there a better way to achieve my goal or should the `final` keyword get removed to make my boilerplate code obsolete again?
