### ISSUE TITLE
Weird "Filter for All Properties" behavior

### ISSUE THREAD

**Issue by alex-pex** [api-platform/api-platform#332]
Hello,

I read the doc about [search filters](https://api-platform.com/docs/core/filters#search-filter) and [filter for all properties](https://api-platform.com/docs/core/filters#enabling-a-filter-for-all-properties-of-a-resource) and the behavior is strange : if I enable the filter on all properties, I'm not limited to fields exposed by the normalization. I can filter on internal properties.

Eg:
```
filter.person_search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ ~ ]
        tags:
            - { name: 'api_platform.filter', id: 'filter.person_search' }
```

```php
/**
 * @ApiResource(attributes={
 *     "normalization_context"={
 *         "groups"={"person_norm"}
 *     },
 *     "denormalization_context"={
 *         "groups"={"person_denorm"}
 *     },
 *     "filters"={
 *         "filter.person_search"
 *     }
 * })
 */
class Person
{
    /**
     * @Groups({"person_norm"})
     */
    private $firstName;

    /**
     * @Groups({"person_norm"})
     */
    private $lastName;

    private $email;
}
```

I can do ```GET /people?email=me@domain.org``` and retrieve firstName and lastName.

I'd like the default behavior to be restricted to normalized fields.
