### ISSUE TITLE
Name converter not working on 2.1

### ISSUE THREAD

**Issue by akadlec** [api-platform/api-platform#345]
When i set up a name converter to convert camel to snake, it is not working, only on doc.

```
services:
    app.name_converter:
        class: Symfony\Component\Serializer\NameConverter\CamelCaseToSnakeCaseNameConverter
        public: false
```

```
api_platform:
    name_converter: 'app.name_converter'
```

In the ui in example section is name correctly converted, but in the real response not.

EXAMPLE:
```
[
  {
    "id": "string",
    "name": "string",
    "last_activity": "2017-06-24T18:47:12.689Z",
    "data_sources": [
      "string"
    ]
  }
]
```

REAL RESPONSE:
```
{
    "@context": "/app_dev.php/contexts/Item",
    "@id": "/app_dev.php/v1/module/items",
    "@type": "hydra:Collection",
    "hydra:member": [
        {
            "id": "05efbfbd-0e48-efbf-bd44-4befbfbdefbf",
            "name": "Some name",
            "lastActivity": null,
            "dataSources": []
        }
        }
    ],
    "hydra:totalItems": 1
}
```
