### ISSUE TITLE
Relation table indexes set to "UNIQUE" using schema generator

### ISSUE THREAD

**Issue by banandam** [api-platform/api-platform#361]
### Actual Result
In relationships table fields user_id and other_user_id are set as indexes type "UNIQUE".

### Expected Result
In relationships table fields user_id and other_user_id are should set as indexes type "INDEX".

### Sample Schema & Entity

In below example attached users and user_friends table structure.

#### /api-platform/app/config/schema.yml

```
    Users:                       
        parent: false
        properties:
            createdAt: { range: "DateTime" }
            updatedAt: { range: "DateTime" } 
            role: { range: "Roles", ormColumn: 'type="bigint"' }
            username: { range: "Text", ormColumn: 'type="string", length=255' }
            email: { range: "Text", ormColumn: 'type="string", length=255' }
            password: { range: "Text", ormColumn: 'type="string", length=255' }
            firstName: { range: "Text", ormColumn: 'type="string", length=255, nullable=true' }
            lastName: { range: "Text", ormColumn: 'type="string", length=255, nullable=true' }

    UserFriends:   
        parent: false
        properties:
            createdAt: { range: "DateTime" }
            updatedAt: { range: "DateTime" } 
            User: { range: "Users", ormColumn: 'type="bigint"' }
            otherUser: { range: "Users", ormColumn: 'type="bigint"' }
```

#### Entity generate using command:

```
php vendor/bin/schema generate-types src/ app/config/schema.yml
```

#### /api-platform/src/AppBundle/Entity/Users.php

```
<?php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * The most generic type of item.
 *
 * @see http://schema.org/Thing Documentation on Schema.org
 *
 * @ORM\Entity
 * @ApiResource(iri="http://schema.org/Thing")
 */
class Users
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    ....
    ....
    ....
}
```  

#### /api-platform/src/AppBundle/Entity/UserFriends.php

```
<?php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * The most generic type of item.
 *
 * @see http://schema.org/Thing Documentation on Schema.org
 *
 * @ORM\Entity
 * @ApiResource(iri="http://schema.org/Thing")
 */
class UserFriends
{
    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     * @Assert\DateTime
     * @Assert\NotNull
     */
    private $createdAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     * @Assert\DateTime
     * @Assert\NotNull
     */
    private $updatedAt;

    /**
     * @var Users
     *
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\Users")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotNull
     */
    private $User;

    /**
     * @var Users
     *
     * @ORM\OneToOne(targetEntity="AppBundle\Entity\Users")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotNull
     */
    private $otherUser;
    ....
    ....
    ....
}
```

#### Update Table using command

```
php bin/console doctrine:schema:update --force
```

#### Create Table Structure 

![table_users](https://user-images.githubusercontent.com/3142065/28421967-53181784-6d84-11e7-99b6-b3fe5ebcadd8.jpg)
![table_ user_friends](https://user-images.githubusercontent.com/3142065/28421981-59cae2e6-6d84-11e7-9288-ef9866fd8a7a.jpg)
