### ISSUE TITLE
POST and inherited relation

### ISSUE THREAD

**Issue by Sybio** [api-platform/api-platform#372]
I would like to POST a new resource **Pick** which has a relation **OneToMany to Subpick** ($subpicks).

Previously I saw that it was possible to POST a resource with a new relation : https://github.com/api-platform/api-platform/issues/371 : 
```yaml
# POST /picks
{
    "bookmaker": "/bookmakers/6ee03de1-711a-11e7-9be1-848f69ce56ef",
    "analysis": "This is my text.",
    "stake": 35.5,
    "confidence": 6,
    "type": "single",
    "subpicks": [
    	{
    	        "bet": "My custom bet!",
    	        "odd": 1.5,
    		"dateKickOff": "2017-07-30T20:00:00+00:00",
    		"category": "/categories/6ee84bf5-711a-11e7-9be1-848f69ce56ef"
        }
    ]
}
```
_(Creation of a Pick and an attached Subpick.)_

**My new problem is that I'm not able to choose which type of inherited relation I want to create with.**

Currently I got this error : 
```yaml
{
    "@context": "/app_dev.php/contexts/Error",
    "@type": "hydra:Error",
    "hydra:title": "An error occurred",
    "hydra:description": "Cannot instantiate abstract class AppBundle\\Entity\\Subpick",
    "trace": [
        {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "",
            "file": "D:\\wamp64\\www\\bet-api\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Serializer\\Normalizer\\AbstractNormalizer.php",
            "line": 367,
            "args": []
        },
}
```
Subpick is an abstract class that has **2 inherited entities** : **SubpickTypeFree** and **SubpickTypeEvent** : 

Pick : 
```php
class Pick
{
    // ...

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Subpick", mappedBy="pick", cascade={"persist", "remove"})
     * @ORM\OrderBy({"position"="ASC"})
     * @Groups({
     *     "pick_post_normalization",
     *     "pick_post_denormalization"
     * })
     */
    private $subpicks;
}
```

Subpick (abstract) : 
```php
/**
 * Subpick
 *
 * @ApiResource(...)
 * @ORM\Table(name="subpick")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\SubpickRepository")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="item_type", type="string")
 * @ORM\DiscriminatorMap({
 *     "event"="SubpickTypeEvent",
 *     "free"="SubpickTypeFree"
 * })
 */
abstract class Subpick
{
    // ...

    /**
     * @var Pick
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Pick", inversedBy="subpicks")
     * @ORM\JoinColumn(name="pick_id", referencedColumnName="id")
     * ...
     */
    private $pick;
}
```

SubpickTypeEvent (Subpick inheritance) : 
```php
/**
 * SubpickTypeEvent
 *
 * @ApiResource(...)
 * @ORM\Entity(repositoryClass="AppBundle\Repository\SubpickTypeEventRepository")
 */
class SubpickTypeEvent extends Subpick
{
    // ...
}
```

SubpickTypeFree (Subpick inheritance) : 
```php
/**
 * SubpickTypeFree
 *
 * @ApiResource(...)
 * @ORM\Entity(repositoryClass="AppBundle\Repository\SubpickTypeFreeRepository")
 */
class SubpickTypeFree extends Subpick
{
    // ...
}
```

I tried to choose which child I wanted to create by specifying the parameter "@type", without success : 

```yaml
# POST /picks
{
    "bookmaker": "/bookmakers/6ee03de1-711a-11e7-9be1-848f69ce56ef",
    # ...
    "subpicks": [
    	{
                "@type": "SubpickTypeFree"
                # ..
        }
    ]
}
```

So is it possible to choose which type of Subpick I want to create with my Pick ? And How ? Thanks for your help.
