### ISSUE TITLE
Operation that returns another type that the resource specified in the routing

### ISSUE THREAD

**Issue by Nek-** [api-platform/api-platform#390]
Hello,

I have a case where I want to return a collection of sub items. I have a ProductType entity and Toy entity. The ProductType have toys. I want to get all toys for a product under the following URI: `/products/1/toys`

I did the following configuration for the product:
```php
<?php

/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ProductTypeRepository")
 * @ApiResource(
 *     itemOperations={
 *         "toys"={"route_name"="products_type_get_toys"}
 *     }
 * )
 */
class ProductType
{
    // ...
}
```

Here is my routing:
```yaml
products_type_get_toys:
    methods: GET
    path: /products/{id}/toys
    defaults:
        _controller: 'app.controller.api.products:getToysAction'
        methods:  [GET]
        _api_resource_class: AppBundle\Entity\ProductType
        _api_item_operation_name: "toys"
    requirements:
        id: \d+
```

And finally my controller:
```php
<?php
class ProductsController extends Controller
{
    public function getToysAction(ProductType $data)
    {
        return $data->getToys();
    }
}
```

I get the following error because the collection have the wrong type and I don't see anything in the documentation to fix it.
```
No resource class found for object of type "AppBundle\Entity\Toy".
```
