### ISSUE TITLE
How I enable doctrine result_cache_driver and set time out?

### ISSUE THREAD

**Issue by lvillarino** [api-platform/api-platform#392]
Hi:

I want to know how I enabled doctrine result_cache_driver and set cache expiration on api-platform.

The documentation only reference the metadata_cache_driver => https://api-platform.com/docs/core/performance

Thanks

**Comment by sh4ka** [comment]
Maybe this helps:
http://symfony.com/doc/current/reference/configuration/doctrine.html

**Comment by devrck** [comment]
Hi,

Result_cache_driver is enabled like so:

```yaml
entity_managers:
     default:
           query_cache_driver: apc
           metadata_cache_driver: apc
           result_cache_driver: apc
```

Or if you want to implement your own cache service:

```yaml
entity_managers:
     default:
           query_cache_driver:
                  type: service
                  id: your.service.id
```

From I know resultCache is set on each query manually.
