### ISSUE TITLE
Hide the ui (Swagger documentation) in my root path

### ISSUE THREAD

**Issue by clementvp** [api-platform/api-platform#394]
Hi everyone.
I actually learn Api Platform, and I wonder how to hide or disable the swagger UI
 (For visibility and security reasons) in my root api path like:

http://api.example.com

I don't want to see the swagger documentation with the possibility to try out all my endpoints.

**Comment by dunglas** [comment]
You can disable it through the config:

```yml
# app/config/config.yml

api_platform:
  enable_swagger_ui: false
```
