### ISSUE TITLE
[Question] How to define a custom enum property and show it in json-schema? 

### ISSUE THREAD

**Issue by razbakov** [api-platform/api-platform#399]
**Background:**
There is [a way to define enum fields in json-schema](https://spacetelescope.github.io/understanding-json-schema/reference/generic.html#enumerated-values) and there is a way [to define enums in api-platform](https://api-platform.com/docs/schema-generator/getting-started#enabling-api-platform-core-support).

**Questions:**
- is there a way to define new custom enumerable without usage of schema-generator?
- if no, then what is the way to define a new enum type, which extends schema.org/Enumeration and defines different option values?
- how to define a field in entity that it is of enum type?
- how to configure [hydra](https://demo.api-platform.com/docs.jsonld) and [swagger](https://demo.api-platform.com/docs.json) to correctly show the type of desired field as [enum with all possible values](https://spacetelescope.github.io/understanding-json-schema/reference/generic.html#enumerated-values)?

See in the following example field `status` (see `5.2.1 Object Example` in [Swagger RESTful API Documentation Specification](http://docs.swagger.io/spec.html))
```json
  "models": {
    "Order": {
      "id": "Order",
      "properties": {
        "status": {
          "type": "string",
          "description": "Order Status",
          "enum": [
            "placed",
            "approved",
            "delivered"
          ]
        }
      }
    }
  }
```

Related #194 #315

**Comment by mab05k** [comment]
I had the same issue with this today and I did a little digging. One way to do it is by overriding the Swagger documentation using the method described in the [override swagger documentation](https://api-platform.com/docs/core/swagger#override-swagger-documentation) which could get really tedious is you have lots of properties to update.

Make sure your array conforms to the [Swagger specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schemaObject)

However, I also looked into why it couldn't be configured via the annotations/yml. I noticed that when the swagger documentation is being generated, it doesn't take into account anything configured in the "attribute" property of the PropertyMetadata (perhaps I didn't look thoroughly enough?). 

My assumption would be that a configuration for these enums should look something like this?

```
resources:
  AppBundle\Entity\Order:
    itemOperations:
      get:
        method: 'GET'
      put:
        method: 'PUT'
      delete:
        method: 'DELETE'
    collectionOperations:
      get:
        method: 'GET'
      post:
        method: 'POST'
    properties:
      status:
        attributes:
          type: string
          enum: [ 'value1', 'value2' ]
          example: value1
```
or
```
    /**
     * @ApiProperty(
     *     attributes={
     *          "type"="string",
     *          "enum"={"value1", "value2"},
     *          "example"="value1"
     *     }
     * )
     */
     private $order;
```

Where "attributes" would define Swagger attributes for the property. I believe the right place to add something here is in the ```getPropertySchema()``` function in src/Swagger/Serializer/DocumentationSerializer.php - some kind of addition to the $valueSchema array.

@dunglas I'm unsure of your intent for that "attributes" property of the PropertyMetadata. I'm happy to contribute with some more direction.
