### ISSUE TITLE
Wrong data type in swagger.

### ISSUE THREAD

**Issue by Metalrex100** [api-platform/api-platform#403]
Hi,

I'am using ApiPlatform with Symfony Doctrine ODM (MongoDB).
My Model:

```

use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @MongoDB\Document(collection="message")
 */
class Message
{
    /**
     * @var integer
     *
     * @MongoDB\Id(strategy="UUID", type="string")
     * @Groups({"read"})
     */
    private $id;

    /**
     * @var string
     *
     * @MongoDB\Field(type="string")
     * @Assert\NotBlank()
     * @Assert\Type("string")
     * @Groups({"read", "write"})
     */
    private $encryptedMessage;

    /**
     * @var \DateTime
     *
     * @MongoDB\Field(type="date")
     * @MongoDB\Index(name="expires", expireAfterSeconds="0")
     */
    private $expires;

    /**
     * @var integer
     *
     * @Assert\NotBlank()
     * @Assert\Type("int")
     * @Groups({"write"})
     */
    private $minutesLimit;

    /**
     * @var integer
     *
     * @MongoDB\Field(type="int")
     * @Assert\Type("int")
     * @Groups({"write"})
     */
    private $queriesLimit;
```

My `resources.yml` file:

```
resources:
    AppBundle\Document\Message:
        itemOperations:
            get:
                method: 'GET'
        collectionOperations:
            post:
                method: 'POST'
        attributes:
            normalization_context:
                groups: ["read"]
            denormalization_context:
                groups: ["write"]
```

Problem: 
Swagger shows me wrong type of my model fields.
![screenshot from 2017-08-30 19-43-22](https://user-images.githubusercontent.com/22449118/29884325-cbba996c-8dbb-11e7-8ae2-ae34c9f06315.png)

What can i do to fix it?
