### ISSUE TITLE
Pagination not working on custom Action

### ISSUE THREAD

**Issue by Dakhtara** [api-platform/api-platform#408]
I have a problem for pagination on my custom action.

The config.yml is correct for the pagination:
``` yaml
api_platform:
    collection:
        pagination:
            client_enabled: true
            enabled_parameter_name: pagination
```
The action return a collection of my entity, it show the total hydra:items, but the number of item in the collection is all the collection i have returned.
Let's say it returns 58 items, the hydra:totalItems is 58 and the hydra:member contains the 58 items.

``` json
{
    "@context": "/app_dev.php/contexts/QuestionSet",
    "@id": "/app_dev.php/question_sets",
    "@type": "hydra:Collection",
    "hydra:member": [
//The 58 item
 ],
    "hydra:totalItems": 58
}
```

Is there anything to do to have the pagination working in a custom action ?
