### ISSUE TITLE
Is @ApiProperty annotation available in YML config?

### ISSUE THREAD

**Issue by benr77** [api-platform/api-platform#413]
Hi,

Is it possible to use YML configuration as an alternative to the `@ApiProperty annotation`?

Specifically I'm trying to use `@ApiProperty(identifier=true)` but everywhere I've tried to specify this does not seem to work.

Thanks

**Comment by benr77** [comment]
As sometimes happens I've immediately found the solution after posting the question. For future reference, this can simply be done as follows:

```
App\Model\MyORMLessEntity:
    properties:
        id:
            identifier: true
```
