### ISSUE TITLE
Can't decorate Swagger documentation

### ISSUE THREAD

**Issue by reminec** [api-platform/api-platform#414]
1) create a fresh project api-platform 2.1 with composer create-project 
2) Trying to decorate the Swagger documentation following the guide
3) Get error : 
```
[Symfony\Component\DependencyInjection\Exception\RuntimeException]             
app_1      |     The definition "serializer" has a reference to an abstract definition "abst    
app_1      |     ract.instanceof.AppBundle\Swagger\SwaggerDecorator". Abstract definitions c    
app_1      |     annot be the target of references. 
```

This MR in docs repository https://github.com/api-platform/docs/pull/267 don't solve the problem.

I setup a repository if you want reproduce the issue :  
https://github.com/reminec/api-platform-swagger-decorator-issue

**Comment by dunglas** [comment]
@reminec can you paste your service definition?

**Comment by reminec** [comment]
yep ! 
```yaml
# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Action\:
        resource: '../../src/AppBundle/Action'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
    
    'AppBundle\Swagger\SwaggerDecorator':
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: [ '@AppBundle\Swagger\SwaggerDecorator.inner' ]
        public: false
```

In my project I also tried to disabled autowiring and declare the service via the old way. 
Same error.

I had setup a repository to reproduce the bug with a fresh create-project with composer : 
https://github.com/reminec/api-platform-swagger-decorator-issue

**Comment by dunglas** [comment]
Thanks for the repo. I can reproduce the problem. There is an issue with the default DI we ship.

**Comment by dunglas** [comment]
The `autoconfigure` feature seems to introduce weird edge cases. Here is a quick fix:

1. Exclude the `Swagger` directory from autoregistration:

```yaml
# app/config/config.yml

    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Swagger}'
```

2. Move the definition of the decorator in a file not having `autoconfigure: true` (for instance `api_filters.yaml`:

```yaml
    'AppBundle\Swagger\SwaggerDecorator':
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: [ '@AppBundle\Swagger\SwaggerDecorator.inner' ]
```

I'll try to find the underlying cause.
