### ISSUE TITLE
Filter nested items

### ISSUE THREAD

**Issue by DariuszLuber** [api-platform/api-platform#424]
That problem was raised in [https://github.com/api-platform/core/issues/944](url) but from opposite side.
I have two entities
```
AppBundle\Entity\Foo:
  foo1:
    id: 1
    bars: ["@bar1", "@bar2"]
  
AppBundle\Entity\Bar:
  bar1:
    id: 1
    prop: "toto"
    foo: "@foo1"
  bar2:
    id: 2
    prop: "tata"
    foo: "@foo1"
```

Now let's make request http://localhost/foos?bar.prop=toto

It will return: 
```
{
  "@context": "/contexts/Foo",
  "@id": "/foos",
  "@type": "hydra:Collection",
  "hydra:member": [
    {
      "@id": "/foos/1",
      "@type": "Foo",
      "bars": [
        {
          "@id": "/bars/1",
          "@type": "Bar",
          "prop": "toto"
        },
        {
          "@id": "/bars/2",
          "@type": "Bar",
          "prop": "tata"
        }
      ]
    }
  ],
  "hydra:totalItems": 2,
  "...otherProps...": "...otherValues...."
}
```

What I want to get in response is:
```
{
  "@context": "/contexts/Foo",
  "@id": "/foos",
  "@type": "hydra:Collection",
  "hydra:member": [
    {
      "@id": "/foos/1",
      "@type": "Foo",
      "bars": [
        {
          "@id": "/bars/1",
          "@type": "Bar",
          "prop": "toto"
        }
      ]
    }
  ],
  "hydra:totalItems": 1,
  "...otherProps...": "...otherValues...."
}
```

How to set to configs to get only those which match filters?
