### ISSUE TITLE
Custom endpoint based on DQL?

### ISSUE THREAD

**Issue by DariuszLuber** [api-platform/api-platform#425]
Hi

How to create custom endpoint without creating new entities?

I have entities:

```
AppBundle\Entity\Assortment:
  assortment1:
    id: 1
   name: 'new assortment'
    products: ["@prod1", "@prod2"]
  
AppBundle\Entity\Product:
  prod1:
    id: 1
    name: "some prod1"
    assortment: "@assortment1"
  prod2:
    id: 2
    name: "some prod2"
    assortment: "@assortment1"
  prod3:
    id: 3
    name: "some prod3"
    assortment: "@assortment1"

AppBundle\Entity\Sale:
  sale1:
    id: 1
    date: "2017-01-01"
    quantitity: 10
    product: "@prod1"
  sale2:
    id: 2
    date: "2017-01-02"
    quantity: 5
    product: "@prod1"
  sale3:
    id: 4
    date: "2017-01-02"
    quantity: 5
    product: "@prod2"
 
 ...
```

Now I want to create estimation of sale but with structure:
```
Assortment : {
    id: 1
    name: 'new assortment'
    sumQuantity: 15
    sumQuantityEstimated: 15
    product:
        {
            id: 1
            name: "some prod1"
            sumQuantity: 15
            sumQuantityEstimated: 15
        },
        {
            id: 2
            name: "some prod2"
            sumQuantity: 5
            sumQuantityEstimated: 5
        }
}
```

For estimations I can create a DQL in Repository in Sale, but how create end point with that structure?
