### ISSUE TITLE
[ Question ] Custom user provider integration with LexikJWT

### ISSUE THREAD

**Issue by devrck** [api-platform/api-platform#426]
Hello,

I'm trying to make a custom user provider work with LexikJWT but can't figure out what is wrong. The documentation on this part is kind of lacking and I was wondering what am I doing wrong? Right now I get the response from the ```SecurityController::checkAction()``` which throws the `\RuntimeException`

```yaml
# app/config/security.yml

security:
    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_READER: ROLE_USER
        ROLE_ADMIN: ROLE_READER

    providers:
        custom_provider:
            id: custom.user.provider

    firewalls:
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: custom_provider
            json_login:
                check_path: /login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            pattern:   ^/
            provider:custom_provider
            stateless: true
            anonymous: true
            lexik_jwt: ~

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cities, roles: [ ROLE_READER ] }
        - { path: ^/languages, roles: [ ROLE_READER ] }

```

```php
class SecurityController extends Controller
{
    /**
     * @Route(
     *     name="user_login_check",
     *     path="/login_check",
     * )
     */
    public function checkAction()
    {
        throw new \RuntimeException('You must configure the check path to be handled by the firewall using form_login in your security firewall configuration.');
    }
}
```

```php
class CustomUserProvider implements UserProviderInterface
{
   
    /**
     * @inheritDoc
     */
    public function loadUserByUsername($username)
    {
        return new User(452527, 'devrck');
    }

    /**
     * @inheritDoc
     */
    public function refreshUser(UserInterface $user)
    {
        return new User(452527, 'devrck');
    }

    /**
     * @inheritDoc
     */
    public function supportsClass($class)
    {
        return User::class === $class;
    }
}

```
