### ISSUE TITLE
enable WebTestCase support

### ISSUE THREAD

**Issue by iCodr8** [api-platform/api-platform#432]
To run Unit-Tests that use the WebTestCase are not working because of this error:

```
GuzzleHttp\Exception\ConnectException: cURL error 6: Couldn't resolve host 'varnish' (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

To get the unit tests working the following configuration should be added by default to the `app/config/config_test.yml` file:

```
api_platform:
    http_cache:
        invalidation:
            enabled: false
```
