### ISSUE TITLE
YAML resource configuration and subresources

### ISSUE THREAD

**Issue by piotaixr** [api-platform/api-platform#440]
I am using YAML to configure resources.
I have a class names Log that have a self-referencing many-to many called links

```php
/**
 * Log
 *
 * @ORM\Table(name="log")
 * @ORM\Entity()
 */
class Log
{
[...] # Other attributes

    /**
     * @var Collection|Log[]
     *
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Log", inversedBy="inverseLinks")
     * @ORM\JoinTable(name="log_links")
     */
    private $links;

[...] # Getters/setters/constructor
}
```

Here is the yml config:

```yaml
resources:
    AppBundle\Entity\Log:
        itemOperations:
            # GET/PUT/DELETE configuration
        collectionOperations:
            # GET/POST configuration
            # Subresources
            api_logs_links_get_subresource:
                method: GET
                normalization_context:
                    groups: ['log_get']
```

If i don't explicitely put the `path` attribute on `api_logs_links_get_subresource` to `/logs/{id}/links`, the `debug:router` console command outputs:
```
api_logs_get_collection                                          GET      ANY      ANY   /logs                   
api_logs_post_collection                                         POST     ANY      ANY    /logs                   
api_logs_api_logs_links_get_subresource_collection               GET      ANY      ANY    /logs.{_format}
api_logs_get_item                                                GET      ANY      ANY    /logs/{id}              
api_logs_put_item                                                PUT      ANY      ANY   /logs/{id}              
api_logs_delete_item                                             DELETE   ANY      ANY   /logs/{id}     
```

When set to `/logs/{id}/links` and querying it, i get a list of all logs and not the list of logs linked to the log of the given id.

What am i missing here?
The only thing i don't have it the `@ApiSubresource` annotation. When addig it, nothing happens (i am not surprised as i'm using YAML and the `@ApiResource` annotation is not set on the class). What is the equivalent in the YAML configuration?

**Comment by soyuka** [comment]
https://github.com/api-platform/core/blob/671b4466a423e982e4f4c4aceed60eb81405f4b4/tests/Fixtures/FileConfigurations/resources.yml#L26

**Comment by piotaixr** [comment]
Thanks @soyuka !
It works (kind of).

Now, y have a new route:
```
api_logs_links_get_subresource                                   GET      ANY      ANY    /logs/{id}/links.{_format}
```

The problem here is that i have prefixed the logs resources URLs by `/application`:
```yaml
resources:
    AppBundle\Entity\Log:
        properties:
            links:
                subresource: { collection: true, resourceClass: AppBundle\Entity\Log }
        itemOperations:
            get:
                method: GET
                path: /application/logs/{id}
        collectionOperations:
            # Subresources
            api_logs_links_get_subresource:
                method: GET
                path: /application/logs/{id}/links
```
This configuration gives me two different routes:
```
api_logs_api_logs_links_get_subresource_collection   GET      ANY      ANY    /application/logs/{id}/links
api_logs_links_get_subresource                       GET      ANY      ANY    /logs/{id}/links.{_format} 
```

Am i using the wrong collection operation name for the subresource? How can i change the path (and then normalization groups) for the subresource operation?

**Comment by soyuka** [comment]
Why don't you prefix everything from the firewall instead of rewriting the paths manually?

But yes, to change the groups you've to use the correct operation name given above:  `api_logs_links_get_subresource`.

**Comment by piotaixr** [comment]
> Why don't you prefix everything from the firewall instead of rewriting the paths manually?

@soyuka You mean in `routing.yml` ?

The thing is that not all my resources are under /application so i don't want to prefix all the resources.
Is it possible to group resources in categories? I didn't see anything like it in the docs but maybe i missed it.


> But yes, to change the groups you've to use the correct operation name given above: `api_logs_links_get_subresource`.

Yes, that's what i did, right? But it does not edit the settings of the subresource operation but creates a new collection operation instead.

**Comment by soyuka** [comment]
> Is it possible to group resources in categories?

Not sure but it'd be a great feature. Maybe by selecting only relevant configuration when declaring the api in `routing.yml`:

```
api:
    resource: 'Specify a routing.yml configuration here'
    type: 'api_platform'
    prefix: /api
```

> Yes, that's what i did, right? But it does not edit the settings of the subresource operation but creates a new collection operation instead.

Looks like you declared: `api_logs_links_get_subresource` which resulted in `api_logs_api_logs_links_get_subresource_collection` maybe just use `links_get_subresource`?
