### ISSUE TITLE
How to change normalization context for action

### ISSUE THREAD

**Issue by DariuszLuber** [api-platform/api-platform#441]
Hi

I have a Foo Entity with normalization_context foo, but I create custom action which is connected to Foo Entity, but I want to change normalization_context to bar.
How can I do that?
I want it becouse i use Foo Entity in diferent contexts and want to serve only data which are needed for specific action.

**Comment by soyuka** [comment]
Example (with yaml it's clearer):

```
# resources.yml
AppBundle\Entity\Foo:
    attributes:
        color:
            groups: [foo.item, foobar.item]
        contrast:
            groups: [foo.item]
        bar:
            groups: [foobar.item]

AppBundle\Entity\Bar:
    attributes:
        color:
            groups: [foobar.item, bar.item]
        contrast:
            groups: [bar.item]
```

```
# api_resources.yml

resources:
    AppBundle\Entity\Foo:
       collectionOperations:
            get:
               method: 'GET'
               # will not serialize bar relation
               normalization_context: {'groups': [foo.item]} 
       itemOperations:
          get:
               method: 'GET'
               # will serialize bar relation only with color attribute
               normalization_context: {'groups': [foobar.item]}

```

**Comment by DariuszLuber** [comment]
Hi, again.

I'm moving configs from annotation to yaml, and I have few questions about file structure.
I created separated yaml files for each entity:
![image](https://user-images.githubusercontent.com/20465509/32279487-3225fdf2-bf19-11e7-93a9-f8a48b560612.png)

here is sample Assortment.yml file:

```
AppBundle\Entity\Assortment:
    attributes:
        filters: [ 'app.apiOrder', 'app.searchFilter', 'app.searchOrFilter' ]
        normalization_context:
            groups: ['assortment']
        id:
            groups: ['assortment', 'drugs_unified', 'sale', 'drugs']
        name:
            groups: ['assortment', 'drugs_unified', 'sale', 'drugs']
        drugsUnified:
            groups: ['assortment']

        pagination_items_per_page: 10
        fetchEager: true

    itemOperations:
        get:
            method: 'GET'
        put:
            method: 'PUT'
        delete:
            method: 'DELETE'
        add:
            route_name: 'api_assortment_add_drugunified'
            swagger_context:
                parameters:
                    - name: 'id'
                      in: 'path'
                      required: 'true'
                      type: 'string'

                    - name:  'ids'
                      in:  'body'
                      type:  'string'
                      schema:
                        type: 'object'
                        properties:
                          ids:
                            type: 'string'
                      style: 'simple'
                summary:  'Add drugs_unified to assortment'

        remove:
            route_name: 'api_assortment_remove_drugunified'
            swagger_context:
                parameters:
                    - name:  'id'
                      in:  'path'
                      required:  'true'
                      type:  'string'

                    - name: 'ids'
                      in:  'body'
                      type:  'string'
                      schema:
                        type: 'object'
                        properties:
                          ids:
                            type: 'string'
                      style: 'simple'
                summary:  'Remove drugs_unified from assortment'
```

Item and collection operation works well, but settings under attributes section not.

Also I tried to create resources.yml in Resources/config and move there:

```
resources:
  AppBundle\Entity\Assortment:
      attributes:
          filters: [ 'app.apiOrder', 'app.searchFilter', 'app.searchOrFilter' ]
          normalization_context:
              groups: ['assortment']
          id:
              groups: ['assortment', 'drugs_unified', 'sale', 'drugs']
          name:
              groups: ['assortment', 'drugs_unified', 'sale', 'drugs']
          drugsUnified:
              groups: ['assortment']

          pagination_items_per_page: 10
          fetchEager: true


  AppBundle\Entity\DrugUnified:
      attributes:
          filters: ['app.apiOrder', 'app.searchFilter', 'app.searchOrFilter','app.drug_unified_in_buffer']
          pagination_items_per_page: 50
          force_eager: true
          normalization_context:
              groups: ['drugs_unified']

          id:
            groups: ['drugs_unified','assortment', 'sale']
          name:
            groups: ['drugs_unified','assortment', 'sale']
          originalSymbol:
            groups: ['drugs_unified']
          drugs:
            groups: ['drugs_unified','assortment']
          assortment:
            groups:  ['drugs_unified', 'sale']

```

Couse normalization is not working so eager loading is also not working.

Of course  I cleared cache ;)
What I'm doing wrong?

**Comment by DariuszLuber** [comment]
It's almost working.

I set config for serialization based on [http://symfony.com/doc/current/serializer.html#using-serialization-groups-annotations](url) - so I created folder "serialization" and there seperate yaml files for entities.

```
//Resources/config/serialization/Assortment.yml
AppBundle\Entity\Assortment:
    attributes:
        id:
            groups: ['assortment', 'drugs_unified', 'sale', 'drugs']
        name:
            groups: ['assortment', 'drugs_unified', 'sale', 'drugs']
        drugsUnified:
            groups: ['assortment']

```
Next I wanted to set default normalization_context in Resources/config/api_resources/Assortment.yml
```
AppBundle\Entity\Assortment:
    attributes:
        normalization_context:
            groups: ['assortment']
        filters: [ 'app.apiOrder', 'app.searchFilter', 'app.searchOrFilter' ]
        pagination_items_per_page: 10

```
None of set attribute works - where I should set it up?
If for each operation in Resources/config/api_resources/Assortment.yml file I set up normalization_context than it works (getting fields, but still not working eager loading)
```
 collectionOperations:
        get:
            method: 'GET'
            normalization_context:
                groups: ['assortment']
``` 

@soyuka - you had right -  with yaml it's really clearer, but getting it working again takes some time ;) - do you have any sugetion which will save my time :)

**Comment by DariuszLuber** [comment]
I found, in my opinion, strange beachaviour with eager loading.
I disabled it in config.yml and there is no annotation / config for entities to use eager loading.
```
 eager_loading:
        enabled: false
        max_joins: 100
        force_eager: false
```
I was thinking, that if it is disabled than no data connected will be loaded, so I supposed to get something like that
```
{
  "@context": "/api/contexts/Assortment",
  "@id": "/api/assortments",
  "@type": "hydra:Collection",
  "hydra:member": [
    {
      "@id": "/api/assortments/1",
      "@type": "Assortment",
      "id": 1,
      "name": "test",
      "drugsUnified": [
        "/api/drug_unifieds/estimation/2",
        "/api/drug_unifieds/estimation/3",
        "/api/drug_unifieds/estimation/4",
        "/api/drug_unifieds/estimation/5"
      ]
    }
  ],
  "hydra:totalItems": 1
}
```
but I get full data fot each element in drugsUnified, and the reason is serialization - I set the same serialization group in drugsUnified which I set for Assortment.
So does eager loading needed? 

P.S. Still don't know where to setup filters for entities :/
