### ISSUE TITLE
Use a service to retrieve the validation groups danamically

### ISSUE THREAD

**Issue by mzmgh** [api-platform/api-platform#453]
I have a `User` class and a `ValidationGroupsGenerator` class that is a service and I want to generate the validation groups dynamically but it doesn't work.
```
<?php
// User.php
namespace PortalBundle\Entity;

...
...
use PortalBundle\Validator\ValidationGroupsGenerator;
...
...

/**
 * @ApiResource(attributes={"validation_groups"=ValidationGroupsGenerator::class})
 * @ORM\Table(name="portal_users")
 * @ORM\Entity()
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity("username")
 * @UniqueEntity("nationalCode")
 */
class User implements AdvancedUserInterface, JWTUserInterface, \Serializable
{
...
}
```
```
<?php
//ValidationGroupsGenerator.php
namespace PortalBundle\Validator;

use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;

class ValidationGroupsGenerator
{
    private $authorizationChecker;
  
    public function __construct(AuthorizationCheckerInterface $authorizationChecker)
    {
        $this->authorizationChecker = $authorizationChecker;
    }

    public function __invoke($entity): array
    {
        dump("invoked");
        ...
        ...
        ...
        return $validationGroups;
    }
}
```
```
#services.yml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    PortalBundle\Validator\ValidatonGroupsGenerator:
        public: true
```
what is the problem?
