### ISSUE TITLE
Disable http_cache setting on specific routes

### ISSUE THREAD

**Issue by benr77** [api-platform/api-platform#473]
I know you can set up the http_cache globally in `api_platform.yml` - e.g.

```
api_platform:
  http_cache:
    max_age: 300
    public: true
```
Is it possible to do this and then disable it for a specific route? I've tried various things along the lines of the following but none seem to work:
```
resources:
  AppBundle\Entity\MyEntity:
    collectionOperations:
      get:
        method: 'GET'
        http_cache:
            max_age: 0
```
Thanks
