### ISSUE TITLE
Login + Jwt security

### ISSUE THREAD

**Issue by pesseyjulien** [api-platform/api-platform#478]
Hi,

Im struggling a lot to properly configure FosUser + Jwt together. What I want to achieve is the following :

- token secured access to the api endpoints, with Jwt.
- login form to access the api doc

For now, the jwt is properly working, login_check gives me a token and then I can use it on y endpoints.
But, when I tried to login via the form and then access the doc, the login form redirect me to the login_check and give me a token instead of redirecting me to the doc (/). When I try to access it afterwards, I have a 401 error. 

Any ideas how to achieve this ? I have read the docs multiple times but I’m missing something here..

Thanks in avance,
Julien

**Comment by sylflo** [comment]
@dleute I am not using FosUser but I am using json_loing instead of form_login, that's maybe what you need

```
firewalls:
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: our_db_provider
            json_login:
                check_path: /login_check
                require_previous_session: false
                username_path: 'username'
                password_path: 'password'
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            provider: our_db_provider
            lexik_jwt:
                authorization_header: # check token in Authorization Header
                    enabled: true
                    prefix:  Bearer

            # activate different ways to authenticate

            # http_basic: ~
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # https://symfony.com/doc/current/security/form_login_setup.html
```
