### ISSUE TITLE
Troubles with boolean filters.

### ISSUE THREAD

**Issue by amaccis** [api-platform/api-platform#483]
Hi.
I would need to filter my entity Object by property, so I wrote this filter

```
#app/config/api_filters.yml
services:
    object.boolean_filter:
        parent: 'api_platform.doctrine.orm.boolean_filter'
        arguments: [ { property: ~ } ]
        tags: [ 'api_platform.filter' ]
```

and I linked it to the resource

```
#src/AppBundle/Resources/config/api_resources/resources.yml
AppBundle\Entity\Object:
        attributes:
            filters:
                'object.boolean_filter'
        itemOperations:
            get:
                method: 'GET'
                path: '/objects/{id}'
        collectionOperations:
            get:
                method: 'GET'
                path: '/objects
```
but it doesn't work (localhost:8000/api/objects?property=true). I mean, the filter is not applied and I can't see the hydra:search property.
What am I missing?
Thanks!
A.
