### ISSUE TITLE
Authorize form/button in SwaggerUI does not react to user input.

### ISSUE THREAD

**Issue by majermi4** [api-platform/api-platform#486]
I have added JWT to my api-platform project and when I wanted to add the token to SwaggerUI apidoc, I was very confused because the form for inputting the token HTTP header did not close itself or notify me of either success or failure.

Only after asking on Slack I was told that it actually works and the header gets added and it's only the UI seems to be broken.

Here is a video where you can see the form not reacting to button clicks:

![form-not-responding](https://user-images.githubusercontent.com/2118173/33799937-b400993e-dd3e-11e7-9634-565dd7953631.gif)

**Comment by rogamoore** [comment]
I had the same issue.

My config was:
```yaml
# api_platform.yaml
swagger:
  api_keys:
    -
      name: "X-AUTH-TOKEN"
      type: "header"
```
Taken from this example: https://github.com/api-platform/core/pull/1351

After changing it to
```yaml
# api_platform.yaml
swagger:
  api_keys:
    apiKey:
      name: "X-AUTH-TOKEN"
      type: "header"
```
everything worked fine - the Authorize button will now change to a Logout button.

Maybe it helps.

**Comment by lyrixx** [comment]
:+1:  I confirm it's working.

Thanks for the tip

**Comment by dunglas** [comment]
Would you mind opening a docs pull request?

**Comment by rogamoore** [comment]
Will do so on the weekend ;)

**Comment by nWidart** [comment]
Nice this worked for me too.

Before:

```yaml
    swagger:
         api_keys:
             - { name: 'Authorization', type: 'header' }
```

After:

```yaml
    swagger:
        api_keys:
            apiKey:
                name: "Authorization"
                type: "header"
```
