### ISSUE TITLE
FOSUserBundle + JWT (possibly out of date docs?)

### ISSUE THREAD

**Issue by dleute** [api-platform/api-platform#512]
I have not been able to get FOSUserBundle + JWT to work. I am not attached to using FOSUserBundle so if there are examples of how to get most of the functionality, resetting passwords, signup etc with the Doctrine User provider (via api only), I am ok being redirected there.

I am using symfony 4 + flex, which may mean I simply have some piece of config in the wrong file (flex is new to me). I have already discovered that api_check_path needs to be in the routes.yaml not in it's own file (like most other modules. doesn't find it) Otherwise you get "Unable to find the controller for path "/login_check". The route is wrongly configured."

If I put the api_check_path into routes I get: "You must configure the check path to be handled by the firewall using form_login in your security firewall configuration"

This doesn't go away unless I add a form_login section (see the commented sections of security.yaml below), but that causes it to always redirect to HTML instead of allowing /login_check to work. See the security.yaml below

I would also like the routes being used to be in swagger ui. My entire API should be available through swagger.

Anyway, I can't find any combination that actually allows JWT and FOSUserBundle to work at all. If I curl login_check like this:

`curl -X POST http://localhost:8080/login_check -d username=whatever -d password=whatever`

I just get HTML redirecting me to /login. Not useful for an API.

I have come up with this by following the FOSUserBundle and JWT documentation multiple times. I am wondering if something has changed in the versions of each bundle, or if I have to specify a version. (Running latest stable lexikJWT and FOSUserBundle)

Thanks!

```
security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_READER: ROLE_USER
        ROLE_ADMIN: ROLE_READER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
#            form_login:
#                provider: fos_userbundle
            json_login:
                check_path: /login_check
#                require_previous_session: false
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            pattern:   ^/
            provider: fos_userbundle
            stateless: true
            anonymous: true
            lexik_jwt: ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
```

**Comment by soyuka** [comment]
Just use a UserProvider https://symfony.com/doc/current/security/custom_provider.html 

I'm just using: 
- a UserRepository (extends EntityRepository, used by the default loader)
- a JWTResponseListener

Here's my `security.yml`:

```yaml
security:
    encoders:
        Core\UserBundle\Entity\User:
            algorithm: bcrypt
    providers:
        entity_provider:
            entity:
                class: CoreUserBundle:User
    firewalls:
        main:
            anonymous: ~
            json_login:
                check_path:               login_check
                username_path: 'username'
                password_path: 'password'
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            anonymous: true
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        default:
            anonymous: ~

    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_ANONYMOUSLY }
```
