### ISSUE TITLE
swagger_context parameters: false don't hide page and itemsperpage

### ISSUE THREAD

**Issue by lvillarino** [api-platform/api-platform#525]
Hi:

I want to report a bug.

The configuration option "parameters: false" don't hide the parameters _page_ and _itemsperpage_ on the swagger.

```
resources:
  App\Entity\MyEntity:
    collectionOperations:
      get:
        method: GET
      post:
        method: POST
      custom_action:
        route_name: 'route_name_action'
        swagger_context:
          parameters: false
```
Thanks
