### ISSUE TITLE
How to get full object relation in api

### ISSUE THREAD

**Issue by Polaris-BS** [api-platform/api-platform#534]
Hello I want to change this : 

```
[
  {
    "id": 1,
    "title": "Mon super article de blog",
    "content": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac gravida risus, non lacinia arcu. Suspendisse molestie mi velit, quis dictum eros iaculis in. Vivamus ac sagittis mauris, vitae efficitur justo. Sed ut erat vulputate, volutpat leo sed, efficitur tellus. Aenean suscipit vestibulum turpis, non elementum ipsum pharetra ut. Ut fringilla ex mauris, at vehicula ipsum condimentum ac. Nulla mollis ligula sit amet diam hendrerit tincidunt. Pellentesque egestas hendrerit turpis eget venenatis. Aenean auctor id augue nec porttitor.",
    "created": "2018-01-24T07:48:43+00:00",
    "comments": [
      "/api/comments/1"
    ]
  }
]
```

by this : 

```
[
  {
    "id": 1,
    "title": "Mon super article de blog",
    "content": "Lorem ipsum .",
    "created": "2018-01-24T07:48:43+00:00",
    "comments": [
      {
          "id":1,
          "content":"lorem ipsum"
       }
    ]
  }
]
```

I don't understand how I to make for this result

**Comment by soyuka** [comment]
You need to set up serialization groups.

For example:

```yaml
# api_resource.yaml
resources:
  - App\Blog:
    attributes:
      denormalization_context: { groups: [blog, comment] }
```

```yaml
# serialization.yml
App\Blog:
  attributes:
    title: 
      groups: [blog]
    content: 
      groups: [blog]
    comments: 
      groups: [blog]
App\Comment:
  attributes:
    content: 
      groups: [comment]
```

[Read more here](https://api-platform.com/docs/core/serialization#the-serialization-context-groups-and-relations)
