### ISSUE TITLE
Using a Pre-existing Database

### ISSUE THREAD

**Issue by gdharris1970** [api-platform/api-platform#539]
I've been reading through the documentation, and I can't seem to find where it talks about using a pre-existing database. Both the Foo and Book examples create a database as part of the process. I want to develop an API that accesses a database that has already been developed and contains data. Can anyone point me in the right direction? Thanks!

**Comment by dunglas** [comment]
API Platform uses Doctrine (by default, it's optional). Doctrine supports this feature. You can just map the existing database in your entities, or generate entities from the existing database: https://symfony.com/doc/current/doctrine/reverse_engineering.html

**Comment by gdharris1970** [comment]
I have read the instructions on the database reverse engineering page thoroughly, and I've hit a snag. It says:

> Before diving into the recipe, be sure your database connection parameters are correctly setup in the .env file.

I have searched my entire filesystem, and I don't have a ".env" file anywhere. Do you know where it's supposed to go and what the format of the file is supposed to be?

Thanks!

**Comment by gdharris1970** [comment]
Does anyone know where the ".env" file is supposed to go and what it should look like?

**Comment by teohhanhui** [comment]
Assuming you're using https://github.com/api-platform/api-platform/tree/master, it exists as `api/.env`

By default, your file explorer (Mac OS / Linux) would hide files starting with `.`

Even with CLI tools like `ls`, it'd be hidden if you don't use `ls -a`

**Comment by wbelhomsi** [comment]
For anyone still lost and is looking for an answers.. this is how i generated entity from already existing database.. (i use Oracle 12c database in my case):

First i used this command to create my project using composer: (from: [https://api-platform.com/docs/distribution#using-symfony-flex-and-composer-advanced-users](url))
```
# Create a new Symfony Flex project
$ composer create-project symfony/skeleton bookshop-api
# Enter the project folder
$ cd bookshop-api
# Install the API Platform's server component in this skeleton
$ composer req api
```

After that navigate to '.env' file found in the root of the project and changed: 'DATABASE_URL' to
`DATABASE_URL=driver:@//host:port/ServiceName` (change the host port and service name)
My case was (example with oracle db):
`DATABASE_URL=oci8:@//dev01:1521/devProj`

Then navigate to 'doctrine.yaml' found in 'config/packages' and edit the following: (don't forget to edit the parameters to fit you)

```
parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''
    database_driver: oci8
    database_host: dev01
    database_port: 1521
    database_name: 
    database_user: 
    database_password: 
    database_service: true
    database_servicename: devProj
    database_charset: UTF8

doctrine:
    dbal:
        # configure these for your database server
        # driver: 'pdo_mysql'
        # server_version: '5.7'
        # charset: utf8mb4
        # default_table_options:
        #     charset: utf8mb4
        #     collate: utf8mb4_unicode_ci
        driver: '%database_driver%'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: '%database_charset%'
        service: '%database_service%'  
        servicename: '%database_servicename%' 

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

```
Ok now the connection is done the next step would be automatically generating the entities:
[https://symfony.com/doc/current/doctrine/reverse_engineering.html](url)

_**Note**: Make sure all your tables got a primary key_

`php bin/console doctrine:mapping:import 'App\Entity' annotation --path=src/Entity` (Generates the entity files)

`php bin/console make:entity --regenerate App` (Generates getters and setters)
If the above command didn't work please make sure you have doctrine maker 
`composer require doctrine maker`

After that go to your entity files and change: `namespace 'App\Entity';` to `namespace App\Entity;` (just remove the quotes

Now your project is ready.. but the /api doesn't show anything 
Last step would be to add the following to your Entity php files: [https://api-platform.com/docs/distribution#bringing-your-own-model](url)
`use ApiPlatform\Core\Annotation\ApiResource;`
And above the the Class add: 
```
/**
 * ..
 * 
 * @ApiResource
 */
class Book
{
    // ...
}
```
Now use the command:
`php -S 127.0.0.1:8000 -t public` and navigate to /api and it will all be there

Hope this helps
