### ISSUE TITLE
Circular reference trying to decorate api_platform.swagger.normalizer.documentation

### ISSUE THREAD

**Issue by emilien-puget** [api-platform/api-platform#544]
Hello,

I tried to decorate api_platform.swagger.normalizer.documentation, as seen here https://api-platform.com/docs/core/swagger/ and ran into a circular reference :

`
Circular reference detected for service "App\Swagger\SwaggerDecorator", path: "App\Swagger\SwaggerDecorator -> serializer -> App\Swagger\SwaggerDecorator".
`

Im using symfony4 and api-pack v1.0.1

```yaml
services:
    App\Swagger\SwaggerDecorator:
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: [ '@App\Swagger\SwaggerDecorator.inner' ]
        autoconfigure: false
```
```php
namespace App\Swagger;

use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

final class SwaggerDecorator implements NormalizerInterface
{
    private $decorated;

    public function __construct(NormalizerInterface $decorated)
    {
        $this->decorated = $decorated;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $docs = $this->decorated->normalize($object, $format, $context);


        return $docs;
    }

    public function supportsNormalization($data, $format = null)
    {
        return $this->decorated->supportsNormalization($data, $format);
    }
}
```

**Comment by emilien-puget** [comment]
I found the issue, the service was autowired, i moved the service declaration in service.yaml instead of an imported file

**Comment by mshavliuk** [comment]
@emilien-puget Can you show your solution?

**Comment by emilien-puget** [comment]
@mshavliuk the solution was to put the service declaration in the main service.yaml file, not in an imported one

**Comment by sfi-fgarnier** [comment]
It does not work with Symfony 5 and API Platform v2.5.4 :(

config/services.yaml :
```yaml
App\Infrastructure\ApiPlatform\Serializer\DomainHydraDecorator:
    decorates: 'api_platform.hydra.normalizer.error'
    arguments: [ '@App\Infrastructure\ApiPlatform\Serializer\DomainHydraDecorator.inner' ]
    autoconfigure: false
```

App\Infrastructure\ApiPlatform\Serializer\DomainHydraDecorator.php :
```php
<?php

declare(strict_types=1);

namespace App\Infrastructure\ApiPlatform\Serializer;

use App\Domain\Exception\DomainException;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class DomainHydraDecorator implements NormalizerInterface
{
    private $decorated;

    public function __construct(NormalizerInterface $decorated)
    {
        $this->decorated = $decorated;
    }

    /**
     * @inheritDoc
     */
    public function normalize($object, string $format = null, array $context = [])
    {
        /** @var DomainException $object */
        $data = $this->decorated->normalize($object, $format, $context);

        return $data;
    }

    /**
     * @inheritDoc
     */
    public function supportsNormalization($data, string $format = null)
    {
        return $this->decorated->supportsNormalization($data, $format);
    }
}
```

Result :
```
Circular reference detected for service "serializer", path: "serializer -> App\Infrastructure\ApiPlatform\Serializer\DomainHydraExceptionListener -> serializer".
```

**Comment by coldic3** [comment]
Exactly the same situation. When I have my normalizers, data providers, etc. inside `services.yaml` it works. When I'll try to put those inside other config files then it breaks.

For example:
`
# services.yaml

imports:
    - { resource: services/serializers.yaml }
    - { resource: services/data_providers.yaml }

parameters:
# ...

services:
    _defaults:
        autowire: true
        autoconfigure: true
    # ...
`
`
# services/serializers.yaml

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: false
    
    App\Serializer\Swagger\DocumentationNormalizer:
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: ['@App\Serializer\Swagger\DocumentationNormalizer.inner']
`

What I've got is: Circular reference detected for service "serializer", path: "serializer -> App\Serializer\Swagger\DocumentationNormalizer -> serializer".

The same with the `data_providers.yaml`, "imported" data providers don't work at all.
I haven't any errors about not existing files or something like that.

**Comment by coldic3** [comment]
Exactly the same situation. When I have my normalizers, data providers, etc. inside `services.yaml` it works. When I'll try to put those inside other config files then it breaks.

For example:
```
#services.yaml

imports:
    - { resource: services/serializers.yaml }
    - { resource: services/data_providers.yaml }

parameters:
# ...

services:
    _defaults:
        autowire: true
        autoconfigure: true
    # ...
```
```
# services/serializers.yaml

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: false
    
    App\Serializer\Swagger\DocumentationNormalizer:
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: ['@App\Serializer\Swagger\DocumentationNormalizer.inner']
```

What I've got is: Circular reference detected for service "serializer", path: "serializer -> App\Serializer\Swagger\DocumentationNormalizer -> serializer".

The same with the `data_providers.yaml`, "imported" data providers don't work at all.
I haven't any errors about not existing files or something like that.

**Comment by sfi-fgarnier** [comment]
Hi @coldic3,

I think it is important to configure decorators after "_defaults" and "App\" sections into services.yaml file :

This configuration works :

```yaml
# config/services.yaml

parameters:
    ...

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Kernel.php,Entity}'

    # Swagger Decorator
    App\Infrastructure\ApiPlatform\Swagger\SwaggerDecorator:
        decorates: 'api_platform.swagger.normalizer.documentation'
```

In your example, your external configurations were imported **before** "_defaults" section and it could not work.
