### ISSUE TITLE
Don't set POST request on api, get 406 Not Acceptable

### ISSUE THREAD

**Issue by krypton-code** [api-platform/api-platform#553]
Hello everyone!
Don't set POST request on api, get 406 Not Acceptable.
Tried to use axios and got 406 error. Was think that axios cause of the problem. Then I tried to use fetch() and got again 406 error. 

I think that not seted header `Content-Type`, when I send his - get 400 Bad Request and in tab Preview `Unauthorized header content-type`.

Need your help, what am I doing wrong?
Thanks everyone for help.

- Environment: node v8.9.4, chrome 64.0.3282.119, Ubuntu 16.04
- axios version: 0.16.2
- Vue.js 2.4.2
- vue-axios 2.0.2
- api-platform/api-pack: 1.0
- Symfony 4.0.4

![image](https://user-images.githubusercontent.com/6662917/35813751-6f3afb20-0aa5-11e8-872b-975feb1f2307.png)

![image](https://user-images.githubusercontent.com/6662917/35813769-7e2d9ee4-0aa5-11e8-9cdd-6cc99ac73c8e.png)

**First example code:**
```
const json = JSON.stringify({
    a: 1,
    b: 2,
});
fetch('http://localhost:8080/api/products', {
    method: 'POST',
    headers: {
         // 'Content-Type': 'application/json',
    },
    body: json,
});
```

**Second example code:**
```
const data = JSON.stringify({
    data: this.cardData.brand,
});
const configAxios = {
    headers: {
     // 'Content-Type': 'application/json',
     },
};
axios.post('api/products', data, configAxios)
.then((res) => {
    this.cardData.brand = res.data;
    console.log(res);
})
.catch((err) => {
    console.warn('error during http call', err);
});
```

**Comment by BonnieDoug** [comment]
What happens when you call that same endpoint from within the  Api-Platform User interface? I'm thinking it might be because your content type is `application/json` where it should be `application/json-ld` OR you need to enable `application/json` in your config.

**Comment by krypton-code** [comment]
@BonnieDoug when I call that same endpiont from within the api-platform - request is request is success.

Config api-platform, json at the first place:
```
api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    # The list of enabled formats. The first one will be the default.
    formats:
        json:
            mime_types: ['application/json']
            
        jsonld:
            mime_types: ['application/ld+json']

        html:
            mime_types: ['text/html']

    # The list of enabled error formats. The first one will be the default.
    error_formats:
        jsonproblem:
            mime_types: ['application/problem+json']

        jsonld:
            mime_types: ['application/ld+json']
```
