### ISSUE TITLE
Two classes with same name but different namespace

### ISSUE THREAD

**Issue by MadisD** [api-platform/api-platform#555]
Hi

I have two Parish entities with namespaces App\Entity and App\Entity\Location and they map to different tables.

If i make both of them as resources then only one of them is applied, but if i try to rename one of their paths, then still only one is shown. Each of them work individually if the other is commented out.

I have configured my the resources like this:

``` yaml
 App\Entity\Location\Parish:
    collectionOperations:
      get:
        method: 'GET'
    itemOperations:
      get:
        method: 'GET'
    properties:
      county:
        subresource:
          resourceClass: 'App\Entity\Location\County' 
```

and 

``` yaml 
 App\Entity\Parish:
    collectionOperations:
      get:
        method: 'GET'
        path: '/custom'
    itemOperations:
      get:
        method: 'GET'
        path: 'custom/{id}'
```

With these configurations the /custom path doesnt work. It says "No route found for "GET /api/custom"
 But if i comment out the other one, the /custom path works, without any other changes.
I mean yes, I can rename the classes so they aren't identical, but is this supposed to work or it is some kind of a bug?

**Comment by soyuka** [comment]
Hi! I think that this is the normal behavior because the ShortNameResourceMetadataFactory is only using the classname as basis: 

https://github.com/api-platform/core/blob/62383baf0deacc136aefc2441da45a3401d004dc/src/Metadata/Resource/Factory/ShortNameResourceMetadataFactory.php#L44

My advise is to replace the following class with your own `ShortNameResourceMetadataFactory`:

```yaml
services:
    _defaults:
        autowire: true
        public: false

Api\Metadata\Resource\Factory\ShortNameResourceMetadataFactory:
        decorates: 'api_platform.metadata.resource.metadata_factory'
        arguments: 
            ['@Api\Metadata\Resource\Factory\ShortNameResourceMetadataFactory.inner']
```

```php
<?php

declare(strict_types=1);

namespace Api\Metadata\Resource\Factory;

use ApiPlatform\Core\Metadata\Resource\Factory\ResourceMetadataFactoryInterface;
use ApiPlatform\Core\Metadata\Resource\ResourceMetadata;

/**
 * Guesses the short name from the class name if not already set.
 *
 * @author Kévin Dunglas <dunglas@gmail.com>
 */
final class ShortNameResourceMetadataFactory implements ResourceMetadataFactoryInterface
{
    private $decorated;

    public function __construct(ResourceMetadataFactoryInterface $decorated)
    {
        $this->decorated = $decorated;
    }

    /**
     * {@inheritdoc}
     */
    public function create(string $resourceClass): ResourceMetadata
    {
        $resourceMetadata = $this->decorated->create($resourceClass);

        $parts = explode('\\', $resourceClass);

        if (null !== $resourceMetadata->getShortName()) {
            return $resourceMetadata;
        }

        return $resourceMetadata->withShortName(substr($resourceClass, strrpos($resourceClass, '\\') + 1));
    }
}
```
