### ISSUE TITLE
401 JWT Token not found

### ISSUE THREAD

**Issue by krypton-code** [api-platform/api-platform#557]
Hello everyone, I need a help.
I will be very happy if someone helps me, because I am already on my second day over this problem.
Thanks a lot.

- Environment: node v8.9.4, chrome 64.0.3282.119, Ubuntu 16.04
- axios version: 0.16.2
- Vue.js 2.4.2
- vue-axios 2.0.2
- api-platform/api-pack: 1.0
- Symfony 4.0.4

**security.yaml**

```
security:

    encoders:
        App\Entity\User:
            algorithm: bcrypt
        
        App\Security\User\WebserviceUser: bcrypt

    providers:
    
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username
     
        webservice:
            id: App\Security\User\WebserviceUserProvider
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            provider: webservice
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api:
            pattern:   ^/api
            stateless: true
            provider: our_db_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }
```

**Headers**

![image](https://user-images.githubusercontent.com/6662917/35891710-c35c0f02-0bb6-11e8-9dea-120feffd9fdb.png)

**curl**

![image](https://user-images.githubusercontent.com/6662917/35891778-fc55c37a-0bb6-11e8-8c11-4affc29373cd.png)

**.env**

```
###> lexik/jwt-authentication-bundle ###
# Key paths should be relative to the project directory
JWT_PRIVATE_KEY_PATH=var/jwt/private.pem
JWT_PUBLIC_KEY_PATH=var/jwt/public.pem
JWT_PASSPHRASE=d70414362252a41ce772dff4823d084d
###< lexik/jwt-authentication-bundle ###
```

**lexik_jwt_authentication.yaml**

```
lexik_jwt_authentication:
    private_key_path: '%kernel.project_dir%/%env(JWT_PRIVATE_KEY_PATH)%'
    public_key_path:  '%kernel.project_dir%/%env(JWT_PUBLIC_KEY_PATH)%'
    pass_phrase:      '%env(JWT_PASSPHRASE)%'
```

**Comment by BonnieDoug** [comment]
Your jwt token seems very short. Have you tried putting it into Jwt.io to see what it actually contains.

Off the top of my head it shoukd contain at least 2 full stops.

**Comment by soyuka** [comment]
related https://github.com/api-platform/api-platform/issues/512 
Numerous issues on the subject btw!

**Comment by krypton-code** [comment]
@BonnieDoug jwt.io tell that token is Invalid Signature. With what it can be connected? I tried use curl with additional parametrs `curl -H "Content-Type: application/json" -H "Authorization: Bearer d70414362252a41ce772dff4823d084d" http://localhost:8080/api/categories`, but I get `{"code":401,"message":"Invalid JWT Token"}`

**Comment by krypton-code** [comment]
@soyuka, to be honest, I can not figure out which direction to go in, since my implementation is the same.

**Comment by BonnieDoug** [comment]
So if you log in using curl e.g: 

`curl -X POST "http://localhost:8000/api/login" -H  "accept: application/ld+json" -H  "Content-Type: application/ld+json" -d "{  \"username\": \"foo\",  \"password\": \"bar\"}"`

You should get a JWT token in response. What is the result of this?

**Comment by krypton-code** [comment]
@BonnieDoug 
![image](https://user-images.githubusercontent.com/6662917/35918902-6a9947cc-0c24-11e8-83d2-0fa13cad5924.png)

**Comment by BonnieDoug** [comment]
I don't think you should be POSTing to login_check, that get's called after by the framework. You log in by going to `/api/login` and filling in the form OR by POSTing to the endpoint. Depending on how you have it set up.

**Comment by soyuka** [comment]
Did you set up the JWT_PASSPHRASE correctly and regenerate certificates as explained on JWT home page?

Looking at your authentication attempt it looks like `admin / [redacted]` user isn't correct.

**Comment by krypton-code** [comment]
@soyuka, I use https://github.com/lexik/LexikJWTAuthenticationBundle. I think that it not connectedly with jwt.io, I'm right?

**Comment by soyuka** [comment]
yes I was speaking about https://github.com/lexik/LexikJWTAuthenticationBundle

**Comment by krypton-code** [comment]
@chalasr greeting, thanks for the response. Studying this repo: https://github.com/chalasr/lexik-jwt-authentication-sandbox, led me to such an error. Also I change file `security.yaml`:

```
security:

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
    
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username
        
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
       
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        
        register:
            pattern:  ^/register
            stateless: true
            anonymous: true

        api:
            pattern:   ^/api
            stateless: true
            anonymous: false
            provider: our_db_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
```

![image](https://user-images.githubusercontent.com/6662917/36039996-303350d4-0dd5-11e8-809b-bbccdec520e3.png)
![image](https://user-images.githubusercontent.com/6662917/36040008-3edc593c-0dd5-11e8-9beb-ec7d57dd6b10.png)
![image](https://user-images.githubusercontent.com/6662917/36039719-65d88656-0dd4-11e8-8bb3-64595d544bb8.png)
