### ISSUE TITLE
@id change with custom action

### ISSUE THREAD

**Issue by abysKri** [api-platform/api-platform#559]
Hi everybody,
For this AP context
`"@context": "/web/app_dev.php/v1/contexts/Articles"`

the normal @id is
`"@id": "/web/app_dev.php/v1/articles"`

after adding a custom action for the same route, and for all GET actions in a Articles collection
```
"@id" change and use the latest one in resources config file:

"@id": "/web/app_dev.php/v1/articles/latest/aop"
```

My Bundle APIBundle/Resources/config/api_resources/api_resources.yml:
```
resources:
    APIBundle\Entity\Articles:
        collectionOperations:
            get:
                method: 'GET'
            latestarticles:
                route_name: 'latest_issues_articles'
                pagination_enabled: false
            latestjaa:
                route_name: 'latest_jaa_articles'
                pagination_enabled: false
            latestaop:
                route_name: 'latest_aop_articles'
                pagination_enabled: false

    APIBundle\Entity\Issues:
        collectionOperations:
            get:
                method: 'GET'
            latest:
                route_name: 'latest_issue'
                pagination_enabled: false
```

```
#app/config/routing.yml				
app:
    resource: '@APIBundle/Action/'
    type: 'annotation'
    prefix: '/v1/'

api:
    resource: '.'
    type:     'api_platform'
    prefix: '/v1/'
```

Is it normal ?
	
And, if i inverse the routing, the "api:" in first and the "app:" after, all custom action return 404 not found
ex:
the entrypoint work:  `app_dev.php/v1/articles`

but this one return "404 not found": `app_dev.php/v1/articles/latest/aop `

```
My routes:

  api_articles_get_collection                   GET      ANY      ANY    /v1/articles.{_format}
  api_articles_get_item                         GET      ANY      ANY    /v1/articles/{id}.{_format}
  api_articles_put_item                         PUT      ANY      ANY    /v1/articles/{id}.{_format}
  api_articles_delete_item                      DELETE   ANY      ANY    /v1/articles/{id}.{_format}
  latest_aop_articles                           GET      ANY      ANY    /v1/articles/latest/aop
  latest_issue                                  GET      ANY      ANY    /v1/issues/latest
  latest_issues_articles                        GET      ANY      ANY    /v1/articles/latest
  latest_jaa_articles                           GET      ANY      ANY    /v1/articles/latest/jaa
```

  Thanks a lot
