### ISSUE TITLE
Custom action with controller with api request - Creating Custom Operations and Controllers

### ISSUE THREAD

**Issue by marinsagovac** [api-platform/api-platform#588]
Due to find tons on issues how to make a custom controller without properly documentation (such as https://api-platform.com/docs/core/operations/) i wrote a sample how to make custom action on GET active request.

Find some custom route: bin/console debug:router 

example: api_countries_get_item

Create a Controller/CountriesSpecial.php

```
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Countries;
use Symfony\Component\Routing\Annotation\Route;

class CountriesSpecial
{
    private $myService;

    /*
    public function __construct(MyService $myService)
    {
        $this->myService = $myService;
    }*/

    /**
     * @Route(
     *     name="api_countries_get_item",
     *     path="/countries/{id}",
     *     methods={"GET"},
     *     defaults={"_api_resource_class"=Countries::class, "_api_item_operation_name"="countries"}
     * )
     */
    public function __invoke(Countries $data): object // API Platform retrieves the PHP entity using the data provider then (for POST and
        // PUT method) deserializes user data in it. Then passes it to the action. Here $data
        // is an instance of Book having the given ID. By convention, the action's parameter
        // must be called $data.
    {
        //die('x');

        //$this->myService->doSomething($data);

        return $data; // API Platform will automatically validate, persist (if you use Doctrine) and serialize an entity
        // for you. If you prefer to do it yourself, return an instance of Symfony\Component\HttpFoundation\Response
    }

    public function special(Countries $data)
    {
        // Handle custom action

        // Here you go, i've added custom arrays inside

        return array($data, array('key' => 'custom'));
    }
}
```

Add routes into routing.yml

```
api_countries_get_item:
    path: '/countries/{id}'
    methods:  ['GET']
    defaults:
        _controller: '\AppBundle\Controller\CountriesSpecial::special'
        _api_resource_class: 'AppBundle\Entity\Countries'
        _api_item_operation_name: 'special'
```

On Entity Countries.php put:

```
/**
 * Country
 *
 * @ApiResource{
 *      "get",
 *      "special"={"route_name"="countries_special"},
 * }
 * @ORM\Entity
 * @ORM\Table(name="country")
 */
class Countries
{
```

Hope this helps someone!

**Comment by antograssiot** [comment]
I might be wrong but your overhead might be due to a bad `@ApiRessouce` declaration. I would have done
```
@ApiResource{
      itemOperations={"get", "special"={"route_name"="countries_special"}},
}
```

**Comment by marinsagovac** [comment]
@antograssiot 

I've tried your solution. On your situation you add only method type.

This is same as (removed methods):

```
api_countries_get_item:
    path: '/countries/{id}'
    defaults:
        _controller: '\AppBundle\Controller\CountriesSpecial::special'
        _api_resource_class: 'AppBundle\Entity\Countries'
        _api_item_operation_name: 'special'
```

A defaults directive and _controller, resource and item should be defined for properly overriding method. 
This already worked.
