### ISSUE TITLE
Need some help with varnish invalidation behind jwilder proxy

### ISSUE THREAD

**Issue by iCodr8** [api-platform/api-platform#591]
I am running an api-platform v2.1.6 with docker behind a [jwilder reverse proxy](https://github.com/jwilder/nginx-proxy) and I have the problem that the invalidation of the varnish cache seems not working.
When I'm running the docker containers on my local machine, varnish is working without any problems. But on the server for example I am getting the same content of `GET /users/12`, even if I requested `PUT /users/12` before.

Has someone a hint for me or a solution for this problem?

This is my `docker-compose-deployment.yml` file for deployment. I am building images from the Dockerfiles and run them with this docker-compose file:

```yml
version: '3'

services:
  app:
    image: ${CONTAINER_APP_IMAGE}
    restart: 'always'
    depends_on:
      - db
    environment:
      - SYMFONY_ENV=${SYMFONY_ENV}
    volumes:
      - ./.env:/srv/api-platform/.env:ro
      - ./parameters.yml:/srv/api-platform/app/config/parameters.yml:rw
      - app-web:/srv/api-platform/web:rw
    networks:
      - back-tier
  db:
    image: ${CONTAINER_DB_IMAGE}
    restart: 'always'
    environment:
      - MYSQL_DATABASE=api_platform
      # You should definitely change the password in production
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=api_platform
    ports:
      - "3306"
    volumes:
      - ./database:/var/lib/mysql:rw
      - db-data:/var/lib/mysql:rw
    networks:
      - back-tier
  nginx:
    image: ${CONTAINER_NGINX_IMAGE}
    restart: 'always'
    volumes:
      - app-web:/srv/api-platform/web:ro
    ports: []
    networks:
      - back-tier

  varnish:
    image: ${CONTAINER_VARNISH_IMAGE}
    restart: 'always'
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${ADMIN_EMAIL}
    depends_on:
      - app
      - nginx
    ports: []
    expose:
      - "80"
      - "443"
    networks:
      - back-tier
      - proxy-tier

volumes:
  app-web: {}
  db-data: {}

networks:
  back-tier:
    driver: bridge
  proxy-tier:
    external:
      name: nginx-proxy
```
