### ISSUE TITLE
Switching to MySQL

### ISSUE THREAD

**Issue by mvaljento** [api-platform/api-platform#594]
I'm a newbie to Docker and Api Platform. I got the latest version running on my Mac, but I'm having trouble changing over from Postgres to MySQL and I did not find anything on it in documentation. 

MySQL seems to be running, but I cannot run php commands to for example create the schema.

Any idea where changes need to be made?

From my docker-compose.yaml:
```

image: mysql
        volumes:
            - "./.data/mysql:/var/lib/mysql"
        environment:
            MYSQL_USER: lorem
            MYSQL_ROOT_PASSWORD: lorem
            MYSQL_PASSWORD: lorem
            MYSQL_DATABASE: my-app
        ports:
            - "3306:3306"
```
I also updated the Dockerfile and changed postgres_pdo into mysql_pdo, and added these:

```
FROM php:7.2-fpm-alpine3.7
RUN docker-php-ext-install mysqli pdo pdo_mysql
RUN docker-php-ext-enable mysqli
```

Unfortunately I'm still getting the following error:

`An exception occurred in driver: could not find driver
`

**Comment by marcw** [comment]
You have to change the `api/config/packages/doctrine.yaml` file and change `pdo_pgsql` by `pdo_mysql` as well.

**Comment by SulivanDotEu** [comment]
I'm also trying to use MySQL instead to build a proof of concept of a full reboot of our IT software and because we use MySQL, I would like to use Mysql instead of Postgres (in order to dump classes from database configuration).

I edited api/DockerFile line 17 (pdfmysql) and doctrine.yaml but it doesn't work

**Comment by sushrest** [comment]
My Symfony App is still pointing to default postgres port 5432, can you point me to the right config..pls

**Comment by teohhanhui** [comment]
@sushrest You also need to change the `DATABASE_URL` environment variable (in the `api/.env` file) to use the `mysql://` protocol instead of `pgsql://`

**Comment by Selion05** [comment]
here's  the outpout from `git diff` with api-platform-2.3.1 and mysql as database
[git-diff.txt](https://github.com/api-platform/api-platform/files/2314225/git-diff.txt)

**Comment by Selion05** [comment]
jep i guess i can do that :)

**Comment by Selion05** [comment]
@dunglas  i have a guide now for the steps for 2.3.2 but i'm not very familiar with creating a pull request. 
that's my fork https://github.com/Selion05/docs/blob/2.2/core/mysql.md

**Comment by Chrysweel** [comment]
I think it's a good idea to include in the Api Platform documentation how to change to use mysql !

**Comment by soyuka** [comment]
@Chrysweel see https://symfony.com/doc/current/doctrine.html#configuring-the-database

**Comment by Fabian-Luque** [comment]
I have this problem.
php_1          | Waiting for db to be ready...

**Comment by constantin-pwrr-expert** [comment]
Any other news on how to use mysql with api-platform? 
I added the db image details to docker-compose.yml. CHanged symfony credentials to connect to the new mysql databse but then the /api and /admin do not work

**Comment by maks-rafalko** [comment]
what is the error message?

it should work, if you configured it properly:

```yaml
db:
    image: mysql:8
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
```

Make sure to update `DATABASE_DSN` from postrge to mysql:

```
DATABASE_URL=mysql://db_user_name:db_user_pass@db/db_name?server_version=8
```
