### ISSUE TITLE
@context ignore serialization groups

### ISSUE THREAD

**Issue by ThibaudLafont** [api-platform/api-platform#597]
Hi, 

I have an issue with JSON-LD context : it serialize all attributes and public properties, despite I set global normalization and denormalization contexts and configure serialization groups.

Client resource config
```
  AppBundle\Entity\User\Client:
    attributes:
      normalization_context:
        groups: ['client_show']
      denormalization_context:
        groups: ['client_create']
    ...///
```

Serialization :
```
AppBundle\Entity\User\Client:
  attributes:
    username:
      groups: ['client_show', 'client_create', 'client_list', 'client_edit']
    firstName:
      groups: ['client_show', 'client_create', 'client_edit']
    lastName:
      groups: ['client_show', 'client_create', 'client_edit']
    mailAddress:
      groups: ['client_show', 'client_create', 'client_edit']
```

/contexts/Client :
```
{
    "@context": {
        "@vocab": "http://bilemo.lan/docs.jsonld#",
        "hydra": "http://www.w3.org/ns/hydra/core#",
        "username": "Client/username",
        "firstName":  "Client/firstNale",
        "lastName": "Client/lastName",
        "mailAddress": "Client/mailAddress",
        "roles": "Client/roles",
        "salt": "Client/salt",
        "password": "Client/password",
        "plainPassword": "Client/plainPassword"
    }
}
```

I search by my side and I finally found something in `ApiPlatform\Core\Metadata\Property\Factory\ExtractorPropertyNameCollectionFactory:create`

Maybe it's a dummy trick but modification below is working and @context take in consideration the given groups.

```
    public function create(string $resourceClass, array $options = []): PropertyNameCollection
    {
        $propertyNames = [];

        if ($this->decorated) {

            $options['serializer_groups']=['client_show'];   // For testing, I manually inject client_show group

            try {
                foreach ($propertyNameCollection = $this->decorated->create($resourceClass, $options) as $propertyName) {
                    $propertyNames[$propertyName] = $propertyName;
                }
            } catch (ResourceClassNotFoundException $resourceClassNotFoundException) {
                // Ignore not found exceptions from parent
            }
        }
    }
```
And then my @context is OK : 
```
{
    "@context": {
        "@vocab": "http://bilemo.lan/docs.jsonld#",
        "hydra": "http://www.w3.org/ns/hydra/core#",
        "firstName": "Client/lastName",
        "lastName": "Client/lastName",
        "mailAddress": "Client/mailAddress",
        "phoneNumber": "Client/phoneNumber",
        "username": "Client/username"
    }
}
```

Do I misunderstand something ? How can I solve my issue ?

Thank you!
