### ISSUE TITLE
Login Method at Swagger Doc 

### ISSUE THREAD

**Issue by ljbergmann** [api-platform/api-platform#623]
As recommended in the docs i'm using a custom user provider in combination with Lexik JWT for user authentication. My setup is working correctly, i can perform a login and secured routes will work only if the user is authenticated. So far so good, but there is no possibility in the Swagger Doc (or is it called OpenAPI Doc i'm not sure ?) to perform a login. 

This is not a big deal but in my opinion it would be very nice if there were a way to perform a login from this point. 

Another funny quirk i'm encountered is every secured path has a lock behind its record. Before i enter the jwt all locks are open, after i enter the jwt via the authorize button all locks are closed. Do i have a config error or is this done intentionally?

Before authorize button:
<img width="272" alt="screen shot 2018-03-26 at 15 09 08" src="https://user-images.githubusercontent.com/1332168/37908185-ba5f2238-3107-11e8-954d-7854701b4f1d.png">

After authorize button:
<img width="282" alt="screen shot 2018-03-26 at 15 09 27" src="https://user-images.githubusercontent.com/1332168/37908184-ba41ef10-3107-11e8-9a15-0424ff883a72.png">

For reference my config files:

**security.yaml**
```
security:
    encoders:
      App\Entity\User:
        algorithm: bcrypt
        
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        user_provider:
          entity:
            class: App\Entity\User
            property: username

    firewalls:
        main:
            pattern:   ^/api/
            provider: user_provider
            stateless: true
            anonymous: ~
            json_login:
                check_path: /api/login
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/api/.*, roles: ROLE_USER }
        - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, role: IS_AUTHENTICATED_ANONYMOUSLY } 
```
**api_platform.yaml**
```
api_platform:
    # The title of the API.
    title: "Some fancy title"

    # The version of the API.
    version: '0.0.1'

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header
```
