### ISSUE TITLE
Unable to change the Swagger UI Location

### ISSUE THREAD

**Issue by comxd** [api-platform/api-platform#635]
Documentation api-platform.com: [Changing the Swagger UI Location](https://api-platform.com/docs/core/swagger/#changing-the-swagger-ui-location)

I got this error for "/" and "/docs" routes:
`Serialization for the format html is not supported.`

```
#api/config/routes.yaml
swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui
```

```
# api/config/packages/api_platform.yaml
api_platform:
    # ...
    enable_swagger_ui: false
```

https://github.com/api-platform/api-platform/issues/195
