### ISSUE TITLE
[ASK] Use two entity managers

### ISSUE THREAD

**Issue by qeude** [api-platform/api-platform#700]
Hello, I have set two entity manager in my app to access to 2 different databases. It works well for Entity generation from db. But in the ApiDoc, when I want to call one of my CRUD requests, I've got a 404 Error, I think it's because it try to use the default em. Any idea to handle that ? 
I have declared my em like this
```
orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity\Main'
                        alias: Main
            test:
                connection: test
                mappings:
                    Test:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity2'
                        prefix: 'App\Entity2'
                        alias: test
```

Thanks :)

**Comment by vasilvestre** [comment]
@qeude you solved it ?

**Comment by mrtnzagustin** [comment]
Same problem here!!

**Comment by teohhanhui** [comment]
I can confirm that this is not solved, because we're injecting `doctrine.orm.default_entity_manager` here: https://github.com/api-platform/core/blob/1d5f020eb55705ed1d58f0c5269631b439dfd08d/src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml#L9

Same for Doctrine MongoDB ODM: https://github.com/api-platform/core/blob/d8e624ba242593365773ec8070d92f548f77d575/src/Bridge/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml#L10 and https://github.com/api-platform/core/blob/d8e624ba242593365773ec8070d92f548f77d575/src/Bridge/Symfony/Bundle/Resources/config/doctrine_mongodb_odm.xml#L16

**Comment by rixbeck** [comment]
I think it is the same situation here #556. @byhorattis has made a workaround [here](https://github.com/api-platform/api-platform/issues/556#issuecomment-363820115) until...

**Comment by rishta** [comment]
In `config/packages/api_platform.yml`:

```yaml
api_platform:
    mapping:
        paths: 
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Entity2'
```
