### ISSUE TITLE
Issue with routing for custom operations

### ISSUE THREAD

**Issue by thib92** [api-platform/api-platform#707]
Hello,

I am having issues creating custom operations with API-Platform.
I am configuring it with the following YAML file :

```yaml
resources:


  App\Entity\User:
    attributes:
      normalization_context:
        groups:
          - user
          - user-read
      denormalization_context:
        groups:
          - user
          - user-write

    collectionOperations:
      me:
        method: GET
        path: /users/me
        controller: App\Controller\UserMeController
        access_control: "is_granted('ROLE_USER')"

    itemOperations:
      get:
        access_control: "is_granted('ROLE_USER') and user.isEqualTo(object)"


  App\Entity\Hobby:
    collectionOperations:
      me:
        method: GET
        path: /hobbies/me
        controller: App\Controller\HobbiesMeController
        access_control: "is_granted('ROLE_USER')"
      putme:
        method: PUT
        path: /hobbies/me
        controller: App\Controller\HobbiesMePutController
        access_control: "is_granted('ROLE_USER')"
    itemOperations:
      get: ~
```

However, trying to access the `/api/users/me` route, I am getting a 404 error from the `api_users_get_item` route.

Here is a screenshot of the Symfony debugger :

![profiler](https://user-images.githubusercontent.com/1472635/40886085-19281102-6732-11e8-950b-88277d33b123.png)

As you can see, the route `api_users_me_collection` is matched, but for some reason, the `api_users_get_item` is used instead. I am guessing that this is why I am getting a 404 (API Platform is trying to reach the User with id `me`).

Using the console, my route is matched as well. Also, my custom route is defined above the `api_users_get_item` route

![image](https://user-images.githubusercontent.com/1472635/40886097-66db4cb6-6732-11e8-9737-b1539c73ea39.png)

![image](https://user-images.githubusercontent.com/1472635/40886102-888d6678-6732-11e8-989f-47417366763c.png)

Thanks in advance for reading my issue 👍

Thibault
