### ISSUE TITLE
Subresource throws execption when pointing to the same entity

### ISSUE THREAD

**Issue by bedrich-schindler** [api-platform/api-platform#718]
Hello,

I have `User` which has many-to-one relations to `User`, called `supervisor`. If I create subresource that returns users which are supervised by selected user (so subresource pointing to the same entity), following `QueryException` is thrown:

```
[Syntax Error] line 0, col 50: Error: Unexpected 'WHERE'
```

When I dump generated DQL, API platform generates following query:

```
SELECT o FROM App\Entity\User o WHERE o IN(SELECT WHERE id_a1.id = :id_p1) ORDER BY o.id ASC
```

Row from log:

```
request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Syntax Error] line 0, col 50: Error: Unexpected 'WHERE'" at /www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 54 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Syntax Error] line 0, col 50: Error: Unexpected 'WHERE' at /www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:54, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT o FROM App\\Entity\\User o WHERE o IN(SELECT WHERE id_a1.id = :id_p1) ORDER BY o.id ASC at /www/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:43)"} []
```

Doctrine configuration file:

```
App\Entity\User:
    type: entity
    table: app_user

    id:
        id:
            type: integer
            generator: { strategy: IDENTITY }

    fields:
        /// ...

    manyToOne:
        supervisor:
            targetEntity: App\Entity\User
            mappedBy: supervised
            joinColumn:
                name: supervisor_id
                referencedColumnName: id
                onDelete: SET NULL
                nullable: true
```

API configuration file:

```
App\Entity\User:
    properties:
        supervised:
            subresource:
                resourceClass: 'App\Entity\User'
                collection: true
    subresourceOperations:
        superviseds_get_subresource:
            method: 'GET'
            path: '/users/{id}/supervised_users'
```

Thank you for your help
