### ISSUE TITLE
Validation of YAML resources configuration files

### ISSUE THREAD

**Issue by piotaixr** [api-platform/api-platform#722]
I am configuring the resources via YAML files.
Just spent 15 mins trying to debug my app because of a circular reference exception even though i added serialization groups and, inside the config file:

```yml
resources:
    My\Entity\Class:
        attributes:
        normaliation_context:
            groups: ['my-group']
        [...]
```

Now, I am aware that a 'z' is missing. But it would have been really nice to have a warning or exception somewhere saying that there was a problem in my config file. It's not the only time i'd have like to have this kind of feature.

Is there currently a way to validate the api-platform resources configuration files?
