### ISSUE TITLE
Deserialization concrete class extended from abstract not filled fully

### ISSUE THREAD

**Issue by voodoo-dn** [api-platform/api-platform#726]
Hi. Sorry for my english.

I have entity AbstractPrize with properties $place, $rating.
I have 2 entities which extended from AbstractPrize: MoneyPrize and PointPrize.

The problem: I send next request
```
{
  "type": "bet_count",
  "platforms": [
    {"id": 1}
  ],
  "name": "Bet count rating",
  "description": "Bet count rating description",
  "isEnabled": true,
  "year": "2018",
  "month": "06",
  "prizes": [
  	{
		"discriminator": "points",
		"count": 100,
		"place": 2
	},
    {
		"discriminator": "money",
		  "amounts": [
		    {
		      "amount": "10.0",
		      "currency": "/api/currencies/1"
		    }
		  ],
		  "wager": 0,
		  "place": 1
	}
	
  ]
}
```
Deserialization works well, but PointPrize object not filled fully. Property `count` is null.

I debug api platform internals + serializer whole day and find some problem.

\ApiPlatform\Core\Serializer\AbstractItemNormalizer::getAllowedAttributes.

$propertyMetadata->isReadable(), $propertyMetadata->isWriteable() returns false and count data not writes to object property.

I dont understand why. MoneyPrize and PointPrize have the same groups. 

```
App\Domain\Entity\Prize\AbstractPrize:
    collectionOperations: ['get', 'post']
    itemOperations: ['get', 'put', 'delete']
    attributes:
        normalization_context:
          groups: ['rating_admin_read']
        denormalization_context:
          groups: ['rating_admin_write']

App\Domain\Entity\Prize\Money\MoneyPrize:
    collectionOperations: ['get', 'post']
    itemOperations: ['get', 'put', 'delete']
    attributes:
        normalization_context:
          groups: ['rating_admin_read']
        denormalization_context:
          groups: ['rating_admin_write']
    properties:
        amounts:
            subresource:
                resourceClass: 'App\Domain\Entity\Prize\Money\Amount'
                collection: true
        currency:
            subresource:
                resourceClass: 'App\Domain\Entity\Currency'
                collection: false

App\Domain\Entity\Prize\Money\Amount:
    collectionOperations: ['get', 'post']
    itemOperations: ['get', 'put', 'delete']
    attributes:
        normalization_context:
          groups: ['rating_admin_read']
        denormalization_context:
          groups: ['rating_admin_write']

App\Domain\Entity\Prize\PointPrize:
    collectionOperations: ['get', 'post']
    itemOperations: ['get', 'put', 'delete']
    attributes:
        normalization_context:
          groups: ['rating_admin_read']
        denormalization_context:
          groups: ['rating_admin_write']

App\Domain\Entity\Rating:
    collectionOperations: ['get', 'post']
    itemOperations: ['get', 'put', 'delete']
    attributes:
        normalization_context:
          groups: ['rating_admin_read']
        denormalization_context:
          groups: ['rating_admin_write']
[issue.tar.gz](https://github.com/api-platform/api-platform/files/2120611/issue.tar.gz)

```
```
App\Domain\Entity\Prize\AbstractPrize:
    attributes:
        id:
            groups: ['rating_admin_read']
        place:
            groups: ['rating_admin_read', 'rating_admin_write']
    discriminator_map:
        type_property: 'discriminator'
        mapping:
            money: 'App\Domain\Entity\Prize\Money\MoneyPrize'
            points: 'App\Domain\Entity\Prize\PointPrize'

App\Domain\Entity\Prize\Money\MoneyPrize:
    attributes:
        wager:
            groups: ['rating_admin_read', 'rating_admin_write']
        amounts:
            groups: ['frontapi', 'rating_admin_read', 'rating_admin_write']

App\Domain\Entity\Prize\Money\Amount:
    attributes:
        amount:
            groups: ['frontapi', 'rating_admin_read', 'rating_admin_write']
        currency:
            groups: ['frontapi', 'rating_admin_read', 'rating_admin_write']

App\Domain\Entity\Prize\PointPrize:
    attributes:
        count:
            groups: ['frontapi', 'rating_admin_read', 'rating_admin_write']

App\Domain\Entity\Rating:
    attributes:
        id:
            groups: ['rating_admin_read']
        type:
            groups: ['frontapi', 'rating_admin_read', 'rating_admin_write']
        name:
            groups: ['frontapi', 'rating_admin_read', 'rating_admin_write']
        description:
            groups: ['frontapi', 'rating_admin_read', 'rating_admin_write']
        prizes:
            groups: ['rating_admin_read', 'rating_admin_write']
        isEnabled:
            groups: ['rating_admin_read', 'rating_admin_write']
        platforms:
            groups: ['rating_admin_read', 'rating_admin_write']
        year:
            groups: ['rating_admin_read', 'rating_admin_write']
        month:
            groups: ['rating_admin_read', 'rating_admin_write']
```
Help me please, I spend second day trying to debug this. The last layer what I found: on reading of yaml files, metadata checks: AbstractPrize contains `count` property, and set to metadata `false` to writable/readable properties.

```
\ApiPlatform\Core\Bridge\Symfony\PropertyInfo\Metadata\Property\PropertyInfoPropertyMetadataFactory::create

$resourceClass: 'App\Domain\Entity\Prize\AbstractPrize'
$name: 'count'
```

Sorry for my english. traumd-dn my skype. I can give you infrormation in more interactive method. Thanks.
