### ISSUE TITLE
Run behat in test environment with the provided docker-compose

### ISSUE THREAD

**Issue by vbourdeix** [api-platform/api-platform#742]
Hello,

I'm struggling to setup my behat tests with an api-platform project that I just created.

My problems are the following :

1. If I run a test with docker-compose exec php vendor/bin/behat, it will use the environment variables of the php container, so it will execute in dev environment. I then added a php-test container in docker-compose. It is a copy of the php container, but it loads another .env.test file and tells it to run in test environment with an sqlite database instead of the postgres one. So far, so good

2. I then run docker-compose exec php vendor/bin/behat again, drop my sqlite database specified for the test environment, and execute my test. The test makes an HTTP POST to my api.
=> I get a "Failed to connect to localhost port 80: Connection refused", which seems logical as it's running from the php-test container. nginx is in the api container.

If I tell behat that the base URL is http://api my queries are run on the api container which runs on the dev environment, whatever I tried. I tried to duplicate the api container to build an api-test container and to tell behat to run queries on api-test, but when debugging from index.php, it revealed that $_SERVER['HTTP_HOST'] was indeed api-test, but gethostname() gave me the container id of the api container, not api-test.

I feel like I'm doing it wrong and that the solution is simple, but I can't find any way to set this up and the documentation [here](https://api-platform.com/docs/distribution/testing/) doesn't help as it doesn't speak about this issue.

I chose to use the full fledged distribution as I felt it would help me using a good docker architecture, but it seems like it gets on my way in the end. I hope you have some tips to share with me so that I can go on.

**Comment by webda2l** [comment]
Hello,

I met some problems last week too about behat testing. Here is my way:

1 - First, keep only one php-docker, with .env file configured for dev (or prod). *It will be able to run your test too*

2.A - Configure your config/packages/test/doctrine.yaml directly with your sqlite db used for test

```
doctrine:
    dbal:
        driver: 'pdo_sqlite'
        charset: 'UTF8'
        url: 'sqlite:///%kernel.cache_dir%/db.sqlite'
```

2.B - Or alternatively, configure your config/packages/doctrine.yaml with default value DATABASE_URL to your sqlite db used for test

```
parameters:
    env(DATABASE_URL): 'sqlite:///%kernel.cache_dir%/db.sqlite'

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_pgsql'
        server_version: '10.3'
        url: '%env(resolve:DATABASE_URL)%'
```

3 - And so, run your commands related to test env, with ```APP_ENV=test``` prerequisite, like:

```
APP_ENV=test bin/console c:c
APP_ENV=test bin/console d:s:d -f
APP_ENV=test bin/console d:s:u -f
APP_ENV=test behat --colors
```

Personally, I use composer scripts, and configure them as:

```
...
    "scripts": {
         ...
        "prepare": [
            "bin/console c:c",
            "bin/console d:d:c --if-not-exists",
            "bin/console d:s:d -f",
            "bin/console d:s:u -f",
            "APP_ENV=test bin/console c:c"
        ],
        "behat": [
            "APP_ENV=test bin/console d:s:d -f",
            "APP_ENV=test bin/console d:s:u -f",
            "APP_ENV=test behat --colors"
        ],
```

to ease:

 ```
docker-compose exec php composer run-script prepare
docker-compose exec php composer run-script behat
```

**Comment by teohhanhui** [comment]
Prepending `APP_ENV=test` is the way to go.

**Comment by vbourdeix** [comment]
Thanks @webda2l for the detailed answer. I used a slightly different approach because I want to reinit my database for each behat scenario in order to keep them independent from their order.

I put a different doctrine config for the test environment and added a hook to my FeatureContext class :
`/**
     * @BeforeScenario
     */
    public function createDatabase()
    {
        $this->schemaTool->dropDatabase();
        $this->schemaTool->createSchema($this->classes);
    }`

I also had an issue with my sqlite database not being accessible when configured in the cache folder, as if it was cleared automatically after each BeforeScenario hook. As soon as I put it elsewhere (in the root project folder for simplicity), I stopped running into "This table doesn't exists" issue.

As it now works for me I will close the issue.

**Comment by geerlingguy** [comment]
Formatting for the above comment:

```php
    /**
     * @BeforeScenario
     */
    public function createDatabase()
    {
        $this->schemaTool->dropDatabase();
        $this->schemaTool->createSchema($this->classes);
    }
```

**Comment by saamorim** [comment]
After a few steps I think I've manage to setup behat+behatch but some errors appear.
To recap:

```
$ docker-compose exec php composer require --dev behatch/contexts behat/mink behat/symfony2-extension behat/mink-browserkit-driver
$ docker-compose exec php vendor/bin/behat -V
$ docker-compose exec php vendor/bin/behat --init
```

Added the `api/behat.yaml` with the content:
```yaml
default:
  calls:
    error_reporting: 16383 # E_ALL & ~E_USER_DREPRECATED
  suites:
    default:
      contexts:
        - FeatureContext: { doctrine: "@doctrine" }
        - Behat\MinkExtension\Context\MinkContext
        - Behatch\Context\RestContext
        - Behatch\Context\JsonContext
  extensions:
    Behat\Symfony2Extension:
      kernel:
        env: 'test'
        debug: 'true'
        bootstrap: "features/bootstrap/bootstrap.php"
        class: "App\\Kernel"
    Behat\MinkExtension:
      base_url: "http://localhost/"
      sessions:
        default:
          symfony2: ~
    Behatch\Extension: ~
```

Added the `api/features/bootstrap/bootstrap.php` with the content
```php
<?php

use Symfony\Component\Dotenv\Dotenv;

// The check is to ensure we don't use .env in production
if (!isset($_SERVER['APP_ENV'])) {
    if (!class_exists(Dotenv::class)) {
        throw new \RuntimeException('APP_ENV environment variable is not defined. You need to define environment variables for configuration or add "symfony/dotenv" as a Composer dependency to load variables from a .env file.');
    }
    (new Dotenv())->load(__DIR__.'/../../.env');
}
```

Change the `api/features/bootstrap/FeatureContext.php` to be:
```php
<?php

use Behat\Behat\Context\Context;
use Behat\Behat\Context\SnippetAcceptingContext;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\ORM\Tools\SchemaTool;
use Behat\Gherkin\Node\PyStringNode;
use Behat\Gherkin\Node\TableNode;

/**
 * Defines application features from the specific context.
 */
class FeatureContext implements Context, SnippetAcceptingContext
{
    /**
     * @var ManagerRegistry
     */
    private $doctrine;
    /**
     * @var SchemaTool
     */
    private $schemaTool;
    /**
     * @var array
     */
    private $classes;

    /**
     * Initializes context.
     *
     * Every scenario gets its own context instance.
     * You can also pass arbitrary arguments to the
     * context constructor through behat.yml.
     */
    public function __construct(ManagerRegistry $doctrine)
    {
        $this->doctrine = $doctrine;
        $manager = $doctrine->getManager();
        $this->schemaTool = new SchemaTool($manager);
        $this->classes = $manager->getMetadataFactory()->getAllMetadata();
    }

    /**
     * @BeforeScenario @createSchema
     */
    public function createDatabase()
    {
        $this->schemaTool->dropSchema($this->classes);
        $this->doctrine->getManager()->clear();
        $this->schemaTool->createSchema($this->classes);
    }
}
```

Finally added the content to the `api/features/book.feature` as stated in https://api-platform.com/docs/distribution/testing

After running `behat`
```
$ docker-compose exec php vendor/bin/behat 
```

got the output:
```
4 scenarios (1 passed, 3 failed)
27 steps (24 passed, 3 failed)
0m0.57s (30.32Mb)
```

All of the failures are due to the ordering of the `id` attribute. Changing the `id`'s to the end fixed the issues
