### ISSUE TITLE
normalization_context seems to not work on a specific ressource operation define in YAML

### ISSUE THREAD

**Issue by ronfroy** [api-platform/api-platform#746]
Hello,

The normalization_context seems to not work on a specific ressource operation define in YAML.

```
resources:
    App\Entity\Sample:
        collectionOperations:
            get:
                method: 'GET'
                filters: ['app.sample.filter.search']
                normalization_context: { groups: ['Sample'] }
                denormalization_context: { groups: ['Sample'] }
            post:
        itemOperations: ['get', 'put', 'delete']
```

Is it implemented? Maybe my config is wrong
