### ISSUE TITLE
401 error in swagger ui with JWT

### ISSUE THREAD

**Issue by robinstraub** [api-platform/api-platform#749]
Hi,

I setup JWT authentication on my project with api-platform and LexikJWTAuthenticationBundle.
I followed the documentation and the JWT authentication is working (I wrote some tests to ensure this).

My issue is when I go to the api main page (`/api`) I get an error `{"code":401,"message":"JWT Token not found"}`.

Here is my security.yaml:
```
security:
    encoders:
        App\Entity\User\BaseUser:
            algorithm: bcrypt

    providers:
        db_provider:
            entity:
                class: App\Entity\User\Teacher
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

```

the api_platform.yml : 
```
api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header

```

If I disable authentication, I can see the Swagger UI, however I obviously need to keep the authentication. Am I missing something? I can generate tokens with curl and once the header is inserted into the request I can get the main page, however I don't have the "Authorize" button the documentation talks about (https://api-platform.com/docs/core/jwt/).
