### ISSUE TITLE
Can't set normalization and denormalization for all operations in YAML configuration

### ISSUE THREAD

**Issue by nik-lampe** [api-platform/api-platform#752]
Hello,

as my app is growing I want to extract the entity configuration from the php files to yaml config files.
This works well for operation configurations and also for normalization/denormalization context *on these operations*.
But I can't get it to work to set these contexts for all operations like I can in the entity annotation.

For example this works:
```
/**
 * @ApiResource(
 *     attributes={
 *      "normalization_context"={"groups"={"plan_read"}},
 *      "denormalization_context"={"groups"={"plan_write"}},
 *     }))
 * @ORM\Entity()
 */
class Plan
```

This works too (in a yaml file):
```
App\Entity\Plan:
    collectionOperations:
        post:
            denormalization_context:
                groups: ['plan_write']
```

But this doesn't (also in a yaml file):
```
App\Entity\Plan:
    attributes:
        normalization_context: { groups: ['plan_read']}
        denormalization_context: { groups: ['plan_write']}
```

Is this even supported? I can't find anything in the docs.

**Comment by soyuka** [comment]
```
App\Entity\Plan:
    attributes:
        normalization_context: { groups: ['plan_read']}
        denormalization_context: { groups: ['plan_write']}
```

This works here:

```
    Api\Entity\BlogPost:
        attributes:
            normalization_context: {'groups': ['packaging.item', 'product.item']}
            denormalization_context: {'groups': ['packaging.save']}
```

**Comment by nik-lampe** [comment]
I still can't get it to work, just came upon this again.

I have created some sample code here:
https://github.com/nik-lampe/api-platform-serialization-group

I have just created the example project from here: https://api-platform.com/docs/distribution
Then I added the resources.yaml File and added it in the api_platform.yaml configuration.

When I set the normalization group on the operation it works, when I set it on the whole entity it does not work in yaml.

```
App\Entity\Book:
    # collectionOperations:
    #     get:
    #         normalization_context:
    #             groups: ['read']
  attributes:
    normalization_context: {'groups': ['read']}
    denormalization_context: {'groups': ['write']}
```

I even copy pasted @soyuka's code. Am I missing something?
