### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by antonioperic** [api-platform/api-platform#760]
HI, i am using symfony4 plus fosuser bundle and i have problem with login, every time i try to login my controller is executed and nothing is happening. I tried, custom user provider, same problem

here is my fos config

```
api_login_check:
    path: /v1/login_check
    controller: App\Controller\AuthenticationController::login
#    methods: ['POST']

```

```
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class AuthenticationController
{
    /**
     * @codeCoverageIgnore
     */
    public function  login(Request $request, AuthenticationUtils $authenticationUtils)
    {
        return new Response();
    }
}

```

```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            provider: fos_userbundle
            json_login:
                check_path: /login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            pattern:   ^/
            provider: fos_userbundle
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }

```
