### ISSUE TITLE
No route found for "OPTIONS" method not allowed

### ISSUE THREAD

**Issue by Ronnie-J** [api-platform/api-platform#768]
Hi guys.

I am running on api-platform v2.3.0.

I am having issues with CORS headers.
When I try and run the following request against my API

```
OPTIONS /myroute HTTP/1.1
Host: localhost:8080
Access-Control-Request-Headers: authorization,content-type
Access-Control-Request-Method: GET
Cache-Control: no-cache
```

I get `No route found for "OPTIONS /myroute": Method Not Allowed (Allow: GET, PUT, DELETE)`

```
nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_methods: ['PUT', 'GET', 'DELETE', 'OPTIONS']
        allow_headers: ['authorization', 'accept', 'content-type']
        expose_headers: []
        max_age: 3600
    paths:
        '^/': ~
```

<img width="782" alt="screen shot 2018-07-17 at 15 08 27" src="https://user-images.githubusercontent.com/7793111/42819313-75f316e8-89d3-11e8-94bd-68a590ec96f2.png">

Any idea why?
