### ISSUE TITLE
Question: how to implement custom child entity routes?

### ISSUE THREAD

**Issue by ghettovoice** [api-platform/api-platform#776]
Hi, first of all thank you for the awesome lib, it really very helpfull :+1: 
I'm trying to implement parent/child entity routes, something like this:
```
  api_dictionaries_get_collection                  GET      ANY      ANY    /api/dictionaries.{_format}                                
  api_dictionaries_post_collection                 POST     ANY      ANY    /api/dictionaries.{_format}                                
  api_dictionaries_get_item                        GET      ANY      ANY    /api/dictionaries/{id}.{_format}                           
  api_dictionaries_put_item                        PUT      ANY      ANY    /api/dictionaries/{id}.{_format}                           
  api_dictionary_records_records_get_collection    GET      ANY      ANY    /api/dictionaries/{dictionaryId}/records.{_format}         
  api_dictionary_records_records_post_collection   POST     ANY      ANY    /api/dictionaries/{dictionaryId}/records.{_format}         
```
I get routes above with this YAML configuration:
```yml
resources:
    App\Model\Dictionary\Dictionary:
        collectionOperations:
            get:
                normalization_context: 
                    groups: [dictionary-read]
            post:
                denormalization_context: 
                    groups: [dictionary-create]
        itemOperations:
            get:
                normalization_context: 
                    groups: [dictionary-read]
            put:
                denormalization_context: 
                    groups: [dictionary-update]
        properties:
            id:
                identifier: true
                    
    App\Model\Dictionary\DictionaryRecord:
        collectionOperations:
            records_get:
                method: GET
                path: /dictionaries/{dictionaryId}/records.{_format}
                controller: App\UI\Controller\Dictionary\GetDictionaryRecords
                defaults:
                    _api_receive: false
                normalization_context:
                    groups: [dictionary-record-read]
                swagger_context:
                    parameters:
                        - name: dictionaryId
                          type: string
                          in: path
                          required: true
                          description: Dictionary UUID
            records_post:
                method: POST
                path: /dictionaries/{dictionaryId}/records.{_format}
                controller: App\UI\Controller\Dictionary\CreateDictionaryRecord
                defaults:
                    _api_receive: false
                normalization_context:
                    groups: [dictionary-record-read]
                denormalization_context:
                    groups: [dictionary-record-create]
                swagger_context:
                    parameters:
                        - name: dictionaryId
                          type: string
                          in: path
                          required: true
                          description: Dictionary UUID
        itemOperations: []        
        properties:
            code:
                identifier: true
```
In the controller, for example GetDictionaryRecords, I have something like this:
```php
final class GetDictionaryRecords
{
    /**
     * @var DictionaryCollection
     */
    private $dictionaryCollection;

    public function __construct(
        DictionaryCollection $dictionaryCollection
    ) {
        $this->dictionaryCollection = $dictionaryCollection;
    }

    public function __invoke(string $dictionaryId): iterable
    {
        $dictionary = $this->dictionaryCollection->findById($dictionaryId);

        return $dictionary->getRecords();
    }
}
```
But this doesn't work due to using of custom route parameter `{dictionaryId}`, it falls with exception when trying to generate IRI route for collection:
```json
{
    "@context": "/api/contexts/Error",
    "@type": "hydra:Error",
    "hydra:title": "An error occurred",
    "hydra:description": "Unable to generate an IRI for \"App\\Model\\Dictionary\\DictionaryRecord\".",
    "trace": [
        {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "",
            "file": "/srv/server/vendor/api-platform/core/src/Bridge/Symfony/Routing/IriConverter.php",
            "line": 142,
            "args": []
        },
        {
            "namespace": "ApiPlatform\\Core\\Bridge\\Symfony\\Routing",
            "short_class": "IriConverter",
            "class": "ApiPlatform\\Core\\Bridge\\Symfony\\Routing\\IriConverter",
            "type": "->",
            "function": "getIriFromResourceClass",
            "file": "/srv/server/vendor/api-platform/core/src/Hydra/Serializer/CollectionNormalizer.php",
            "line": 83,
            "args": [
                [
                    "string",
                    "Sv\\App\\Model\\Dictionary\\DictionaryRecord"
                ]
            ]
        },
        {
            "namespace": "ApiPlatform\\Core\\Hydra\\Serializer",
            "short_class": "CollectionNormalizer",
            "class": "ApiPlatform\\Core\\Hydra\\Serializer\\CollectionNormalizer",
            "type": "->",
            "function": "normalize",
            "file": "/srv/server/vendor/api-platform/core/src/Hydra/Serializer/PartialCollectionViewNormalizer.php",
            "line": 47,
            "args": [
                [
                    "array",
                    []
                ],
                [
                    "string",
                    "jsonld"
                ],
                [
                    "array",
                    {
                        "groups": [
                            "array",
                            [
                                [
                                    "string",
                                    "dictionary-record-read"
                                ]
                            ]
                        ],
                        "collection_operation_name": [
                            "string",
                            "records_get"
                        ],
                        "operation_type": [
                            "string",
                            "collection"
                        ],
                        "resource_class": [
                            "string",
                            "Sv\\App\\Model\\Dictionary\\DictionaryRecord"
                        ],
                        "request_uri": [
                            "string",
                            "/api/dictionaries/3ded86b6-7bbb-4eae-8573-0b2a742a45b2/records"
                        ],
                        "uri": [
                            "string",
                            "http://localhost:8080/api/dictionaries/3ded86b6-7bbb-4eae-8573-0b2a742a45b2/records"
                        ],
                        "resources": [
                            "object",
                            "ApiPlatform\\Core\\Serializer\\ResourceList"
                        ],
                        "jsonld_has_context": [
                            "boolean",
                            true
                        ],
                        "api_sub_level": [
                            "boolean",
                            true
                        ]
                    }
                ]
            ]
        },
....
```
POST route also doesn't work with the same error related to IRI converter but from Http purge listener.
From here https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Routing/IriConverter.php#L140 I see that collection routes expected to be without any route parameters.
Subresource feature also doesn't help because as I understand from other issues there is no support for POST method for subresources.
So what is the common way to implement such endpoints? Should I implement custom collection normalizer and IRI converter? Or there is another more convenient solution?
Thanks!
