### ISSUE TITLE
Is it possible to define access_control in yaml config?

### ISSUE THREAD

**Issue by mikemilano** [api-platform/api-platform#785]
Regarding security: s://api-platform.com/docs/core/security

There is no YAML example. Is it possible to define access_control in YAML?
```
/**
 * Secured resource.
 *
 * @ApiResource(
 *     attributes={"access_control"="is_granted('ROLE_USER')"},
 *     collectionOperations={
 *         "get",
 *         "post"={"access_control"="is_granted('ROLE_ADMIN')"}
 *     },
 *     itemOperations={
 *         "get"={"access_control"="is_granted('ROLE_USER') and object.owner == user"}
 *     }
 * )
 * @ORM\Entity
 */
class Book
{
...
```

**Comment by soyuka** [comment]
Could you try this?

```yaml
    App\Entity\Book:
        collectionOperations:
            get:
                method: 'GET'
                access_control: 'is_granted("ROLE_ADMIN")'
        attributes:
            access_control: 'is_granted("ROLE_USER")'
```
