### ISSUE TITLE
POST operation started to fail, unless content-type is ld+json

### ISSUE THREAD

**Issue by kermorgant** [api-platform/api-platform#787]
Hi,

I've been using a DTO to handle user registration from a VueJS webapp.

The operation is configured like this

```yaml
    App\Application\Service\User\UserRegister\UserRegisterRequest:
        itemOperations: {}
        collectionOperations:
            post:
                method: 'POST'
                path: '/user/register'
```

I've been testing the endpoint with a payload like this

```bash
POST http://localhost:8080/user/register
content-type: application/json

{
  "email": "email@ran.dom",
  "password": "123456",
  "passwordRepeat": "123456"
}
```

This fails with this 

>  "hydra:description": "Cannot validate values of type \"NULL\" automatically. Please provide a constraint.",

During debug, I noticed that in ``ApiPlatform\Core\Validator\EventListener\ValidateListener`` at line 55, ``$data`` is null (``$data`` being set like this ``$data = $event->getControllerResult();`` )

However, the same endpoint works well when I specify ``content-type: application/ld+json``

This used to work without this change, but I've not found where it stems from. I've tested with api-platform/core 2.1, 2.2 and 2.3 with the same result (originally installed from api-platform standard distribution with php 7.2 linux + docker setup)

Any idea about this ?
