### ISSUE TITLE
Property and @Groups() annotation to YAML

### ISSUE THREAD

**Issue by mikemilano** [api-platform/api-platform#794]
Given the entity below, how do I move the `id` and `name`, along with their annotated serialization groups, into the API Platform resource YAML (defined below the entity)?

I'll create a PR for the docs project once I get this working.

src/Entity/Org.php
```php
<?php declare(strict_types=1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrgRepository")
 */
class Org
{
    /**
     * @var int
     *
     * @Groups({"read"})
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @Groups({"read", "write"})
     * @ORM\Column(type="string", length=128, unique=true, nullable=false)
     */
    private $name;

   // ...
```

config/api_platform/resources/Org.yaml
```yaml
resources:
    App\Entity\Org:
        attributes:
            normalization_context:
                groups: ['read']
            denormalization_context:
                groups: ['write']
        collectionOperations:
            get: ~
            post: ~
        itemOperations:
            get: ~
            put: ~
```

**Comment by borNfreee** [comment]
I agree this is so unclear from the docs.

You should move your annotations from 1 place (entity) to 2 files:

The first one is `config/api_platform/resources/Org.yaml` for API-platform as you mentioned above, the second one is a *separate* file for Serializer component, e.g. `./config/serializer/Org.yml` and there you would add:

```yaml
App\Entity\Org:
    attributes:
       id:
            groups: ['read']
       name:
            groups: ['read', 'write']
```
