### ISSUE TITLE
How can i ignore relations in Entity

### ISSUE THREAD

**Issue by e1sep0** [api-platform/api-platform#809]
Hello, i want to get only several params, but i can`t change the Entity
```
resources:
    Entity\Hotel:
      itemOperations:
        get: ~
      collectionOperations:
        get:
          filters:
            - 'hotel.name_filter'
            - 'hotel.search_filter'
            - 'hotel.trash_filter'
      attributes:
        normalization_context:
          groups: ['hotel']
```

```
Entity\Hotel:
  attributes:
    id:
      groups: ['hotel']
    name:
      groups: ['hotel']
    city:
      groups: ['hotel']
    category:
      groups: ['hotel']
```

But Entity has too much relations:
```
class Hotel
{
    /**
     * @ORM\Id
     * @ORM\Column(name="id",type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @var integer
     */
    private $id;

    /**
     * @ORM\Column(length=255)
     * @Gedmo\Translatable
     * @var string
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity="Uts\Dictionary\GeoBundle\Entity\City")
     * @var GEO\City
     */
    private $city;

    /**
     * @ORM\ManyToOne(targetEntity="HotelCategory")
     * @var HotelCategory
     */
    private $category;

    /**
     * @ORM\ManyToOne(targetEntity="HotelChain")
     * @var HotelChain
     */
    private $chain;

    /**
     * @ORM\ManyToMany(targetEntity="HotelTheme",fetch="EXTRA_LAZY")
     * @ORM\JoinTable(name="dictionary.rel_hotel_theme",
     *      joinColumns={@ORM\JoinColumn(name="hotel_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="theme_id", referencedColumnName="id")}
     *      ) 
     * @var  ArrayCollection|HotelTheme[]
     */
    private $themes;

    /**
     * @ORM\ManyToOne(targetEntity="HotelType")
     * @var HotelType
     */
    private $type;

    /**
     * @ORM\OneToMany(targetEntity="HotelPhoto",cascade={"all"},orphanRemoval=true,mappedBy="hotel",fetch="EXTRA_LAZY")
     * @var ArrayCollection;
     */
    private $photos;

    /**
     * @ORM\OneToMany(targetEntity="HotelRoom",cascade={"all"},orphanRemoval=true,mappedBy="hotel",fetch="EXTRA_LAZY")
     * @var ArrayCollection|HotelRoom[];
     */
    private $rooms;

    /**
     * @ORM\ManyToMany(targetEntity="Uts\Dictionary\GeoBundle\Entity\Location",fetch="EXTRA_LAZY")
     * @ORM\JoinTable(name="dictionary.rel_hotel_location",
     *      joinColumns={@ORM\JoinColumn(name="hotel_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="location_id", referencedColumnName="id")}
     *      )
     * @var ArrayCollection;
     */
    protected $locations;

    /**
     * @ORM\ManyToMany(targetEntity="Uts\Dictionary\GeoBundle\Entity\Underground",fetch="EXTRA_LAZY")
     * @ORM\JoinTable(name="dictionary.rel_hotel_underground",
     *      joinColumns={@ORM\JoinColumn(name="hotel_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="underground_id", referencedColumnName="id")}
     *      )
     * @var ArrayCollection;
     */
    protected $undergrounds;

    /**
     * @ORM\OneToMany(targetEntity="HotelFacilityDescription", mappedBy="hotel", fetch="EXTRA_LAZY", cascade={"all"}, orphanRemoval=true)
     * @var ArrayCollection|HotelFacilityDescription[];
     */
    protected $hotelFacilityDescriptions;

    /**
     * @ORM\OneToMany(targetEntity="HotelRoomAmenityDescription", mappedBy="hotel", fetch="EXTRA_LAZY", cascade={"all"}, orphanRemoval=true)
     * @var ArrayCollection|HotelRoomAmenityDescription[];
     */
    protected $roomAmenityDescriptions;

    /**
     * @ORM\OneToOne(targetEntity="HotelDetails",mappedBy="hotel",cascade={"all"},orphanRemoval=true,fetch="EXTRA_LAZY")
     * @var HotelDetails
     */
    private $details;

    /**
     * @ORM\OneToOne(targetEntity="HotelTripAdvisorRating",mappedBy="hotel",cascade={"all"},orphanRemoval=true,fetch="EXTRA_LAZY")
     * @var HotelTripAdvisorRating
     */
    private $tripAdvisorRating;

    /**
     * @ORM\OneToOne(targetEntity="Uts\Dictionary\HotelBundle\Entity\AbstractHotelAdditionalDetails",mappedBy="hotel",cascade={"all"},orphanRemoval=true,fetch="EXTRA_LAZY")
     * @var AbstractHotelAdditionalDetails|null
     */
    private $additionalDetails;
```

And for getting only id and name, too much SQL requests are sended. How can i ignore this ORM Relation and get only id and name from hotels?
Thank you

**Comment by soyuka** [comment]
Looks correct, maybe a cache issue? Serialization groups are definitely the way to go here.

**Comment by soyuka** [comment]
Is eager loading off for some reason?

**Comment by e1sep0** [comment]
no, eager is enabled in api_platform config
```
eager_loading:
        # To enable or disable eager loading.
        enabled: true

        # Fetch only partial data according to serialization groups.
        # If enabled, Doctrine ORM entities will not work as expected if any of the other fields are used.
        fetch_partial: true

        # Max number of joined relations before EagerLoading throws a RuntimeException.
        max_joins: 30

        # Force join on every relation.
        # If disabled, it will only join relations having the EAGER fetch mode.
        force_eager: true
```
