### ISSUE TITLE
[Question] How to change "normalization_context" from GET parameter

### ISSUE THREAD

**Issue by byhoratiss** [api-platform/api-platform#812]
I'm aware of normalization_context serialization groups, but I was wondering how could I use different serialization groups in collection or item operations by a GET parameter, something that a Client (Javascript, PHP, Java) could use.

Getting collection like:
- GET /posts?groups[]=foo&groups[]=bar
Expected result: "post" collection including "foo" and "bar" groups defined within the given Resource.

- GET /post/123?groups[]=foo&groups[]=bar
Expected result: "post" item including "foo" and "bar" groups.

- GET /post/123
Expected result: "post" item using "normalization_context" just like it works now.

Any ideas? Am I missing something?
Thank you!

**Comment by antograssiot** [comment]
isn't that already what the [Group Filter](https://api-platform.com/docs/core/filters/#group-filter)  does ?

**Comment by byhoratiss** [comment]
@antograssiot Thank you! I was missing that.
Can't find or figure out how to configure the filter in YML format instead of Annotations

**Comment by byhoratiss** [comment]
I'll answer my question for other users.
To enable the Group Filter as defined in the docs (https://api-platform.com/docs/core/filters#group-filter) but using YML format you should first register a Service, because the @ApiFilter annotation just do that.

So, here is an example of the service definition:
```
services:
    my_entity.my_filter_name:
        parent: 'api_platform.serializer.group_filter'
        arguments: [ 'groups', true, null ] # parameters for __construct() method
        tags: [ 'api_platform.filter' ]
```

And this service now can be used as a Filter, just like the docs establishes: https://api-platform.com/docs/core/filters#basic-knowledge
