### ISSUE TITLE
GraphQL question about configuration security for collection and item

### ISSUE THREAD

**Issue by antonioperic** [api-platform/api-platform#813]
hi, 
i have this kind of configuration for my resource

```
App\Entity\SomeEntity:
    graphql:
            query:
                access_control: 'has_role("ROLE_ADMIN") or (has_role("ROLE_USER") and object.getUser() == user)'
            delete:
                access_control: 'has_role("ROLE_ADMIN") or (has_role("ROLE_USER") and object.getUser() == user)'
            update:
                access_control: 'has_role("ROLE_ADMIN") or (has_role("ROLE_USER") and object.getUser() == user)'
            create:
                access_control: 'has_role("ROLE_ADMIN") or (has_role("ROLE_USER") and object.getUser() == user)'
```

it is logical that this query won't work (it will throw an error) for collections. my question is: is it possible to differentiate collection from an item in graphql setup.

P.S. I know this is possible to solve with doctrine extension, but it will be nice if it is possible to use configuration 

thnx
