### ISSUE TITLE
dynamic api metadata

### ISSUE THREAD

**Issue by videni** [api-platform/api-platform#823]
apiplatform gives us a very good approach to write UI based on api metadata, but currently the metadata is static,  in a complex system , the metadata is dynamic for different user with different permission. can we expand the further? 

## 1.  Dynamic form fields  metadata. 
 this means the metadata we use to construct a form is dynamic. when a user try to update a resource, we need to know what form fields the use have access.  in traditional way, we can create a dynamic form using Symfony form, and use the form to build user interface. but now , we use API. what is the appropriate  way to get the dynamic form fields metadata? 
maybe can build the metadata based on Symfony FormView,  when user try to update, we fetch the FormView first, then use the FormView data structure to build user interface  at client side.

## 2. Show  available actions for  a user.
 I created a issue [can we add api relation like BazingaHateoasBundle](https://github.com/api-platform/api-platform/issues/778), let us add the links to 'GET' operation, so we can show  available actions for current user. I did this for HAL in my project, it would be great if it is native in apiplatform.

```
  get:
                method: 'GET'
                path: '/admin/advertisements'
                access_control: is_granted('app_advertisement_view')
                acl_enabled: true
                format: jsonhal
                fields_acl:
                    columns:
                        - name: organization
                          data_name: o.organization
                relations:
                        - rel: publish
                          access_controll: is_granted('app_advertisement_publish') && workflow_can(object, 'publish')
                          href:
                                route: api_advertisement_publish
                                parameters:
                                    id: object.getId()
```
