### ISSUE TITLE
How can we forbidden postman?

### ISSUE THREAD

**Issue by paoloBirdOffice** [api-platform/api-platform#835]
Hello,
I'm using Nelmio wit api platform,
And i try to block all the request execpet from specific servor,
My probleme is that i can still do request with postman, i set the allow origin but post man can still call it.
Thank alot
Paolo

```
nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: [ 'http://blabla.com*$']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': ~
```
