### ISSUE TITLE
don't force use to specify item route for an entity

### ISSUE THREAD

**Issue by videni** [api-platform/api-platform#839]
sometimes a simple entity is not necessary to have an item operation,
sometimes an entity have two item operations ,one for admin ,one for customer. at this situation, it should let the developer to specify which one. 

api-platform can handle the general case, but also should add the flexibility.

@dunglas ,are you willing to add API relation to api-platform please? I created issue[api relation](https://github.com/api-platform/api-platform/issues/778) a  month ago? in my case API relation customization is very urgent.

**Comment by dunglas** [comment]
You can already enable and disable operations you want, and create "custom" ones: https://api-platform.com/docs/core/operations/#enabling-and-disabling-operations
Isn't it what you want?

**Comment by videni** [comment]
@dunglas , nope, my situation is more complex.  for customer, I only want to show api_account_order_view in links relation, but for admin , I want to show api_admin_order_view, both routes are added to Order resource  item operation,  their paths are different.

**Comment by videni** [comment]
@dunglas , now I am trying to disable  api-platfom links relation, use "willdurand/hateoas" instead.

**Comment by dunglas** [comment]
What do you mean by "links relations"? The normalizer decorator is a service, so you can inject the SecurityContext in, retrieve the role of the current user and add the link accordingly.

**Comment by videni** [comment]
@dunglas it would be nice if we can add relation like this, so we don't need to write extra normalizer for every entity.
```
App\AppBundle\View\OrderView:
    relations:
        - rel: self
          href:
            route: api_shop_account_order_view
            parameters:
                code: expr(object.getId())
                version: 1
          exclusion:
            groups: [Details]

```

**Comment by videni** [comment]
@dunglas , only get operation need item operation, it is best to allow us to specify it like this
```
App\Bundle\OrderBundle\Entity\Order:
    collectionOperations:
            get:
                path: '/admin/orders'
                access_control: is_granted('app_order_view')
                force_eager: false
                normalization_context:
                    groups: [ "Details"]
                    enable_max_depth: true
                iri: 'api_orders_get_item'
    itemOperations:
            get:
                path: '/admin/orders/{id}'
                access_control: is_granted('app_order_view')
```
