### ISSUE TITLE
[v2.0.0-alpha.1] The parent definition "api.resource" [...] does not exist

### ISSUE THREAD

**Issue by bpolaszek** [api-platform/api-platform#84]
Hello,

Perfectly new to ApiPlatform, I wanted to give it a try, starting with the latest v2.0.0-alpha.1 release (which is, as its name states, not stable, I know that).

I just created a simple AppBundle\Entity\Offer class like this:
```php
namespace AppBundle\Entity;

class Offer {

    protected $duration = 3600;

    /**
     * @return int
     */
    public function getDuration() {
        return $this->duration;
    }

    /**
     * @param int $duration
     * @return $this - Provides Fluent Interface
     */
    public function setDuration($duration) {
        $this->duration = $duration;
        return $this;
    }

}
```

And followed the instructions in the doc to map this entity to the whole "resource" scope:
```yml
services:
    resource.offer:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Offer" ]
        tags:
            - { name: "api.resource" }
```

Now when I try to access http://localhost:8000/offer here's the exception I get:
```
RuntimeException in ResolveDefinitionTemplatesPass.php line 100:
The parent definition "api.resource" defined for definition "resource.offer" does not exist.
```

It looks like we're trying to override an existing api.resource service, (or an api_platform.resource service with the new notation, if I understand well), but there's no such service provided actually.

Is there a new behavior for mapping entities? Or is it just my brain running out of coffee? ^^

Thanks,
Ben
