### ISSUE TITLE
sphinx filter

### ISSUE THREAD

**Issue by karser** [api-platform/api-platform#86]
Hello @dunglas, I implemented api filiter based on sphinx. I'm forcing page and count parameters to 1 and 999 accordingly in order to obtain all ids from sphinx and then pass them to QueryBuilder.
Is it a good approach? What's your opinion on this implementation? 

``` php
class FooSphinxFilter implements FilterInterface
{
    /** @var SphinxSearchEngine */
    private $engine;

    /**
     * @param SphinxSearchEngine $engine
     */
    public function __construct($engine)
    {
        $this->engine = $engine;
    }


    public function apply(ResourceInterface $resource, QueryBuilder $queryBuilder, Request $request)
    {
        $searchRequest = $this->engine->createRequest($request);
        $searchRequest->setStartPage(1);
        $searchRequest->setCount(999);
        $result = $this->engine->execute($searchRequest);
        $ids = $result->getResults();
        $alias = $queryBuilder->getAllAliases()[0];
        $queryBuilder->andWhere($queryBuilder->expr()->in($alias.'.id', ':sphinx_ids'))
            ->setParameter('sphinx_ids', $ids);
    }

    public function getDescription(ResourceInterface $resource)
    {
        return [
            'count' => ['property' => 'count', 'type' => 'string', 'required' => 'false'],
            'page' => ['property' => 'page', 'type' => 'string', 'required' => 'false'],
            'orderBy' => ['property' => 'orderBy', 'type' => 'string', 'required' => 'false'],
        ];
    }
}
```

``` yml
services:
    resource.foo:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Foo" ]
        calls:
            -      method:    "initFilters"
                   arguments: [ [ "@resource.foo.sphinx_filter"] ]
        tags:      [ { name: "api.resource" } ]

    resource.foo.sphinx_filter:
        class: AppBundle\ApiFilter\FooSphinxFilter
        arguments: ["@search.foo.engine.sphinx"]
```
