### ISSUE TITLE
Disable Swagger on prod results in "Serialization for the format html is not supported"

### ISSUE THREAD

**Issue by siewert87** [api-platform/api-platform#870]
Hey,

I changed the route for swagger_ui to /docs. 

```yaml
swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui
```

On prod I disabled swagger:

```yaml
api_platform:
    enable_swagger: false
```

However, when requesting /docs on prod I get an 500 with the following message:

```[2018-10-18 13:31:21] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Serializer\Exception\NotEncodableValueException: "Serialization for the format html is not supported" at /var/www/html/vendor/symfony/serializer/Serializer.php line 107 {"exception":"[object] (Symfony\\Component\\Serializer\\Exception\\NotEncodableValueException(code: 0): Serialization for the format html is not supported at /var/www/html/vendor/symfony/serializer/Serializer.php:107)"} []```

Has anybody ever stumbled across it and knows how to get rid of that?

Best,
Christian

**Comment by siewert87** [comment]
I also disabled docs on prod and it's working now:

`enable_docs: false`

**Comment by cve** [comment]
I have the same result even with enable_docs: false

**Comment by tonyellow** [comment]
I also have the same result with both to false

**Comment by christiansiewert** [comment]
At that time I had deactivated the entry point because I don't need it, so the request on `prod` returns a 404 and on `dev` it returns the default symfony welcome page.

`config/packages/api_platform.yaml:`

```yaml
    api_platform:
        enable_entrypoint: false
        enable_docs: false
        enable_swagger_ui: false
        enable_re_doc: false
```

`config/packages/dev/api_platform.yaml:`

```yaml
    api_platform:
        enable_docs: true
        enable_swagger_ui: true
        enable_re_doc: true
```

```bash
christian@E6240T:~foo$ docker-compose exec php bin/console debug:router

 ---------------------------------------- -------- -------- ------ ---------------------------
  Name                                     Method   Scheme   Host   Path 
 ---------------------------------------- -------- -------- ------ ---------------------------
  api_doc                                  ANY      ANY      ANY    /docs.{_format}
```
