### ISSUE TITLE
[YAML] Restricting accept types per resource operation

### ISSUE THREAD

**Issue by tezvi** [api-platform/api-platform#884]
Hi guys,

Since I'm mostly using yaml for resource definition I'd like to define which formats are valid per resource in YAML file instead of using annotations. 
Something like this:

```
App\Entity\Book:
   collectionOperations:
        get:
            attributes:
                formats:
                    excel: ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
```

The annotation approach is described here https://api-platform.com/docs/core/content-negotiation/#enabling-additional-formats-on-a-specific-resourceoperation

```
<?php
// api/src/Entity/Book.php

namespace App\Entity;

/**
 * @ApiResource(attributes={"formats"={"xml", "jsonld", "csv"={"text/csv"}}})
 */
class Book
{
    // ...
}
```

Is that possible in yaml configuration?

**Comment by antograssiot** [comment]
It should work indeed as it uses attributes.

if you are in an operation I think, the correct syntax is.
```
App\Entity\Book:
  collectionOperations:
    get:
      formats:
        excel: ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
```

If it is for every operation, then it is like in the example 

```
App\Entity\Book:
  attributes:
    formats:
      excel: ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet']
```

**Comment by tezvi** [comment]
Thanks for examples. It seems it does not work. I would expect that resource is available only for accept formats defined with formats yaml property (excel in example). However, I can still request json-ld, but HTTP 406 should be returned instead.

**Comment by antograssiot** [comment]
I can't reproduce your issue. I took a fresh install with the Greeting entity.
After clearing the cache, the

I've declared the resource like this:
```yaml
# api/config/api_platform/resources.yaml
resources:
    App\Entity\Greeting:
        collectionOperations:
            get:
                formats:
                    xml: ['text/xml'] # works also with "text/html"
        attributes:
            formats:
               0: 'jsonld' # already existing format in the config
               csv: 'text/csv'
```

My format config looks like:
```yaml
api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity', '%kernel.project_dir%/config/api_platform']
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
