### ISSUE TITLE
The swagger normalizer does not detect overridden operation format attribute

### ISSUE THREAD

**Issue by tezvi** [api-platform/api-platform#886]
Sorry for opening a new issue for related problem, the previous one was already closed.

_Originally posted by @antograssiot in https://github.com/api-platform/api-platform/issues/884#issuecomment-435647395_

The swagger normalizer does not detect overridden operation format attribute, instead I have to explicitly define swagger_context produces attribute to use the SwaggerUI with new format type. 

```
resources:
    App\Entity\Greeting:
        collectionOperations:
            get:
                formats:
                    xml: ['text/xml'] # works also with "text/html"
                    excel: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' # new format
            swagger_context:
                produces:
                    - 'text/xml'
                    - 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
```

My example format config looks like:

```
api_platform:
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']
```

If I don't define swagger_context produces attribute manually the Swagger is being rendered with api_platform formats, ie. missing excel content type and adding operation formats that should be unsupported.

Is this by design or am I doing something wrong?
