### ISSUE TITLE
POST request doesn't work

### ISSUE THREAD

**Issue by zacrasta** [api-platform/api-platform#89]
When I am trying to POST a request it's treated as GET and returns me GET response.

***API-Platform Version***
```
dunglas/api-bundle                   v1.0.1  JSON-LD / Hydra REST API for Symfony
dunglas/php-property-info            v0.2.3  Retrieve type and description of PHP properties using various 
```
This is the response with is actually same as GET request response 
[response.txt](https://github.com/api-platform/api-platform/files/281886/response.txt)

***Headers***
Content-Type : application/json

***URL:Parameters  using x-www-form-urlencoded***   (tried other options using POST MAN app same result :|   )
```
_format:json
access_token:ZGMwMTE1OGNhZmMwZjM5YTM0ZjkwZDQyNzc5ZWM2NTdiMzQ5YzQxOGI1Y2U3YmQzMmI4NzY4MzM0YTc5MDQ2NQ 
```
***Body Parameters*** 
```
provider:/api/v1/providers/1
state:ACTIVE
name:EventName
dateEnd:2016-05-27T23:00:00.000Z
```
**Here is my entity:**

```php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Event
 *
 * @ORM\Table(name="event")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\EventRepository")
 */
class Event
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     * @Assert\NotBlank(message="Please enter event name.")
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="state", columnDefinition="ENUM('ACTIVE', 'FINISHED')")
     * @Assert\NotBlank(message="Please enter event state.")
     */
    private $state;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="date_end", type="datetime")
     * @Assert\NotBlank(message="Please enter event date end.")
     * @Assert\DateTime(message="Please enter a valid event date end.")
     */
    private $dateEnd;

    /**
     * @ORM\ManyToOne(targetEntity="Provider")
     * @ORM\JoinColumn(name="provider_id", referencedColumnName="id")
     * @Assert\NotBlank(message="Please enter a provider.")
     */
    private $provider;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Event
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set state
     *
     * @param string $state
     *
     * @return Event
     */
    public function setState($state)
    {
        $this->state = $state;

        return $this;
    }

    /**
     * Get state
     *
     * @return string
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     * Set dateEnd
     *
     * @param \DateTime $dateEnd
     *
     * @return Event
     */
    public function setDateEnd($dateEnd)
    {
        $this->dateEnd = $dateEnd;

        return $this;
    }

    /**
     * Get dateEnd
     *
     * @return \DateTime
     */
    public function getDateEnd()
    {
        return $this->dateEnd;
    }

    /**
     * Set provider
     *
     * @param \AppBundle\Entity\Provider $provider
     *
     * @return Event
     */
    public function setProvider(\AppBundle\Entity\Provider $provider = null)
    {
        $this->provider = $provider;

        return $this;
    }

    /**
     * Get provider
     *
     * @return \AppBundle\Entity\Provider
     */
    public function getProvider()
    {
        return $this->provider;
    }
}
```
**Here I declared services:**

```yaml
services:
    # Event active
    resource.event.filter:
        parent:    "api.doctrine.orm.search_filter"
        arguments: [ { 'name': 'partial' , "state": 'exact'} ]

    # Event date filter
    resource.event.date_filter:
        parent:    "api.doctrine.orm.date_filter"
        arguments: [ { "dateEnd": ~ } ]

    # event CRUD
    resource.event:
        parent:    "api.resource"
        arguments: [ 'AppBundle\Entity\Event' ]
        calls:
            -      method:    "initFilters"
                   arguments: [ [ "@resource.event.filter", "@resource.event.date_filter", "@resource.general.order_filter" ] ]
        tags:      [ { name: "api.resource" } ]

    event_data_provider:
        parent: "api.doctrine.orm.data_provider"
        class: ApiBundle\DataProvider\Event
        tags:  [ { name: "api.data_provider", priority: 1 } ]
        calls:
            - [setToken, ['@security.token_storage']]
            - [setRequest, ['@request_stack']] 
 ```

 Any help would be really appreciated.
