### ISSUE TITLE
Error 502 on some api routes "upstream sent too big header while reading response header from upstream"

### ISSUE THREAD

**Issue by sushicodeur** [api-platform/api-platform#890]
Hello, 

i've got 502 errors on some routes of my api on my dev machine running api-platform on docker.

The logs shows this :

```
api     | 2018/11/12 13:14:09 [error] 7#7: *6 upstream sent too big header while reading response header from upstream, client: 172.18.0.2, server: , request: "GET /v2/contact_functions HTTP/1.1", upstream: "fastcgi://172.19.0.4:9000", host: "api.test:8000", referrer: "http://api.test:8000/"
api     | 172.18.0.2 - - [12/Nov/2018:13:14:09 +0000] "GET /v2/contact_functions HTTP/1.1" 502 559 "http://api.test:8000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36" "172.18.0.1"
```

I'm not sure I get what's wrong, it looks like it's an nginx error. Can we add configs (it looks like fastcgi_buffers / fastcgi_buffer_size could help). Or is there a way to control these headers ?

On some other working routes, I can see a lot of informations under Cache-Tags Headers, could it be the problem ? Again, can I do something on these headers ?

**Comment by sushicodeur** [comment]
Ok, this config did the trick, but it looks like I'm missing some caching features ? :)

```
    http_cache: 
        invalidation: 
            enabled: false
#        invalidation:
#            enabled: true
#            varnish_urls: ['%env(VARNISH_URL)%']
#        max_age: 0
#        shared_max_age: 3600
#        vary: ['Content-Type', 'Authorization']
#        public: true
```
