### ISSUE TITLE
Expose vendor entity

### ISSUE THREAD

**Issue by kl3sk** [api-platform/api-platform#891]
Hello,

First I don't find any answer for my problem.

I simple like to expose resource (and make custom resource) from a bundle that add an entity. 

Eg :[DataDogAuditBundle](https://github.com/DATA-DOG/DataDogAuditBundle)

I try to extend it but `empty result` or `Unable to generate an IRI for the item of type ...`

How could I achieve this ?

Thanks

**Comment by dunglas** [comment]
To expose vendor entities, you should use YAML or XML mappings instead of annotations.

**Comment by kl3sk** [comment]
That's indeed what i use 😄 

```
resources:
    Namespace\To\Ventor\entity:
        attributes:
            normalization_context:
                groups: [ 'log.read' ]
        collectionOperations:
            get:
                method: 'GET'
        itemOperations:
            get:
                method: 'GET'
```

May I forgot something ?

And how could I customise operation ? like I did in my entities with serialisation groups.

**Comment by kl3sk** [comment]
Ok, that's was a cache behavior. After clearing it it seems to work.

But how to create serialisation groups with `yaml`?

**Comment by dunglas** [comment]
It's described in the Symfony Serializer docs: https://symfony.com/doc/current/components/serializer.html#attributes-groups

**Comment by kl3sk** [comment]
Ok thanks that works:

**For other users.**

# Enable serialiser
`config/packages/framework.yaml`

##  Add this if it doesn't exists:
```
    serializer:
        enabled: true
        mapping:
            paths: ['%kernel.project_dir%/path/to/your/entity_yaml_files_folder/']
```

## And the YAML entity:

```
Your\Vendor\Entity:
    attributes:
        id:
            groups: ['group1']
        any_property:
            groups: ['group1']
        ...
```
