### ISSUE TITLE
Error in Authorize controller using FOSAuthServer bundle

### ISSUE THREAD

**Issue by awesemo** [api-platform/api-platform#923]
Controller "fos_oauth_server.controller.authorize" does neither exist as service nor as class

Config:
```
fos_oauth_server:
    db_driver:              orm
    authorize:              false
    client_class:           App\Entity\OAuth\Client
    access_token_class:     App\Entity\OAuth\AccessToken
    refresh_token_class:    App\Entity\OAuth\RefreshToken
    auth_code_class:        App\Entity\OAuth\AuthCode
    service:
        user_provider:      App\Security\UserProvider
        options:
          supported_scopes: user
```

Route:
```
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"
```

Security:
```
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            anonymous:  true
            provider:   user_provider
            form_login:
                provider:   user_provider
                check_path: user_login
                login_path: user_login
            logout:
                path:               /logout
                target:             /
                invalidate_session: true
```
