### ISSUE TITLE
Data access through DTO: works in API via JSON, but not in Admin component

### ISSUE THREAD

**Issue by christianfriedl** [api-platform/api-platform#925]
I want to use a dto that serves as a high-level sort of entity for some underlying entites.
In the standard api web interface, or via curl on the console, all CRUD operations work just fine.
However, in the Admin component, I always end up with the following error message:

Error: "Unable to find the URL for "http://localhost:8080/docs.jsonld#Entrypoint/myFancyDto"."
	parseHydraDocumentation http://localhost:81/static/js/1.chunk.js:3489:17

Here is the relevant code, as far as I can see it:

MyFancyDtoController.php:

```
/**
     * @return MyFancyDto[]
     * @Route(
     *     name="api_my_fancy_dtos_get_collection",
     *     methods={"GET"},
     *     path="/my_fancy_dtos",
     *     defaults={
     *          "_api_respond"=true,
     *          "_api_receive"=false,
     *     }
     * )
     */
    public function getCollectionAction(Request $httpRequest)
(...)
```
MyFancyDto.php:

```
/**
 * Flattens the percentages into a common structure
 *
 * @ApiResource(
 *      collectionOperations={
 *          "get"={
 *              "method"="GET",
 *              "route_name"="api_my_fancy_dtos_get_collection",
 *              "path"="/my_fancy_dtos",
 *              "swagger_context"={
 *                  "summary"="Gets one DTO",
 *              },
 *              "defaults"={"_api_receive"=false, "_api_respond"=true}
 *          },
(...)
```
(collection-post, item-get and item-put are implemented the same way, and also work via curl)

services.yaml:

```

  Namespace...\MyFancyDtoController:
    public: true
(...)
```

api_platform.yaml:
```
api_platform:
    mapping:
        paths:
        - '%kernel.project_dir%/src/...Namespace.../Entity'
        - '%kernel.project_dir%/src/...Namespace.../Entity'
        - '%kernel.project_dir%/src/...Namespace.../Dto'
        - '%kernel.project_dir%/src/...Namespace.../Controller'
        - '%kernel.project_dir%/config/api-platform'
```

The App.js just contains the standard authenticated example from the documentation.

All non-dto entites work just fine, so there has to be some difference between the "normal" entites and the dto that I'm just not able to see.
