### ISSUE TITLE
Swagger Decorator does not work anymore

### ISSUE THREAD

**Issue by oschwartz** [api-platform/api-platform#938]
Since updating Symfony to version 4.2.2 the swagger decorator no longer works.
Two projects and same result.

**Comment by you-ser** [comment]
Hi. Try to decorate `api_platform.swagger.normalizer.api_gateway` service instead of api_platform.swagger.normalizer.documentation.

**Comment by vbourdeix** [comment]
Hello, I had the same issue, and your suggestion solved it. Thanks @you-ser .

**Comment by dunglas** [comment]
Would you mind updating the docs please?

**Comment by oschwartz** [comment]
@you-ser  Thank you

**Comment by oschwartz** [comment]
@dunglas PR sent

**Comment by jakobeissler** [comment]
That worked!

**Comment by abdeljabar** [comment]
Using symfony 3.5 and api platform 2.5, the provided solution didn't work for me.

I had to add 

```
tags:
            - { name: serializer.normalizer }
```

The full code is:

```
App\Swagger\SwaggerDecorator:
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: [ '@App\Swagger\SwaggerDecorator.inner' ]
        autoconfigure: false
        tags:
            - { name: serializer.normalizer }
```
