### ISSUE TITLE
!tagged service not working

### ISSUE THREAD

**Issue by botjaeger** [api-platform/api-platform#941]
I have a DataProvider with constructor like this.

`public function __construct(EntityManagerInterface $manager, iterable $extension)`

registered as service
```
  pablo.data_provider.project_data_provider:
    class: 'PabloBundle\DataProvider\ProjectDataProvider'
    arguments:
      - '@doctrine.orm.entity_manager'
      - !tagged 'api_platform.doctrine.orm.query_extension.item'
    tags:
      - { name: 'api_platform.collection_data_provider', priority: 1 }
      - { name: 'api_platform.item_data_provider', priority: 2 }
```

but I always get this error

> Cannot autowire service "PabloBundle\DataProvider\ProjectDataProvider": argument "$extension" of method "__construct()" is type-hinted "iterable", you should configure its value explicitly.

I just followed the docs written here -> https://api-platform.com/docs/core/data-providers#injecting-extensions-pagination-filter-eagerloading-etc

**Comment by botjaeger** [comment]
I fixed this by doing this.

`public function __construct(ManagerRegistry $manager, iterable $itemExtensions = [])`

**Comment by flaushi** [comment]
I have a similar issue. But my constructor is called twice!

```
public function __construct(EntityManagerInterface $entityManager,
                                DataEvaluator $dataEvaluator,
                                iterable $placeholders = [])
    {
        $this->entityManager = $entityManager;
        $this->dataEvaluator = $dataEvaluator;

        foreach ($placeholders as $placeholder) {
            $this->placeholders[] = $placeholder;
        }
        dump($this->placeholders);
    }
```
Dumps twice: first an **empty** array, then my tagged services.
The service is registered as follows:
```
report_helper:
        class: App\Service\ReportHelper
        public: true
        arguments: [!tagged app.reportplaceholder]
```

**Comment by teohhanhui** [comment]
@flaushi:
> But my constructor is called twice!

You should open an issue on Symfony, perhaps? But I suspect you may be doing something wrong somewhere. Maybe try the #support channel on Symfony Slack.

**Comment by flaushi** [comment]
Solved it on my own, but learned a lot during this, 
see https://stackoverflow.com/a/56655789/5330805

Viele Grüße,
Olli Demetz

Von meinem iPhone gesendet

**Comment by MAbohassan** [comment]
When you define your service like this 
```
report_helper:
        class: App\Service\ReportHelper
        public: true
        arguments: [!tagged app.reportplaceholder]
```
you are creating a new service which id is `report_helper`, Try to debug the container
```
php bin/console debug:container
```
you will find your service but with `report_helper` id, so unless you tried to override your controller definition in service.yaml and pass it the correct service like this
```
    App\Controller\DefaultController:
        tags: [controller.service_arguments]
        bind:
            $placeholders: '@report_helper'
```
It won't work as the service container wouldn't be able to detect what do you mean by `iterable`, because it's trying to using the service which he autowired automatically.

So the solution is what @flaushi says you can use `alias` to be like this
```
report_helper:
        alias: App\Service\ReportHelper
        public: true
        arguments: [!tagged app.reportplaceholder]
```

Or you can use alias directly by using it as service id like this
```
App\Service\ReportHelper:
        public: true
        arguments: [!tagged app.reportplaceholder]
```
