### ISSUE TITLE
[Yaml] Operation normalization_context does not inherit values from resource attributes

### ISSUE THREAD

**Issue by tezvi** [api-platform/api-platform#945]
Hi everyone,

I've just noticed that normalization_context does not inherit groups attribute from normalization_context defined at resource level.

Example:

```
Acme\Entity\Example:
    collectionOperations:
        get:
            path: '/api/acme/entity/examples'
            normalization_context:
                enable_max_depth: true
        get2:
            path: '/api/acme/entity/examples/custom'
            method: 'GET'
            normalization_context:
                enable_max_depth: true
                groups: ['default_group']
    attributes:
        normalization_context:
            groups: ['default_group']
            swagger_definition_name: 'Example'
```

The "_default_group_" is not used in **get** operation. I have to define it explicitly at operation level (get2 operation).
Is this expected behavior?

Using api-platform/core v2.3.4

Thanks.
