### ISSUE TITLE
Default order + OrderFilter produce duplicate columns in orderby

### ISSUE THREAD

**Issue by mweidt** [api-platform/api-platform#953]
Hi,

I'm using ApiPlatform 2.3.5 with MS-SQL-Server as DBMS and Doctrine. In this setup I encountered the following problem.

I defined an entity with overriding the default order - e.g. _@ApiResource(attributes={"order"={"foo": "ASC"}})_ - and allowed an OrderFilter on the same field - e.g. _@ApiFilter(OrderFilter::class, properties={"foo": "ASC"})_.

The request on _"/entities?order[foo]=asc"_ produces an error with MS-SQL-Server:
> A column has been specified more than once in the order by list. Columns in the order by list must be unique.

Here is the sql
> ... ORDER BY d0_.foo ASC, d0_.foo ASC

On MySQL the same sql is produced - but no error occures because MySQL is able to optimize the code.

In my opinion, ApiPlatform should add the default orderby only if it's not already added by OrderFilter.

Thanks for your work and your support

**Comment by mweidt** [comment]
I think it's useful to define a default order in case a API caller omits any order parameter. Therefore I defined it like this.

```php
/**
 * @ApiResource(
 *     attributes={
 *        "order"={"isbn": "ASC"}
 *     }
 * )
 * @ApiFilter(
 *     OrderFilter::class, properties={
 *        "isbn": "ASC",
 *        "title": "ASC"
 *     }
 * )
 *
 * @ORM\Table(name="books")
 * @ORM\Entity
 */
class Book
{
	...
}
```

Requesting `/books?order[isbn]=asc` will produce the duplicate order by in SQL `... ORDER BY d0_.isbn ASC, d0_.isbn ASC`.

Of course I could remove the configuration for ApiResource. Then all callers of the API have to provide a order parameter to get an ordered collection.
But I think in this case ApiPlatform will also add a default order on the identifier field. So the error will occure if I allow the identifier field as OrderFilter...

**Comment by mweidt** [comment]
What would be the correct solution in your optinion? Apply the default order only if there isn't any order by criteria?

Or should it be the job of doctrine to omit duplicate order by entries - if someone calls addOrderBy with a field more than once?

**Comment by mweidt** [comment]
Ok - but then it's not possible to request `/books?order[isbn]=desc` ... 

I also think the solution by merging configurations or current values is not trivial :-(

**Comment by deancsmith** [comment]
We also encountered this problem on `api-platform/core` v2.5.0 running against MS SQL, which out of the box, made the OrderFilter unusable for our use-case of applying custom (user) filtering to different properties across many collections.

When adding an `OrderFilter` and then trying to apply ordering to the default property (id) we get a database exception because a default ASC filtering is applied by the API Platform in addition to our `OrderFilter` which results in the Doctrine SQL query looking like `...ORDER BY e0_.id DESC, e0_.id ASC..`. As stated earlier this is invalid on Microsoft SQL Server and results in the SQL error `[SQL Server] A column has been specified more than once in the order by list. Columns in the order by list must be unique.`.

Our workaround has been to turn off the default resource ordering by supplying an empty config value so that we can apply our own. We do not care about the default ordering of the resource, as it is not being used elsewhere, but it actually appears to be ordering in ASC order by the primary key (id) anyway, so this may be good enough behaviour for anyone else (until there is a better way to handle this within API Platform itself).

```php
/**
 * @ApiResource(
 *     ...
 *     attributes={
 *        "order"={}
 *     }
 * )
 * @ApiFilter(OrderFilter::class, properties={"id": "DESC", "createdAt": "DESC"})
 *
 * @ORM\Table(name="books")
 * @ORM\Entity
 */
class Book
{
	...
}
```

**Comment by leandro980** [comment]
Same issue here with `api-platform/core` v2.5.7 and yaml configuration, i have double ordering field that causes an error.
Yaml is used 'cos Acme\Ind\Entity are in a separate bundle.

**config/services.yaml**
```yaml
############################################################
# FILTERS
############################################################
app.cliente_resource.order_filter:
    parent: 'api_platform.doctrine.orm.order_filter'
    arguments:
        $properties:
            codiceCliente: ~
    tags: [ { name: 'api_platform.filter', id: 'cliente.order_filter' } ]
    autowire: false # required, explained below
    autoconfigure: false # required, explained below
```

**config/api_platform/cliente.yaml**
```yaml
resources:
  Acme\Ind\Entity\Cliente\Cliente:
    shortName: 'Cliente'
    description: 'Cliente di Acme'
    collectionOperations:
      get:
        path: /clienti
        filters: ['cliente.order_filter']
    itemOperations:
      get:
        path: cliente/{id}
        requirements:
          id: '\d{1,6}'
        openapi_context:
          summary: Recupera un cliente in base al codice Acme
          parameters:
            - in: path
              name: id
              schema:
                type: integer
              required: true
              description: Codice cliente, nominato id
    attributes: # optional
      input: App\Dto\Cliente\ClienteDtoInput
      output: App\Dto\Cliente\ClienteDtoOutput
      pagination_items_per_page: 25
````

Any idea how to solve?
