### ISSUE TITLE
[Bug] A filter with a `partial` strategy is not applied to the generated SQL if an array of values is passed.

### ISSUE THREAD

**Issue by marioprudhomme** [api-platform/api-platform#965]
For example:
```
services:
  ds_config.filter.config.search:
    parent: api_platform.doctrine.orm.search_filter
    arguments:
      - id: exact
        uuid: exact
        owner: exact
        ownerUuid: exact
        key: partial <------------Partial
    tags:
      - { name: api_platform.filter, id: ds_config.config.search }
```

Request #1 works returning 1 item in the collection:
`GET` /configs?key=username
SQL: `... WHERE key LIKE ?`

Request #2 does not work returning all items in the collection:
`GET` /configs?key[0]=username&key[1]=uuid
SQL: no conditions found for key
