### ISSUE TITLE
[Feature] provide option to change GraphiQL path

### ISSUE THREAD

**Issue by lautr** [api-platform/api-platform#988]
## What problems does this feature solve?
* if there is a caching infrastructure in front of GraphQL the UI can get randomly cached
* currently we can change the [path for swagger ui ](https://api-platform.com/docs/core/swagger/#manually-registering-the-swagger-ui-controller)but not GraphiQL making it inconsistent

## What does the proposed changes look like?
The graphiql option set could simply be extended with the path option:
```
# api/config/packages/api_platform.yaml
api_platform:
    graphql:
        graphiql:
            enabled: false
            path: /docs/graphiql
```

### Related Issues
* Should be considered as well if GraphQL Playground is used #975
