### ISSUE TITLE
Using 3rd-party DTOs in GraphQL

### ISSUE THREAD

**Issue by kiler129** [api-platform/api-platform#995]
It seems like there's no way to use object which are not defined as `@ApiResource` in GraphQL - they are simply invisible. This is not that big of a limitation, since one can define this in YAML like so:

```
resources:
    libphonenumber\PhoneNumber: ~
```

Serialization groups are also not a problem, since Symfony Serializer can read the config from YAML:
```
libphonenumber\PhoneNumber:
    attributes:
        countryCode: &std
            groups: ['GraphQLQuery']
        nationalNumber: *std
        extension: *std
        italianLeadingZero: *std
        numberOfLeadingZeros: *std
        rawInput: *std
        countryCodeSource: *std
        preferredDomesticCarrierCode: *std
```

The biggest issue is IDs - it seems like you cannot have objects without IDs as resources. This makes sense from resource perspective, but for simple value objects it's just not possible to get any IDs. Additionally the method above does not seem to work with core objects (e.g. `\DateTimeZone`) :(

I looked into docs, but they're very sparse for GraphQL. I will happily improve them, but I cannot find a reliable way of making this working for objects without IDs (short of hacking `\ApiPlatform\Core\GraphQl\Type\SchemaBuilder`)?

This is similar to https://github.com/api-platform/core/issues/1870, but deals with really a different issue - code which you cannot change.

**Comment by alanpoulain** [comment]
It's a duplicate of https://github.com/api-platform/core/issues/1759 I think.

**Comment by kiler129** [comment]
Just for future lurkers (and today's me):

So the last piece (IDs requirement) I was able to resolve by creating a class `class BlankIdentifierIriConverter implements IriConverterInterface` which implements https://json-ld.org/spec/ED/json-ld/20180215/#identifying-blank-nodes strategy.

**Comment by alanpoulain** [comment]
But with your method, the schema is not modified, is it? Only the query result.

**Comment by kiler129** [comment]
No, the schema itself is 100% correct due to making the `libphonenumber\PhoneNumber` a resource. Everything works as expected then ;)

**Comment by Siregacvek** [comment]
@kiler129 let me ask you how did you make your custom iriConverter to work in Api-Platform for value objects? `IriConverterInterface` doesnt assume any `supports` method. Or may be you decorated default `iriConverter`?

**Comment by kiler129** [comment]
@Siregacvek:

That's simple, you just use the standard Symfony DIC functionality of services decoration.

```yaml
    App\Serializer\BlankIriConverter:
        decorates: api_platform.iri_converter
        arguments: ['@App\Serializer\BlankIriConverter.inner']
```

and the IRI converter itself will simply use composition like the following:

```php
<?php

class BlankIriConverter implements IriConverterInterface
{
    private $composed;

    public function __construct(IriConverterInterface $composed)
    {
        $this->composed = $composed;
    }

    public function getItemFromIri(string $iri, array $context = [])
    {
        if (\substr($iri, 0, 1) === '_') {
            throw new ItemNotFoundException(....); //Prevent requesting objects with blank identifiers
        }

        return $this->converter->getItemFromIri($iri, $context);
    }

    public function getIriFromItem($item, int $referenceType = UrlGeneratorInterface::ABS_PATH): string
    {
        try {
            return $this->converter->getIriFromItem($item, $referenceType);
        } catch (\Throwable $t) {
            return '_:' . [your blank identifier logic];
        }
    }

    public function getIriFromResourceClass(string $resourceClass, int $referenceType = UrlGeneratorInterface::ABS_PATH): string {
        try {
            return $this->converter->getIriFromResourceClass($resourceClass, $referenceType);
        } catch (\Throwable $t) {
            return '_:' . $resourceClass;
        }
    }

    public function getItemIriFromResourceClass(string $resourceClass, array $identifiers, int $referenceType = UrlGeneratorInterface::ABS_PATH): string {
        try {
            return $this->converter->getItemIriFromResourceClass($resourceClass, $identifiers, $referenceType);
        } catch (\Throwable $t) {
            return '_:' . [your blank identifier logic];
        }
    }

    public function getSubresourceIriFromResourceClass(string $resourceClass, array $identifiers, int $referenceType = UrlGeneratorInterface::ABS_PATH): string {
        try {
            return $this->converter->getSubresourceIriFromResourceClass($resourceClass, $identifiers, $referenceType);
        } catch (\Throwable $t) {
            return '_:' . [your blank identifier logic];
        }
    }
}
```
