### ISSUE TITLE
Response codes for authorization are not documented

### ISSUE THREAD

**Issue by Eydamos** [api-platform/api-platform#998]
If authorization is set up in api_platform.yml
```
api_platform:
    swagger:
        api_keys:
            bearer:
                name: Authorization
                type: header
```
The response codes 401 and 403 should automatically be documented as well for all endpoints that are protected by the firewall. Adding the documentation for each request would be very cumbersome as we would also have to re-add the documentation for the 200 response
